Repository Expensify/App, pull requests merged in 2021-06, with the labels that each got.

#3254 Update version to 1.0.58-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3255 Update version to 1.0.58-1 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/GrowlNotification/GrowlNotificationContainer/GrowlNotificationContainerPropTypes.js
  src/components/GrowlNotification/GrowlNotificationContainer/index.js
  src/components/GrowlNotification/GrowlNotificationContainer/index.native.js
  src/components/GrowlNotification/index.js
  src/components/TextInputFocusable/index.js
  src/libs/Growl.js
  src/libs/GrowlNotification/GrowlNotificationContainer/index.native.js
  src/pages/settings/Profile/ProfilePage.js
  src/styles/styles.js
Labels: automerge

#3258 Update version to 1.0.58-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3259 Update version to 1.0.58-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/languages/en.js
  src/libs/API.js
  src/libs/actions/IOU.js
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#3261 Update version to 1.0.58-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3262 Update version to 1.0.58-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3264 Update version to 1.0.58-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3265 Update version to 1.0.58-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/reportUtils.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionContextMenu.js
Labels: automerge

#3267 Update version to 1.0.58-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3268 Update version to 1.0.58-5 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#3269 Update version to 1.0.59-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3270 Update version to 1.0.59-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3277 Update version to 1.0.59-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3278 Update version to 1.0.59-1 on staging
  android/app/build.gradle
  desktop/README.md
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/AnchorWithAuthToken.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.native.js
  src/components/AnchorForCommentsOnly/anchorForCommentsOnlyPropTypes.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/AnchorForCommentsOnly/index.native.js
  src/components/IOUBadge.js
  src/components/Picker/index.js
  src/components/RenderHTML.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/pages/DetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionItemDate.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/settings/Profile/LoginField.js
  src/pages/signin/ChangeExpensifyLoginLink.js
Labels: automerge

#3281 Update version to 1.0.59-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3282 Update version to 1.0.59-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3286 Update version to 1.0.59-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3287 Update version to 1.0.59-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUParticipantsPage/index.js
Labels: automerge

#3289 Update version to 1.0.59-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3290 Update version to 1.0.59-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/getEmailKeyboardType/index.js
  src/libs/getEmailKeyboardType/index.native.js
  src/pages/signin/LoginForm.js
Labels: automerge

#3291 Update version to 1.0.60-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3292 Update version to 1.0.60-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3298 Update version to 1.0.60-0 on production
  android/app/build.gradle
  desktop/README.md
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/AnchorWithAuthToken.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.native.js
  src/components/AnchorForCommentsOnly/anchorForCommentsOnlyPropTypes.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/AnchorForCommentsOnly/index.native.js
  src/components/IOUBadge.js
  src/components/Picker/index.js
  src/components/RenderHTML.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/libs/getEmailKeyboardType/index.js
  src/libs/getEmailKeyboardType/index.native.js
  src/pages/DetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionItemDate.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/iou/steps/IOUParticipantsPage/index.js
  src/pages/settings/Profile/LoginField.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/LoginForm.js
Labels: automerge

#3299 Update version to 1.0.60-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3300 Update version to 1.0.60-1 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ReportActionItemIOUAction.js
  src/components/ReportActionItemIOUPreview.js
  src/components/ReportTransaction.js
  src/languages/en.js
  src/libs/API.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionPropTypes.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
  src/pages/iou/IOUTransactions.js
  src/styles/styles.js
  src/styles/utilities/flex.js
  tests/actions/ReportTest.js
Labels: automerge

#3305 Update version to 1.0.61-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3306 Update version to 1.0.61-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3304 Test PR B - Change borderFocus from blue to yellow
  src/styles/themes/default.js
Labels: CP Staging

#3312 Update version to 1.0.61-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3315 Test PR D - Make buttonSuccessBR red
  src/styles/themes/default.js
Labels: CP Staging

#3316 Update version to 1.0.61-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3319 Test PR E - Make sidebarHover blue
  src/styles/themes/default.js
Labels: CP Staging

#3320 Update version to 1.0.61-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3324 Test PR F - Make icons blue
  src/styles/themes/default.js
Labels: CP Staging

#3325 Update version to 1.0.61-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3328 Test PR G - Make badgeDangerBackground blue
  src/styles/themes/default.js
Labels: CP Staging

#3329 Update version to 1.0.61-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3331 Test PR H - Orange is the new black
  src/styles/colors.js
Labels: CP Staging

#3334 Update version to 1.0.61-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3336 Dummy change in sidebar text
  src/pages/settings/AboutPage.js
Labels: CP Staging

#3337 Update version to 1.0.61-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3340 Update version to 1.0.61-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3341 Update version to 1.0.61-8 on staging
  .github/actions/getMergeCommitForPullRequest/action.yml
  .github/actions/getMergeCommitForPullRequest/getMergeCommitForPullRequest.js
  .github/actions/getMergeCommitForPullRequest/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/workflows/cherryPick.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#3342 Update version to 1.0.61-9 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3344 Update version to 1.0.62-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3345 Update version to 1.0.62-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
Labels: automerge

#3356 Update version to 1.0.62-0 on production
  .github/actions/getMergeCommitForPullRequest/action.yml
  .github/actions/getMergeCommitForPullRequest/getMergeCommitForPullRequest.js
  .github/actions/getMergeCommitForPullRequest/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/workflows/cherryPick.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/IOUConfirmationList.js
  src/components/OptionsList.js
  src/components/ReportActionItemIOUAction.js
  src/components/ReportActionItemIOUPreview.js
  src/components/ReportTransaction.js
  src/languages/en.js
  src/libs/API.js
  src/libs/OptionsListUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionPropTypes.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
  src/pages/iou/IOUTransactions.js
  src/styles/styles.js
  src/styles/utilities/flex.js
  tests/actions/ReportTest.js
Labels: automerge

#3357 Update version to 1.0.62-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3358 Update version to 1.0.62-1 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/FAB/FAB.js
  src/components/GrowlNotification/GrowlNotificationContainer/GrowlNotificationContainerPropTypes.js
  src/components/GrowlNotification/GrowlNotificationContainer/index.js
  src/components/GrowlNotification/GrowlNotificationContainer/index.native.js
  src/languages/en.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#3256 [HOLD Auth 5613 Web-Expensify 31078 Web-Expensify 31113] [IOU] Pay with Expensify option
  src/CONST.js
  src/languages/en.js
  src/libs/API.js
  src/libs/Permissions.js
  src/libs/actions/IOU.js
  src/pages/iou/IOUDetailsModal.js
Labels: InternalQA

#3364 Update version to 1.0.62-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3365 Update version to 1.0.62-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/languages/en.js
  src/libs/API.js
  src/libs/Permissions.js
  src/libs/actions/IOU.js
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#3366 Update version to 1.0.62-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3367 Update version to 1.0.62-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3368 Update version to 1.0.62-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3369 Update version to 1.0.62-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/Policy.js
Labels: automerge

#3370 Update version to 1.0.62-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3371 Update version to 1.0.62-5 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItemIOUAction.js
Labels: automerge

#3372 Update version to 1.0.62-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3373 Update version to 1.0.62-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/HeaderWithCloseButton.js
  src/languages/en.js
  src/pages/iou/IOUModal.js
Labels: automerge

#3375 Update version to 1.0.62-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3376 Update version to 1.0.62-7 on staging
  android/app/build.gradle
  desktop/main.js
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3377 Update version to 1.0.63-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3378 Update version to 1.0.63-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3393 Update version to 1.0.63-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3394 Update version to 1.0.63-1 on staging
  .github/workflows/cherryPick.yml
  .github/workflows/deploy.yml
  android/app/build.gradle
  android/build.gradle
  apple-app-site-association
  config/webpack/webpack.common.js
  ios/ExpensifyCash.xcodeproj/project.pbxproj
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/Checkbox.js
  src/components/FullscreenLoadingIndicator.js
  src/components/IOUBadge.js
  src/components/Onfido/index.css
  src/components/Onfido/index.js
  src/components/Onfido/index.native.js
  src/components/Onfido/onfidoPropTypes.js
  src/components/TextInputWithLabel.js
  src/components/TextLink.js
  src/languages/en.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/BankAccounts.js
  src/libs/getPlatform/index.android.js
  src/libs/getPlatform/index.ios.js
  src/libs/isViaExpensifyCashNative/index.js
  src/libs/isViaExpensifyCashNative/index.native.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/EnablePayments/index.js
  src/pages/EnablePayments/userWalletPropTypes.js
  src/pages/home/report/EmojiPickerMenu/index.js
  src/styles/colors.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/utilities/spacing.js
Labels: automerge

#3395 Update version to 1.0.63-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3396 Update version to 1.0.63-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/pages/settings/PaymentsPage.js
Labels: automerge

#3398 Update version to 1.0.63-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3399 Update version to 1.0.63-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/OptionRow.js
Labels: automerge

#3405 Update version to 1.0.64-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3406 Update version to 1.0.64-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3411 Update version to 1.0.64-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3412 Update version to 1.0.64-1 on staging
  README.md
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/IOUBadge.js
  src/languages/es.js
  src/libs/Permissions.js
  src/styles/colors.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#3417 Update version to 1.0.64-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3418 Update version to 1.0.64-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
Labels: automerge

#3424 Update version to 1.0.64-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3427 Update version to 1.0.64-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3428 Update version to 1.0.64-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItemIOUAction.js
  src/components/ReportActionItemIOUPreview.js
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#3430 Update version to 1.0.64-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3431 Update version to 1.0.64-5 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
  src/pages/home/report/ReportActionContextMenu.js
  src/pages/iou/IOUModal.js
Labels: automerge

#3432 Update version to 1.0.64-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3433 Update version to 1.0.64-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3436 Update version to 1.0.64-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3437 Update version to 1.0.64-7 on staging
  android/app/build.gradle
  desktop/main.js
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3439 Update version to 1.0.65-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3440 Update version to 1.0.65-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3453 Update version to 1.0.65-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3454 Update version to 1.0.65-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
Labels: automerge

#3457 Update version to 1.0.65-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3458 Update version to 1.0.65-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/pages/settings/InitialPage.js
Labels: automerge

#3461 Update version to 1.0.65-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3462 Update version to 1.0.65-5 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3464 Update version to 1.0.65-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3465 Update version to 1.0.65-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#3466 Update version to 1.0.65-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3467 Update version to 1.0.65-7 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3468 Update version to 1.0.65-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3469 Update version to 1.0.65-8 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
Labels: automerge

#3470 Update version to 1.0.65-9 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3471 Update version to 1.0.65-9 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3472 Update version to 1.0.65-10 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3473 Update version to 1.0.65-10 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/InvertedFlatList/index.js
  src/components/TextLink.js
  src/components/Tooltip/index.js
  src/components/VideoChatButtonAndMenu.js
  src/libs/Navigation/Navigation.js
  src/libs/actions/IOU.js
  src/libs/fileDownload/index.js
  src/libs/openURLInNewTab/index.js
  src/libs/openURLInNewTab/index.native.js
  src/pages/home/report/ReportActionContextMenuItem.js
  src/pages/settings/AboutPage.js
  src/pages/settings/AppDownloadLinks.js
Labels: automerge

#3474 Update version to 1.0.65-11 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3475 Update version to 1.0.65-11 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/Permissions.js
  src/pages/NewChatPage.js
  src/pages/NewGroupPage.js
  src/pages/SearchPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#3478 Update version to 1.0.66-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3479 Update version to 1.0.66-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3489 Update version to 1.0.66-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3492 Update version to 1.0.66-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3494 Update version to 1.0.66-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3495 🍒 Cherry pick PR #3486 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.js
Labels: automerge

#3496 Update version to 1.0.66-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3497 🍒 Cherry pick PR #3483 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3500 Update version to 1.0.66-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3501 🍒 Cherry pick PR #3481 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/Permissions.js
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#3505 Update version to 1.0.66-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3509 Update version to 1.0.66-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3516 Update version to 1.0.66-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3519 Update version to 1.0.66-9 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3520 Update version to 1.0.66-10 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3522 Update version to 1.0.66-11 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3528 Update version to 1.0.66-12 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3530 Update version to 1.0.66-13 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3531 Update version to 1.0.66-13 on staging
  .github/workflows/cherryPick.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/withLocalize.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Network.js
  src/libs/actions/Report.js
  src/libs/translate.js
  src/pages/NewChatPage.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses.js
Labels: automerge

#3532 Update version to 1.0.67-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3533 Update version to 1.0.67-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3548 Update version to 1.0.68-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3549 Update version to 1.0.68-0 on staging
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/settings.gradle
  assets/images/bank.svg
  assets/images/example-check-image.png
  assets/images/paycheck.svg
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/AddPlaidBankAccount.js
  src/components/Checkbox.js
  src/components/CheckboxWithLabel.js
  src/components/Icon/Expensicons.js
  src/components/Picker/PickerPropTypes.js
  src/components/ReportActionItemIOUAction.js
  src/components/ReportActionItemIOUPreview.js
  src/components/TextInputWithLabel.js
  src/components/TextLink.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/IOU.js
  src/libs/actions/PersonalDetails.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/BusinessBankAccount/NewPage.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Profile/ProfilePage.js
  src/styles/styles.js
Labels: automerge

#3550 Upgrade react-native-document-picker to 5.1.0
  ios/ExpensifyCash.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: CP Staging

#3553 Update version to 1.0.68-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3554 🍒 Cherry pick PR #3550 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash.xcodeproj/project.pbxproj
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#3555 Add capturing event listeners to the KeyboardShortcut library
  src/libs/KeyboardShortcut/index.js
Labels: CP Staging

#3556 Update version to 1.0.68-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3557 🍒 Cherry pick PR #3555 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/KeyboardShortcut/index.js
Labels: automerge

#3563 Update version to 1.0.68-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3581 fix: Document Picker crash on IOS
  src/components/AttachmentPicker/index.native.js
Labels: CP Staging

#3583 Update version to 1.0.68-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3584 🍒 Cherry pick PR #3581 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
Labels: automerge

#3591 Update version to 1.0.68-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3594 Update version to 1.0.69-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3595 Update version to 1.0.69-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3611 Add latest bank + paycheck icons
  assets/images/bank.svg
  assets/images/paycheck.svg
Labels: Design

#3617 Update version to 1.0.69-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3618 Update version to 1.0.69-1 on staging
  android/app/build.gradle
  assets/images/bank.svg
  assets/images/paycheck.svg
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/Modal/BaseModal.js
  src/components/Modal/ModalPropTypes.js
  src/components/Modal/index.js
  src/components/Popover/PopoverPropTypes.js
  src/components/Popover/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/models/BankAccount.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/BusinessBankAccount/NewPage.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ReportActionItem.js
  src/pages/settings/PreferencesPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
Labels: automerge

#3621 Update version to 1.0.69-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3622 Update version to 1.0.69-2 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  web/index.html
Labels: automerge

#3624 Update version to 1.0.69-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3625 Update version to 1.0.69-3 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/Expensify.js
Labels: automerge

#3628 Update version to 1.0.70-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3629 Update version to 1.0.70-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
