Repository Expensify/App, pull requests merged in 2021-10, with the labels that each got.

#5633 Update version to 1.1.4-0 on production
  README.md
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/lets-chat.svg
  assets/images/request-call.svg
  colors.json
  fastlane/Fastfile
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/CommunicationsLink.js
  src/components/DatePicker/datepickerPropTypes.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/index.js
  src/components/DatePicker/styles.css
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/baseExpensiTextInputPropTypes.js
  src/components/Onfido/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/SignoutManager.js
  src/libs/ValidationUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Session.js
  src/libs/actions/SignInRedirect.js
  src/libs/addEncryptedAuthTokenToURL.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/RequestCallPage.js
  src/pages/workspace/WorkspaceCardPage.js
  src/stories/Datepicker.stories.js
  src/styles/utilities/spacing.js
Labels: automerge

#5634 Update version to 1.1.4-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5635 Update version to 1.1.4-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/AvatarWithImagePicker.js
  src/components/ButtonWithMenu.js
  src/components/IOUConfirmationList.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/MakeCancellablePromise.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/Permissions.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/PersonalDetails.js
  src/libs/cardUtils.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
  src/pages/iou/IOUSendPage.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
Labels: automerge

#5638 Update version to 1.1.4-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5639 Update version to 1.1.4-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/styles.css
Labels: automerge

#5640 Update version to 1.1.5-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5253 Skintone Emoji Border Radius and Size
  src/pages/home/report/EmojiPickerMenuItem.js
  src/pages/home/report/EmojiSkinToneList.js
  src/styles/styles.js
Labels: n6-hold

#5661 [CP Stg] Add Venmo only if sending money
  src/components/IOUConfirmationList.js
Labels: CP Staging

#5664 Update version to 1.1.5-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5692 Update version to 1.1.5-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ValidationUtils.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/EmojiPickerMenuItem.js
  src/pages/home/report/EmojiSkinToneList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/signin/SignInPage.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutNarrow.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/pages/signin/SignInPageLayout/index.js
  src/styles/styles.js
Labels: automerge

#5714 [NO QA] Improve workspace welcome note
  src/languages/en.js
  src/languages/es.js
Labels: Internal

#5719 Update version to 1.1.7-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5734 Update version to 1.1.7-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5752 🍒 Cherry pick PR #5749 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#5763 Set loading to false when requestorStep is submittted
  src/libs/actions/BankAccounts.js
Labels: CP Staging

#5764 Update version to 1.1.7-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5765 🍒 Cherry pick PR #5763 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
Labels: automerge

#5784 Update version to 1.1.7-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5808 Update version to 1.1.7-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5813 Fix link to OldDot's reports page
  src/pages/workspace/reimburse/WorkspaceReimburseVBAView.js
Labels: CP Staging

#5820 🍒 Cherry pick PR #5803 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
Labels: automerge

#5787 Only show fancy loading page when we are submitting verifications
  src/components/FullscreenLoadingIndicator.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/VBALoadingIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/styles/styles.js
Labels: CP Staging

#5823 🍒 Cherry pick PR #5787 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/FullscreenLoadingIndicator.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/VBALoadingIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/styles/styles.js
Labels: automerge

#5824 Update version to 1.1.7-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5830 Update version to 1.1.7-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5770 [N6] Use AddressSearch for identity form
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: CP Staging

#5833 Update version to 1.1.7-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5832 Close AddressSearch results on blur
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: CP Staging

#5838 Update version to 1.1.7-16 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5844 Update version to 1.1.7-17 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5849 Update version to 1.1.7-19 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5859 Update version to 1.1.7-22 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5858 Remove pointer events from label, modify styling of textinput
  src/components/ExpensiTextInput/ExpensiTextInputLabel/index.js
  src/styles/styles.js
Labels: CP Staging

#5868 Load policy list when url from Linking.getInitialURL is not available
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: CP Staging

#5872 Update version to 1.1.7-24 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5877 Update version to 1.1.7-25 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5885 Update version to 1.1.8-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5318 Updates NewDot homepage to reflect N6 campaign
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/styles/colors.js
  src/styles/styles.js
Labels: CP Staging

#5901 Update version to 1.1.8-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5908 Make sure we go to settings page rather than card route when creating a new workspace
  src/libs/actions/Policy.js
Labels: CP Staging

#5910 🍒 Cherry pick PR #5908 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#5932 🍒 Cherry pick PR #5913 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
Labels: automerge

#5959 Adds background to label
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/styles/styles.js
Labels: CP Staging

#5967 Update version to 1.1.8-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5980 🍒 Cherry pick PR #5978 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6014 Update version to 1.1.8-9 on production
  .github/workflows/e2e.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch.js
  src/components/AttachmentModal.js
  src/components/Checkbox.js
  src/components/CheckboxWithTooltip/CheckboxWithTooltipForMobileWebAndNative.js
  src/components/CheckboxWithTooltip/CheckboxWithTooltipPropTypes.js
  src/components/CheckboxWithTooltip/index.js
  src/components/CheckboxWithTooltip/index.native.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/ExpensiTextInputLabel/index.js
  src/components/FormAlertWithSubmitButton.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/StatePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/UnreadIndicatorUpdater/index.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.ios.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseNoVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseVBAView.js
  src/styles/colors.js
  src/styles/styles.js
  src/styles/variables.js
  web/index.html
  web/og-preview-image.png
Labels: automerge

#6015 Update version to 1.1.8-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6019 Update version to 1.1.8-11 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch.js
  src/libs/GooglePlacesUtils.js
  tests/unit/GooglePlacesUtilsTest.js
Labels: automerge

#6020 Update version to 1.1.8-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6114 hasSelfSelectedPronouns boolean fix
  src/pages/settings/Profile/ProfilePage.js
Labels: CP Staging

#6117 Update version to 1.1.11-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6118 🍒 Cherry pick PR #6114 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#6124 Update version to 1.1.11-1 on production
  CONTRIBUTING.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/FormAlertWithSubmitButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/CardUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/cardUtils.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/setup/index.js
  tests/unit/CardUtilsTest.js
  web/data_flow.png
Labels: automerge

#6125 Update version to 1.1.11-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6126 Update version to 1.1.11-2 on staging
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/java/com/expensify/chat/generated/BasePackageList.java
  android/settings.gradle
  ios/NewExpensify/AppDelegate.h
  ios/NewExpensify/AppDelegate.m
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/PressableWithSecondaryInteraction/index.android.js
  src/components/PressableWithSecondaryInteraction/index.ios.js
Labels: automerge

#6128 Update version to 1.1.11-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6129 Update version to 1.1.11-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.native.js
  src/components/AttachmentView.js
Labels: automerge

#6134 Update version to 1.1.11-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6135 Update version to 1.1.11-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextLink.js
Labels: automerge
