Repository Expensify/App, pull requests merged in 2021-09, with the labels that each got.

#4967 Remove internationalization beta
  src/CONST.js
  src/components/LocalePicker.js
  src/libs/Permissions.js
Labels: CP Staging

#4969 Update version to 1.0.90-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4970 🍒 Cherry pick PR #4967 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/LocalePicker.js
  src/libs/Permissions.js
Labels: automerge

#4974 Update version to 1.0.90-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4975 Update version to 1.0.90-3 on staging
  .github/workflows/cherryPick.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Button.js
  src/components/IOUConfirmationList.js
  src/components/InboxCallButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/iou/IOUModal.js
  src/pages/signin/LoginForm.js
  src/pages/workspace/WorkspacePeoplePage.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#4983 Update version to 1.0.90-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4984 Update version to 1.0.90-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
Labels: automerge

#4988 Update version to 1.0.91-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4989 Update version to 1.0.91-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5001 Update version to 1.0.91-0 on production
  .github/workflows/cherryPick.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Button.js
  src/components/IOUConfirmationList.js
  src/components/InboxCallButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/iou/IOUModal.js
  src/pages/signin/LoginForm.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/pages/workspace/WorkspacePeoplePage.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#5002 Update version to 1.0.91-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5003 Update version to 1.0.91-1 on staging
  .eslintrc.js
  .github/workflows/platformDeploy.yml
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  desktop/README.md
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/App.js
  src/CONFIG.js
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/Button.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/OnyxProvider.js
  src/components/OpacityView.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Report.js
  src/libs/actions/Timing.js
  src/libs/translate.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/SetPasswordPage.js
  src/pages/signin/SignInPage.js
  src/pages/signin/SignInPageLayout/index.native.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.android.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.ios.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.js
  src/pages/signin/TermsAndLicenses/index.js
  src/setup/index.js
  src/setup/index.native.js
  src/setup/platformSetup/index.desktop.js
  src/setup/platformSetup/index.native.js
  src/setup/platformSetup/index.website.js
  src/styles/styles.js
Labels: automerge

#5006 Update version to 1.0.91-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5007 Update version to 1.0.91-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/ValidationUtils.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: automerge

#5009 Update version to 1.0.91-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5010 Update version to 1.0.91-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: automerge

#5016 Update version to 1.0.92-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5017 Update version to 1.0.92-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5043 Update version to 1.0.92-0 on production
  .eslintrc.js
  .github/workflows/platformDeploy.yml
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  desktop/README.md
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/App.js
  src/CONFIG.js
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/Button.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/OnyxProvider.js
  src/components/OpacityView.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/ValidationUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Report.js
  src/libs/actions/Timing.js
  src/libs/translate.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/SetPasswordPage.js
  src/pages/signin/SignInPage.js
  src/pages/signin/SignInPageLayout/index.native.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.android.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.ios.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.js
  src/pages/signin/TermsAndLicenses/index.js
  src/setup/index.js
  src/setup/index.native.js
  src/setup/platformSetup/index.desktop.js
  src/setup/platformSetup/index.native.js
  src/setup/platformSetup/index.website.js
  src/styles/styles.js
Labels: automerge

#5044 Update version to 1.0.92-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5045 Update version to 1.0.92-1 on staging
  .github/workflows/platformDeploy.yml
  Gemfile.lock
  PERFORMANCE.md
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONFIG.js
  src/components/AddPlaidBankAccount.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/canCaptureMetrics/index.native.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/signin/PasswordForm.js
Labels: automerge

#5049 Update version to 1.0.92-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5050 Update version to 1.0.92-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
Labels: automerge

#5051 Update version to 1.0.92-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5052 Update version to 1.0.92-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
Labels: automerge

#5053 Update version to 1.0.92-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5054 Update version to 1.0.92-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5055 Update version to 1.0.92-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5056 Update version to 1.0.92-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUTransactions.js
Labels: automerge

#4602 Assign CP PRs to the deployer that triggered them
  .github/actions/getPullRequestDetails/action.yml
  .github/actions/getPullRequestDetails/getPullRequestDetails.js
  .github/actions/getPullRequestDetails/index.js
  .github/scripts/buildActions.sh
  .github/workflows/cherryPick.yml
Labels: InternalQA

#5057 Update version to 1.0.92-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5058 Update version to 1.0.92-6 on staging
  .github/actions/getPullRequestDetails/action.yml
  .github/actions/getPullRequestDetails/getPullRequestDetails.js
  .github/actions/getPullRequestDetails/index.js
  .github/scripts/buildActions.sh
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5061 Update version to 1.0.93-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5062 Update version to 1.0.93-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5063 Add new encrypted distribution cert and provisioning profile
  ios/Certificates.p12.gpg
  ios/chat_expensify_appstore.mobileprovision.gpg
Labels: CP Staging

#5064 Update version to 1.0.93-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5065 🍒 Cherry pick PR #5063 to staging 🍒
  android/app/build.gradle
  ios/Certificates.p12.gpg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/chat_expensify_appstore.mobileprovision.gpg
  package-lock.json
  package.json
Labels: automerge

#5083 Update version to 1.0.93-1 on production
  .github/actions/getPullRequestDetails/action.yml
  .github/actions/getPullRequestDetails/getPullRequestDetails.js
  .github/actions/getPullRequestDetails/index.js
  .github/scripts/buildActions.sh
  .github/workflows/cherryPick.yml
  .github/workflows/platformDeploy.yml
  Gemfile.lock
  PERFORMANCE.md
  android/app/build.gradle
  fastlane/Fastfile
  ios/Certificates.p12.gpg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/chat_expensify_appstore.mobileprovision.gpg
  package-lock.json
  package.json
  src/CONFIG.js
  src/components/AddPlaidBankAccount.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/BankAccounts.js
  src/libs/canCaptureMetrics/index.native.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUTransactions.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/signin/PasswordForm.js
Labels: automerge

#5084 Update version to 1.0.93-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5085 Update version to 1.0.93-2 on staging
  .github/actions/bumpVersion/index.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  assets/images/bankicons/american-express.svg
  assets/images/bankicons/bank-of-america.svg
  assets/images/bankicons/bb-t.svg
  assets/images/bankicons/capital-one.svg
  assets/images/bankicons/charles-schwab.svg
  assets/images/bankicons/chase.svg
  assets/images/bankicons/citibank.svg
  assets/images/bankicons/citizens-bank.svg
  assets/images/bankicons/discover.svg
  assets/images/bankicons/fidelity.svg
  assets/images/bankicons/huntington-bank.svg
  assets/images/bankicons/navy-federal-credit-union.svg
  assets/images/bankicons/pnc.svg
  assets/images/bankicons/regions-bank.svg
  assets/images/bankicons/suntrust.svg
  assets/images/bankicons/td-bank.svg
  assets/images/bankicons/us-bank.svg
  assets/images/bankicons/usaa.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/Icon/BankIcons.js
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Session.js
  src/libs/actions/SignInRedirect.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/styles/getModalStyles.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#5098 Update version to 1.0.94-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5099 Update version to 1.0.94-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5014 Use currentBalance instead of availableBalance
  src/components/CurrentWalletBalance.js
  src/pages/settings/InitialPage.js
Labels: InternalQA

#5135 Fix exitTo link by adding missing ?
  src/libs/actions/App.js
Labels: CP Staging

#5137 Update version to 1.0.94-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5139 🍒 Cherry pick PR #5135 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/App.js
Labels: automerge

#5143 Update version to 1.0.94-1 on production
  .github/actions/bumpVersion/index.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  assets/images/bankicons/american-express.svg
  assets/images/bankicons/bank-of-america.svg
  assets/images/bankicons/bb-t.svg
  assets/images/bankicons/capital-one.svg
  assets/images/bankicons/charles-schwab.svg
  assets/images/bankicons/chase.svg
  assets/images/bankicons/citibank.svg
  assets/images/bankicons/citizens-bank.svg
  assets/images/bankicons/discover.svg
  assets/images/bankicons/fidelity.svg
  assets/images/bankicons/huntington-bank.svg
  assets/images/bankicons/navy-federal-credit-union.svg
  assets/images/bankicons/pnc.svg
  assets/images/bankicons/regions-bank.svg
  assets/images/bankicons/suntrust.svg
  assets/images/bankicons/td-bank.svg
  assets/images/bankicons/us-bank.svg
  assets/images/bankicons/usaa.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/Icon/BankIcons.js
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Session.js
  src/libs/actions/SignInRedirect.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/styles/getModalStyles.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#5144 Update version to 1.0.94-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5145 Update version to 1.0.94-2 on staging
  .github/ISSUE_TEMPLATE/Standard.md
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/deploy.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  apple-app-site-association
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/CurrentWalletBalance.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Permissions.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PersonalDetails.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ExistingOwners.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/InitialPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#5147 Update version to 1.0.95-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5148 Update version to 1.0.95-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5160 Revert "Fix: Reduced Emojipicker landscape modal height"
  src/components/withWindowDimensions.js
  src/styles/getModalStyles.js
Labels: CP Staging

#5163 Update version to 1.0.95-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5164 🍒 Cherry pick PR #5160 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/withWindowDimensions.js
  src/styles/getModalStyles.js
Labels: automerge

#5174 Update version to 1.0.95-1 on production
  .github/ISSUE_TEMPLATE/Standard.md
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/deploy.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  apple-app-site-association
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/CurrentWalletBalance.js
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Permissions.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PersonalDetails.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ExistingOwners.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/InitialPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/styles/getModalStyles.js
Labels: automerge

#5175 Update version to 1.0.95-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5176 Update version to 1.0.95-2 on staging
  android/app/build.gradle
  assets/emojis.js
  config/checkMetroBundlerPort.js
  config/checkPort.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AvatarWithImagePicker.js
  src/components/AvatarWithIndicator.js
  src/components/ThumbnailImage.js
  src/languages/en.js
  src/languages/es.js
  src/libs/HttpUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/OptionsListUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/User.js
  src/pages/NewChatPage.js
  src/pages/NewGroupPage.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/report/EmojiPickerMenu/getSkinToneEmojiFromIndex.js
  src/pages/home/report/EmojiPickerMenu/index.js
  src/pages/home/report/EmojiPickerMenu/index.native.js
  src/pages/home/report/EmojiPickerMenuItem.js
  src/pages/home/report/EmojiSkinToneList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Profile/currentUserPersonalDetailsPropsTypes.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/styles/animation/SpinningIndicatorAnimation.js
  src/styles/getAvatarWithIndicatorStyles.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#5178 Update version to 1.0.95-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5179 Update version to 1.0.95-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/libs/Navigation/linkingConfig.js
Labels: automerge

#5180 Update version to 1.0.96-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5181 Update version to 1.0.96-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5200 Update version to 1.0.96-0 on production
  android/app/build.gradle
  assets/emojis.js
  config/checkMetroBundlerPort.js
  config/checkPort.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AvatarWithImagePicker.js
  src/components/AvatarWithIndicator.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/ThumbnailImage.js
  src/languages/en.js
  src/languages/es.js
  src/libs/HttpUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/User.js
  src/pages/NewChatPage.js
  src/pages/NewGroupPage.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/report/EmojiPickerMenu/getSkinToneEmojiFromIndex.js
  src/pages/home/report/EmojiPickerMenu/index.js
  src/pages/home/report/EmojiPickerMenu/index.native.js
  src/pages/home/report/EmojiPickerMenuItem.js
  src/pages/home/report/EmojiSkinToneList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Profile/currentUserPersonalDetailsPropsTypes.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/styles/animation/SpinningIndicatorAnimation.js
  src/styles/getAvatarWithIndicatorStyles.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#5201 Update version to 1.0.96-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5202 Update version to 1.0.96-1 on staging
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/AttachmentPickerPropTypes.js
  src/components/AttachmentPicker/index.js
  src/components/AttachmentPicker/index.native.js
  src/components/AvatarWithImagePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5206 Update version to 1.0.97-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5207 Update version to 1.0.97-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5221 Update version to 1.0.97-0 on production
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/AttachmentPickerPropTypes.js
  src/components/AttachmentPicker/index.js
  src/components/AttachmentPicker/index.native.js
  src/components/AvatarWithImagePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5222 Update version to 1.0.97-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5223 Update version to 1.0.97-1 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/index.native.js
  src/components/FAB/FAB.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/PaymentMethods.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/PaymentMethodList.js
Labels: automerge

#5225 Update version to 1.0.97-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5226 Update version to 1.0.97-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/EmojiUtils.js
  src/libs/ValidationUtils.js
  src/pages/home/report/ReportActionItemFragment.js
  tests/unit/EmojiRegexTest.js
Labels: automerge

#5227 Update version to 1.0.97-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5228 Update version to 1.0.97-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/SignInRedirect.js
Labels: automerge

#5230 Update version to 1.0.98-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5231 Update version to 1.0.98-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5243 [Deploy Blocker] Changed max length to 11 for alignment issues
  src/CONST.js
  src/pages/iou/steps/IOUAmountPage.js
Labels: CP Staging

#5272 Update version to 1.0.98-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5273 🍒 Cherry pick PR #5243 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#5276 Update version to 1.0.98-1 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/index.native.js
  src/components/FAB/FAB.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/ValidationUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/SignInRedirect.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  tests/unit/EmojiRegexTest.js
Labels: automerge

#5277 Update version to 1.0.98-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5278 Update version to 1.0.98-2 on staging
  .github/workflows/preDeploy.yml
  CONTRIBUTING.md
  android/app/build.gradle
  android/app/src/main/res/values/styles.xml
  assets/images/bankicons/expensify.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/baseExpensiTextInputPropTypes.js
  src/components/ExpensiTextInput/index.android.js
  src/components/ExpensiTextInput/index.ios.js
  src/components/ExpensiTextInput/index.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/Icon/BankIcons.js
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/components/LocalePicker.js
  src/components/OptionsList.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Permissions.js
  src/libs/Pusher/EventType.js
  src/libs/ValidationUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/libs/reportUtils.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/settings/AboutPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5281 Update version to 1.0.98-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5282 Update version to 1.0.98-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: automerge

#5283 Update version to 1.0.99-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5284 Update version to 1.0.99-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5288 Revert PR #5037
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Pusher/EventType.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
Labels: CP Staging

#5292 Update version to 1.0.99-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5293 🍒 Cherry pick PR #5288 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Pusher/EventType.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
Labels: automerge

#5307 Add safety net for timezone in DateUtils
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: CP Staging

#5313 Update version to 1.0.99-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5314 🍒 Cherry pick PR #5307 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: automerge

#5330 Check isOnfidoSetupComplete in the requestor step to prevent showing it again
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: CP Staging

#5334 Update version to 1.0.99-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5335 🍒 Cherry pick PR #5330 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: automerge

#5360 Revert "Skip showing create for new users if user already has a workspace"
  src/pages/home/sidebar/SidebarScreen.js
Labels: CP Staging

#5361 Update version to 1.0.99-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5362 🍒 Cherry pick PR #5360 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#5365 Update version to 1.0.99-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5366 Update version to 1.0.99-4 on production
  .github/workflows/preDeploy.yml
  CONTRIBUTING.md
  android/app/build.gradle
  android/app/src/main/res/values/styles.xml
  assets/images/bankicons/expensify.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/baseExpensiTextInputPropTypes.js
  src/components/ExpensiTextInput/index.android.js
  src/components/ExpensiTextInput/index.ios.js
  src/components/ExpensiTextInput/index.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/Icon/BankIcons.js
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/components/LocalePicker.js
  src/components/OptionsList.js
  src/languages/en.js
  src/languages/es.js
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Permissions.js
  src/libs/ValidationUtils.js
  src/libs/reportUtils.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/settings/AboutPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5367 Update version to 1.0.99-5 on staging
  .github/ISSUE_TEMPLATE/Standard.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  android/app/build.gradle
  assets/images/bankicons/expensify.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/AttachmentPicker/index.native.js
  src/components/Checkbox.js
  src/components/CheckboxWithLabel.js
  src/components/ExpensiPicker.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/Hoverable/HoverablePropTypes.js
  src/components/Hoverable/index.js
  src/components/Icon/BankIcons.js
  src/components/InlineErrorText.js
  src/components/StatePicker.js
  src/components/Tooltip/TooltipPropTypes.js
  src/components/Tooltip/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ValidationUtils.js
  src/libs/Visibility/index.native.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session.js
  src/libs/getBrowser/index.web.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ExistingOwners.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/PasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/pages/workspace/WorkspaceSidebar.js
  src/stories/CheckboxWithLabel.stories.js
  src/styles/styles.js
Labels: automerge

#5371 Update version to 1.0.99-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5372 Update version to 1.0.99-6 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5373 Update version to 1.0.99-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5374 Update version to 1.0.99-7 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5375 Update version to 1.0.99-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5376 Update version to 1.0.99-8 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/reportUtils.js
  src/pages/home/ReportScreen.js
Labels: automerge

#5377 Update version to 1.1.0-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5378 Update version to 1.1.0-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5379 Update version to 1.1.0-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5380 🍒 Cherry pick PR #5369 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#5401 Update version to 1.1.0-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5402 🍒 Cherry pick PR #5398 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/actions/Session.js
  src/pages/SetPasswordPage.js
Labels: automerge

#5407 Update version to 1.1.0-2 on production
  .github/ISSUE_TEMPLATE/Standard.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/platformDeploy.yml
  CONTRIBUTING.md
  android/app/build.gradle
  assets/images/bankicons/expensify.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/AttachmentPicker/index.native.js
  src/components/Checkbox.js
  src/components/CheckboxWithLabel.js
  src/components/ExpensiPicker.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/Hoverable/HoverablePropTypes.js
  src/components/Hoverable/index.js
  src/components/Icon/BankIcons.js
  src/components/InlineErrorText.js
  src/components/StatePicker.js
  src/components/Tooltip/TooltipPropTypes.js
  src/components/Tooltip/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ValidationUtils.js
  src/libs/Visibility/index.native.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session.js
  src/libs/getBrowser/index.web.js
  src/libs/reportUtils.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ExistingOwners.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/SetPasswordPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/PasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/pages/workspace/WorkspaceSidebar.js
  src/stories/CheckboxWithLabel.stories.js
  src/styles/styles.js
Labels: automerge

#5408 Update version to 1.1.0-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5409 Update version to 1.1.0-3 on staging
  .github/ISSUE_TEMPLATE/Accessibility.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/CheckboxWithLabel.js
  src/components/InboxCallButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/actions/App.js
  src/libs/actions/Session.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/workspace/WorkspacePeoplePage.js
Labels: automerge

#5413 Update version to 1.1.1-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5414 Update version to 1.1.1-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5270 fix: message highlight issue & mini context-menu issue
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
Labels: n6-hold

#5419 Update version to 1.1.1-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5420 🍒 Cherry pick PR #5396 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/SCREENS.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/Session.js
  src/pages/LogInWithShortLivedTokenPage.js
  src/pages/workspace/WorkspaceNew.js
Labels: automerge

#5425 Avoid logging AuthToken from transition links
  src/libs/Navigation/NavigationRoot.js
Labels: CP Staging

#5426 Update version to 1.1.1-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5427 🍒 Cherry pick PR #5425 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/NavigationRoot.js
Labels: automerge

#5430 Rename route so that we expect traditional query paramters
  src/ROUTES.js
  src/libs/Navigation/NavigationRoot.js
Labels: CP Staging

#5433 Update version to 1.1.1-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5434 🍒 Cherry pick PR #5430 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/libs/Navigation/NavigationRoot.js
Labels: automerge

#5394 Dont toggle create menu if we already have a free policy
  src/libs/actions/Policy.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: CP Staging

#5436 Update version to 1.1.1-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5437 🍒 Cherry pick PR #5394 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#5439 Add spinner so policy links don't break
  src/pages/workspace/WorkspaceSidebar.js
Labels: CP Staging

#5440 Update version to 1.1.1-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5441 🍒 Cherry pick PR #5439 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5443 Fix navigating to workspace by preloading betas
  src/pages/LogInWithShortLivedTokenPage.js
Labels: CP Staging

#5453 Update version to 1.1.1-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5454 🍒 Cherry pick PR #5443 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/LogInWithShortLivedTokenPage.js
Labels: automerge

#5466 Use correct api params for NewDot>OldDot links
  src/libs/actions/App.js
Labels: CP Staging

#5186 Return to the correct sub step in VBA flow after error in adding Bank Account manually
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/BankAccountStep.js
Labels: CP Staging

#5469 Update version to 1.1.1-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5470 Update version to 1.1.1-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5471 🍒 Cherry pick PR #5466 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/App.js
Labels: automerge

#5472 🍒 Cherry pick PR #5186 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/BankAccountStep.js
Labels: automerge

#5474 Update version to 1.1.1-8 on production
  .github/ISSUE_TEMPLATE/Accessibility.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/SCREENS.js
  src/components/CheckboxWithLabel.js
  src/components/InboxCallButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Session.js
  src/pages/LogInWithShortLivedTokenPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BeneficialOwnersStep.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/workspace/WorkspaceNew.js
  src/pages/workspace/WorkspacePeoplePage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#5475 Update version to 1.1.1-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5476 Update version to 1.1.1-9 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Onfido/index.js
  src/components/Onfido/index.native.js
  src/components/Onfido/onfidoPropTypes.js
  src/components/PDFView/index.js
  src/components/PDFView/index.native.js
  src/components/Text.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/actions/BankAccounts.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
Labels: automerge

#5479 Update version to 1.1.1-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5480 Update version to 1.1.1-10 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/Navigation.js
Labels: automerge

#5485 Moves all free plan beta checks to use free plan soft launch beta
  src/CONST.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/Navigation.js
  src/libs/Permissions.js
  src/pages/LoginWithValidateCode2FAPage.js
  src/pages/LoginWithValidateCodePage.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/workspace/WorkspaceCardPage.js
  src/pages/workspace/WorkspaceEditorPage.js
  src/pages/workspace/WorkspacePeoplePage.js
Labels: CP Staging

#5486 Update version to 1.1.1-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5488 Update version to 1.1.1-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#5489 Update version to 1.1.2-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
