Repository Expensify/App, pull requests merged in 2021-07, with the labels that each got.

#3847 Fix particpant related and searching behavior for default rooms.
  src/libs/OptionsListUtils.js
Labels: InternalQA

#3845 Fix domain all rooms' subtitle
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/OptionsListUtils.js
  src/libs/reportUtils.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
Labels: InternalQA

#3903 Update version to 1.0.75-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3906 Update version to 1.0.75-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3907 Update version to 1.0.75-7 on staging
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getMergeCommitForPullRequest/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3910 Update version to 1.0.75-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3911 Update version to 1.0.75-8 on staging
  .github/actions/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3914 Update version to 1.0.75-9 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3915 Update version to 1.0.75-9 on staging
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3916 Update version to 1.0.75-10 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3917 Update version to 1.0.75-10 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#3918 Update version to 1.0.75-11 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3919 Update version to 1.0.75-11 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
Labels: automerge

#3929 Update version to 1.0.76-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3930 Update version to 1.0.76-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3932 Fix IOU currency routes
  src/ROUTES.js
  src/libs/Navigation/linkingConfig.js
Labels: CP Staging

#3934 Update version to 1.0.76-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3935 🍒 Cherry pick PR #3932 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/libs/Navigation/linkingConfig.js
Labels: automerge

#3948 Update version to 1.0.76-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3949 🍒 Cherry pick PR #3908 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
Labels: automerge

#3955 Update version to 1.0.76-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3961 Update version to 1.0.77-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3962 Update version to 1.0.77-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3891 Add avatars based on svg icons for default rooms
  assets/images/avatars/room.svg
  src/components/Avatar.js
  src/components/MultipleAvatars.js
  src/libs/OptionsListUtils.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/OptionRow.js
Labels: InternalQA

#3989 Make button visible in WorkspaceInvitePage
  src/pages/workspace/WorkspaceInvitePage.js
Labels: CP Staging

#3990 Update version to 1.0.77-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3991 🍒 Cherry pick PR #3989 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#3966 Only provide a default lineHeight when the fontSize is default
  src/components/Text.js
Labels: CP Staging

#3996 Update version to 1.0.77-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3997 🍒 Cherry pick PR #3966 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/Text.js
Labels: automerge

#3967 Add link to Concierge on Validation screen when bank account is verifying
  src/CONST.js
  src/ROUTES.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/Navigation.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/workspace/NewWorkspacePage.js
  src/pages/workspace/WorkspaceCardPage.js
Labels: InternalQA

#4020 Fix display of report typing indicator and participant local time
  src/languages/en.js
  src/languages/es.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportTypingIndicator.js
  src/styles/styles.js
Labels: CP Staging

#4032 Update version to 1.0.77-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4033 🍒 Cherry pick PR #4020 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportTypingIndicator.js
  src/styles/styles.js
Labels: Engineering, Hourly, automerge

#3894 Get&returnValueList=reportSummaryList
  src/libs/API.js
  src/libs/actions/Report.js
Labels: InternalQA

#4016 [No QA] Change expensify.cash => new.expensify.com
  .env.example
  .env.production
  .env.staging
  .github/workflows/platformDeploy.yml
  CONTRIBUTING.md
  README.md
  android/app/src/main/AndroidManifest.xml
  package.json
  src/CONFIG.js
  src/CONST.js
  src/libs/Navigation/linkingConfig.js
Labels: CP Staging

#4038 Update version to 1.0.77-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4039 🍒 Cherry pick PR #4016 to staging 🍒
  .env.example
  .env.production
  .env.staging
  .github/workflows/platformDeploy.yml
  CONTRIBUTING.md
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/libs/Navigation/linkingConfig.js
Labels: automerge

#4037 [No QA] Fix incorect staging url
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#4041 Update version to 1.0.77-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4042 🍒 Cherry pick PR #4037 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4044 Update version to 1.0.77-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4048 [No QA] Changed App Store Icon
  ios/ExpensifyCash/Images.xcassets/AppIcon.appiconset/Store.png
Labels: CP Staging

#4050 Update version to 1.0.77-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4051 Update version to 1.0.77-7 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Images.xcassets/AppIcon.appiconset/Store.png
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4053 Update version to 1.0.78-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4054 Update version to 1.0.78-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4059 [CP Staging] Don't show all chats in LHN in #focus mode
  src/libs/actions/Report.js
Labels: CP Staging

#4064 Update version to 1.0.78-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4065 🍒 Cherry pick PR #4059 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#4085 Reverting 3979
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Report.js
Labels: CP Staging

#4087 Update version to 1.0.78-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4088 🍒 Cherry pick PR #4085 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Report.js
Labels: automerge

#4092 Update version to 1.0.78-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4093 Update version to 1.0.78-3 on staging
  CONTRIBUTING.md
  README.md
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/components/Button.js
  src/components/ConfirmModal.js
  src/components/IOUConfirmationList.js
  src/components/InvertedFlatList/index.android.js
  src/components/InvertedFlatList/index.ios.js
  src/components/InvertedFlatList/index.js
  src/components/Modal/BaseModal.js
  src/components/RenderHTML/index.js
  src/components/StatePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/OptionsListUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/workspace/NewWorkspacePage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#4094 Update version to 1.0.78-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4095 Update version to 1.0.78-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4099 Update version to 1.0.78-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4100 Update version to 1.0.78-5 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4102 Update version to 1.0.79-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4103 Update version to 1.0.79-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4117 [CP Staging] Remove duplicate form fields
  src/pages/workspace/WorkspaceInvitePage.js
Labels: CP Staging

#4124 Update version to 1.0.79-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4125 🍒 Cherry pick PR #4117 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#4148 Update version to 1.0.79-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4149 🍒 Cherry pick PR #4131 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInputFocusable/index.js
Labels: automerge

#4143 Modify line height so text does not get cut off in LHN
  src/styles/styles.js
Labels: CP Staging

#4151 Update version to 1.0.79-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4152 🍒 Cherry pick PR #4143 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#4165 Prevent infinite loading in validateBankAccount
  src/libs/actions/BankAccounts.js
Labels: InternalQA

#4192 Update version to 1.0.79-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4193 🍒 Cherry pick PR #4019 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/IOUConfirmationList.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/OptionsListUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUConfirmPage.js
Labels: automerge

#4196 Update version to 1.0.79-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4201 Update version to 1.0.79-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4202 Update version to 1.0.79-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/RenderHTML/BaseRenderHTML.js
Labels: automerge

#4203 Update version to 1.0.80-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4204 Update version to 1.0.80-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4243 Web - Settings - Dropdown symbol overlaps with text in the box
  src/pages/settings/AboutPage.js
  src/styles/styles.js
Labels: CP Staging

#4244 Update version to 1.0.80-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4245 🍒 Cherry pick PR #4243 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/AboutPage.js
  src/styles/styles.js
Labels: automerge

#4239 Make sure we get state/status from the right variable name when we get chat report name
  src/libs/actions/Report.js
Labels: CP Staging

#4248 Update version to 1.0.80-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4249 🍒 Cherry pick PR #4239 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#4227 Remove Bintray repository to speed up Android builds
  android/build.gradle
Labels: InternalQA

#4277 Update version to 1.0.80-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4281 Update version to 1.0.81-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4282 Update version to 1.0.81-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4286 Fix staging due to undefined Onyx key
  src/components/LocalePicker.js
  src/libs/actions/SignInRedirect.js
Labels: CP Staging

#4288 Update version to 1.0.81-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4289 🍒 Cherry pick PR #4286 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/LocalePicker.js
  src/libs/actions/SignInRedirect.js
Labels: automerge

#4303 Update version to 1.0.81-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4300 Fix broken list components on staging
  src/components/OptionsList.js
Labels: CP Staging

#4305 Update version to 1.0.81-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4306 🍒 Cherry pick PR #4300 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsList.js
Labels: automerge

#4322 Patch for PR #4190
  src/pages/settings/Profile/ProfilePage.js
Labels: CP Staging

#4326 Update version to 1.0.81-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4327 🍒 Cherry pick PR #4322 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#4331 Update version to 1.0.81-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4332 Update version to 1.0.81-5 on staging
  .github/ISSUE_TEMPLATE/Standard.md
  android/app/build.gradle
  android/app/src/debug/java/com/reactnativechat/ReactNativeFlipper.java
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/gradle.properties
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/Badge.js
  src/components/EnvironmentBadge.js
  src/components/IOUBadge.js
  src/components/MenuItem.js
  src/components/PopoverWithMeasuredContent.js
  src/components/ReportTransaction.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/DateUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/SearchPage.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/GenericReportActionContextMenuPropTypes.js
  src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
  src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.native.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportActionContextMenu.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportTypingIndicator.js
  src/pages/settings/InitialPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/setup/index.native.js
  src/styles/addOutlineWidth/index.js
  src/styles/styles.js
  src/styles/utilities/sizing.js
  tests/unit/NetworkTest.js
  tests/unit/TranslateTest.js
  web/index.html
Labels: automerge

#4334 Update version to 1.0.81-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4335 Update version to 1.0.81-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/libs/API.js
  src/libs/actions/App.js
  src/pages/workspace/WorkspaceCardPage.js
Labels: automerge

#4340 Update version to 1.0.81-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4341 Update version to 1.0.81-7 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/App.js
  src/components/withLocalize.js
Labels: automerge

#4343 Update version to 1.0.81-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4344 Update version to 1.0.81-8 on staging
  android/app/build.gradle
  assets/images/arrow-up.svg
  assets/images/printer.svg
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/CollapsibleSection/Collapsible/index.js
  src/components/CollapsibleSection/Collapsible/index.native.js
  src/components/CollapsibleSection/CollapsibleSectionPropTypes.js
  src/components/CollapsibleSection/index.js
  src/components/Icon/Expensicons.js
  src/languages/en.js
  src/languages/es.js
  src/pages/EnablePayments/TermsPage/LongTermsForm.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/EnablePayments/TermsStep.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#4346 Update version to 1.0.82-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4347 Update version to 1.0.82-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
