Repository Expensify/App, pull requests merged in 2021-11, with the labels that each got.

#6141 Update version to 1.1.11-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6142 Update version to 1.1.11-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialPage.js
Labels: automerge

#6143 Update version to 1.1.11-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6144 Update version to 1.1.11-6 on staging
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/DrawerNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/drawerNavigatorPropTypes.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.native.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/CustomActions.js
Labels: automerge

#6145 Update version to 1.1.12-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6146 Update version to 1.1.12-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6156 Remove lineHeight from baseFontStyle to stop text from flowing into links
  src/styles/styles.js
Labels: CP Staging

#6162 Update version to 1.1.12-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6163 🍒 Cherry pick PR #6156 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#6161 Revert "Fix: back handler for Drawer"
  config/webpack/webpack.common.js
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/drawerNavigatorPropTypes.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.native.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/CustomActions.js
Labels: CP Staging

#6166 Update version to 1.1.12-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6167 🍒 Cherry pick PR #6161 to staging 🍒
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/drawerNavigatorPropTypes.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.js
  src/libs/Navigation/AppNavigator/DrawerNavigator/index.native.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/CustomActions.js
Labels: automerge

#6168 Use git+https when loading expensify-common
  package-lock.json
  package.json
Labels: CP Staging

#6170 Update version to 1.1.12-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6171 🍒 Cherry pick PR #6168 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6179 Update version to 1.1.12-3 on production
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/java/com/expensify/chat/generated/BasePackageList.java
  android/settings.gradle
  ios/NewExpensify/AppDelegate.h
  ios/NewExpensify/AppDelegate.m
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly/index.native.js
  src/components/AttachmentView.js
  src/components/AvatarWithIndicator.js
  src/components/PressableWithSecondaryInteraction/index.android.js
  src/components/PressableWithSecondaryInteraction/index.ios.js
  src/components/TextLink.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialPage.js
  src/styles/styles.js
Labels: automerge

#6180 Update version to 1.1.12-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6181 Update version to 1.1.12-4 on staging
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/IOUConfirmationList.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Inbox.js
  src/libs/actions/Report.js
  src/libs/actions/Session.js
  src/libs/actions/User.js
  src/pages/RequestCallPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportTypingIndicator.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
Labels: automerge

#6188 Update version to 1.1.13-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6191 Fix an apostrophe to trigger a CP Build
  src/languages/en.js
Labels: CP Staging

#6193 Update version to 1.1.13-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6194 🍒 Cherry pick PR #6191 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
Labels: automerge

#6201 Update popover menu check to use isEmpty
  src/components/PopoverMenu/BasePopoverMenu.js
Labels: CP Staging

#6214 Update version to 1.1.13-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6215 🍒 Cherry pick PR #6201 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/PopoverMenu/BasePopoverMenu.js
Labels: automerge

#6219 Update version to 1.1.13-2 on production
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/IOUConfirmationList.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Inbox.js
  src/libs/actions/Report.js
  src/libs/actions/Session.js
  src/libs/actions/User.js
  src/pages/RequestCallPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportTypingIndicator.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
Labels: automerge

#6220 Update version to 1.1.13-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6221 Update version to 1.1.13-3 on staging
  android/app/build.gradle
  assets/images/example-check-image-en.png
  assets/images/example-check-image-es.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/HeaderWithCloseButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/exampleCheckImage.js
  src/pages/SetPasswordPage.js
  src/pages/ValidateLoginPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/validateLinkPropTypes.js
  src/styles/utilities/spacing.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#6224 Update version to 1.1.13-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/codeStyles/index.ios.js
Labels: automerge

#6225 Update version to 1.1.14-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6226 Update version to 1.1.14-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6240 [CP Staging] Fix blank page upon signing out
  src/pages/home/sidebar/SidebarLinks.js
Labels: CP Staging

#6243 Update version to 1.1.14-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6244 🍒 Cherry pick PR #6240 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/sidebar/SidebarLinks.js
Labels: automerge

#6252 Removing draft comments param
  src/pages/home/sidebar/SidebarLinks.js
Labels: CP Staging

#6254 Update version to 1.1.14-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6255 🍒 Cherry pick PR #6252 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/sidebar/SidebarLinks.js
Labels: automerge

#6262 Update version to 1.1.14-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6264 Update version to 1.1.14-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6265 🍒 Cherry pick PR #6257 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
Labels: automerge

#6102 Start generating internal QA checklist with assignments
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/GithubUtils.js
  tests/unit/GithubUtilsTest.js
Labels: InternalQA

#6303 Update version to 1.1.14-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6302 Update version to 1.1.14-4 on production
  android/app/build.gradle
  assets/images/example-check-image-en.png
  assets/images/example-check-image-es.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/HeaderWithCloseButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/exampleCheckImage.js
  src/pages/SetPasswordPage.js
  src/pages/ValidateLoginPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/validateLinkPropTypes.js
  src/styles/codeStyles/index.ios.js
  src/styles/utilities/spacing.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#6307 Update version to 1.1.14-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6308 Update version to 1.1.14-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/Pusher/EventType.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: automerge

#6311 Update version to 1.1.15-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6312 Update version to 1.1.15-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6313 Revert "Deep link to add secondary login in OldDot"
  src/languages/en.js
  src/languages/es.js
  src/libs/Pusher/EventType.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: CP Staging

#6317 Update version to 1.1.15-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6318 🍒 Cherry pick PR #6313 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/Pusher/EventType.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: automerge

#6327 Fix blank screen displayed on Company Step VBA flow
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: CP Staging

#6330 Update version to 1.1.15-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6331 🍒 Cherry pick PR #6327 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: automerge

#6332 Fix switching to manual address when adding bank account
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: CP Staging

#6338 Update version to 1.1.15-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6339 🍒 Cherry pick PR #6332 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: automerge

#6341 Pass translateX prop to TextInput component
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: CP Staging

#6342 Update version to 1.1.15-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6349 Update version to 1.1.15-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6351 Update version to 1.1.15-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6353 Update version to 1.1.15-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6354 Update version to 1.1.15-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6355 🍒 Cherry pick PR #6341 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: automerge

#6365 Update README.md
  README.md
Labels: Emergency

#6369 Update version to 1.1.15-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6370 🍒 Cherry pick PR #6366 to staging 🍒
  android/app/build.gradle
  apple-app-site-association
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6368 Sign commits for @OSBotify
  .github/workflows/OSBotify-private-key.asc.gpg
  .github/workflows/createNewVersion.yml
Labels: CP Staging

#6371 Import from the GPG key from the right directory
  .github/workflows/createNewVersion.yml
Labels: CP Staging

#6372 Update version to 1.1.15-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6374 [No QA] Update botify workflows to use new signing key
  .github/workflows/cherryPick.yml
  .github/workflows/deploy.yml
  .github/workflows/updateProtectedBranch.yml
Labels: CP Staging

#6375 Update version to 1.1.15-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6376 Update version to 1.1.15-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6378 Update version to 1.1.15-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6380 Update version to 1.1.15-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6382 Update version to 1.1.15-15 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6383 🍒 Cherry pick PR #6381 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6393 Update version to 1.1.15-16 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6394 Update version to 1.1.15-17 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6397 Update version to 1.1.15-18 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6400 Update version to 1.1.15-19 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6401 Update version to 1.1.15-19 on staging
  .well-known/apple-app-site-association
  android/app/build.gradle
  apple-app-site-association
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/ValidationUtils.js
  src/libs/actions/User.js
  src/pages/settings/PasswordPage.js
Labels: automerge

#6402 Update version to 1.1.15-20 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6403 Update version to 1.1.15-20 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6362 Update Plaid Link Component
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/PlaidLink/index.native.js
Labels: CP Staging

#6404 Update version to 1.1.15-21 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6405 🍒 Cherry pick PR #6362 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/PlaidLink/index.native.js
Labels: automerge

#6406 Update version to 1.1.16-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6407 Update version to 1.1.16-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6408 [No QA] Update webpack path for apple app association
  config/webpack/webpack.common.js
Labels: CP Staging

#6409 Update version to 1.1.16-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6410 🍒 Cherry pick PR #6408 to staging 🍒
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6419 Strip prefix and translate pronouns when needed
  src/components/ReportWelcomeText.js
Labels: CP Staging

#6420 Update version to 1.1.16-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6421 🍒 Cherry pick PR #6419 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportWelcomeText.js
Labels: automerge

#6430 [No QA] Update webpack so the apple association file is served from .well-known directory
  config/webpack/webpack.common.js
Labels: CP Staging

#6443 Update version to 1.1.16-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6444 🍒 Cherry pick PR #6441 to staging 🍒
  android/app/build.gradle
  build/react-native-web.sh
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/InvertedFlatList/index.js
Labels: automerge

#6445 Update version to 1.1.16-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6446 🍒 Cherry pick PR #6433 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/AddSecondaryLoginPage.js
Labels: automerge

#6447 Update version to 1.1.16-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6448 🍒 Cherry pick PR #6417 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnimatedStep.js
  src/pages/iou/IOUModal.js
Labels: automerge

#6440 Testing #32409 (part2)
  README.md
Labels: InternalQA

#6451 Update version to 1.1.16-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6452 🍒 Cherry pick PR #6319 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/Pusher/EventType.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: automerge, Engineering, Hourly

#6463 Update version to 1.1.16-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6464 🍒 Cherry pick PR #6459 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#6467 Update version to 1.1.16-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6468 🍒 Cherry pick PR #6458 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#6479 Encode secondary login URL
  src/CONST.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: CP Staging

#6480 Update version to 1.1.16-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6481 🍒 Cherry pick PR #6479 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/workspace/card/WorkspaceCardVBANoECardView.js
Labels: automerge, Engineering, Hourly

#6483 [No QA] Fix const import on staging
  src/pages/ReimbursementAccount/EnableStep.js
Labels: CP Staging

#6493 Update version to 1.1.16-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6494 🍒 Cherry pick PR #6483 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/EnableStep.js
Labels: automerge, Engineering, Hourly

#6503 Update version to 1.1.16-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6506 Update version to 1.1.16-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6507 Update version to 1.1.16-12 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/AddSecondaryLoginPage.js
Labels: automerge

#6165 Do not include CP merge commits in the list of PR merge commits
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  tests/unit/GitUtilsTest.js
Labels: Internal

#6509 Update version to 1.1.16-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6510 Update version to 1.1.16-13 on staging
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/GitUtilsTest.js
Labels: automerge

#6513 Update version to 1.1.17-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6514 Update version to 1.1.17-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6411 Get parameters for Plaid link token based on platform
  src/CONST.js
  src/libs/API.js
  src/libs/getPlaidLinkTokenParameters/index.android.js
  src/libs/getPlaidLinkTokenParameters/index.ios.js
  src/libs/getPlaidLinkTokenParameters/index.js
  src/pages/ReimbursementAccount/BankAccountStep.js
Labels: CP Staging, InternalQA

#6516 Update version to 1.1.17-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6517 🍒 Cherry pick PR #6411 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/API.js
  src/libs/getPlaidLinkTokenParameters/index.android.js
  src/libs/getPlaidLinkTokenParameters/index.ios.js
  src/libs/getPlaidLinkTokenParameters/index.js
  src/pages/ReimbursementAccount/BankAccountStep.js
Labels: automerge

#6531 Fix infinite loop in withFullPolicy HOC
  src/pages/workspace/withFullPolicy.js
Labels: CP Staging

#6532 Update version to 1.1.17-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6533 🍒 Cherry pick PR #6531 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/withFullPolicy.js
Labels: automerge

#6523 Revert "Supports big screens mobile devices for popover menu"
  src/components/Popover/index.native.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: CP Staging

#6540 Update version to 1.1.17-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6541 🍒 Cherry pick PR #6523 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Popover/index.native.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/pages/home/sidebar/SidebarScreen.js
Labels: automerge

#6548 Revert "Remove div usage in Onfido Web"
  src/components/Onfido/index.js
Labels: CP Staging

#6549 Update version to 1.1.17-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6551 🍒 Cherry pick PR #6548 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Onfido/index.js
Labels: automerge
