Repository Expensify/App, pull requests merged in 2021-08, with the labels that each got.

#4358 Fix User is able to upload a file larger than 50mb
  src/components/AttachmentPicker/index.native.js
Labels: CP Staging

#4368 Update version to 1.0.82-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4369 🍒 Cherry pick PR #4358 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
Labels: automerge

#4372 Update version to 1.0.82-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4373 🍒 Cherry pick PR #4339 to staging 🍒
  .github/workflows/createNewVersion.yml
  .github/workflows/e2e.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#4237 [InternalQA] Update Workspace button text during pending account validation
  src/CONST.js
  src/pages/workspace/WorkspaceCardPage.js
Labels: InternalQA

#4366 Fix: Selecting a language does not update in real time
  src/components/withLocalize.js
Labels: CP Staging

#4389 Update version to 1.0.82-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4390 🍒 Cherry pick PR #4366 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/withLocalize.js
Labels: automerge

#4416 Attempt at fixing race
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: CP Staging

#4427 Update version to 1.0.82-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4428 🍒 Cherry pick PR #4416 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: automerge

#4429 Update version to 1.0.82-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4430 🍒 Cherry pick PR #4397 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session.js
Labels: automerge

#4400 [No QA] Catch http errors that don't trigger `.then()`
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/BankAccounts.js
Labels: InternalQA

#4436 Race fix attempt 2
  src/pages/home/HeaderView.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: CP Staging

#4438 Update version to 1.0.82-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4439 🍒 Cherry pick PR #4436 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/HeaderView.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: automerge

#4336 Update getPullRequestsMergedBetween to run pre-set string command
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
Labels: CP Staging

#4441 Update version to 1.0.82-7 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4442 🍒 Cherry pick PR #4336 to staging 🍒
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4445 Update version to 1.0.82-8 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4449 Update version to 1.0.82-9 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4450 Update version to 1.0.82-9 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/signin/SignInPageLayout/SignInPageLayoutNarrow.js
  src/styles/styles.js
Labels: automerge

#4451 Update version to 1.0.82-10 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4452 Update version to 1.0.82-10 on staging
  CONTRIBUTING.md
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4454 Update version to 1.0.82-11 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4455 Update version to 1.0.82-11 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/AuthScreens.js
Labels: automerge

#4457 Update version to 1.0.83-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4458 Update version to 1.0.83-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#3414 Create custom TextInput
  ios/Podfile.lock
  src/components/AddPlaidBankAccount.js
  src/components/ExpensiPicker.js
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/ExpensiTextInputLabel/index.js
  src/components/ExpensiTextInput/ExpensiTextInputLabel/index.native.js
  src/components/ExpensiTextInput/ExpensiTextInputLabel/propTypes.js
  src/components/ExpensiTextInput/index.android.js
  src/components/ExpensiTextInput/index.ios.js
  src/components/ExpensiTextInput/index.js
  src/components/ExpensiTextInput/propTypes.js
  src/components/FullNameInputRow.js
  src/components/IOUConfirmationList.js
  src/components/LocalePicker.js
  src/components/MenuItem.js
  src/components/OptionsSelector.js
  src/components/Picker/PickerPropTypes.js
  src/components/Picker/index.js
  src/components/Picker/pickerDisabledStyles/index.android.js
  src/components/Picker/pickerDisabledStyles/index.ios.js
  src/components/Picker/pickerDisabledStyles/index.js
  src/components/Picker/pickerStyles/index.android.js
  src/components/Picker/pickerStyles/index.ios.js
  src/components/Picker/pickerStyles/index.js
  src/components/TextInputWithLabel.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/TermsPage/LongTermsForm.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/RequestCallPage.js
  src/pages/ValidateLogin2FANewWorkspacePage.js
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/InitialPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutNarrow.js
  src/pages/workspace/NewWorkspacePage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: Design

#4474 [InternalQA] Update Onyx after validating bank account
  src/libs/actions/BankAccounts.js
Labels: InternalQA

#4535 Update version to 1.0.83-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4536 🍒 Cherry pick PR #4503 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/InlineCodeBlock/index.native.js
  src/components/RenderHTML/BaseRenderHTML.js
  src/styles/styles.js
Labels: automerge

#4552 Update version to 1.0.83-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4480 [InternalQA] Prevent UI change on VBA flow during data fetch
  src/libs/actions/BankAccounts.js
Labels: InternalQA

#4555 Update version to 1.0.83-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4557 Update version to 1.0.83-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4558 Update version to 1.0.83-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4560 Update version to 1.0.83-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4561 Update version to 1.0.83-5 on staging
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getMergeCommitForPullRequest/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/GithubUtils.js
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/Expensify.js
  src/ROUTES.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/Policy.js
  src/pages/ValidateLogin2FANewWorkspacePage.js
  src/pages/ValidateLoginNewWorkspacePage.js
  src/pages/workspace/NewWorkspacePage.js
  src/pages/workspace/WorkspaceSidebar.js
Labels: automerge

#4562 Update version to 1.0.83-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4563 Update version to 1.0.83-6 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4565 Update version to 1.0.84-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4566 Update version to 1.0.84-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4568 Make a dummy change for a test PR
  .github/workflows/README.md
Labels: CP Staging

#4570 Update version to 1.0.84-1 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4574 Update version to 1.0.84-2 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4575 Update version to 1.0.84-2 on staging
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/workflows/test.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4576 Cleanup dummy change
  .github/workflows/test.yml
Labels: CP Staging

#4580 Update version to 1.0.84-3 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4581 Update version to 1.0.84-3 on staging
  .github/workflows/README.md
  .github/workflows/test.yml
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4582 Update version to 1.0.84-4 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4583 Update version to 1.0.84-4 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4584 Update version to 1.0.84-5 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4585 Update version to 1.0.84-5 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/AddPlaidBankAccount.js
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#4587 Update version to 1.0.84-6 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4588 Update version to 1.0.85-0 on main
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4589 Update version to 1.0.85-0 on staging
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4613 Check for value before checking length
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: CP Staging

#4618 Update version to 1.0.85-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4614 Clear storage immediately on sign out
  src/libs/actions/SignInRedirect.js
Labels: CP Staging

#4619 🍒 Cherry pick PR #4613 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: automerge

#4620 Update version to 1.0.85-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4621 🍒 Cherry pick PR #4614 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/SignInRedirect.js
Labels: automerge

#4626 Update version to 1.0.85-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4627 🍒 Cherry pick PR #4593 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: automerge

#4632 Fix: autofill on the BaseExpensiInput
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: CP Staging

#4638 Update version to 1.0.85-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4639 🍒 Cherry pick PR #4632 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: automerge

#4641 Change picker value color
  src/styles/styles.js
Labels: CP Staging

#4642 Update version to 1.0.85-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4643 🍒 Cherry pick PR #4641 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#4603 Added new marker Badge for Report unread messages
  src/languages/en.js
  src/languages/es.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/MarkerBadge.js
  src/pages/home/report/ReportActionsView.js
  src/styles/styles.js
  src/styles/utilities/visibility/index.js
  src/styles/utilities/visibility/index.native.js
Labels: Design

#4633 Update state picker component in VBA flow
  src/components/StatePicker.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: CP Staging, InternalQA

#4651 Update version to 1.0.85-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4652 🍒 Cherry pick PR #4633 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/components/StatePicker.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: automerge

#4607 Hide Password mismatch incase both the passwords are empty
  src/pages/settings/PasswordPage.js
Labels: CP Staging

#4682 Update version to 1.0.85-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4683 🍒 Cherry pick PR #4607 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/PasswordPage.js
Labels: automerge

#4684 [CP Staging] Use props not state in NewPasswordForm
  src/pages/settings/NewPasswordForm.js
Labels: CP Staging

#4685 Update version to 1.0.85-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4686 🍒 Cherry pick PR #4684 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/NewPasswordForm.js
Labels: automerge

#4636 Changed Personal and Company Address Labels
  src/languages/en.js
  src/languages/es.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/styles/styles.js
Labels: Design

#4692 Update version to 1.0.85-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4693 🍒 Cherry pick PR #4636 to staging 🍒
  android/app/build.gradle
  ios/ExpensifyCash/Info.plist
  ios/ExpensifyCashTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/styles/styles.js
Labels: automerge

#4699 Update version to 1.0.85-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4703 Update version to 1.0.86-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4704 Update version to 1.0.86-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4706 Bump Onyx version to fix recent regressions
  package-lock.json
  package.json
Labels: CP Staging

#4708 Update version to 1.0.86-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4709 🍒 Cherry pick PR #4706 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4676 Update withOnyx to fix prop dependent key updates
  package-lock.json
  package.json
Labels: CP Staging

#4713 Update version to 1.0.86-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4714 🍒 Cherry pick PR #4676 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4721 Fix enable payments page with another Onyx update
  package-lock.json
  package.json
Labels: CP Staging

#4734 Update version to 1.0.86-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4735 🍒 Cherry pick PR #4721 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4761 Fix StagingDeployBlocker where chat draft message is kept in the test input while switching chats
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#4763 Update version to 1.0.86-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4764 🍒 Cherry pick PR #4761 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#4783 Update version to 1.0.86-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4784 Update version to 1.0.86-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4786 Update version to 1.0.86-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4787 🍒 Cherry pick PR #4774 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/MarkerBadge/MarkerBadgeContainer/MarkerBadgeContainerPropTypes.js
  src/pages/home/report/MarkerBadge/MarkerBadgeContainer/index.android.js
  src/pages/home/report/MarkerBadge/MarkerBadgeContainer/index.js
  src/pages/home/report/MarkerBadge/index.js
  src/styles/styles.js
Labels: automerge

#4790 Update version to 1.0.86-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4791 🍒 Cherry pick PR #4741 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
  src/components/ExpensiTextInput/propTypes.js
Labels: automerge

#4661 Added tooltips to all Icon buttons
  src/components/AvatarWithImagePicker.js
  src/components/HeaderWithCloseButton.js
  src/components/VideoChatButtonAndMenu.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/IOUModal.js
Labels: Waiting for copy

#4804 Update fastlane version
  Gemfile.lock
Labels: CP Staging

#4808 Update version to 1.0.86-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4809 🍒 Cherry pick PR #4804 to staging 🍒
  Gemfile.lock
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4811 Update version to 1.0.86-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4812 🍒 Cherry pick PR #4742 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: automerge

#4807 Remove unnecessary style causing bug in android
  src/components/ExpensiTextInput/BaseExpensiTextInput.js
Labels: CP Staging

#4813 Update version to 1.0.86-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4913 Update version to 1.0.88-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4914 Update version to 1.0.88-3 on staging
  .github/workflows/cherryPick.yml
  .github/workflows/deployBlocker.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/ExpensiTextInput/index.android.js
  src/components/ExpensiTextInput/index.ios.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/ImageView/index.js
  src/components/Picker/index.js
  src/components/Picker/pickerStyles/index.js
  src/components/VBALoadingIndicator.js
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Report.js
  src/libs/getBrowser/index.js
  src/libs/getBrowser/index.web.js
  src/libs/userUtils.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/RequestCallPage.js
  src/pages/home/report/EmojiPickerMenu/dynamicEmojiSize.js
  src/pages/home/report/EmojiPickerMenu/index.js
  src/pages/home/report/EmojiPickerMenu/index.native.js
  src/pages/home/report/EmojiPickerMenuItem.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/signin/TermsAndLicenses/TermsWithLicenses/index.ios.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceSidebar.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#4915 Add string comparison to boolean expressions
  .github/workflows/cherryPick.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#4920 Update version to 1.0.88-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4927 Properly JSON-decode outputs
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/finishReleaseCycle.yml
Labels: CP Staging

#4930 Update version to 1.0.88-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4931 Make dummy change in README
  .github/workflows/README.md
Labels: CP Staging

#4933 Update version to 1.0.88-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4935 Update version to 1.0.88-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4936 🍒 Cherry pick PR #4934 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/setup/index.website.js
Labels: automerge

#4937 Update version to 1.0.89-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4938 Update version to 1.0.89-0 on staging
  .github/actions/checkDeployBlockers/checkDeployBlockers.js
  .github/actions/checkDeployBlockers/index.js
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/libs/DateUtils.js
  src/libs/actions/BankAccounts.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/InitialPage.js
  src/pages/workspace/WorkspaceCardPage.js
  tests/unit/checkDeployBlockersTest.js
Labels: automerge

#4942 Update version to 1.0.90-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4943 Update version to 1.0.90-0 on staging
  .github/workflows/platformDeploy.yml
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4961 Allow builds to distribute to external testers
  fastlane/Fastfile
Labels: CP Staging

#4965 Update version to 1.0.90-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#4966 🍒 Cherry pick PR #4961 to staging 🍒
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
