Repository Expensify/App, pull requests merged in 2021-12, with the labels that each got.

#6259 [PlaidLink OAuth] Add web redirect_uri to `/bank-accounts` page
  src/ROUTES.js
  src/components/AddPlaidBankAccount.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/plaidLinkPropTypes.js
  src/libs/Navigation/linkingConfig.js
  src/libs/getPlaidLinkTokenParameters/index.android.js
  src/libs/getPlaidLinkTokenParameters/index.js
  src/libs/getPlaidOAuthReceivedRedirectURI/index.js
  src/libs/getPlaidOAuthReceivedRedirectURI/index.native.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
Labels: CP Staging

#6570 Update version to 1.1.17-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6571 🍒 Cherry pick PR #6259 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AddPlaidBankAccount.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/plaidLinkPropTypes.js
  src/libs/Navigation/linkingConfig.js
  src/libs/getPlaidLinkTokenParameters/index.android.js
  src/libs/getPlaidLinkTokenParameters/index.js
  src/libs/getPlaidOAuthReceivedRedirectURI/index.js
  src/libs/getPlaidOAuthReceivedRedirectURI/index.native.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
Labels: automerge, Engineering, Hourly

#6578 [CP STAGING] Fix redirect_uri for Plaid web
  src/libs/getPlaidLinkTokenParameters/index.js
Labels: CP Staging

#6579 Update version to 1.1.17-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6580 🍒 Cherry pick PR #6578 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/getPlaidLinkTokenParameters/index.js
Labels: automerge

#6535 6326: fix bug reported at #6518
  src/components/ImageView/index.js
  src/styles/StyleUtils.js
Labels: CP Staging

#6595 Update version to 1.1.17-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6596 🍒 Cherry pick PR #6535 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ImageView/index.js
  src/styles/StyleUtils.js
Labels: automerge

#6603 Update version to 1.1.17-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6606 Update version to 1.1.18-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6607 Update version to 1.1.18-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6616 Update version to 1.1.18-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6617 🍒 Cherry pick PR #6615 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
Labels: automerge

#6630 [CP STG] Revert WorkspaceBankAccount page changes
  src/pages/workspace/WorkspaceBankAccountPage.js
Labels: CP Staging

#6632 Update version to 1.1.18-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6633 🍒 Cherry pick PR #6630 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceBankAccountPage.js
Labels: automerge

#6631 [CP STAG] Fix FormData issue
  src/libs/API.js
Labels: CP Staging

#6636 Update version to 1.1.18-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6637 🍒 Cherry pick PR #6631 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/API.js
Labels: automerge

#6643 Update version to 1.1.18-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6644 Update version to 1.1.18-4 on staging
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/res/values-large/orientation.xml
  android/app/src/main/res/values-sw600dp/orientation.xml
  android/app/src/main/res/values/orientation.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/CurrentWalletBalance.js
  src/components/DatePicker/index.ios.js
  src/components/ExpensiPicker.js
  src/components/ExpensifyText.js
  src/components/InlineCodeBlock/index.js
  src/components/PressableWithSecondaryInteraction/index.android.js
  src/components/PressableWithSecondaryInteraction/index.ios.js
  src/components/SVGImage/propTypes.js
  src/components/TextInputFocusable/index.android.js
  src/components/TextInputFocusable/index.ios.js
  src/components/TextInputFocusable/index.js
  src/components/TextInputWithFocusStyles.js
  src/components/TextInputWithLabel.js
  src/components/TextInputWithName/index.js
  src/components/TextInputWithName/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/actions/User.js
  src/pages/EnablePayments/TermsPage/LongTermsForm.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/home/report/EmojiPickerMenu/index.js
  src/pages/home/report/EmojiPickerMenu/index.native.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/SignInPageLayout/SignInPageLayoutWide.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/signin/SignInPageLayout/signInPageStyles/index.ios.js
  src/pages/signin/SignInPageLayout/signInPageStyles/index.js
  src/styles/styles.js
  src/styles/utilities/flex.js
  src/styles/utilities/spacing.js
Labels: automerge

#6646 Update version to 1.1.18-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6650 Update version to 1.1.18-5 on staging
  .github/workflows/OSBotify-private-key.asc.gpg
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6652 Update version to 1.1.18-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6653 Update version to 1.1.18-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/AddPaymentMethodMenu.js
  src/components/AddPlaidBankAccount.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/BankAccounts.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/settings/Payments/PaymentsPage.js
Labels: automerge

#6656 Update version to 1.1.19-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6657 Update version to 1.1.19-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6670 [CP Stg] Fix iPad pro SignInPageLayout
  src/components/withWindowDimensions.js
  src/pages/signin/SignInPage.js
Labels: CP Staging

#6678 🍒 Cherry pick PR #6670 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/withWindowDimensions.js
  src/pages/signin/SignInPage.js
Labels: automerge

#6672 [CP Stg] Wrap AddPersonalBankAccount with KeyboardAvoidingView
  src/pages/AddPersonalBankAccountPage.js
Labels: CP Staging

#6679 Update version to 1.1.19-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6680 🍒 Cherry pick PR #6672 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/AddPersonalBankAccountPage.js
Labels: automerge

#6655 [No QA]Sign cherry pick PRs as @OSBotify
  .github/workflows/cherryPick.yml
Labels: CP Staging

#6682 Update version to 1.1.19-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6683 🍒 Cherry pick PR #6655 to staging 🍒
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6686 Update version to 1.1.19-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6687 🍒 Cherry pick PR #6684 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#6673 Adding support for chunked chats
  src/libs/Pusher/EventType.js
  src/libs/Pusher/pusher.js
  src/libs/actions/Report.js
Labels: Improvement

#6701 Update version to 1.1.19-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6702 Update version to 1.1.19-5 on staging
  android/app/build.gradle
  assets/images/hashtag.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AttachmentPicker/index.native.js
  src/components/ButtonWithMenu.js
  src/components/ExpensiPicker.js
  src/components/IOUConfirmationList.js
  src/components/Icon/Expensicons.js
  src/components/SettlementButton.js
  src/components/TextInputWithLabel.js
  src/components/TextInputWithPrefix/index.android.js
  src/components/TextInputWithPrefix/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/CustomActions.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Navigation/navigationRef.js
  src/libs/Pusher/EventType.js
  src/libs/Pusher/pusher.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Security/SecuritySettingsPage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/optionAlternateTextPlatformStyles/index.ios.js
  src/styles/optionAlternateTextPlatformStyles/index.js
  src/styles/styles.js
Labels: automerge

#6704 Update version to 1.1.20-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6705 Update version to 1.1.20-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6724 [CP Staging] Fix same name policy rooms and policy room title and mobile app crashing when creating policy room
  src/libs/actions/Report.js
  src/pages/home/HeaderView.js
Labels: CP Staging

#6735 Update version to 1.1.20-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6736 🍒 Cherry pick PR #6724 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/pages/home/HeaderView.js
Labels: automerge

#6741 Fix app crashes tapping the room name in the chat
  src/pages/ReportParticipantsPage.js
Labels: CP Staging

#6742 Update version to 1.1.20-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6743 🍒 Cherry pick PR #6741 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportParticipantsPage.js
Labels: automerge

#6752 Update "Additional details" form in KYC wallet upgrade flow
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/FormScrollView.js
  src/libs/ValidationUtils.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
Labels: InternalQA

#6776 Update version to 1.1.20-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6777 Update version to 1.1.20-3 on staging
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  build/react-native-web.sh
  ios/NewExpensify/AppDelegate.m
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/BigNumberPad.js
  src/components/CurrentWalletBalance.js
  src/components/ErrorBoundary/BaseErrorBoundary.js
  src/components/ExpensiPicker.js
  src/components/ExpensifyButton.js
  src/components/FormScrollView.js
  src/components/InlineCodeBlock/index.js
  src/components/KeyboardShortcutsModal.js
  src/components/Popover/index.native.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/components/PressableWithSecondaryInteraction/index.android.js
  src/components/PressableWithSecondaryInteraction/index.ios.js
  src/languages/en.js
  src/languages/es.js
  src/libs/BootSplash/index.js
  src/libs/BootSplash/index.native.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/OptionsListUtils.js
  src/libs/Pusher/EventType.js
  src/libs/ValidationUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/User.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen.js
  src/pages/iou/IOUTransactions.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/styles/styles.js
Labels: automerge

#6782 Update version to 1.1.21-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6783 Update version to 1.1.21-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6798 Fix inverted flatlist at ReportActionsView with few items should stick to bottom of page
  src/components/InvertedFlatList/index.js
  src/pages/home/report/ReportActionsView.js
  src/styles/styles.js
Labels: CP Staging

#6801 Update version to 1.1.21-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6802 🍒 Cherry pick PR #6798 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/InvertedFlatList/index.js
  src/pages/home/report/ReportActionsView.js
  src/styles/styles.js
Labels: automerge

#6813 Update version to 1.1.21-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6814 Update version to 1.1.21-2 on staging
  .github/actions/checkBundleVersionStringMatch/action.yml
  .github/actions/checkBundleVersionStringMatch/checkBundleVersionStringMatch.js
  .github/actions/checkBundleVersionStringMatch/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isPullRequestMergeable/isPullRequestMergeable.js
  .github/scripts/buildActions.sh
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MenuItem.js
  src/components/SelectCircle.js
  src/components/menuItemPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/stories/MenuItem.stories.js
  src/styles/StyleUtils.js
  src/styles/optionAlternateTextPlatformStyles/index.ios.js
  src/styles/styles.js
  tests/unit/isPullRequestMergeableTest.js
Labels: automerge

#6816 Update version to 1.1.22-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6817 Update version to 1.1.22-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6842 Revert "Remove create new workspace button from workspace settings"
  src/pages/workspace/WorkspaceInitialPage.js
Labels: CP Staging

#6846 Update version to 1.1.22-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6853 Update version to 1.1.22-0 on production
  .github/actions/checkBundleVersionStringMatch/action.yml
  .github/actions/checkBundleVersionStringMatch/checkBundleVersionStringMatch.js
  .github/actions/checkBundleVersionStringMatch/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isPullRequestMergeable/isPullRequestMergeable.js
  .github/scripts/buildActions.sh
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MenuItem.js
  src/components/SelectCircle.js
  src/components/menuItemPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/stories/MenuItem.stories.js
  src/styles/StyleUtils.js
  src/styles/optionAlternateTextPlatformStyles/index.ios.js
  src/styles/styles.js
  tests/unit/isPullRequestMergeableTest.js
Labels: automerge

#6854 Update version to 1.1.22-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6855 Update version to 1.1.22-2 on staging
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  STORYBOOK.md
  STYLING.md
  android/app/build.gradle
  assets/images/keyboard.svg
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AttachmentModal.js
  src/components/AttachmentPicker/attachmentPickerPropTypes.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/ButtonWithDropdown.js
  src/components/ButtonWithMenu.js
  src/components/ConfirmModal.js
  src/components/FormAlertWithSubmitButton.js
  src/components/Icon/Expensicons.js
  src/components/InboxCallButton.js
  src/components/KeyboardShortcutsModal.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/KeyboardShortcuts.js
  src/libs/actions/Policy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/NewChatPage.js
  src/pages/RequestCallPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/AboutPage.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Profile/LoginField.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/setup/platformSetup/index.desktop.js
  src/stories/Button.stories.js
  src/styles/getModalStyles.js
  src/styles/variables.js
Labels: automerge

#6857 Update version to 1.1.22-2 on production
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  STORYBOOK.md
  STYLING.md
  android/app/build.gradle
  assets/images/keyboard.svg
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AttachmentModal.js
  src/components/AttachmentPicker/attachmentPickerPropTypes.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/ButtonWithDropdown.js
  src/components/ButtonWithMenu.js
  src/components/ConfirmModal.js
  src/components/FormAlertWithSubmitButton.js
  src/components/Icon/Expensicons.js
  src/components/InboxCallButton.js
  src/components/KeyboardShortcutsModal.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/KeyboardShortcuts.js
  src/libs/actions/Policy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/NewChatPage.js
  src/pages/RequestCallPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/AboutPage.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Profile/LoginField.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/setup/platformSetup/index.desktop.js
  src/stories/Button.stories.js
  src/styles/getModalStyles.js
  src/styles/variables.js
Labels: automerge

#6858 Update version to 1.1.22-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6859 Update version to 1.1.22-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6861 Update version to 1.1.22-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6862 Update version to 1.1.22-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: automerge

#6865 Update version to 1.1.22-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6866 Update version to 1.1.22-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/HeaderWithCloseButton.js
Labels: automerge

#6867 Update version to 1.1.23-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6868 Update version to 1.1.23-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6881 Hide Keyboard shortcuts menu in Native Devices
  src/CONST.js
  src/libs/getPlatform/index.desktop.js
  src/libs/getPlatform/index.website.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/pages/settings/AboutPage/index.js
Labels: CP Staging

#6886 Update version to 1.1.23-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6888 🍒 Cherry pick PR #6881 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/getPlatform/index.desktop.js
  src/libs/getPlatform/index.website.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/pages/settings/AboutPage/index.js
Labels: automerge

#4329 Adjusting IOUModal and adding createAndPayIOU
  src/components/IOUConfirmationList.js
  src/libs/API.js
  src/libs/actions/IOU.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/index.js
Labels: InternalQA

#6917 Update version to 1.1.23-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/HeaderWithCloseButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/getPlatform/index.desktop.js
  src/libs/getPlatform/index.website.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/pages/settings/AboutPage/index.js
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: automerge

#6918 Update version to 1.1.23-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6923 Update version to 1.1.23-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6924 Update version to 1.1.23-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#6925 Update version to 1.1.24-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6926 Update version to 1.1.24-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6930 [No QA] fix: Added translate key for street name based on the form
  src/pages/ReimbursementAccount/AddressForm.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: CP Staging

#6934 Update version to 1.1.24-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6935 🍒 Cherry pick PR #6930 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/AddressForm.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
Labels: automerge

#6936 [No QA] fix: null check for app state subscription added
  src/libs/AppStateMonitor/index.js
Labels: CP Staging

#6938 Update version to 1.1.24-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6939 🍒 Cherry pick PR #6936 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/AppStateMonitor/index.js
Labels: automerge

#6949 fix: Paypal address and Venmo phone number
  src/pages/iou/IOUDetailsModal.js
Labels: CP Staging

#6952 Update version to 1.1.24-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6953 🍒 Cherry pick PR #6949 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#6951 fix: room page layout
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: CP Staging

#6955 Update version to 1.1.24-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6959 Update version to 1.1.24-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6960 Update version to 1.1.24-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6962 Update version to 1.1.24-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6963 Update version to 1.1.24-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#6964 🍒 Cherry pick PR #6951 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: automerge, Engineering, Hourly
