Repository Expensify/App, pull requests merged in 2022-06, with the labels that each got.

#9273 Update version to 1.1.70-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9274 Update version to 1.1.70-2 on staging
  FORMS.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch.js
  src/components/Banner.js
  src/components/Button.js
  src/components/Form.js
  src/components/Modal/BaseModal.js
  src/components/ReportTransaction.js
  src/libs/Pusher/pusher.js
  src/libs/actions/Inbox.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/signin/ResendValidationForm.js
  src/stories/Form.stories.js
  src/styles/styles.js
  src/styles/utilities/positioning.js
Labels: automerge

#9271 Update version to 1.1.70-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/API.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Middleware/Retry.js
  src/libs/Middleware/SaveResponseInOnyx.js
Labels: automerge

#9284 Revert "Fix status bar color when a modal is open"
  src/components/Modal/BaseModal.js
Labels: CP Staging

#9285 Update version to 1.1.70-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9286 🍒 Cherry pick PR #9284 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Modal/BaseModal.js
Labels: automerge

#9295 Update `electron-notarize` and use new notary tool
  desktop/notarize.js
  package-lock.json
  package.json
Labels: CP Staging

#9297 🍒 Cherry pick PR #9295 to staging 🍒
  android/app/build.gradle
  desktop/notarize.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9299 Try our other Team ID for notarizing the Desktop app
  desktop/notarize.js
Labels: CP Staging

#9302 🍒 Cherry pick PR #9299 to staging 🍒
  android/app/build.gradle
  desktop/notarize.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9272 Update version to 1.1.71-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, CP Staging

#9303 Update version to 1.1.71-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9304 🍒 Cherry pick PR #9272 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, Engineering, Hourly

#9291 Decouple policyRoom and defaultRoom betas
  src/libs/OptionsListUtils.js
  src/pages/home/ReportScreen.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: CP Staging, InternalQA

#9310 Update version to 1.1.71-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9311 🍒 Cherry pick PR #9291 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/pages/home/ReportScreen.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: automerge

#9315 Fix console error caused by incorrect propTypes
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/VideoChatButtonAndMenu/videoChatButtonAndMenuPropTypes.js
Labels: CP Staging

#9316 Update version to 1.1.71-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9319 Update version to 1.1.72-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9322 Update version to 1.1.72-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9324 Update version to 1.1.73-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9325 Update version to 1.1.73-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9120 Move Android build variables to env
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  android/app/my-upload-key.keystore.gpg
  android/gradle.properties
Labels: CP Staging

#9337 🍒 Cherry pick PR #9120 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  android/app/my-upload-key.keystore.gpg
  android/gradle.properties
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9343 Revert "Fix resizes on image upload"
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/ThumbnailImage.js
  src/pages/home/report/ReportActionItemFragment.js
Labels: CP Staging

#9344 Update version to 1.1.73-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9357 Update version to 1.1.74-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9358 Update version to 1.1.74-0 on staging
  .well-known/apple-app-site-association
  android/app/build.gradle
  ios/NewExpensify/Chat.entitlements
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/AmountTextInput.js
  src/components/Button.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Report.js
  src/libs/toggleReportActionComposeView/index.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/Payments/AddDebitCardPage.js
  tests/actions/ReportTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#9361 🍒 Cherry pick PR #9346 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/ThumbnailImage.js
  src/pages/home/report/ReportActionItemFragment.js
Labels: automerge

#9371 Update version to 1.1.74-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9372 🍒 Cherry pick PR #9369 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
Labels: automerge

#9374 Update version to 1.1.74-2 on production
  .well-known/apple-app-site-association
  android/app/build.gradle
  ios/NewExpensify/Chat.entitlements
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/AmountTextInput.js
  src/components/Button.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/components/ThumbnailImage.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Report.js
  src/libs/toggleReportActionComposeView/index.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/Payments/AddDebitCardPage.js
  tests/actions/ReportTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#9376 Update version to 1.1.75-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
  src/libs/Pusher/EventType.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  tests/actions/ReportTest.js
Labels: automerge

#9381 Remove isChunked since no longer used
  src/libs/PusherUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
Labels: CP Staging

#9383 Update version to 1.1.75-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9384 🍒 Cherry pick PR #9381 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/PusherUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
Labels: automerge

#9386 Update version to 1.1.75-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
  src/libs/Pusher/EventType.js
  src/libs/PusherUtils.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
Labels: automerge

#9387 Update version to 1.1.76-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9388 Update version to 1.1.76-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9395 Update version to 1.1.76-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9396 Update version to 1.1.76-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ArchivedReportFooter.js
  src/components/Banner.js
  src/components/ReportWelcomeText.js
  src/libs/ReportUtils.js
  src/pages/home/ReportScreen.js
  src/stories/Banner.stories.js
Labels: automerge

#9429 Update version to 1.1.76-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9430 Update version to 1.1.76-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Security/CloseAccountPage.js
Labels: automerge

#9432 Update version to 1.1.76-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9433 Update version to 1.1.76-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9434 Update version to 1.1.76-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9435 Update version to 1.1.76-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Timing.js
Labels: automerge

#9446 Update version to 1.1.76-5 on production
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ArchivedReportFooter.js
  src/components/Banner.js
  src/components/ReportWelcomeText.js
  src/libs/ReportUtils.js
  src/libs/actions/Timing.js
  src/pages/home/ReportScreen.js
  src/pages/settings/Security/CloseAccountPage.js
  src/stories/Banner.stories.js
Labels: automerge

#9447 Update version to 1.1.77-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9448 Update version to 1.1.77-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Button.js
  src/components/MenuItem.js
Labels: automerge

#9453 Update version to 1.1.77-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9454 Update version to 1.1.77-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
Labels: automerge

#9455 Update version to 1.1.77-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9456 Update version to 1.1.77-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Errors/HttpsError.js
  src/libs/HttpUtils.js
  src/libs/Middleware/Logging.js
  tests/unit/NetworkTest.js
Labels: automerge

#9477 Update version to 1.1.77-2 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Button.js
  src/components/MenuItem.js
  src/libs/Errors/HttpsError.js
  src/libs/HttpUtils.js
  src/libs/Middleware/Logging.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#9479 Update version to 1.1.78-0 on staging
  .github/actions/awaitStagingDeploys/index.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/actions/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  assets/images/collapse.svg
  assets/images/expand.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/Button.js
  src/components/Composer/index.android.js
  src/components/Composer/index.ios.js
  src/components/Composer/index.js
  src/components/ContextMenuItem.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HeaderWithCloseButton.js
  src/components/IOUConfirmationList.js
  src/components/Icon/Expensicons.js
  src/components/withDelayToggleButtonState.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ComposerUtils/index.js
  src/libs/ComposerUtils/index.native.js
  src/libs/ComposerUtils/updateIsFullComposerAvailable.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/OptionsListUtils.js
  src/libs/PolicyUtils.js
  src/libs/Pusher/EventType.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/libs/actions/Welcome.js
  src/pages/SetPasswordPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/styles/styles.js
Labels: automerge

#9496 Update fastlane to the latest version
  Gemfile.lock
Labels: CP Staging

#9498 Update version to 1.1.78-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9499 🍒 Cherry pick PR #9496 to staging 🍒
  Gemfile.lock
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9515 Update version to 1.1.78-2 on staging
  android/app/build.gradle
  config/webpack/webpack.dev.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
  src/libs/actions/Link.js
  src/libs/actions/PaymentMethods.js
  src/pages/RequestCallPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
Labels: automerge

#9516 Update version to 1.1.78-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9518 Update version to 1.1.78-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Tooltip/TooltipRenderedOnPageBody.js
Labels: automerge

#9521 Update version to 1.1.78-4 on staging
  README.md
  android/app/build.gradle
  docs/API.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9528 Update version to 1.1.78-6 on staging
  android/app/build.gradle
  config/webpack/webpack.dev.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/libs/Environment/Environment.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
Labels: automerge

#9530 Update version to 1.1.78-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9531 Update version to 1.1.78-7 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemSingle.js
Labels: automerge

#9561 Update version to 1.1.78-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9562 🍒 Cherry pick PR #9555 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#7702 Standardize arrow navigation in OptionsLists
  src/CONST.js
  src/components/ArrowKeyFocusManager.js
  src/components/IOUConfirmationList.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector.js
  src/languages/en.js
  src/languages/es.js
  src/libs/KeyboardShortcut/index.js
  src/pages/NewChatPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: External

#9584 Update version to 1.1.79-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9585 Update version to 1.1.79-0 on staging
  .github/scripts/validateActionsAndWorkflows.sh
  CONTRIBUTING.md
  android/app/build.gradle
  docs/API.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ArrowKeyFocusManager.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/IOUConfirmationList.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/ComponentUtils/index.js
  src/libs/ComponentUtils/index.native.js
  src/libs/KeyboardShortcut/index.js
  src/libs/OptionsListUtils.js
  src/libs/SessionUtils.js
  src/libs/actions/App.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/LogOutPreviousUserPage.js
  src/pages/NewChatPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/variables.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#9587 Update version to 1.1.79-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9588 Update version to 1.1.79-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ImageView/index.native.js
Labels: automerge

#9590 Update version to 1.1.79-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9610 Double max participant message fix
  src/components/OptionsSelector.js
  src/pages/NewChatPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
Labels: CP Staging

#9615 Update version to 1.1.79-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9616 🍒 Cherry pick PR #9610 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
  src/pages/NewChatPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
Labels: automerge

#9632 Allow free policies to have their default rooms be shown
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/OptionsListUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Welcome.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
Labels: CP Staging

#9633 Update version to 1.1.79-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9636 Update version to 1.1.79-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9637 🍒 Cherry pick PR #9632 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/OptionsListUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Welcome.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
Labels: automerge

#9644 Update version to 1.1.79-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9645 🍒 Cherry pick PR #9639 to staging 🍒
  .github/workflows/createNewVersion.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9643 [No QA] Wait for checks to complete before giving up due to mergeable_state blocked
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isPullRequestMergeable/isPullRequestMergeable.js
  tests/unit/isPullRequestMergeableTest.js
Labels: CP Staging

#9646 Update version to 1.1.79-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9652 Update version to 1.1.79-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9619 Create composite action to set up git for OSBotify
  .github/actions/composite/setupGitForOSBotify/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/updateProtectedBranch.yml
Labels: CP Staging

#9655 Update version to 1.1.79-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9656 🍒 Cherry pick PR #9619 to staging 🍒
  .github/actions/composite/setupGitForOSBotify/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9657 Update version to 1.1.79-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
