Repository Expensify/App, pull requests merged in 2022-07, with the labels that each got.

#9674 Fix off-by-one error in scrollToIndex
  src/components/OptionsSelector.js
Labels: CP Staging

#9675 Update version to 1.1.79-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9676 🍒 Cherry pick PR #9674 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
Labels: automerge

#9672 Make CMD+Enter work for single-selection pages
  src/components/OptionsSelector.js
  src/pages/NewChatPage.js
Labels: CP Staging

#9683 Update version to 1.1.79-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9684 🍒 Cherry pick PR #9672 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
  src/pages/NewChatPage.js
Labels: automerge

#9690 Revert "Fix off-by-one error in scrollToIndex"
  src/components/OptionsSelector.js
Labels: CP Staging

#9691 Update version to 1.1.79-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9692 🍒 Cherry pick PR #9690 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
Labels: automerge

#9682 Fix ArrowKeyFocusManager for lists with only two options
  src/components/ArrowKeyFocusManager.js
Labels: CP Staging

#9699 Update version to 1.1.79-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9700 🍒 Cherry pick PR #9682 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ArrowKeyFocusManager.js
Labels: automerge

#9714 Fix OptionsSelector crash
  src/components/OptionsSelector.js
Labels: CP Staging

#9716 Update version to 1.1.79-15 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9717 🍒 Cherry pick PR #9714 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
Labels: automerge

#9350 Replace Report_AddComment with AddComment (Part 2)
  src/CONST.js
  src/components/InlineSystemMessage.js
  src/libs/DateUtils.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/reportActionPropTypes.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  tests/README.md
  tests/actions/ReportTest.js
Labels: CP Staging

#9719 Update version to 1.1.79-16 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9720 🍒 Cherry pick PR #9350 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/InlineSystemMessage.js
  src/libs/DateUtils.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/reportActionPropTypes.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  tests/README.md
  tests/actions/ReportTest.js
Labels: automerge

#9626 Scroll to the top when new options are selected on multiple-selection screens
  src/components/OptionsSelector.js
Labels: CP Staging

#9723 Update version to 1.1.79-17 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9724 🍒 Cherry pick PR #9626 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector.js
Labels: automerge

#9654 [No QA] Migrate updateProtectedBranch from workflow to composite action
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
  .github/workflows/updateProtectedBranch.yml
Labels: CP Staging

#9729 [No QA] Fix updateProtectedBranch composite action
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
Labels: CP Staging

#9730 Update version to 1.1.79-18 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9649 Add FullPageNotFoundView
  src/components/BlockingViews/BlockingView.js
  src/components/BlockingViews/FullPageNotFoundView.js
  src/components/BlockingViews/FullPageOfflineBlockingView.js
  src/components/FullPageOfflineBlockingView.js
  src/languages/en.js
  src/languages/es.js
  src/pages/NotFound.js
Labels: InternalQA

#9770 Update version to 1.1.80-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9777 Update version to 1.1.82-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9779 Update version to 1.1.82-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9780 Update version to 1.1.82-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9787 Update version to 1.1.82-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9788 Update version to 1.1.82-2 on staging
  .eslintrc.js
  android/app/build.gradle
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9789 Update version to 1.1.82-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9790 Update version to 1.1.82-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9791 Update version to 1.1.82-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9792 Update version to 1.1.82-4 on staging
  .github/actions/getDeployPullRequestList/action.yml
  .github/actions/getDeployPullRequestList/getDeployPullRequestList.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getReleaseBody/action.yml
  .github/actions/getReleaseBody/getReleaseBody.js
  .github/actions/getReleaseBody/index.js
  .github/actions/markPullRequestsAsDeployed/action.yml
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/workflows/deploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9602 Use new API command `LogOut`
  src/libs/actions/Session/index.js
Labels: InternalQA

#9796 Update version to 1.1.82-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9797 Update version to 1.1.82-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
Labels: automerge

#9843 Update version to 1.1.83-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9844 Update version to 1.1.82-5 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/getDeployPullRequestList/action.yml
  .github/actions/getDeployPullRequestList/getDeployPullRequestList.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getReleaseBody/action.yml
  .github/actions/getReleaseBody/getReleaseBody.js
  .github/actions/getReleaseBody/index.js
  .github/actions/markPullRequestsAsDeployed/action.yml
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/deploy.yml
  .github/workflows/platformDeploy.yml
  README.md
  android/app/src/main/AndroidManifest.xml
  assets/images/venmo.svg
  desktop/main.js
  docs/CNAME
  docs/README.md
  package-lock.json
  package.json
  src/CONST.js
  src/components/ButtonWithMenu.js
  src/components/IOUConfirmationList.js
  src/components/Icon/Expensicons.js
  src/components/ImageView/index.js
  src/components/ImageView/index.native.js
  src/components/OptionsSelector.js
  src/components/SettlementButton.js
  src/components/TextInput/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Middleware/Logging.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Pusher/pusher.js
  src/libs/ValidationUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/Session/index.js
  src/libs/deprecatedAPI.js
  src/libs/isAppInstalled/index.js
  src/libs/isAppInstalled/index.native.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Profile/LoginField.js
  src/stories/ButtonWithDropdown.stories.js
  tests/actions/ReportTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#9845 Update version to 1.1.83-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9846 Update version to 1.1.83-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/FormAlertWrapper.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
Labels: automerge

#9850 Update version to 1.1.83-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9851 Update version to 1.1.83-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/App.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/libs/migrateOnyx.js
  src/libs/migrations/RenameExpensifyNewsStatus.js
  src/pages/settings/PreferencesPage.js
Labels: automerge

#9852 Update version to 1.1.83-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9853 Update version to 1.1.83-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9854 Update version to 1.1.83-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9855 Update version to 1.1.83-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9858 Update version to 1.1.84-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9859 Update version to 1.1.84-0 on staging
  .github/actions/composite/updateProtectedBranch/action.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9860 Update version to 1.1.84-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9861 Update version to 1.1.84-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9863 Update version to 1.1.84-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9864 Update version to 1.1.84-2 on staging
  .github/actions/composite/setupNode/action.yml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/lint.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/test.yml
  .github/workflows/validateGithubActions.yml
  .github/workflows/verifyPodfile.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9881 Update version to 1.1.84-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9883 Update version to 1.1.84-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9885 Update version to 1.1.84-5 on staging
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  docs/Gemfile.lock
  docs/README.md
  docs/_includes/home-lhn.html
  docs/_includes/home-navigation-tree.html
  docs/_includes/request-money-lhn.html
  docs/_includes/request-money-navigation-tree.html
  docs/_includes/send-money-lhn.html
  docs/_includes/send-money-navigation-tree.html
  docs/_layouts/default.html
  docs/_sass/_main.scss
  docs/articles/request-money/SmartScan.md
  docs/assets/images/circle-hourglass.svg
  docs/assets/js/main.js
  docs/hubs/request-money.html
  docs/hubs/send-money.html
  docs/index.html
  docs/main.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Button.js
  src/components/FormAlertWithSubmitButton.js
  src/components/FormAlertWrapper.js
  src/components/ScreenWrapper.js
  src/components/SettlementButton.js
  src/components/withNavigation.js
  src/components/withNavigationFocus.js
  src/libs/actions/App.js
  src/libs/actions/GeoLocation.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
Labels: automerge

#9886 Fix crash when accessing bad method in `ReportActionsView`
  src/pages/home/report/ReportActionsView.js
Labels: CP Staging

#9887 Update version to 1.1.84-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9888 🍒 Cherry pick PR #9886 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#9893 Update version to 1.1.84-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9894 Update version to 1.1.84-7 on staging
  Gemfile.lock
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9896 Update version to 1.1.84-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9897 Update version to 1.1.84-8 on staging
  .github/actions/javascript/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/getDeployPullRequestList.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/getPullRequestsMergedBetweenTest.sh
  tests/utils/getPullRequestsMergedBetween.js
  tests/utils/getPullRequestsMergedBetween.mjs
Labels: automerge

#9898 Update version to 1.1.84-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9899 Update version to 1.1.84-9 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#9903 Update version to 1.1.84-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9904 Update version to 1.1.84-10 on staging
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9907 Update version to 1.1.84-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9908 Update version to 1.1.84-11 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/styles/styles.js
Labels: automerge

#9947 Fix the styles of the form submit button on requestCallPage
  src/pages/RequestCallPage.js
Labels: CP Staging

#9952 Update version to 1.1.84-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9953 🍒 Cherry pick PR #9947 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/RequestCallPage.js
Labels: automerge

#9961 Return `data` from `Reauthentication` middleware when `shouldRetry: false`
  src/components/TestToolMenu.js
  src/libs/Middleware/Reauthentication.js
  src/libs/actions/Session/index.js
  src/pages/settings/PreferencesPage.js
Labels: CP Staging

#9965 🍒 Cherry pick PR #9961 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TestToolMenu.js
  src/libs/Middleware/Reauthentication.js
  src/libs/actions/Session/index.js
  src/pages/settings/PreferencesPage.js
Labels: automerge

#9641 Capture ios|android sourcemaps as deploy job artifacts
  .github/workflows/platformDeploy.yml
  ios/NewExpensify.xcodeproj/project.pbxproj
  package.json
Labels: InternalQA

#9985 Update version to 1.1.85-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9986 Update version to 1.1.85-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/FormAlertWrapper.js
Labels: automerge

#9988 Update version to 1.1.85-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9989 Update version to 1.1.85-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
Labels: automerge

#9996 Update version to 1.1.85-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9997 🍒 Cherry pick PR #9994 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/IOUModal.js
Labels: automerge

#10002 Remove MY_PERSONAL_DETAILS from timezone update logic
  src/libs/actions/Report.js
Labels: CP Staging

#10004 Update version to 1.1.85-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10005 🍒 Cherry pick PR #10002 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#10008 Update Onyx to 1.0.10
  package-lock.json
  package.json
Labels: CP Staging

#10013 🍒 Cherry pick PR #10008 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10043 [CP Stag] Fix lodashGet usage
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/pages/settings/Profile/ProfilePage.js
Labels: CP Staging

#10044 Update version to 1.1.85-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10045 🍒 Cherry pick PR #10043 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#10054 Update version to 1.1.85-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10055 🍒 Cherry pick PR #9956 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#10062 Minor comment change to test CP
  src/libs/actions/Report.js
Labels: CP Staging

#10063 Update version to 1.1.85-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10064 🍒 Cherry pick PR #10062 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#10075 Update version to 1.1.86-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10096 Revert "7470 - added onLayout to textinput perent component & used dynamic he…"
  src/components/TextInput/BaseTextInput.js
  src/styles/styles.js
Labels: CP Staging

#10102 Update version to 1.1.86-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10103 🍒 Cherry pick PR #10096 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
  src/styles/styles.js
Labels: automerge

#10113 Revert Update Global Offline Indicator
  src/components/ScreenWrapper.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/GetAssistancePage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/RequestCallPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/ChooseTransferAccountPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
Labels: CP Staging

#10092 Prevent rendering plaidData.error as empty string
  src/components/AddPlaidBankAccount.js
Labels: CP Staging

#10114 Update version to 1.1.86-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10115 🍒 Cherry pick PR #10113 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ScreenWrapper.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/GetAssistancePage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/RequestCallPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/ChooseTransferAccountPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
Labels: automerge, Engineering, Hourly

#10120 Update version to 1.1.86-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10121 🍒 Cherry pick PR #10092 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddPlaidBankAccount.js
Labels: automerge

#10123 Fix line breaks not working properly
  src/pages/home/report/ReportActionItemFragment.js
Labels: CP Staging

#10124 Update version to 1.1.86-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10125 🍒 Cherry pick PR #10123 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemFragment.js
Labels: automerge

#10136 Fix back from bank account manual page
  src/libs/actions/ReimbursementAccount/errors.js
Labels: CP Staging

#10138 Update version to 1.1.86-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10139 🍒 Cherry pick PR #10136 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/ReimbursementAccount/errors.js
Labels: automerge
