Repository Expensify/App, pull requests merged in 2022-11, with the labels that each got.

#12336 [CP Staging] Revert PR 11907 which introduced missing FAB bug
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/PopoverModal.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
Labels: CP Staging

#12337 Update version to 1.2.22-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12338 🍒 Cherry pick PR #12336 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/PopoverModal.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
Labels: automerge

#12343 Update version to 1.2.22-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12344 🍒 Cherry pick PR #12342 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#12178 Fix P2P Debit cards are being displayed twice on the Payments page
  src/libs/actions/PaymentMethods.js
Labels: InternalQA

#12375 Update version to 1.2.22-3 on production
  android/app/build.gradle
  config/webpack/webpack.common.js
  config/webpack/webpack.dev.js
  docs/_config.yml
  docs/_includes/request-money-lhn.html
  docs/_includes/send-money-lhn.html
  docs/articles/request-money/SmartScan.md
  docs/hubs/request-money.html
  docs/hubs/send-money.html
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcworkspace/contents.xcworkspacedata
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/FAB/fabPropTypes.js
  src/components/FAB/index.ios.js
  src/components/FAB/index.js
  src/components/FloatingActionButton.js
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/KeyboardAvoidingView/index.js
  src/components/PDFView/index.native.js
  src/components/Popover/popoverPropTypes.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/components/PopoverMenu/popoverMenuPropTypes.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/App.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/withReportOrNavigateHome.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/PopoverModal.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/signin/SignInPageLayout/LoginKeyboardAvoidingView/index.js
  src/pages/signin/SignInPageLayout/LoginKeyboardAvoidingView/index.native.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/SignInPageLayout/SignInPageGraphics.js
  src/pages/signin/SignInPageLayout/index.js
  src/setup/index.js
  src/stories/OptionRow.stories.js
Labels: automerge

#12404 Update version to 1.2.23-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12405 Update version to 1.2.23-1 on staging
  .github/workflows/createNewVersion.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#12409 Update version to 1.2.23-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12410 Update version to 1.2.23-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12411 Update version to 1.2.23-2 on staging
  .github/actions/composite/setupNode/action.yml
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
  src/libs/deprecatedAPI.js
  src/libs/isViaExpensifyCashNative/index.js
  src/libs/isViaExpensifyCashNative/index.native.js
Labels: automerge

#12412 Update version to 1.2.23-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12413 Update version to 1.2.23-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12414 Update version to 1.2.23-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12415 Update version to 1.2.23-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12416 Update version to 1.2.23-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12364 Fix members page spinner (and lack of icon on participant page)
  src/libs/ReportUtils.js
  src/pages/DetailsPage.js
  src/pages/ReportParticipantsPage.js
Labels: InternalQA

#12417 Update version to 1.2.23-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12418 Update version to 1.2.23-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/pages/DetailsPage.js
  src/pages/ReportParticipantsPage.js
Labels: automerge

#12420 Update version to 1.2.23-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12421 Update version to 1.2.23-7 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#12460 Add errors object back to menu item, remove unused isPolicy
  src/pages/workspace/WorkspacesListPage.js
Labels: CP Staging

#12461 Update version to 1.2.23-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12462 🍒 Cherry pick PR #12460 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspacesListPage.js
Labels: automerge

#12468 Revert PR11313
  src/CONST.js
  src/components/AttachmentModal.js
Labels: CP Staging

#12469 Update version to 1.2.23-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12470 🍒 Cherry pick PR #12468 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
Labels: automerge

#12475 Update version to 1.2.24-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/FormAlertWrapper.js
  src/components/FormHelpMessage.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/Picker/index.js
  src/components/RadioButtonWithLabel.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextLink.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/stories/FormAlertWithSubmitButton.stories.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#12219 Make `API.read` wait on all requests on the SequentialQueue to respond
  src/libs/API.js
  src/libs/Network/SequentialQueue.js
Labels: InternalQA

#12510 [NO-QA] Resolve upstream ReactNative android build blocker
  android/build.gradle
Labels: CP Staging

#12515 Update version to 1.2.24-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12516 🍒 Cherry pick PR #12510 to staging 🍒
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12525 [NO-QA] Lock Android Hermes gradle version
  android/build.gradle
Labels: CP Staging

#12527 Update version to 1.2.24-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12528 🍒 Cherry pick PR #12525 to staging 🍒
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12532 Stop using deprecated jcenter repository for android dependencies
  android/build.gradle
Labels: CP Staging

#12535 Update version to 1.2.24-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12536 🍒 Cherry pick PR #12532 to staging 🍒
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12533 fix crash on profile detail
  src/pages/DetailsPage.js
Labels: CP Staging

#12538 Update version to 1.2.24-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12539 🍒 Cherry pick PR #12533 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/DetailsPage.js
Labels: automerge

#12560 Update version to 1.2.24-4 on production
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/FormAlertWrapper.js
  src/components/FormHelpMessage.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/components/Picker/index.js
  src/components/RadioButtonWithLabel.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextLink.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/pages/DetailsPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/stories/FormAlertWithSubmitButton.stories.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#12561 Update version to 1.2.25-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12613 Update version to 1.2.26-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12614 Update version to 1.2.26-0 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md
  docs/_data/routes.yml
  docs/_includes/hub-card.html
  docs/_layouts/default.html
  docs/_sass/_main.scss
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CommunicationsLink.js
  src/components/ContextMenuItem.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.native.js
  src/libs/EmojiUtils.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/unit/EmojiTest.js
Labels: automerge

#12401 Update expensify-common to newest version
  package-lock.json
  package.json
Labels: InternalQA

#12282 Updated code to use custom workspace name from oldDot
  src/libs/actions/App.js
  src/libs/actions/Policy.js
Labels: InternalQA

#12659 Update version to 1.2.26-0 on production
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md
  docs/_data/routes.yml
  docs/_includes/hub-card.html
  docs/_layouts/default.html
  docs/_sass/_main.scss
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CommunicationsLink.js
  src/components/ContextMenuItem.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.native.js
  src/libs/EmojiUtils.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/unit/EmojiTest.js
Labels: automerge

#12660 Update version to 1.2.27-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12661 Update version to 1.2.27-0 on staging
  README.md
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/README.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/PDFView/index.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/SettlementButton.js
  src/components/participantPropTypes.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/libs/models/BankAccount.js
  src/libs/shouldDelayFocus/index.android.js
  src/libs/shouldDelayFocus/index.js
  src/pages/ConciergePage.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/SearchPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUTransactions.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/reimburse/WorkspaceReimbursePage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  tests/actions/ReimbursementAccountTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/fetchFreePlanVerifiedBankAccountTest.js
Labels: automerge

#12680 Update version to 1.2.27-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12683 🍒 Cherry pick PR #12679 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/SearchPage.js
Labels: automerge

#12682 Update version to 1.2.27-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12688 Remove renderCell method as it's no longer needed and causes errors
  src/pages/home/report/ReportActionsList.js
Labels: CP Staging

#12689 Update version to 1.2.27-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12690 🍒 Cherry pick PR #12688 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsList.js
Labels: automerge

#12722 Reverts elements from #12169
  src/ONYXKEYS.js
  src/libs/actions/App.js
  src/pages/home/ReportScreen.js
Labels: CP Staging

#12733 Update version to 1.2.27-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12734 🍒 Cherry pick PR #12722 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/libs/actions/App.js
  src/pages/home/ReportScreen.js
Labels: automerge

#12750 Update version to 1.2.27-4 on production
  README.md
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/README.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/PDFView/index.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/SettlementButton.js
  src/components/participantPropTypes.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/libs/models/BankAccount.js
  src/libs/shouldDelayFocus/index.android.js
  src/libs/shouldDelayFocus/index.js
  src/pages/ConciergePage.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/SearchPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUTransactions.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/reimburse/WorkspaceReimbursePage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  tests/actions/ReimbursementAccountTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/fetchFreePlanVerifiedBankAccountTest.js
Labels: automerge

#12751 Update version to 1.2.28-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12754 [NoQA] Smarter regex for parsing No QA PRs
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  tests/unit/GithubUtilsTest.js
Labels: CP Staging

#12764 🍒 Cherry pick PR #12754 to staging 🍒
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/GithubUtilsTest.js
Labels: automerge

#12785 Splash Web - Fix mapping of production logo and do work only after DOM is ready
  config/webpack/webpack.common.js
  web/splash/splash.js
Labels: CP Staging

#12787 Update version to 1.2.28-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12788 🍒 Cherry pick PR #12785 to staging 🍒
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/splash/splash.js
Labels: automerge

#12810 Update version to 1.2.29-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12813 Update version to 1.2.29-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12814 Update version to 1.2.29-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: automerge

#12815 Update version to 1.2.29-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12816 Update version to 1.2.29-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportSettingsPage.js
Labels: automerge

#12818 Update version to 1.2.29-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12819 Update version to 1.2.29-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsList.js
Labels: automerge

#12829 [CP Staging] Fix Success / Danger Button Text Color, Fix Growl Colors
  src/styles/styles.js
  src/styles/themes/default.js
Labels: CP Staging

#12843 Update version to 1.2.29-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12844 🍒 Cherry pick PR #12829 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#12830 [No QA]Add Browserstack API call to staging deploys
  .github/workflows/README.md
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#12847 Update version to 1.2.29-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12849 🍒 Cherry pick PR #12830 to staging 🍒
  .github/workflows/README.md
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12855 [No QA]Attempt to fix iOS uploads to browserstack with different path
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#12856 Update version to 1.2.29-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12857 🍒 Cherry pick PR #12855 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12897 Revert "removed resetting the report fields to allow user to operate multiple actions on same popover"
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
Labels: CP Staging

#12901 Update version to 1.2.29-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12902 🍒 Cherry pick PR #12897 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
Labels: automerge

#12932 Update version to 1.2.30-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12936 [Internal QA] Fix the way the reviewer checklist is found
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/reviewerChecklist/reviewerChecklist.js
Labels: InternalQA

#12974 Update version to 1.2.31-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12979 Update version to 1.2.31-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12980 Update version to 1.2.31-1 on staging
  android/app/build.gradle
  android/app/src/main/res/drawable-hdpi/ic_notification.png
  android/app/src/main/res/drawable-mdpi/ic_notification.png
  android/app/src/main/res/drawable-xhdpi/ic_notification.png
  android/app/src/main/res/drawable-xxhdpi/ic_notification.png
  android/app/src/main/res/drawable-xxxhdpi/ic_notification.png
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  assets/images/expensify-logo-round-clearspace.png
  assets/images/expensify-logo-round.png
  assets/images/expensify-wordmark.svg
  assets/images/new-expensify-dev.svg
  assets/images/new-expensify-stg.svg
  assets/images/new-expensify.svg
  desktop/icon-dev.png
  desktop/icon-stg.png
  desktop/icon.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/Store.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/iOS@2x.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/iOS@3x.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/iPad.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/iPad@2x.png
  ios/NewExpensify/Images.xcassets/AppIcon.appiconset/iPadPro.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/favicon-unread.png
  web/favicon.png
Labels: automerge

#12984 Update version to 1.2.31-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12985 Update version to 1.2.31-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#12959 [No QA] Fix small button padding
  src/styles/styles.js
Labels: CP Staging

#12990 Update version to 1.2.31-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12991 🍒 Cherry pick PR #12959 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#12994 Update version to 1.2.31-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12995 Update version to 1.2.31-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12996 Update version to 1.2.31-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/TextLink.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
Labels: automerge

#12997 Update version to 1.2.31-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
  src/pages/ReportSettingsPage.js
Labels: automerge

#12880 Look at the platform to decide how to choose API
  src/libs/HttpUtils.js
  src/libs/shouldUseStagingServer/index.js
  src/libs/shouldUseStagingServer/index.native.js
Labels: InternalQA

#13010 Revert "Merge pull request #12648 from margelo/@thomas/fast-image-cac…
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/Avatar.js
  src/components/FastImage/index.js
  src/components/FastImage/index.native.js
  src/components/ImageView/index.js
  src/components/ImageView/index.native.js
  src/components/ImageWithSizeCalculation.js
  src/components/ThumbnailImage.js
  src/libs/chatAttachmentTokenHeaders.js
Labels: CP Staging

#13015 Update version to 1.2.31-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13014 Revert "refactor navigation modal card styles"
  src/libs/Navigation/AppNavigator/modalCardStyleInterpolator.js
  src/pages/SearchPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/styles/cardStyles/index.js
  src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
  src/styles/styles.js
Labels: CP Staging

#13016 🍒 Cherry pick PR #13010 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/Avatar.js
  src/components/FastImage/index.js
  src/components/FastImage/index.native.js
  src/components/ImageView/index.js
  src/components/ImageView/index.native.js
  src/components/ImageWithSizeCalculation.js
  src/components/ThumbnailImage.js
  src/libs/chatAttachmentTokenHeaders.js
Labels: automerge, Engineering, Hourly

#13019 Update version to 1.2.31-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13020 🍒 Cherry pick PR #13014 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/modalCardStyleInterpolator.js
  src/pages/SearchPage.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/styles/cardStyles/index.js
  src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
  src/styles/styles.js
Labels: automerge

#13028 Only navigate to chat reports
  src/libs/ReportUtils.js
Labels: CP Staging

#13030 Update version to 1.2.31-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13031 🍒 Cherry pick PR #13028 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#12859 [Internal QA] Test mobile deployment
  .github/actions/composite/setupNode/action.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lint.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/test.yml
  .github/workflows/testBuild.yml
  .github/workflows/validateGithubActions.yml
  .github/workflows/verifyPodfile.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: InternalQA

#13057 Update version to 1.2.32-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13058 Update version to 1.2.32-0 on staging
  .github/actions/composite/setupNode/action.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lint.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/test.yml
  .github/workflows/testBuild.yml
  .github/workflows/validateGithubActions.yml
  .github/workflows/verifyPodfile.yml
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-reanimated+3.0.0-rc.3.patch
  src/components/Avatar.js
  src/languages/en.js
  src/languages/es.js
  src/libs/DateUtils.js
  src/libs/IOUUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/libs/migrations/AddLastActionCreated.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/reportPropTypes.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/DateUtilsTest.js
  tests/unit/MigrationTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
Labels: automerge

#13060 Update version to 1.2.32-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13061 Update version to 1.2.32-1 on staging
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13093 Sort archived rooms using Unix epoch
  src/CONST.js
  src/libs/OptionsListUtils.js
Labels: CP Staging

#13094 Update version to 1.2.32-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13096 Update version to 1.2.32-2 on production
  .github/actions/composite/setupNode/action.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lint.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/test.yml
  .github/workflows/testBuild.yml
  .github/workflows/validateGithubActions.yml
  .github/workflows/verifyPodfile.yml
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-reanimated+3.0.0-rc.3.patch
  src/CONST.js
  src/components/Avatar.js
  src/languages/en.js
  src/languages/es.js
  src/libs/DateUtils.js
  src/libs/IOUUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/libs/migrations/AddLastActionCreated.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/reportPropTypes.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/DateUtilsTest.js
  tests/unit/MigrationTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
Labels: automerge

#13097 Update version to 1.2.33-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13098 Update version to 1.2.33-0 on staging
  .env.staging
  .github/workflows/testBuild.yml
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/lets-chat.svg
  config/electronBuilder.config.js
  contributingGuides/CONTRIBUTING.md
  fastlane/Fastfile
  ios/NewExpensify/BootSplash.storyboard
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
  src/CONFIG.js
  src/CONST.js
  src/components/Checkbox.js
  src/components/CustomStatusBar/index.android.js
  src/components/CustomStatusBar/index.js
  src/components/ImageView/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#13100 Update version to 1.2.33-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13102 Update version to 1.2.33-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13012 Update version of expensify-common
  package-lock.json
  package.json
Labels: InternalQA

#13119 Fix autofill styles
  web/index.html
Labels: CP Staging

#13135 Update version to 1.2.33-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13136 🍒 Cherry pick PR #13119 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/index.html
Labels: automerge

#13142 Dark Picker Icon Colour Scheme Added
  src/components/DatePicker/styles.css
Labels: CP Staging

#13148 Update version to 1.2.33-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13149 🍒 Cherry pick PR #13142 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DatePicker/styles.css
Labels: automerge

#13106 fix android keyboard issue
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/KeyboardAvoidingView/index.js
  src/components/PDFView/index.native.js
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/components/ScreenWrapper/index.android.js
  src/components/ScreenWrapper/index.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
Labels: CP Staging

#13156 Update version to 1.2.33-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13157 🍒 Cherry pick PR #13106 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/KeyboardAvoidingView/index.js
  src/components/PDFView/index.native.js
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/components/ScreenWrapper/index.android.js
  src/components/ScreenWrapper/index.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
Labels: automerge

#13164 Fix autofill colors
  web/index.html
Labels: CP Staging

#13167 Add reimbursement account draft
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: CP Staging

#13168 Update version to 1.2.33-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13169 🍒 Cherry pick PR #13164 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/index.html
Labels: automerge

#13172 Update version to 1.2.33-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13174 Add a color to the options in the picker when using Windows
  src/components/Picker/index.js
Labels: CP Staging

#13175 Update version to 1.2.33-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13176 🍒 Cherry pick PR #13174 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Picker/index.js
Labels: automerge

#13177 Update version to 1.2.33-7 on production
  .env.staging
  .github/workflows/testBuild.yml
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/lets-chat.svg
  config/electronBuilder.config.js
  contributingGuides/CONTRIBUTING.md
  fastlane/Fastfile
  ios/NewExpensify/BootSplash.storyboard
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
  src/CONFIG.js
  src/CONST.js
  src/components/Checkbox.js
  src/components/CustomStatusBar/index.android.js
  src/components/CustomStatusBar/index.js
  src/components/DatePicker/styles.css
  src/components/ImageView/index.native.js
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/KeyboardAvoidingView/index.js
  src/components/PDFView/index.native.js
  src/components/Picker/index.js
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/components/ScreenWrapper/index.android.js
  src/components/ScreenWrapper/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/styles.js
  src/styles/themes/default.js
  web/index.html
Labels: automerge

#13178 Update version to 1.2.34-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13090 Remove the reviewer checklist from the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: InternalQA

#13201 Revert filtering out workspaces with pending delete action
  src/pages/workspace/WorkspacesListPage.js
Labels: CP Staging

#13206 Update version to 1.2.34-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
