Repository Expensify/App, pull requests merged in 2022-09, with the labels that each got.

#10689 Remove workspace chats on delete even if they are pinned
  src/libs/OptionsListUtils.js
Labels: ContributorPlusReview

#10745 Update version to 1.1.95-4 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/Button.js
  src/components/Checkbox.js
  src/components/CheckboxWithLabel.js
  src/components/Icon/index.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/TextInput/BaseTextInput.js
  src/libs/NumberUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/getClickedElementLocation/index.js
  src/libs/getClickedTargetLocation/index.js
  src/libs/getClickedTargetLocation/index.native.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/bills/WorkspaceBillsNoVBAView.js
  src/pages/workspace/card/WorkspaceCardNoVBAView.js
  src/pages/workspace/invoices/WorkspaceInvoicesNoVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelNoVBAView.js
  src/styles/styles.js
  src/styles/variables.js
  tests/unit/LHNOrderTest.js
Labels: automerge

#10746 Update version to 1.1.96-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10764 Fix for delete comment refactor
  src/libs/actions/Report.js
Labels: CP Staging

#10773 Update version to 1.1.96-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10774 🍒 Cherry pick PR #10764 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#10775 Revert "update react-native-svg version"
  package-lock.json
  package.json
Labels: CP Staging

#10777 Update version to 1.1.96-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10778 🍒 Cherry pick PR #10775 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10781 Update version to 1.1.96-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10782 🍒 Cherry pick PR #10779 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsList.js
Labels: automerge

#10783 Add resendLink message to successData
  src/libs/actions/Session/index.js
Labels: CP Staging

#10786 Update version to 1.1.96-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10787 🍒 Cherry pick PR #10783 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
Labels: automerge

#10780 Show deleted messages with a strike-through when offline
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessage.js
Labels: CP Staging

#10795 Update version to 1.1.96-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10796 🍒 Cherry pick PR #10780 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessage.js
Labels: automerge

#10805 Update version to 1.1.96-5 on production
  android/app/build.gradle
  contributingGuides/OFFLINE_UX.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DotIndicatorMessage.js
  src/components/OfflineWithFeedback.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/NumberUtils.js
  src/libs/OptionsListUtils.js
  src/libs/Pusher/EventType.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/Session/index.js
  src/libs/deprecatedAPI.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/signin/LoginForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/styles.js
  tests/actions/ReportTest.js
Labels: automerge

#10806 Update version to 1.1.97-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10814 Update version to 1.1.97-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/InitialSettingsPage.js
Labels: automerge

#10815 Update version to 1.1.97-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10816 Update version to 1.1.97-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/PDFView/PDFInfoMessage.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.js
  src/components/PDFView/index.native.js
  src/components/PDFView/pdfViewPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/report/ReportActionsList.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#10557 Refactor custom unit rate update
  src/CONST.js
  src/components/DotIndicatorMessage.js
  src/libs/actions/Policy.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: CP Staging

#10836 Update version to 1.1.97-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10844 [NO QA] Update iOS cert and provisioning profile
  ios/Certificates.p12.gpg
  ios/chat_expensify_appstore.mobileprovision.gpg
Labels: CP Staging

#10845 Update version to 1.1.97-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10854 Update version to 1.1.97-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10856 [No QA] Fetch full PR object to fix CPs
  .github/actions/javascript/getPullRequestDetails/getPullRequestDetails.js
  .github/actions/javascript/getPullRequestDetails/index.js
Labels: CP Staging

#10857 Update version to 1.1.97-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10858 🍒 Cherry pick PR #10856 to staging 🍒
  .github/actions/javascript/getPullRequestDetails/getPullRequestDetails.js
  .github/actions/javascript/getPullRequestDetails/index.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10859 🍒 Cherry pick PR #10844 to staging 🍒
  android/app/build.gradle
  ios/Certificates.p12.gpg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/chat_expensify_appstore.mobileprovision.gpg
  package-lock.json
  package.json
Labels: automerge

#10861 🍒 Cherry pick PR #10557 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/DotIndicatorMessage.js
  src/libs/actions/Policy.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#10867 Attempt to workaround a workflow CP edge case
  README.md
Labels: CP Staging

#10868 Update version to 1.1.97-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10869 🍒 Cherry pick PR #10867 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10881 Update version to 1.1.98-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10908 Partial revert of "Use `window.location.href` for current URL"
  src/CONST.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/NavigationRoot.js
Labels: CP Staging

#10909 Update version to 1.1.98-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10911 🍒 Cherry pick PR #10908 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/NavigationRoot.js
Labels: automerge

#10914 Update version to 1.1.99-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10915 Update version to 1.1.99-0 on staging
  .github/workflows/contributorChecklists.yml
  .github/workflows/contributorPlusChecklists.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/components/TestToolMenu.js
  src/libs/HttpUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/home/ReportScreen.js
  src/pages/settings/PreferencesPage.js
Labels: automerge

#10918 Update version to 1.1.99-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10919 Update version to 1.1.99-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ArrowKeyFocusManager.js
  src/components/OptionsSelector/BaseOptionsSelector.js
Labels: automerge

#10920 Revert "Toggle staging and production server api"
  src/CONFIG.js
  src/CONST.js
  src/components/TestToolMenu.js
  src/libs/HttpUtils.js
  src/libs/actions/User.js
  src/pages/settings/PreferencesPage.js
Labels: CP Staging

#10921 Update version to 1.1.99-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10922 🍒 Cherry pick PR #10920 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/components/TestToolMenu.js
  src/libs/HttpUtils.js
  src/libs/actions/User.js
  src/pages/settings/PreferencesPage.js
Labels: automerge

#10937 Return early if policy doesn't have `customUnits` to prevent crash
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: CP Staging

#10940 Update version to 1.1.99-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10942 CP a useless commit to fix failed release
  README.md
Labels: CP Staging

#10944 Update version to 1.1.99-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10945 🍒 Cherry pick PR #10942 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10955 Update version to 1.1.99-4 on production
  .github/workflows/contributorChecklists.yml
  .github/workflows/contributorPlusChecklists.yml
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ArrowKeyFocusManager.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
Labels: automerge

#10956 Update version to 1.2.0-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10957 Update version to 1.2.0-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/KYCWall/kycWallPropTypes.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/RoomNameInput.js
  src/components/SettlementButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Report.js
  src/libs/actions/Wallet.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/EnablePayments/walletTermsPropTypes.js
  src/pages/ReportSettingsPage.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/PaymentsPage/paymentsPagePropTypes.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withPolicy.js
Labels: automerge

#10979 Revert "Refactor withFullPolicy"
  src/components/AvatarWithIndicator.js
  src/components/RoomNameInput.js
  src/pages/ReportSettingsPage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withFullPolicy.js
Labels: CP Staging

#10980 Update version to 1.2.0-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10981 🍒 Cherry pick PR #10979 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
  src/components/RoomNameInput.js
  src/pages/ReportSettingsPage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withFullPolicy.js
Labels: automerge

#10999 Update version to 1.2.0-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11000 Dummy change to allow new staging CP
  README.md
Labels: CP Staging

#11001 Update version to 1.2.0-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11002 🍒 Cherry pick PR #11000 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11006 Omit default Avatar param to prevent crash on app start
  src/libs/OptionsListUtils.js
Labels: CP Staging

#11007 Update version to 1.2.0-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11008 🍒 Cherry pick PR #11006 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#10974 Remove usages of `onyxRates`
  src/libs/actions/Policy.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: CP Staging

#11014 Update version to 1.2.0-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11016 🍒 Cherry pick PR #10974 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#11022 Use existing personal details' avatar when it exists
  src/libs/OptionsListUtils.js
Labels: CP Staging

#11024 Update version to 1.2.0-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11023 Add missing `alternateText` option in option
  src/libs/OptionsListUtils.js
Labels: CP Staging

#11025 🍒 Cherry pick PR #11022 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#11027 Update version to 1.2.0-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11028 🍒 Cherry pick PR #11023 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#11029 Only use personal detail login as `alternateText` if we're not making the option for a report
  src/libs/OptionsListUtils.js
Labels: CP Staging

#11031 Update version to 1.2.0-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11032 🍒 Cherry pick PR #11029 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#11040 Update version to 1.2.0-8 on production
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/components/AnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/anchorForCommentsOnlyPropTypes.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/AnchorForCommentsOnly/index.native.js
  src/components/AvatarWithIndicator.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/KYCWall/kycWallPropTypes.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/SettlementButton.js
  src/components/TestToolMenu.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/languages/en.js
  src/languages/es.js
  src/libs/HttpUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/libs/actions/Wallet.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/EnablePayments/walletTermsPropTypes.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/PaymentsPage/paymentsPagePropTypes.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  tests/unit/LHNOrderTest.js
Labels: automerge

#11041 Update version to 1.2.1-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11042 Update version to 1.2.1-0 on staging
  .github/actions/javascript/contributorChecklist/contributorChecklist.js
  .github/actions/javascript/contributorChecklist/index.js
  .storybook/main.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Middleware/Logging.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/validateBankAccount.js
  src/libs/actions/Wallet.js
  src/libs/deprecatedAPI.js
  src/libs/getPermittedDecimalSeparator/index.ios.js
  src/libs/getPermittedDecimalSeparator/index.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#11105 Update version to 1.2.1-0 on production
  .github/actions/javascript/contributorChecklist/contributorChecklist.js
  .github/actions/javascript/contributorChecklist/index.js
  .storybook/main.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Middleware/Logging.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/validateBankAccount.js
  src/libs/actions/Wallet.js
  src/libs/deprecatedAPI.js
  src/libs/getPermittedDecimalSeparator/index.ios.js
  src/libs/getPermittedDecimalSeparator/index.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#11107 Update version to 1.2.2-0 on staging
  .env.temp
  __mocks__/@react-native-firebase/crashlytics.js
  __mocks__/pusher-js/react-native.js
  __mocks__/react-native-safe-area-context.js
  __mocks__/react-native.js
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/Checkbox.js
  src/components/DisplayNames/index.native.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/ReportWelcomeText.js
  src/components/UnreadActionIndicator.js
  src/libs/Authentication.js
  src/libs/DateUtils.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Middleware/index.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/NameValuePair.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/Session/index.js
  src/libs/actions/SignInRedirect.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/SetPasswordPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/FloatingMessageCounter/FloatingMessageCounterContainer/index.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/settings/PasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPage.js
  src/setup/platformSetup/index.native.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/LHNOrderTest.js
  tests/unit/loginTest.js
  tests/utils/TestHelper.js
  tests/utils/waitForPromisesToResolveWithAct.js
Labels: automerge

#11136 Update version to 1.2.2-0 on production
  .env.temp
  __mocks__/@react-native-firebase/crashlytics.js
  __mocks__/pusher-js/react-native.js
  __mocks__/react-native-safe-area-context.js
  __mocks__/react-native.js
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/Checkbox.js
  src/components/DisplayNames/index.native.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/ReportWelcomeText.js
  src/components/UnreadActionIndicator.js
  src/libs/Authentication.js
  src/libs/DateUtils.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Middleware/index.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/NameValuePair.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/Session/index.js
  src/libs/actions/SignInRedirect.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/SetPasswordPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/FloatingMessageCounter/FloatingMessageCounterContainer/index.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/settings/PasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPage.js
  src/setup/platformSetup/index.native.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/LHNOrderTest.js
  tests/unit/loginTest.js
  tests/utils/TestHelper.js
  tests/utils/waitForPromisesToResolveWithAct.js
Labels: automerge

#11137 Update version to 1.2.3-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11138 Update version to 1.2.3-0 on staging
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/contributorChecklist/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AvatarWithImagePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/libs/fileDownload/FileUtils.js
  src/pages/SetPasswordPage.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceInitialPage.js
Labels: automerge

#11154 Add `app_id` for fastlane's `upload_symbols_to_crashlytics` Testflight build step
  fastlane/Fastfile
Labels: InternalQA

#11174 Update version to 1.2.3-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11175 🍒 Cherry pick PR #11173 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/IOUConfirmationList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#11178 Update version to 1.2.3-1 on production
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/contributorChecklist/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AvatarWithImagePicker.js
  src/components/IOUConfirmationList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/libs/fileDownload/FileUtils.js
  src/pages/SetPasswordPage.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceInitialPage.js
Labels: automerge

#11179 Update version to 1.2.4-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11180 Update version to 1.2.4-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest/setup.js
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/anchorForCommentsOnlyPropTypes.js
  src/components/LHNOptionsList/LHNOptionsList.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/OptionRow.js
  src/components/ReportActionItem/IOUPreview.js
  src/libs/ErrorUtils.js
  src/libs/OptionsListUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/pages/SetPasswordPage.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  tests/unit/LHNOrderTest.js
Labels: automerge

#11182 [No QA] Fix syntax error in `upload_symbols_to_crashlytics`
  fastlane/Fastfile
Labels: CP Staging

#11183 Update version to 1.2.4-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11184 🍒 Cherry pick PR #11182 to staging 🍒
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11209 Update version to 1.2.4-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11210 🍒 Cherry pick PR #11188 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/SidebarUtils.js
Labels: automerge

#11212 Update version to 1.2.4-2 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest/setup.js
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/anchorForCommentsOnlyPropTypes.js
  src/components/LHNOptionsList/LHNOptionsList.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/OptionRow.js
  src/components/ReportActionItem/IOUPreview.js
  src/libs/ErrorUtils.js
  src/libs/OptionsListUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/pages/SetPasswordPage.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  tests/unit/LHNOrderTest.js
Labels: automerge

#11213 Update version to 1.2.5-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11214 Update version to 1.2.5-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/RoomNameInput.js
  src/components/SignInPageForm/index.js
  src/components/TextInput/TextInputLabel/index.js
  src/components/TextInput/index.js
  src/libs/API.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/Performance.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/NewPasswordForm.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
Labels: automerge

#11240 Revert "OptionsSelector - Migrate setNativeProps to state"
  src/components/OptionsSelector/BaseOptionsSelector.js
Labels: CP Staging

#11242 Update version to 1.2.5-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11243 🍒 Cherry pick PR #11240 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector/BaseOptionsSelector.js
Labels: automerge

#11244 Add teamdot check to SideBarUtils.js
  src/libs/SidebarUtils.js
Labels: CP Staging

#11247 Update version to 1.2.5-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11248 🍒 Cherry pick PR #11244 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/SidebarUtils.js
Labels: automerge

#11249 Update version to 1.2.5-2 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/RoomNameInput.js
  src/components/SignInPageForm/index.js
  src/components/TextInput/TextInputLabel/index.js
  src/components/TextInput/index.js
  src/libs/API.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/Performance.js
  src/libs/SidebarUtils.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/NewPasswordForm.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
Labels: automerge

#11250 Update version to 1.2.6-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11251 Update version to 1.2.6-0 on staging
  .gitignore
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcworkspace/contents.xcworkspacedata
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarWithIndicator.js
  src/components/RoomNameInput.js
  src/libs/NumberUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Link.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/asyncOpenURL/index.website.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimbursePage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withPolicy.js
  src/styles/styles.js
Labels: automerge

#10899 Add a rotating slate of placeholder text for Concierge chat
  src/languages/en.js
  src/languages/es.js
  src/pages/home/report/ReportActionCompose.js
Labels: InternalQA, ContributorPlusReview

#11294 Update version to 1.2.6-0 on production
  .gitignore
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcworkspace/contents.xcworkspacedata
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarWithIndicator.js
  src/components/RoomNameInput.js
  src/libs/NumberUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Link.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/asyncOpenURL/index.website.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimbursePage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withPolicy.js
  src/styles/styles.js
Labels: automerge

#11295 Update version to 1.2.7-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11296 Update version to 1.2.7-0 on staging
  android/app/build.gradle
  docs/_sass/_main.scss
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPaymentMethodMenu.js
  src/components/AddPlaidBankAccount.js
  src/components/InvertedFlatList/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Performance.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/SidebarUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Plaid.js
  src/libs/actions/ReimbursementAccount/errors.js
  src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/setupWithdrawalAccount.js
  src/libs/actions/Session/index.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/plaidDataPropTypes.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  tests/actions/ReimbursementAccountTest.js
  tests/unit/LHNOrderTest.js
  tests/utils/TestHelper.js
Labels: automerge

#11298 Update version to 1.2.7-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11299 Update version to 1.2.7-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#11303 [CP Staging] Pass `report` instead of `reportID` to `ReportActionItem`
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
Labels: CP Staging

#11307 Update version to 1.2.7-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11308 🍒 Cherry pick PR #11303 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
Labels: automerge

#11355 Update version to 1.2.7-2 on production
  android/app/build.gradle
  docs/_sass/_main.scss
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPaymentMethodMenu.js
  src/components/AddPlaidBankAccount.js
  src/components/InvertedFlatList/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Performance.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/SidebarUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Plaid.js
  src/libs/actions/ReimbursementAccount/errors.js
  src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/setupWithdrawalAccount.js
  src/libs/actions/Session/index.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/plaidDataPropTypes.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  tests/actions/ReimbursementAccountTest.js
  tests/unit/LHNOrderTest.js
  tests/utils/TestHelper.js
Labels: automerge

#11356 Update version to 1.2.8-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11357 Update version to 1.2.8-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/CopyTextToClipboard.js
  src/components/LHNOptionsList/LHNOptionsList.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/styles/styles.js
Labels: automerge

#11374 Update version to 1.2.8-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/CopyTextToClipboard.js
  src/components/LHNOptionsList/LHNOptionsList.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/styles/styles.js
Labels: automerge

#11373 Update version to 1.2.9-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11375 Update version to 1.2.9-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/actions/PersonalDetails.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#11442 Update version to 1.2.9-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/actions/PersonalDetails.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#11443 Update version to 1.2.10-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11445 Update version to 1.2.10-0 on staging
  .well-known/apple-app-site-association
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  desktop/dev.js
  desktop/start.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AddPaymentMethodMenu.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/FormAlertWithSubmitButton.js
  src/components/ReportWelcomeText.js
  src/components/paypalMeDataPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PaymentUtils.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/libs/models/BankAccount.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceInvitePage.js
  tests/unit/fetchFreePlanVerifiedBankAccountTest.js
Labels: automerge

#11363 Render banner in Concierge chat
  src/ONYXKEYS.js
  src/components/ArchivedReportFooter.js
  src/components/Banner.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/DeprecatedCustomActions.js
  src/pages/home/ReportScreen.js
  src/styles/styles.js
Labels: InternalQA

#11477 Update version to 1.2.10-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11478 🍒 Cherry pick PR #11466 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: automerge

#10452 Migrate policy API to remove policy members
  package-lock.json
  package.json
  src/components/BlockingViews/FullPageNotFoundView.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ActiveClientManager/index.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/ActiveClients.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/withPolicy.js
Labels: ContributorPlusReview

#11482 Update version to 1.2.10-1 on production
  .well-known/apple-app-site-association
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  desktop/dev.js
  desktop/start.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AddPaymentMethodMenu.js
  src/components/BigNumberPad.js
  src/components/Button.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/FormAlertWithSubmitButton.js
  src/components/ReportWelcomeText.js
  src/components/paypalMeDataPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PaymentUtils.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/libs/models/BankAccount.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/NewChatPage.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceInvitePage.js
  tests/unit/fetchFreePlanVerifiedBankAccountTest.js
Labels: automerge

#11483 Update version to 1.2.11-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
