Repository Expensify/App, pull requests merged in 2022-04, with the labels that each got.

#8488 Update version to 1.1.50-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8489 Update version to 1.1.49-1 on production
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/index.native.js
  src/components/Button.js
  src/components/EmojiPicker/index.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInput/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/HttpUtils.js
  src/libs/Network.js
  src/libs/Network/NetworkEvents.js
  src/libs/Network/NetworkStore.js
  src/libs/Network/PersistedRequestsQueue.js
  src/libs/Network/enhanceParameters.js
  src/libs/Network/index.js
  src/libs/Network/processRequest.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/RetryCounter.js
  src/libs/actions/NetworkRequestQueue.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/PersistedRequests.js
  src/libs/actions/Session/index.js
  src/libs/actions/Session/setSessionLoadingAndError.js
  src/libs/actions/User.js
  src/libs/reportUtils.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReportDetailsPage.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/settings/userPropTypes.js
  src/pages/wallet/WalletStatementPage.js
  src/styles/styles.js
  tests/actions/ReimbursementAccountTest.js
  tests/actions/SessionTest.js
  tests/unit/MigrationTest.js
  tests/unit/NetworkTest.js
  tests/unit/enhanceParametersTest.js
Labels: automerge

#8490 Update version to 1.1.51-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8491 Update version to 1.1.51-0 on staging
  android/app/build.gradle
  config/electronBuilder.config.js
  config/webpack/webpack.dev.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
  src/components/ErrorBoundary/index.js
  src/components/ErrorBoundary/index.native.js
  src/components/ImageView/index.js
  src/components/ImageView/index.native.js
  src/components/ImageWithSizeCalculation.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/HttpUtils.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/setup/platformSetup/index.website.js
  src/styles/styles.js
Labels: automerge

#8513 Update version to 1.1.51-0 on production
  android/app/build.gradle
  config/electronBuilder.config.js
  config/webpack/webpack.dev.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
  src/components/ErrorBoundary/index.js
  src/components/ErrorBoundary/index.native.js
  src/components/ImageView/index.js
  src/components/ImageView/index.native.js
  src/components/ImageWithSizeCalculation.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/HttpUtils.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/setup/platformSetup/index.website.js
  src/styles/styles.js
Labels: automerge

#8514 Update version to 1.1.52-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8515 Update version to 1.1.52-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ArchivedReportFooter.js
  src/components/FullscreenLoadingIndicator.js
  src/components/ReportWelcomeText.js
  src/components/WalletStatementModal/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Network/index.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/home/ReportScreen.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#8561 Update version to 1.1.52-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ArchivedReportFooter.js
  src/components/FullscreenLoadingIndicator.js
  src/components/ReportWelcomeText.js
  src/components/WalletStatementModal/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Network/index.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/home/ReportScreen.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#8562 Update version to 1.1.53-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8564 Update version to 1.1.54-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8565 Update version to 1.1.54-0 on staging
  .github/actions/awaitStagingDeploys/index.js
  .github/actions/checkDeployBlockers/checkDeployBlockers.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/actions/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
  .storybook/main.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/LocalePicker.js
  src/components/Picker/BasePicker/basePickerPropTypes.js
  src/components/Picker/BasePicker/index.js
  src/components/Picker/index.js
  src/components/StatePicker.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReportSettingsPage.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseNoVBAView.js
  src/stories/Form.stories.js
  src/stories/Picker.stories.js
  tests/unit/GithubUtilsTest.js
  tests/unit/createOrUpdateStagingDeployTest.js
Labels: automerge

#8598 Update version to 1.1.54-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8599 🍒 Cherry pick PR #8596 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#8627 Update version to 1.1.55-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8629 Update version to 1.1.54-1 on production
  .github/actions/awaitStagingDeploys/index.js
  .github/actions/checkDeployBlockers/checkDeployBlockers.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/actions/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
  .storybook/main.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/LocalePicker.js
  src/components/Picker/BasePicker/basePickerPropTypes.js
  src/components/Picker/BasePicker/index.js
  src/components/Picker/index.js
  src/components/StatePicker.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Report.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReportSettingsPage.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseNoVBAView.js
  src/stories/Form.stories.js
  src/stories/Picker.stories.js
  tests/unit/GithubUtilsTest.js
  tests/unit/createOrUpdateStagingDeployTest.js
Labels: automerge

#8630 Update version to 1.1.55-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8628 Update version to 1.1.55-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/RoomNameInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportSettingsPage.js
  src/pages/SearchPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
Labels: automerge

#8695 Key fix for timezone
  src/pages/settings/Profile/ProfilePage.js
Labels: CP Staging

#8696 Update version to 1.1.55-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8697 🍒 Cherry pick PR #8695 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#8705 Update version to 1.1.56-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8704 Update version to 1.1.55-2 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/RoomNameInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportSettingsPage.js
  src/pages/SearchPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
Labels: automerge

#8773 Update version to 1.1.57-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8775 Update version to 1.1.57-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8781 Update version to 1.1.57-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8771 Add platform to each network request in addition to referer
  src/libs/Network/enhanceParameters.js
  tests/unit/enhanceParametersTest.js
Labels: InternalQA

#8803 Adjust webpack type to apple-app-site-association
  config/webpack/webpack.common.js
Labels: CP Staging

#8806 Update version to 1.1.57-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8807 🍒 Cherry pick PR #8803 to staging 🍒
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
