Repository Expensify/App, pull requests merged in 2022-12, with the labels that each got.

#13238 Update version to 1.2.35-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13239 Update version to 1.2.35-0 on staging
  .env.staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/SCREENS.js
  src/components/BlockingViews/FullPageNotFoundView.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/linkingConfig.js
  src/pages/ConciergePage.js
  src/pages/ErrorPage/NotFoundPage.js
  src/pages/home/ReportScreen.js
Labels: automerge

#13271 Revert PR 13187 to resolve checkbox bug
  src/components/Checkbox.js
  src/components/Checkbox/index.js
  src/components/Checkbox/index.native.js
  src/components/TextInput/BaseTextInput.js
Labels: CP Staging

#13273 Update version to 1.2.35-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13280 Update version to 1.2.35-0 on production
  .env.staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/SCREENS.js
  src/components/BlockingViews/FullPageNotFoundView.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/linkingConfig.js
  src/pages/ConciergePage.js
  src/pages/ErrorPage/NotFoundPage.js
  src/pages/home/ReportScreen.js
Labels: automerge

#13281 Update version to 1.2.36-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13284 Update Onfido to latest to resolve deploy issues
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: CP Staging

#13305 Update version to 1.2.36-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13306 🍒 Cherry pick PR #13284 to staging 🍒
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#13298 [CP Staging] Changed border style
  src/styles/styles.js
Labels: CP Staging

#13334 Update version to 1.2.36-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13335 🍒 Cherry pick PR #13298 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#13029 Enable native staging apps to use Staging API
  src/components/TestToolMenu.js
  src/libs/HttpUtils.js
  src/libs/shouldUseStagingServer/index.js
  src/libs/shouldUseStagingServer/index.native.js
Labels: InternalQA

#13407 Revert "Display banner to enable 2FA when setting up VBBA"
  assets/images/simple-illustrations/simple-illustration__shield.svg
  src/components/Icon/Illustrations.js
  src/languages/en.js
  src/languages/es.js
  src/pages/ReimbursementAccount/Enable2FAPrompt.js
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: CP Staging

#13410 Update version to 1.2.36-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13411 🍒 Cherry pick PR #13407 to staging 🍒
  android/app/build.gradle
  assets/images/simple-illustrations/simple-illustration__shield.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Icon/Illustrations.js
  src/languages/en.js
  src/languages/es.js
  src/pages/ReimbursementAccount/Enable2FAPrompt.js
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: automerge

#13412 Refactor the function for filtering the currency list
  src/libs/OptionsListUtils.js
  src/pages/iou/IOUCurrencySelection.js
Labels: CP Staging

#13421 Update version to 1.2.36-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13422 🍒 Cherry pick PR #13412 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/pages/iou/IOUCurrencySelection.js
Labels: automerge

#13428 Update version to 1.2.37-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13214 Fix border radii
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/ContextMenuItem.js
  src/components/TextInput/BaseTextInput.js
  src/styles/StyleUtils.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
Labels: Design

#13448 fix "Upload photo" popup menu not hiding
  src/components/AttachmentPicker/index.js
Labels: CP Staging

#13468 Update version to 1.2.37-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13469 🍒 Cherry pick PR #13448 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.js
Labels: automerge

#13475 Remove extra flex from style
  src/styles/styles.js
Labels: CP Staging

#13486 Update version to 1.2.37-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13487 🍒 Cherry pick PR #13475 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#13495 Update version to 1.2.38-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13526 Update version to 1.2.38-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13527 🍒 Cherry pick PR #13522 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
Labels: automerge

#13519 Stop displaying Closed Account message when the user starts typing
  src/pages/signin/LoginForm.js
Labels: CP Staging

#13537 Update version to 1.2.38-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13530 fix button position
  src/components/Form.js
Labels: CP Staging

#13541 Update version to 1.2.38-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13542 🍒 Cherry pick PR #13530 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Form.js
Labels: automerge

#13531 Report can be a {}, improve check for emptyness/falsey
  src/libs/ReportUtils.js
Labels: CP Staging

#13544 Update version to 1.2.38-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13545 🍒 Cherry pick PR #13531 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#13553 Update version to 1.2.38-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13554 🍒 Cherry pick PR #13535 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OfflineWithFeedback.js
Labels: automerge

#13559 Fix Shell Lint
  .github/scripts/buildActions.sh
  .github/scripts/validateActionsAndWorkflows.sh
Labels: InternalQA

#13525 Flatten styles to avoid crash
  src/components/OptionRow.js
Labels: CP Staging

#13567 Update version to 1.2.38-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13568 🍒 Cherry pick PR #13525 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionRow.js
Labels: automerge

#13569 Update version to 1.2.38-6 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Avatar.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/ContextMenuItem.js
  src/components/CurrencySymbolButton.js
  src/components/Form.js
  src/components/OfflineWithFeedback.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsList/optionsListPropTypes.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.js
  src/components/PDFView/index.native.js
  src/components/Picker/index.js
  src/components/ReportActionItem/IOUAction.js
  src/components/RoomNameInput/index.native.js
  src/components/SettlementButton.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Clipboard/index.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/signin/LoginForm.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/colors.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#13570 Update version to 1.2.39-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13571 Update version to 1.2.39-0 on staging
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/testBuild.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Form.js
  src/components/Modal/BaseModal.js
  src/components/MultipleAvatars.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/RoomHeaderAvatars.js
  src/libs/Navigation/AppNavigator/modalCardStyleInterpolator.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/variables.js
Labels: automerge

#13399 use time-analytics-webpack-plugin
  config/webpack/webpack.dev.js
  package-lock.json
  package.json
Labels: InternalQA

#13608 Update version to 1.2.39-0 on production
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/testBuild.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Form.js
  src/components/Modal/BaseModal.js
  src/components/MultipleAvatars.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/RoomHeaderAvatars.js
  src/libs/Navigation/AppNavigator/modalCardStyleInterpolator.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/variables.js
Labels: automerge

#13609 Update version to 1.2.40-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13610 Update version to 1.2.40-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  .github/workflows/testBuild.yml
  android/app/build.gradle
  assets/images/bankicons/generic-bank-account.svg
  config/webpack/webpack.dev.js
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/KeyboardAvoidingView/index.js
  src/libs/actions/Report.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
Labels: automerge

#13613 Update version to 1.2.40-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13614 Update version to 1.2.40-1 on staging
  android/app/build.gradle
  docs/_data/routes.yml
  docs/articles/other/Your-Expensify-Account-Manager.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13617 Update version to 1.2.40-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13619 Update version to 1.2.40-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13620 Update version to 1.2.40-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/IOUPreview.js
Labels: automerge

#13651 Update version to 1.2.40-3 on production
  .github/PULL_REQUEST_TEMPLATE.md
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  .github/workflows/testBuild.yml
  android/app/build.gradle
  assets/images/bankicons/generic-bank-account.svg
  config/webpack/webpack.dev.js
  contributingGuides/REVIEWER_CHECKLIST.md
  docs/_data/routes.yml
  docs/articles/other/Your-Expensify-Account-Manager.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONFIG.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/KeyboardAvoidingView/index.js
  src/components/ReportActionItem/IOUPreview.js
  src/libs/Url.js
  src/libs/actions/Report.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  tests/unit/UrlTest.js
Labels: automerge

#13652 Update version to 1.2.41-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13653 Update version to 1.2.41-0 on staging
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/PDFView/index.js
  src/components/RoomNameInput/index.native.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/focusTextInputAfterAnimation/index.android.js
  src/libs/focusTextInputAfterAnimation/index.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#13656 Update version to 1.2.41-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13657 Update version to 1.2.41-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/SelectionScraper/index.js
Labels: automerge

#13703 Make sure that we pass markdown to parser when getting the parsed originalCommentHTML
  src/libs/actions/Report.js
Labels: CP Staging

#13705 Update version to 1.2.41-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12646 Refactor pay with wallet API
  src/components/ReportTransaction.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/ReportActions.js
  src/libs/deprecatedAPI.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/IOUModal.js
Labels: InternalQA

#13706 🍒 Cherry pick PR #13703 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge, Engineering, Hourly

#13707 Revert "Load pdfjs webworker script from source"
  config/webpack/webpack.common.js
  src/components/PDFView/index.js
Labels: CP Staging

#13709 Update version to 1.2.41-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13710 🍒 Cherry pick PR #13707 to staging 🍒
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/PDFView/index.js
Labels: automerge

#13716 🍒 Cherry pick PR #13712 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13720 Update version to 1.2.41-4 on production
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/buildActions.sh
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/RoomNameInput/index.native.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/focusTextInputAfterAnimation/index.android.js
  src/libs/focusTextInputAfterAnimation/index.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#13721 Update version to 1.2.42-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13724 Update version to 1.2.42-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13725 Update version to 1.2.42-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/IOUPreview.js
  src/libs/actions/Report.js
  src/pages/iou/IOUDetailsModal.js
Labels: automerge

#13730 [Internal QA] Update location usage key
  ios/NewExpensify/Info.plist
Labels: InternalQA

#13758 Revert "Use Onyx.clear to preserve state when logging out"
  package-lock.json
  package.json
  src/libs/actions/SignInRedirect.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/NetworkTest.js
Labels: CP Staging

#13759 Update version to 1.2.42-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13760 🍒 Cherry pick PR #13758 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/SignInRedirect.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#13775 Update version to 1.2.43-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13776 Update version to 1.2.43-0 on staging
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  contributingGuides/CONTRIBUTING.md
  docs/README.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/CheckboxWithTooltip/CheckboxWithTooltipForMobileWebAndNative.js
  src/components/CheckboxWithTooltip/checkboxWithTooltipPropTypes.js
  src/components/CheckboxWithTooltip/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/Form.js
  src/components/ImageView/index.native.js
  src/components/InvertedFlatList/index.android.js
  src/components/RoomNameInput/index.js
  src/components/RoomNameInput/index.native.js
  src/components/RoomNameInput/roomNameInputPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Middleware/Logging.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session/index.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Profile/LoginField.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#13782 [Internal QA] Update location usage key #2
  ios/NewExpensify/Info.plist
Labels: InternalQA

#13785 Update version to 1.2.43-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13786 Update version to 1.2.43-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13840 Update version to 1.2.43-1 on production
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  contributingGuides/CONTRIBUTING.md
  docs/README.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/CheckboxWithTooltip/CheckboxWithTooltipForMobileWebAndNative.js
  src/components/CheckboxWithTooltip/checkboxWithTooltipPropTypes.js
  src/components/CheckboxWithTooltip/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/Form.js
  src/components/ImageView/index.native.js
  src/components/InvertedFlatList/index.android.js
  src/components/RoomNameInput/index.js
  src/components/RoomNameInput/index.native.js
  src/components/RoomNameInput/roomNameInputPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Middleware/Logging.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session/index.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUModal.js
  src/pages/settings/Profile/LoginField.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#13841 Update version to 1.2.44-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13842 Update version to 1.2.44-0 on staging
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  config/webpack/webpack.desktop.js
  desktop/ELECTRON_EVENTS.js
  desktop/contextBridge.js
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddPlaidBankAccount.js
  src/components/AvatarWithImagePicker.js
  src/components/ConfirmationPage.js
  src/components/DisplayNames/index.js
  src/components/MenuItem.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/ReportActionItem/IOUQuote.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Localize/LocaleListener/BaseLocaleListener.js
  src/libs/Localize/LocaleListener/index.desktop.js
  src/libs/Localize/LocaleListener/index.js
  src/libs/Localize/index.js
  src/libs/LoginUtils.js
  src/libs/Network/NetworkStore.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/ValidationUtils.js
  src/libs/actions/App.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Plaid.js
  src/libs/actions/ReimbursementAccount/store.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/actions/Wallet.js
  src/libs/onScreenTransitionEnd/index.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/RequestCallConfirmationScreen.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/PasswordConfirmationScreen.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  tests/actions/SessionTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#13865 Update version to 1.2.44-0 on production
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  config/webpack/webpack.desktop.js
  desktop/ELECTRON_EVENTS.js
  desktop/contextBridge.js
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddPlaidBankAccount.js
  src/components/AvatarWithImagePicker.js
  src/components/ConfirmationPage.js
  src/components/DisplayNames/index.js
  src/components/MenuItem.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/ReportActionItem/IOUQuote.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Localize/LocaleListener/BaseLocaleListener.js
  src/libs/Localize/LocaleListener/index.desktop.js
  src/libs/Localize/LocaleListener/index.js
  src/libs/Localize/index.js
  src/libs/LoginUtils.js
  src/libs/Network/NetworkStore.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/ValidationUtils.js
  src/libs/actions/App.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Plaid.js
  src/libs/actions/ReimbursementAccount/store.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/actions/Wallet.js
  src/libs/onScreenTransitionEnd/index.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/RequestCallConfirmationScreen.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/PasswordConfirmationScreen.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  tests/actions/SessionTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#13866 Update version to 1.2.45-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13867 Update version to 1.2.45-0 on staging
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/Form.js
  src/components/Picker/index.js
  src/components/ScrollViewWithContext.js
  src/libs/actions/CloseAccount.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/styles/styles.js
Labels: automerge

#13888 Update version to 1.2.45-0 on production
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/Form.js
  src/components/Picker/index.js
  src/components/ScrollViewWithContext.js
  src/libs/actions/CloseAccount.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/styles/styles.js
Labels: automerge

#13889 Update version to 1.2.46-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13890 Update version to 1.2.46-0 on staging
  .github/workflows/testBuild.yml
  .gitignore
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/android-repackage-app-bundle-and-sign.sh
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/DragAndDrop/index.js
  src/components/ReportActionItem/IOUAction.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportFooter.js
  src/pages/iou/IOUDetailsModal.js
  tests/e2e/ADDING_TESTS.md
  tests/e2e/README.md
  tests/e2e/config.js
  tests/e2e/config.local.js
  tests/e2e/testRunner.js
  tests/e2e/utils/androidReversePort.js
  tests/e2e/utils/getCurrentBranchName.js
  tests/e2e/utils/installApp.js
  tests/e2e/utils/logger.js
Labels: automerge
