Repository Expensify/App, pull requests merged in 2022-08, with the labels that each got.

#10167 Update version to 1.1.87-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10171 Update version to 1.1.87-1 on staging
  android/app/build.gradle
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CopySelectionHelper.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/libs/Clipboard/index.js
  src/libs/Clipboard/index.native.js
  src/libs/SelectionScraper/index.js
  src/libs/SelectionScraper/index.native.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ContextMenu/genericReportActionContextMenuPropTypes.js
  src/pages/home/report/ReportActionItem.js
  src/pages/settings/AppDownloadLinks.js
Labels: automerge

#10175 Update version to 1.1.87-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10176 Update version to 1.1.87-2 on staging
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10178 Update version to 1.1.87-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10179 Update version to 1.1.87-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10191 Update version to 1.1.87-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10192 Update version to 1.1.87-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/PaymentMethods.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
Labels: automerge

#10195 Update version to 1.1.87-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10196 Update version to 1.1.87-5 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
Labels: automerge

#10200 Update version to 1.1.87-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10201 Update version to 1.1.87-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/pages/LogOutPreviousUserPage.js
Labels: automerge

#10209 Update version to 1.1.87-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10210 Update version to 1.1.87-7 on staging
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10212 Update version to 1.1.87-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10213 Update version to 1.1.87-8 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10231 Fix timezone not showing correct timezone after save
  src/libs/actions/App.js
Labels: CP Staging

#10241 Update version to 1.1.87-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10242 🍒 Cherry pick PR #10231 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/App.js
Labels: automerge

#10251 Update version to 1.1.88-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10254 Update version to 1.1.88-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10255 Update version to 1.1.88-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
Labels: automerge

#10266 Revert "Start Using BeginSignIn command and remove obsolete API command calls"
  README.md
  src/ONYXKEYS.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Network/MainQueue.js
  src/libs/Network/enhanceParameters.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/SetPasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/signin/SignInPage.js
  tests/actions/ReimbursementAccountTest.js
  tests/actions/ReportTest.js
  tests/unit/NetworkTest.js
  tests/utils/TestHelper.js
Labels: CP Staging

#10268 Update version to 1.1.88-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10270 🍒 Cherry pick PR #10266 to staging 🍒
  README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Network/MainQueue.js
  src/libs/Network/enhanceParameters.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/SetPasswordPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/signin/SignInPage.js
  tests/actions/ReimbursementAccountTest.js
  tests/actions/ReportTest.js
  tests/unit/NetworkTest.js
  tests/utils/TestHelper.js
Labels: automerge

#10276 Add missing parameter from the propTypes
  src/pages/home/report/ReportTypingIndicator.js
Labels: CP Staging

#10280 Update version to 1.1.88-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10281 🍒 Cherry pick PR #10276 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportTypingIndicator.js
Labels: automerge

#10229 Fix button opacity problem when saving personal details
  src/components/OpacityView.js
Labels: CP Staging

#10294 Update version to 1.1.88-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10295 🍒 Cherry pick PR #10229 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OpacityView.js
Labels: automerge

#10299 Revert "Smart banner issue"
  web/index.html
Labels: CP Staging

#10301 Update version to 1.1.88-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10302 🍒 Cherry pick PR #10299 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/index.html
Labels: automerge

#10239 Memoize some functions in `OptionsListUtils`
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/actions/App.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  tests/unit/OptionsListUtilsTest.js
Labels: CP Staging

#10303 Update version to 1.1.88-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10305 🍒 Cherry pick PR #10239 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/actions/App.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge, Engineering, Hourly

#10307 [No QA] Add documentation for composite actions
  .github/workflows/README.md
Labels: CP Staging

#10308 Update version to 1.1.88-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10309 🍒 Cherry pick PR #10307 to staging 🍒
  .github/workflows/README.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10310 Exclude concierge links from OldDot link handling
  src/CONFIG.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
Labels: InternalQA

#10378 [No QA] Use force-push to update staging and production
  .github/actions/composite/updateProtectedBranch/action.yml
Labels: CP Staging

#10380 Update version to 1.1.88-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10381 🍒 Cherry pick PR #10378 to staging 🍒
  .github/actions/composite/updateProtectedBranch/action.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10383 Update version to 1.1.88-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10384 Update version to 1.1.88-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#9914 Refactor part of ActivateWallet into UpdatePersonalDetailsForWallet
  src/CONST.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/userWalletPropTypes.js
Labels: InternalQA

#10388 Update version to 1.1.88-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10390 Update version to 1.1.88-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10398 Update version to 1.1.88-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10399 Update version to 1.1.88-13 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10418 Make sure we unsubscribe the pressOnEnter handler for the login form when we render the password form
  src/pages/signin/LoginForm.js
Labels: CP Staging

#10420 Update version to 1.1.88-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10421 🍒 Cherry pick PR #10418 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/signin/LoginForm.js
Labels: automerge

#10472 Update version to 1.1.88-15 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10473 🍒 Cherry pick PR #10465 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/PDFView/index.native.js
Labels: automerge

#10519 Adding reportActionID client generation
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
  tests/actions/ReportTest.js
Labels: InternalQA

#10540 Wrap setString instead of using Clipboard object
  src/libs/Clipboard/index.js
  src/libs/Clipboard/index.native.js
Labels: CP Staging

#10542 Update version to 1.1.89-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10543 🍒 Cherry pick PR #10540 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Clipboard/index.js
  src/libs/Clipboard/index.native.js
Labels: automerge

#10546 [CP Stg] Remove LayoutAnimation from KeyboardSpacer
  src/components/KeyboardSpacer/BaseKeyboardSpacer.js
Labels: CP Staging

#10548 Update version to 1.1.89-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10549 🍒 Cherry pick PR #10546 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/KeyboardSpacer/BaseKeyboardSpacer.js
Labels: automerge

#10545 Move report fetch to `ReportScreen` to populate `props.report`
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
Labels: CP Staging

#10560 Update version to 1.1.89-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10561 🍒 Cherry pick PR #10545 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#10567 Use defaultProps instead of hardcoded value
  src/components/ScreenWrapper/index.android.js
  src/pages/home/ReportScreen.js
Labels: CP Staging

#10570 🍒 Cherry pick PR #10567 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ScreenWrapper/index.android.js
  src/pages/home/ReportScreen.js
Labels: automerge

#10573 Update version to 1.1.90-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10574 Update version to 1.1.90-0 on staging
  android/app/build.gradle
  docs/404.html
  docs/README.md
  docs/_includes/CONST.html
  docs/_includes/floating-concierge-button.html
  docs/_layouts/default.html
  docs/_sass/_breakpoints.scss
  docs/_sass/_colors.scss
  docs/_sass/_main.scss
  docs/_sass/_mixins.scss
  docs/hubs/request-money.html
  docs/index.html
  docs/main.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ROUTES.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Navigation/linkingConfig.js
  src/libs/NumberUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/User.js
  src/libs/actions/Wallet.js
  src/libs/deprecatedAPI.js
  src/pages/ConciergePage.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/withFullPolicy.js
  src/styles/fontFamily/emoji/index.js
  src/styles/fontFamily/emoji/index.native.js
  src/styles/fontFamily/index.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/unit/NumberUtilsTest.js
Labels: automerge

#10576 Update version to 1.1.91-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10577 Update version to 1.1.91-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10588 Revert "Refactor ValidateLogin"
  src/Expensify.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/actions/User.js
Labels: CP Staging

#10589 Update version to 1.1.91-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10590 🍒 Cherry pick PR #10588 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/Expensify.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/actions/User.js
Labels: automerge

#10593 Update version to 1.1.91-1 on production
  android/app/build.gradle
  docs/404.html
  docs/README.md
  docs/_includes/CONST.html
  docs/_includes/floating-concierge-button.html
  docs/_layouts/default.html
  docs/_sass/_breakpoints.scss
  docs/_sass/_colors.scss
  docs/_sass/_main.scss
  docs/_sass/_mixins.scss
  docs/hubs/request-money.html
  docs/index.html
  docs/main.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/linkingConfig.js
  src/libs/NumberUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/actions/Wallet.js
  src/libs/deprecatedAPI.js
  src/pages/ConciergePage.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/withFullPolicy.js
  src/styles/fontFamily/emoji/index.js
  src/styles/fontFamily/emoji/index.native.js
  src/styles/fontFamily/index.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/unit/NumberUtilsTest.js
Labels: automerge

#10594 Update version to 1.1.92-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10595 Update version to 1.1.92-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/walletOnfidoDataPropTypes.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#10634 Update version to 1.1.92-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/EnablePayments/walletOnfidoDataPropTypes.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#10635 Update version to 1.1.93-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10636 Update version to 1.1.93-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Session/index.js
  src/pages/ReportParticipantsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: automerge

#10638 Update version to 1.1.93-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10639 Update version to 1.1.93-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AvatarWithIndicator.js
  src/libs/NetworkConnection.js
  src/libs/actions/Network.js
  src/libs/promiseAllSettled/index.js
  src/libs/promiseAllSettled/index.native.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: automerge

#10640 Update version to 1.1.93-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10644 Update version to 1.1.93-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10645 Update version to 1.1.93-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarWithIndicator.js
  src/components/OfflineWithFeedback.js
  src/libs/NumberUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/withFullPolicy.js
Labels: automerge

#10652 Fix crash from AvatarWithIndicator error checking methods
  src/components/AvatarWithIndicator.js
Labels: CP Staging

#10656 Update version to 1.1.93-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10657 🍒 Cherry pick PR #10652 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithIndicator.js
Labels: automerge

#10660 [No QA] Pull latest code after waiting for turnstyle but before creating new branch
  .github/workflows/createNewVersion.yml
Labels: CP Staging

#10672 Update version to 1.1.93-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10673 🍒 Cherry pick PR #10660 to staging 🍒
  .github/workflows/createNewVersion.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10674 Update version to 1.1.93-5 on production
  .github/workflows/createNewVersion.yml
  android/app/build.gradle
  contributingGuides/OFFLINE_UX.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AvatarWithIndicator.js
  src/components/OfflineWithFeedback.js
  src/languages/en.js
  src/languages/es.js
  src/libs/NetworkConnection.js
  src/libs/NumberUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Network.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/libs/promiseAllSettled/index.js
  src/libs/promiseAllSettled/index.native.js
  src/pages/ReportParticipantsPage.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/withFullPolicy.js
Labels: automerge

#10675 Update version to 1.1.94-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10680 Update version to 1.1.94-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10681 Update version to 1.1.94-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10682 Update version to 1.1.94-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/es.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/bills/WorkspaceBillsNoVBAView.js
  src/pages/workspace/card/WorkspaceCardNoVBAView.js
  src/pages/workspace/invoices/WorkspaceInvoicesNoVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelNoVBAView.js
Labels: automerge

#10683 Update version to 1.1.94-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10685 Update version to 1.1.94-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithImagePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/pages/DetailsPage.js
  src/pages/SetPasswordPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/withFullPolicy.js
  tests/utils/TestHelper.js
Labels: automerge

#10686 Update version to 1.1.94-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10707 Update version to 1.1.94-4 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/AmountTextInput.js
  src/components/AvatarWithImagePicker.js
  src/components/AvatarWithIndicator.js
  src/components/BigNumberPad.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInputWithCurrencySymbol.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/libs/actions/Report.js
  src/pages/DetailsPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/bills/WorkspaceBillsNoVBAView.js
  src/pages/workspace/card/WorkspaceCardNoVBAView.js
  src/pages/workspace/invoices/WorkspaceInvoicesNoVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelNoVBAView.js
  src/pages/workspace/withFullPolicy.js
  tests/unit/OptionsListUtilsTest.js
  tests/utils/TestHelper.js
Labels: automerge

#10708 Update version to 1.1.95-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10710 Update version to 1.1.95-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/Button.js
  src/components/Checkbox.js
  src/components/CheckboxWithLabel.js
  src/components/Icon/index.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/TextInput/BaseTextInput.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/getClickedElementLocation/index.js
  src/libs/getClickedTargetLocation/index.js
  src/libs/getClickedTargetLocation/index.native.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/signin/PasswordForm.js
  src/pages/workspace/WorkspaceBankAccountPage.js
  src/pages/workspace/bills/WorkspaceBillsNoVBAView.js
  src/pages/workspace/card/WorkspaceCardNoVBAView.js
  src/pages/workspace/invoices/WorkspaceInvoicesNoVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelNoVBAView.js
  src/styles/styles.js
  src/styles/variables.js
  tests/unit/LHNOrderTest.js
Labels: automerge

#10711 Update version to 1.1.95-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10713 Update version to 1.1.95-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10715 Update version to 1.1.95-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10716 Update version to 1.1.95-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/NumberUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
Labels: automerge

#10719 Update version to 1.1.95-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10720 Update version to 1.1.95-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#10721 Update version to 1.1.95-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#10722 Update version to 1.1.95-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/LHNOrderTest.js
Labels: automerge
