Repository Expensify/App, pull requests merged in 2022-10, with the labels that each got.

#11499 Update version to 1.2.11-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11500 Update version to 1.2.11-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReimbursementAccountLoadingIndicator.js
Labels: automerge

#11539 Add early return to ActiveClientManager
  src/libs/ActiveClientManager/index.js
Labels: CP Staging

#11540 Update version to 1.2.11-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11541 🍒 Cherry pick PR #11539 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ActiveClientManager/index.js
Labels: automerge

#11556 [CP Staging] save routingNumber and accountNumber in connectBankAccountManually
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/FormActions.js
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: CP Staging

#11593 Update version to 1.2.11-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11594 🍒 Cherry pick PR #11556 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/FormActions.js
  src/pages/ReimbursementAccount/CompanyStep.js
Labels: automerge

#11552 Only debounce saving draft when user is typing
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#11616 Fix masked account number and default values
  src/CONST.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
Labels: CP Staging

#11617 Update version to 1.2.11-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11618 🍒 Cherry pick PR #11616 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
Labels: automerge

#11621 Update version to 1.2.12-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11641 Update version to 1.2.12-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11642 🍒 Cherry pick PR #11631 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  tests/unit/LHNFilterTest.js
Labels: automerge

#11634 Only show reports without comments if they are non-archived policy rooms
  src/libs/ReportUtils.js
  tests/unit/LHNFilterTest.js
  tests/unit/OptionsListUtilsTest.js
Labels: CP Staging

#11648 Update version to 1.2.12-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11649 🍒 Cherry pick PR #11634 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  tests/unit/LHNFilterTest.js
  tests/unit/OptionsListUtilsTest.js
Labels: automerge

#11702 [No QA] Revert "[Refactor] Use new API Command: VerifyIdentityForBankAccount"
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/RequestorOnfidoStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: CP Staging

#11705 🍒 Cherry pick PR #11702 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/RequestorOnfidoStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
Labels: automerge

#11725 Make sure that archived reports are shown properly in the LHN and the search options
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  tests/unit/LHNFilterTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/utils/LHNTestUtils.js
Labels: CP Staging

#11734 Update version to 1.2.12-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11736 🍒 Cherry pick PR #11725 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  tests/unit/LHNFilterTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/utils/LHNTestUtils.js
Labels: automerge

#11739 Update version to 1.2.13-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11740 Update version to 1.2.13-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/javascript/contributorChecklist/contributorChecklist.js
  .github/actions/javascript/contributorChecklist/index.js
  .github/workflows/test.yml
  .gitignore
  android/app/build.gradle
  contributingGuides/FORMS.md
  contributingGuides/OFFLINE_UX.md
  contributingGuides/OfflineUX_Patterns_Flowchart.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/BigNumberPad.js
  src/components/BlockingViews/FullPageNotFoundView.js
  src/components/Button.js
  src/components/CopyTextToClipboard.js
  src/components/Form.js
  src/components/KeyboardShortcutsModal.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/PDFView/index.native.js
  src/components/Picker/BasePicker/index.js
  src/components/Picker/index.js
  src/components/ReportActionItem/RenameAction.js
  src/components/ReportActionsSkeletonView/index.js
  src/components/RoomHeaderAvatars.js
  src/components/StatePicker.js
  src/components/withWindowDimensions.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/libs/UnreadIndicatorUpdater/index.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Policy.js
  src/libs/actions/User.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReportSettingsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/stories/Form.stories.js
  src/stories/Picker.stories.js
  src/styles/styles.js
Labels: automerge

#11743 Update version to 1.2.13-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11744 Update version to 1.2.13-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Checkbox.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInput/baseTextInputPropTypes.js
Labels: automerge

#11745 Update version to 1.2.13-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11746 Update version to 1.2.13-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AnimatedStep.js
  src/styles/styles.js
Labels: automerge

#11759 Go back to lower version of onyx
  package-lock.json
  package.json
Labels: CP Staging

#11761 Update version to 1.2.13-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11774 Fix Free Workspace transitions, add `Admin` badge to all admins
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: CP Staging

#11779 Update version to 1.2.13-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11780 🍒 Cherry pick PR #11774 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge

#11750 Refactor PLAID_DATA and fix plaid bankAccounts selector
  src/components/AddPlaidBankAccount.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
Labels: CP Staging

#11788 Update version to 1.2.13-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11789 🍒 Cherry pick PR #11750 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddPlaidBankAccount.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
Labels: automerge

#11791 Update version to 1.2.14-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11792 Update version to 1.2.14-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/javascript/contributorChecklist/contributorChecklist.js
  .github/actions/javascript/contributorChecklist/index.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Composer/index.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/setSelection/index.js
  src/libs/setSelection/index.native.js
Labels: automerge

#11827 Update version to 1.2.14-0 on production
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/javascript/contributorChecklist/contributorChecklist.js
  .github/actions/javascript/contributorChecklist/index.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Composer/index.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/setSelection/index.js
  src/libs/setSelection/index.native.js
Labels: automerge

#11828 Update version to 1.2.15-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11829 Update version to 1.2.15-0 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/actions/Link.js
  src/libs/actions/Policy.js
Labels: automerge

#11831 Fix policy name when creating a workspace for another user
  src/libs/actions/Policy.js
Labels: CP Staging

#11832 Update version to 1.2.15-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11833 🍒 Cherry pick PR #11831 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Policy.js
Labels: automerge

#11834 Update version to 1.2.15-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11835 Update version to 1.2.15-2 on staging
  __mocks__/react-freeze.js
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ReportHeaderSkeletonView.js
  src/libs/Navigation/DeprecatedCustomActions.js
  src/libs/Navigation/NavigationRoot.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
  tests/ui/UnreadIndicatorsTest.js
  tests/utils/TestHelper.js
Labels: automerge

#11853 Re-render ReportFooter when transitioning to new chat
  src/pages/home/ReportScreen.js
Labels: CP Staging

#11861 Update version to 1.2.15-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11862 🍒 Cherry pick PR #11853 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
Labels: automerge

#11869 Update version to 1.2.15-3 on production
  .github/workflows/platformDeploy.yml
  __mocks__/react-freeze.js
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/ReportHeaderSkeletonView.js
  src/libs/Navigation/DeprecatedCustomActions.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/actions/Link.js
  src/libs/actions/Policy.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
  tests/ui/UnreadIndicatorsTest.js
  tests/utils/TestHelper.js
Labels: automerge

#11870 Update version to 1.2.16-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11876 Update version to 1.2.16-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11878 Update version to 1.2.16-1 on staging
  android/app/build.gradle
  docs/_includes/floating-concierge-button.html
  docs/_layouts/default.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ExceededCommentLength.js
  src/components/IOUConfirmationList.js
  src/libs/Authentication.js
  src/libs/DateUtils.js
  src/libs/Middleware/Reauthentication.js
  src/libs/Middleware/index.js
  src/libs/actions/NameValuePair.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/SignInRedirect.js
  src/libs/deprecatedAPI.js
  src/styles/utilities/spacing.js
Labels: automerge

#11881 Update version to 1.2.16-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11882 Update version to 1.2.16-2 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11896 Update version to 1.2.16-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11897 Update version to 1.2.16-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#11527 Update handling so that Concierge link redirects to chat
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: InternalQA

#11898 Update version to 1.2.16-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11899 Update version to 1.2.16-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: automerge

#11909 Revert "Update handling so that Concierge link redirects to chat"
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: CP Staging

#11912 🍒 Cherry pick PR #11909 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: automerge

#11918 Update version to 1.2.17-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11923 Update version to 1.2.17-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11924 Update version to 1.2.17-1 on staging
  .github/workflows/e2ePerformanceRegressionTests.yml
  .gitignore
  README.md
  android/app/build.gradle
  android/app/src/e2eRelease/AndroidManifest.xml
  e2e/.env.e2e
  e2e/ADDING_TESTS.md
  e2e/README.md
  e2e/compare/compare.js
  e2e/compare/math.js
  e2e/compare/output/console.js
  e2e/compare/output/format.js
  e2e/compare/output/markdown.js
  e2e/compare/output/markdownTable.js
  e2e/config.js
  e2e/measure/math.js
  e2e/measure/writeTestStats.js
  e2e/server/index.js
  e2e/server/routes.js
  e2e/testRunner.js
  e2e/utils/androidReversePort.js
  e2e/utils/execAsync.js
  e2e/utils/installApp.js
  e2e/utils/killApp.js
  e2e/utils/launchApp.js
  e2e/utils/logger.js
  e2e/utils/startRecordingVideo.js
  e2e/utils/withFailTimeout.js
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/libs/E2E/actions/e2eLogin.js
  src/libs/E2E/client.js
  src/libs/E2E/isE2ETestSession.js
  src/libs/E2E/isE2ETestSession.native.js
  src/libs/E2E/reactNativeLaunchingTest.js
  src/libs/E2E/tests/appStartTimeTest.e2e.js
  src/libs/Performance.js
  src/pages/signin/SignInPage.js
Labels: automerge

#11931 Update version to 1.2.17-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11932 Update version to 1.2.17-2 on staging
  android/app/build.gradle
  config/checkMetroBundlerPort.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11937 Update version to 1.2.17-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11938 Update version to 1.2.17-3 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11939 [No QA] Remove pip install for wheel
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#11940 Update version to 1.2.17-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11941 🍒 Cherry pick PR #11939 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11976 Update version to 1.2.17-4 on production
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/platformDeploy.yml
  .gitignore
  README.md
  android/app/build.gradle
  android/app/src/e2eRelease/AndroidManifest.xml
  config/checkMetroBundlerPort.js
  e2e/.env.e2e
  e2e/ADDING_TESTS.md
  e2e/README.md
  e2e/compare/compare.js
  e2e/compare/math.js
  e2e/compare/output/console.js
  e2e/compare/output/format.js
  e2e/compare/output/markdown.js
  e2e/compare/output/markdownTable.js
  e2e/config.js
  e2e/measure/math.js
  e2e/measure/writeTestStats.js
  e2e/server/index.js
  e2e/server/routes.js
  e2e/testRunner.js
  e2e/utils/androidReversePort.js
  e2e/utils/execAsync.js
  e2e/utils/installApp.js
  e2e/utils/killApp.js
  e2e/utils/launchApp.js
  e2e/utils/logger.js
  e2e/utils/startRecordingVideo.js
  e2e/utils/withFailTimeout.js
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/libs/E2E/actions/e2eLogin.js
  src/libs/E2E/client.js
  src/libs/E2E/isE2ETestSession.js
  src/libs/E2E/isE2ETestSession.native.js
  src/libs/E2E/reactNativeLaunchingTest.js
  src/libs/E2E/tests/appStartTimeTest.e2e.js
  src/libs/Performance.js
  src/libs/actions/BankAccounts.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/signin/SignInPage.js
Labels: automerge

#11977 Update version to 1.2.18-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11978 Update version to 1.2.18-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/javascript/markPullRequestsAsDeployed/action.yml
  android/app/build.gradle
  desktop/ELECTRON_EVENTS.js
  desktop/contextBridge.js
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Composer/index.js
  src/components/Form.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/MenuItem.js
  src/libs/NetworkConnection.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/SidebarUtils.js
  src/libs/Visibility/index.desktop.js
  src/libs/Visibility/index.js
  src/libs/Visibility/index.native.js
  src/libs/actions/CloseAccount.js
  src/libs/actions/FormActions.js
  src/libs/actions/Session/index.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/signin/LoginForm.js
  src/styles/pointerEventsAuto/index.js
  src/styles/pointerEventsAuto/index.native.js
  src/styles/styles.js
Labels: automerge

#11980 Update version to 1.2.18-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11981 Update version to 1.2.18-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OfflineWithFeedback.js
  src/pages/home/report/ReportFooter.js
  src/styles/styles.js
Labels: automerge

#11942 [No QA] Upgrade Fastlane
  Gemfile.lock
Labels: CP Staging

#11984 Update version to 1.2.18-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11985 🍒 Cherry pick PR #11942 to staging 🍒
  Gemfile.lock
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12013 Show Default Rooms when there is a team.expensify.com account on the report
  src/libs/ReportUtils.js
Labels: CP Staging

#12016 Update version to 1.2.18-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12017 🍒 Cherry pick PR #12013 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#12038 [CP Staging] Fix hasExpensifyGuidesEmails call
  src/libs/ReportUtils.js
Labels: CP Staging

#12039 Update version to 1.2.18-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12040 🍒 Cherry pick PR #12038 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#11944 Upgrade react-navigation/drawer to use our fork
  package-lock.json
  package.json
Labels: CP Staging

#12063 Update version to 1.2.18-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12064 🍒 Cherry pick PR #11944 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12068 [No QA] Update to macos-12 and XCode 14 in GitHub Actions
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
Labels: CP Staging

#12069 Update version to 1.2.18-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12070 🍒 Cherry pick PR #12068 to staging 🍒
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12072 [No QA] Upgrade actions/checkout, actions/setup-node, ruby/setup-ruby to latest
  .github/actions/composite/setupNode/action.yml
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/deployBlocker.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
Labels: CP Staging

#12073 Update version to 1.2.18-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12074 🍒 Cherry pick PR #12072 to staging 🍒
  .github/actions/composite/setupNode/action.yml
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/deployBlocker.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12085 Update version to 1.2.18-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12086 🍒 Cherry pick PR #12084 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#12092 [No QA] Disable signing for generated projects
  ios/Podfile
  ios/Podfile.lock
Labels: CP Staging

#12093 Update version to 1.2.18-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12094 🍒 Cherry pick PR #12092 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#12099 Onyx package revert
  package-lock.json
  package.json
Labels: CP Staging

#12100 Update version to 1.2.18-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12105 Update version to 1.2.18-10 on production
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/composite/setupNode/action.yml
  .github/actions/composite/updateProtectedBranch/action.yml
  .github/actions/javascript/markPullRequestsAsDeployed/action.yml
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/deployBlocker.yml
  .github/workflows/e2ePerformanceRegressionTests.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  Gemfile.lock
  android/app/build.gradle
  desktop/ELECTRON_EVENTS.js
  desktop/contextBridge.js
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/Composer/index.js
  src/components/Form.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/MenuItem.js
  src/components/OfflineWithFeedback.js
  src/libs/NetworkConnection.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ReportUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/SidebarUtils.js
  src/libs/Visibility/index.desktop.js
  src/libs/Visibility/index.js
  src/libs/Visibility/index.native.js
  src/libs/actions/CloseAccount.js
  src/libs/actions/FormActions.js
  src/libs/actions/Session/index.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportFooter.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/signin/LoginForm.js
  src/styles/pointerEventsAuto/index.js
  src/styles/pointerEventsAuto/index.native.js
  src/styles/styles.js
Labels: automerge

#12106 Update version to 1.2.19-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12110 Update version to 1.2.19-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12111 Update version to 1.2.19-1 on staging
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#11996 Update expensify-common
  package-lock.json
  package.json
Labels: CP Staging

#12133 Update version to 1.2.19-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12134 🍒 Cherry pick PR #11996 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12163 Update version to 1.2.20-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12176 Revert "Upgrade react-native-svg to 13.4.0"
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: CP Staging

#12179 Update version to 1.2.20-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12180 🍒 Cherry pick PR #12176 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: automerge

#12192 Use Onyx set if creating new report
  src/libs/actions/IOU.js
Labels: CP Staging

#12214 Update version to 1.2.20-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12215 🍒 Cherry pick PR #12192 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
Labels: automerge

#12216 Add loading spinner to IOUConfirmationList
  src/components/IOUConfirmationList.js
Labels: CP Staging

#12217 Update version to 1.2.20-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12218 🍒 Cherry pick PR #12216 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/IOUConfirmationList.js
Labels: automerge

#12221 Update version to 1.2.21-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12222 Update version to 1.2.21-0 on staging
  .github/ISSUE_TEMPLATE/Standard.md
  android/app/build.gradle
  docs/_sass/_breakpoints.scss
  docs/_sass/_main.scss
  docs/articles/send-money/The-Free-Plan.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/BlockingViews/BlockingView.js
  src/components/CheckboxWithLabel.js
  src/components/Composer/index.android.js
  src/components/Composer/index.ios.js
  src/components/Composer/index.js
  src/components/MenuItem.js
  src/components/MultipleAvatars.js
  src/components/menuItemPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/utilities/positioning.js
  src/styles/variables.js
  tests/README.md
  tests/unit/EmojiCodeTest.js
  tests/unit/EmojiTest.js
Labels: automerge

#12224 Update version to 1.2.21-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12225 Update version to 1.2.21-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DatePicker/index.js
Labels: automerge

#12227 Update version to 1.2.21-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12228 Update version to 1.2.21-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12229 Update version to 1.2.21-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12230 Update version to 1.2.21-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/LoginUtils.js
  src/libs/OptionsListUtils.js
  src/libs/actions/User.js
  src/pages/RequestCallPage.js
  src/pages/settings/Profile/ProfilePage.js
Labels: automerge

#12231 Update version to 1.2.21-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12232 Update version to 1.2.21-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/libs/ReportScrollManager/index.js
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#12302 Update version to 1.2.21-4 on production
  .github/ISSUE_TEMPLATE/Standard.md
  android/app/build.gradle
  docs/_sass/_breakpoints.scss
  docs/_sass/_main.scss
  docs/articles/send-money/The-Free-Plan.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/BlockingViews/BlockingView.js
  src/components/CheckboxWithLabel.js
  src/components/Composer/index.android.js
  src/components/Composer/index.ios.js
  src/components/Composer/index.js
  src/components/DatePicker/index.js
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/components/MenuItem.js
  src/components/MultipleAvatars.js
  src/components/menuItemPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/LoginUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/ReportScrollManager/index.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/utilities/positioning.js
  src/styles/variables.js
  tests/README.md
  tests/unit/EmojiCodeTest.js
  tests/unit/EmojiTest.js
Labels: automerge

#12303 Update version to 1.2.22-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12304 Update version to 1.2.22-0 on staging
  android/app/build.gradle
  config/webpack/webpack.common.js
  config/webpack/webpack.dev.js
  docs/_config.yml
  docs/_includes/request-money-lhn.html
  docs/_includes/send-money-lhn.html
  docs/articles/request-money/SmartScan.md
  docs/hubs/request-money.html
  docs/hubs/send-money.html
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcworkspace/contents.xcworkspacedata
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/FAB/fabPropTypes.js
  src/components/FAB/index.ios.js
  src/components/FAB/index.js
  src/components/FloatingActionButton.js
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/KeyboardAvoidingView/index.js
  src/components/PDFView/index.native.js
  src/components/Popover/popoverPropTypes.js
  src/components/PopoverMenu/BasePopoverMenu.js
  src/components/PopoverMenu/popoverMenuPropTypes.js
  src/components/ScreenWrapper/BaseScreenWrapper.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/App.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/withReportOrNavigateHome.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/PopoverModal.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/signin/SignInPageLayout/LoginKeyboardAvoidingView/index.js
  src/pages/signin/SignInPageLayout/LoginKeyboardAvoidingView/index.native.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/SignInPageLayout/SignInPageGraphics.js
  src/pages/signin/SignInPageLayout/index.js
  src/setup/index.js
  src/stories/OptionRow.stories.js
Labels: automerge

#12306 Update version to 1.2.22-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12307 Update version to 1.2.22-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/PaymentMethods.js
Labels: automerge
