Repository Expensify/App, pull requests merged in 2022-03, with the labels that each got.

#7944 Update version to 1.1.40-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7945 🍒 Cherry pick PR #7939 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#7952 Update version to 1.1.41-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7955 Fix storybook build
  .storybook/webpack.config.js
Labels: CP Staging

#7959 Update version to 1.1.41-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7960 🍒 Cherry pick PR #7955 to staging 🍒
  .storybook/webpack.config.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7873 Add ability to download statement PDF
  src/libs/API.js
  src/libs/actions/User.js
  src/pages/wallet/WalletStatementPage.js
Labels: InternalQA

#7989 Add the `zip` target to fix Desktop auto updates
  config/electronBuilder/electronBuilder.config.js
Labels: CP Staging

#7993 Update version to 1.1.41-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7994 🍒 Cherry pick PR #7989 to staging 🍒
  android/app/build.gradle
  config/electronBuilder/electronBuilder.config.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7852 Set up Avatars for Workspace Chats
  src/CONST.js
  src/components/Avatar.js
  src/components/Icon/Expensicons.js
  src/components/MultipleAvatars.js
  src/components/OptionsList/optionsListPropTypes.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/RoomAvatar.js
  src/components/RoomHeaderAvatars.js
  src/components/SubscriptAvatar.js
  src/components/optionPropTypes.js
  src/libs/OptionsListUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/libs/reportUtils.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/home/sidebar/optionPropTypes.js
  src/pages/settings/InitialSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
Labels: InternalQA

#7996 [CP Stg] Add title and artifactName back in ElectronBuilder config
  config/electronBuilder.config.js
  desktop/main.js
  desktop/notarize.js
  scripts/build-desktop.sh
Labels: CP Staging

#7997 Update version to 1.1.41-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7998 🍒 Cherry pick PR #7996 to staging 🍒
  android/app/build.gradle
  config/electronBuilder.config.js
  desktop/main.js
  desktop/notarize.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
Labels: automerge

#8000 [No QA][CP Stg] Export ELECTRON_ENV to electronBuilder.config.js
  scripts/build-desktop.sh
Labels: CP Staging

#8002 Update version to 1.1.41-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8003 🍒 Cherry pick PR #8000 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/build-desktop.sh
Labels: automerge

#8011 Fix reportDetails icons for chatrooms
  src/pages/ReportDetailsPage.js
  src/styles/styles.js
Labels: CP Staging

#8012 Update version to 1.1.41-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8013 🍒 Cherry pick PR #8011 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportDetailsPage.js
  src/styles/styles.js
Labels: automerge, Engineering, Hourly

#8054 Revert PR 8013, which introduced a bug
  src/pages/ReportDetailsPage.js
Labels: CP Staging

#8055 Update version to 1.1.41-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8056 🍒 Cherry pick PR #8054 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportDetailsPage.js
Labels: automerge

#8072 Update version to 1.1.42-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8079 Update version to 1.1.42-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8080 Update version to 1.1.42-1 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8078 Update statement URLS
  src/libs/actions/User.js
  src/pages/wallet/WalletStatementPage.js
Labels: CP Staging

#8083 Update version to 1.1.42-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8084 Update version to 1.1.42-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/User.js
  src/pages/wallet/WalletStatementPage.js
Labels: automerge

#8085 Update version to 1.1.42-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8086 Update version to 1.1.42-3 on staging
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8058 Reapply RoomHeaderAvatars Logic to fix regression correctly this time
  src/pages/ReportDetailsPage.js
Labels: CP Staging

#8095 Update version to 1.1.42-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8096 🍒 Cherry pick PR #8058 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportDetailsPage.js
Labels: automerge

#8140 🍒 Cherry pick PR #8106 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/NewChatPage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#8162 🍒 Cherry pick PR #8143 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#8168 Update version to 1.1.43-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8171 Update version to 1.1.43-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8172 Update version to 1.1.43-1 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8186 [CP Stg] Fix autoComplete crash
  src/components/AddressSearch.js
Labels: CP Staging

#8188 Update version to 1.1.43-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8189 🍒 Cherry pick PR #8186 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch.js
Labels: automerge

#8208 Update version to 1.1.44-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8209 Update version to 1.1.44-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  assets/images/avatars/admin-room.svg
  assets/images/avatars/announce-room.svg
  assets/images/avatars/deleted-room.svg
  assets/images/avatars/room.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/Icon/Expensicons.js
  src/components/InlineErrorText.js
  src/components/Picker/index.js
  src/components/RadioButtonWithLabel.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/libs/API.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Session/index.js
  src/libs/reportUtils.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReportSettingsPage.js
  src/styles/styles.js
Labels: automerge

#8063 Use GH CLI instead of community actions
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/updateProtectedBranch.yml
Labels: CP Staging

#8214 🍒 Cherry pick PR #8063 to staging 🍒
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8204 Exit to the proper page when transitioning
  src/pages/LogInWithShortLivedTokenPage.js
Labels: CP Staging

#8216 Update version to 1.1.44-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8217 🍒 Cherry pick PR #8204 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/LogInWithShortLivedTokenPage.js
Labels: automerge

#8218 Update version to 1.1.44-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8219 🍒 Cherry pick PR #8211 to staging 🍒
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8257 Sign in, out, or navigate on transition mount
  src/libs/actions/WelcomeActions.js
  src/pages/LogInWithShortLivedTokenPage.js
Labels: CP Staging

#8277 Update version to 1.1.44-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8278 🍒 Cherry pick PR #8257 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/WelcomeActions.js
  src/pages/LogInWithShortLivedTokenPage.js
Labels: automerge

#8279 Update version to 1.1.44-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8280 🍒 Cherry pick PR #8271 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/GrowlNotification/index.js
  src/libs/ActiveClientManager/index.js
  src/libs/Growl.js
  src/libs/createOnReadyTask.js
Labels: automerge

#8296 Update version to 1.1.44-5 on production
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  assets/images/avatars/admin-room.svg
  assets/images/avatars/announce-room.svg
  assets/images/avatars/deleted-room.svg
  assets/images/avatars/room.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/GrowlNotification/index.js
  src/components/Icon/Expensicons.js
  src/components/InlineErrorText.js
  src/components/Picker/index.js
  src/components/RadioButtonWithLabel.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/libs/API.js
  src/libs/ActiveClientManager/index.js
  src/libs/Growl.js
  src/libs/OptionsListUtils.js
  src/libs/actions/Session/index.js
  src/libs/actions/WelcomeActions.js
  src/libs/createOnReadyTask.js
  src/libs/reportUtils.js
  src/pages/LogInWithShortLivedTokenPage.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReportSettingsPage.js
  src/styles/styles.js
Labels: automerge

#8298 Update version to 1.1.45-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8303 Update version to 1.1.46-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8304 Update version to 1.1.46-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8314 IOU - Fix Infinite loading spinner on split bill with invalid phone number
  src/libs/actions/IOU.js
Labels: CP Staging

#8318 Update version to 1.1.46-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8319 🍒 Cherry pick PR #8314 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/IOU.js
Labels: automerge

#8322 Fix blank screen when signing in with Expensifail account
  src/libs/actions/Session/index.js
Labels: CP Staging

#8326 Update version to 1.1.46-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8327 🍒 Cherry pick PR #8322 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
Labels: automerge

#8343 [No QA] Fix policyExpenseChat beta not being applied correctly
  src/libs/Permissions.js
Labels: CP Staging

#8344 Update version to 1.1.46-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8345 🍒 Cherry pick PR #8343 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Permissions.js
Labels: automerge

#8370 Update version to 1.1.46-3 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Permissions.js
  src/libs/actions/IOU.js
  src/libs/actions/Session/index.js
Labels: automerge

#8371 Update version to 1.1.47-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8373 Update version to 1.1.47-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8374 Update version to 1.1.48-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8372 Update version to 1.1.47-0 on staging
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/index.native.js
  src/components/EmojiPicker/index.js
  src/components/ReportWelcomeText.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInput/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/HttpUtils.js
  src/libs/Network.js
  src/libs/Network/NetworkEvents.js
  src/libs/Network/NetworkStore.js
  src/libs/Network/PersistedRequestsQueue.js
  src/libs/Network/enhanceParameters.js
  src/libs/Network/index.js
  src/libs/Network/processRequest.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/RetryCounter.js
  src/libs/actions/NetworkRequestQueue.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/PersistedRequests.js
  src/libs/actions/Session/index.js
  src/libs/actions/Session/setSessionLoadingAndError.js
  src/libs/actions/User.js
  src/libs/reportUtils.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReportDetailsPage.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/settings/userPropTypes.js
  src/pages/wallet/WalletStatementPage.js
  src/styles/styles.js
  tests/actions/ReimbursementAccountTest.js
  tests/actions/SessionTest.js
  tests/unit/MigrationTest.js
  tests/unit/NetworkTest.js
  tests/unit/enhanceParametersTest.js
Labels: automerge

#8376 Update version to 1.1.49-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8377 Update version to 1.1.49-0 on staging
  .storybook/preview.js
  __mocks__/MockNavigationProvider.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8412 Revert changes related to #7623
  .storybook/preview.js
  __mocks__/MockNavigationProvider.js
  src/components/Button.js
  src/pages/RequestCallPage.js
Labels: CP Staging

#8414 Update version to 1.1.49-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#8415 🍒 Cherry pick PR #8412 to staging 🍒
  .storybook/preview.js
  __mocks__/MockNavigationProvider.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Button.js
  src/pages/RequestCallPage.js
Labels: automerge
