Repository Expensify/App, pull requests merged in 2022-02, with the labels that each got.

#7501 Update version to 1.1.33-3 on production
  .github/actions/checkDeployBlockers/checkDeployBlockers.js
  .github/actions/checkDeployBlockers/index.js
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/isPullRequestMergeable/index.js
  .github/actions/isStagingDeployLocked/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/reopenIssueWithComment/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/GithubUtils.js
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AddPlaidBankAccount.js
  src/components/ImageView/index.native.js
  src/components/ImageWithSizeCalculation.js
  src/components/ReportActionItem/RenameAction.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/OptionsListUtils.js
  src/libs/PaymentUtils.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/libs/virtualKeyboard/index.js
  src/libs/virtualKeyboard/index.native.js
  src/pages/ReportSettingsPage.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/OptionRow.js
  src/pages/settings/Payments/ChooseTransferAccountPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/styles/styles.js
  tests/unit/checkDeployBlockersTest.js
Labels: automerge

#7502 Update version to 1.1.33-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7503 Update version to 1.1.33-4 on staging
  .github/workflows/updateProtectedBranch.yml
  HOW_TO_CREATE_A_PLAN.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  metro.config.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/ImageView/index.native.js
  src/components/PlaidLink/index.native.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Network.js
  src/libs/actions/NetworkRequestQueue.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/GenericErrorPage/ErrorBodyText/index.js
  src/pages/GenericErrorPage/ErrorBodyText/index.native.js
  src/pages/GenericErrorPage/ErrorBodyText/index.website.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  tests/unit/NetworkTest.js
Labels: automerge

#7505 Update version to 1.1.33-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7506 Update version to 1.1.33-5 on staging
  CONTRIBUTING.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7507 Update version to 1.1.34-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7508 Update version to 1.1.34-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7525 Update version to 1.1.34-0 on production
  .github/workflows/updateProtectedBranch.yml
  CONTRIBUTING.md
  HOW_TO_CREATE_A_PLAN.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  metro.config.js
  package-lock.json
  package.json
  src/CONST.js
  src/components/ImageView/index.native.js
  src/components/PlaidLink/index.native.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/Network.js
  src/libs/actions/NetworkRequestQueue.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/GenericErrorPage/ErrorBodyText/index.js
  src/pages/GenericErrorPage/ErrorBodyText/index.native.js
  src/pages/GenericErrorPage/ErrorBodyText/index.website.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/MarkerBadge/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  tests/unit/NetworkTest.js
Labels: automerge

#7526 Update version to 1.1.35-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7534 Allow hitting production web-secure from staging
  .env.staging
Labels: InternalQA

#7551 Fix broken max length in "SNN Last 4 digits" input
  src/components/TextInput/baseTextInputPropTypes.js
Labels: CP Staging

#7554 🍒 Cherry pick PR #7551 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/baseTextInputPropTypes.js
Labels: automerge

#7511 Disable guides calling if user is blocked from concierge
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Inbox.js
  src/pages/RequestCallPage.js
Labels: InternalQA

#7562 Update version to 1.1.36-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7563 Update version to 1.1.36-0 on staging
  .env.staging
  .github/workflows/lockDeploys.yml
  CONTRIBUTING.md
  android/app/build.gradle
  assets/images/product-illustrations/gps-track--orange.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Icon/Illustrations.js
  src/components/ReportWelcomeText.js
  src/components/RoomHeaderAvatars.js
  src/components/RoomNameInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/API.js
  src/libs/actions/Inbox.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/RequestCallPage.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseNoVBAView.js
  src/pages/workspace/withFullPolicy.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#7606 Update version to 1.1.37-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7607 Update version to 1.1.37-0 on staging
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/verifyActions.sh
  CONTRIBUTING.md
  STYLE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/pages/GenericErrorPage/index.js
  src/pages/LogInWithShortLivedTokenPage.js
  src/pages/ReportSettingsPage.js
  src/pages/settings/InitialSettingsPage.js
  src/styles/getTooltipStyles.js
  tests/unit/GitUtilsTest.js
Labels: automerge

#7631 Revert "Separate report name and icon configuration from personal details"
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
Labels: CP Staging

#7634 Update version to 1.1.37-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7635 🍒 Cherry pick PR #7631 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
Labels: automerge

#7649 Optimize loops in formatting personal details
  src/CONST.js
  src/libs/actions/PersonalDetails.js
Labels: CP Staging

#7650 Update version to 1.1.37-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7651 🍒 Cherry pick PR #7649 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/actions/PersonalDetails.js
Labels: automerge

#7652 Update version to 1.1.37-2 on production
  .github/actions/createOrUpdateStagingDeploy/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/scripts/verifyActions.sh
  CONTRIBUTING.md
  STYLE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/TextInput/BaseTextInput.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/pages/GenericErrorPage/index.js
  src/pages/LogInWithShortLivedTokenPage.js
  src/pages/ReportSettingsPage.js
  src/pages/settings/InitialSettingsPage.js
  src/styles/getTooltipStyles.js
  tests/unit/GitUtilsTest.js
Labels: automerge

#7653 Update version to 1.1.38-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7656 Update version to 1.1.38-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7665 [CP Stg] Fix CORS errors in desktop application
  config/electron.config.js
  desktop/ELECTRON_ENVIRONMENT.js
  desktop/main.js
  src/CONST/ENVIRONMENT.js
  src/CONST/index.js
Labels: CP Staging

#7682 Update version to 1.1.38-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7683 🍒 Cherry pick PR #7665 to staging 🍒
  android/app/build.gradle
  config/electron.config.js
  desktop/ELECTRON_ENVIRONMENT.js
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST/ENVIRONMENT.js
  src/CONST/index.js
Labels: automerge

#7685 [CP Stg] Fix electron build
  config/electron.config.js
Labels: CP Staging

#7689 Update version to 1.1.38-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7691 🍒 Cherry pick PR #7685 to staging 🍒
  android/app/build.gradle
  config/electron.config.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7760 Update version to 1.1.39-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7761 Update version to 1.1.39-1 on staging
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/deployBlocker.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/lockDeploys.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
  .github/workflows/updateProtectedBranch.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7752 [InternalQA] Update the isExpensifyEmployee job
  .github/workflows/preDeploy.yml
Labels: InternalQA

#7663 [P2P Statements] Add Wallet Statements Page + Modal
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/settings.gradle
  config/webpack/webpack.common.js
  ios/ExpensifyCash.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/WalletStatementModal/WalletStatementModalPropTypes.js
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/pages/wallet/WalletStatementPage.js
Labels: InternalQA

#7782 fix: crash when value is `undefined`
  src/components/TextInput/BaseTextInput.js
Labels: CP Staging

#7866 Update version to 1.1.39-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7867 🍒 Cherry pick PR #7782 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
Labels: automerge

#7802 Comment on deploy checklist when a pull request is CP'd
  .github/actions/awaitStagingDeploys/action.yml
  .github/actions/awaitStagingDeploys/awaitStagingDeploys.js
  .github/actions/awaitStagingDeploys/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/ActionUtils.js
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/preDeploy.yml
  tests/unit/awaitStagingDeploysTest.js
Labels: CP Staging, InternalQA

#7870 Update version to 1.1.39-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7871 🍒 Cherry pick PR #7802 to staging 🍒
  .github/actions/awaitStagingDeploys/action.yml
  .github/actions/awaitStagingDeploys/awaitStagingDeploys.js
  .github/actions/awaitStagingDeploys/index.js
  .github/actions/getDeployPullRequestList/index.js
  .github/actions/getPullRequestDetails/index.js
  .github/actions/getReleaseBody/index.js
  .github/actions/markPullRequestsAsDeployed/index.js
  .github/actions/triggerWorkflowAndWait/index.js
  .github/libs/ActionUtils.js
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/awaitStagingDeploysTest.js
Labels: automerge

#7881 Update version to 1.1.40-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7767 Don't set default badge when only one defaultable payment method is available
  src/pages/settings/Payments/PaymentMethodList.js
Labels: InternalQA

#7921 [P2P Statements] Add Loading Indicator
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: InternalQA

#7933 Revert "feat: add image loading placeholder"
  src/components/ImageWithSizeCalculation.js
Labels: CP Staging

#7938 Update version to 1.1.40-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#7940 🍒 Cherry pick PR #7933 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ImageWithSizeCalculation.js
Labels: automerge

#7939 Revert "Make push notifications navigate to the correct chat - iOS"
  src/libs/actions/Report.js
Labels: CP Staging
