Repository Expensify/App, pull requests merged in 2023-05, with the labels that each got.

#18279 Update version to 1.3.9-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18284 Update version to 1.3.9-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18286 Update version to 1.3.9-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18287 Update version to 1.3.9-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18288 Update version to 1.3.9-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18290 Update version to 1.3.9-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18292 Update version to 1.3.9-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18294 Update version to 1.3.9-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18296 Update version to 1.3.9-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18302 Update version to 1.3.9-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18309 Update version to 1.3.9-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18312 Update version to 1.3.9-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18316 Update version to 1.3.9-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18317 Update version to 1.3.9-13 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemMessageEdit.js
Labels: automerge

#18319 Update version to 1.3.9-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18320 Update version to 1.3.9-14 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ContextMenuItem.js
  src/components/MenuItem.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.native.js
  src/styles/getContextMenuItemStyles/index.js
  src/styles/getContextMenuItemStyles/index.native.js
  src/styles/styles.js
Labels: automerge

#18336 Rename referral-program.md to Referral-Program.md
  docs/articles/other/Referral-Program.md
Labels: CP Staging

#18346 Update version to 1.3.9-15 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18348 🍒 Cherry pick PR #18336 to staging 🍒
  android/app/build.gradle
  docs/articles/other/Referral-Program.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18360 Revert "Fix for: Web - Triple clicking an edited message select’s the (edited) label along with the actual message"
  src/components/HTMLEngineProvider/HTMLRenderers/EditedRenderer.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/styles/editedLabelStyles/index.js
  src/styles/editedLabelStyles/index.native.js
  src/styles/utilities/display.js
Labels: CP Staging

#18361 [CP Staging] Update the check for default avatars to account for new naming
  src/libs/ReportUtils.js
Labels: CP Staging

#18363 Update version to 1.3.9-16 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18364 🍒 Cherry pick PR #18361 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#18367 Update version to 1.3.9-17 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18369 [CP Staging] Re-add old-style default avatar prefix
  src/libs/ReportUtils.js
Labels: CP Staging

#18378 Update version to 1.3.9-18 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18379 🍒 Cherry pick PR #18369 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#18380 Revert "Fix: Copying the messages and marking a message in between as unread generates 'new' in the text"
  src/components/UnreadActionIndicator.js
  src/libs/SelectionScraper/index.js
Labels: CP Staging

#18381 Update version to 1.3.9-19 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18395 Followup fixes on invite message page implementation
  src/pages/workspace/WorkspaceInviteMessagePage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: CP Staging

#18405 🍒 Cherry pick PR #18395 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceInviteMessagePage.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#18409 Update version to 1.3.10-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18413 Update version to 1.3.10-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestConfirmationList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/pages/ReimbursementAccount/AddressForm.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/styles/styles.js
Labels: automerge

#18430 Revert "fix add reaction icon position changed when user add emoji"
  src/styles/styles.js
Labels: CP Staging

#18425 Only subscribe shortcuts when modal is open
  src/components/KeyboardShortcutsModal.js
Labels: CP Staging

#18435 Update version to 1.3.10-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18436 🍒 Cherry pick PR #18430 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#18437 Update version to 1.3.10-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18438 🍒 Cherry pick PR #18425 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/KeyboardShortcutsModal.js
Labels: automerge

#18496 Update version to 1.3.11-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18499 Update version to 1.3.11-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18500 Update version to 1.3.11-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/SidebarUtils.js
  src/pages/home/sidebar/SidebarLinks.js
  tests/unit/SidebarTest.js
  tests/utils/LHNTestUtils.js
Labels: automerge

#18501 Update version to 1.3.11-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18502 Update version to 1.3.11-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18143 Enable IOUPreview for bill splits
  src/components/MoneyRequestConfirmationList.js
  src/components/ReportActionItem/IOUAction.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/IOUQuote.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.js
  src/pages/home/report/ReportActionItem.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/workspace/WorkspaceInviteMessagePage.js
Labels: Ready To Build

#18599 Fix arrow focus shortcut modal local state (v2.0)
  src/components/ArrowKeyFocusManager.js
  src/components/ButtonWithMenu.js
  src/components/KeyboardShortcutsModal.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/actions/KeyboardShortcuts.js
  src/pages/iou/steps/MoneyRequestAmountPage.js
Labels: CP Staging

#18613 🍒 Cherry pick PR #18599 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ArrowKeyFocusManager.js
  src/components/ButtonWithMenu.js
  src/components/KeyboardShortcutsModal.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/actions/KeyboardShortcuts.js
  src/pages/iou/steps/MoneyRequestAmountPage.js
Labels: automerge

#18611 Additional changes for #17202
  src/components/TextInput/BaseTextInput.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: CP Staging

#18617 Update version to 1.3.11-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18618 🍒 Cherry pick PR #18611 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/TextInput/BaseTextInput.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#18619 [CP Stg] Fix bad merge
  src/libs/actions/Session/index.js
Labels: CP Staging

#18621 Update version to 1.3.11-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18622 🍒 Cherry pick PR #18619 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
Labels: automerge

#18625 Update version to 1.3.12-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18712 Update version to 1.3.12-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18713 🍒 Cherry pick PR #18709 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
Labels: automerge

#18761 Update version to 1.3.12-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
Labels: automerge

#18762 Update version to 1.3.13-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17445 Fix keyboard flicker and input overlap in SignInPage
  src/pages/signin/SignInPageLayout/Footer.js
  src/pages/signin/SignInPageLayout/index.js
Labels: Reviewing

#18778 Reset the min supported iOS version to 13
  ios/Podfile
  ios/Podfile.lock
Labels: CP Staging, Ready To Build

#18797 Update version to 1.3.13-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18486 Implement the RequestPreview component and update the IOUPreview
  src/components/MoneyRequestHeader.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/ReportActionItem/MoneyRequestAction.js
  src/components/ReportActionItem/ReportPreview.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/signin/SignInPageLayout/Footer.js
  src/styles/getModalStyles/getBaseModalStyles.js
  src/styles/styles.js
Labels: CP Staging, Ready To Build

#18832 Update version to 1.3.13-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18833 🍒 Cherry pick PR #18486 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestHeader.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/ReportActionItem/MoneyRequestAction.js
  src/components/ReportActionItem/ReportPreview.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/pages/iou/IOUDetailsModal.js
  src/styles/styles.js
Labels: automerge, Engineering, Hourly

#18842 fix: android app crash fix due to wrong position of LayoutAnimation
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#18845 Update version to 1.3.13-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18522 New Thread Report Empty State, Header, LHN, OpenReport, Buttons for DEV
  src/components/LHNOptionsList/OptionRowLHN.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemParentAction.js
  src/pages/home/report/ReportActionsList.js
  src/styles/styles.js
Labels: Ready To Build

#18788 fix skeleton loading forever on options list when offline
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
Labels: CP Staging

#18900 Update version to 1.3.13-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18901 🍒 Cherry pick PR #18788 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
Labels: automerge, Engineering, Hourly

#18897 fix: call onModalHide when the confirm modal is closed
  src/components/AttachmentModal.js
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#18919 Update version to 1.3.13-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18920 🍒 Cherry pick PR #18897 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#18936 Update version to 1.3.14-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18939 Update version to 1.3.14-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18940 Update version to 1.3.14-1 on staging
  android/app/build.gradle
  assets/images/avatars/room.png
  assets/images/expensify_wordmark_white.svg
  assets/images/qrcode.svg
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/Icon/Expensicons.js
  src/components/QRShare/QRShareWithDownload/index.js
  src/components/QRShare/QRShareWithDownload/index.native.js
  src/components/QRShare/getQrCodeDownloadFileName.js
  src/components/QRShare/index.js
  src/components/QRShare/propTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/NetworkConnection.js
  src/libs/fileDownload/index.android.js
  src/pages/ReportDetailsPage.js
  src/pages/ShareCodePage.js
  src/pages/home/report/ReportDetailsShareCodePage.js
  src/pages/settings/InitialSettingsPage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#18942 Update version to 1.3.14-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18943 Update version to 1.3.14-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: automerge

#18835 [NoQA] Fix e2e pipeline
  .github/workflows/e2ePerformanceTests.yml
Labels: Ready To Build

#18953 Update version to 1.3.14-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18961 Update version to 1.3.14-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18962 🍒 Cherry pick PR #18941 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionRow.js
  src/libs/OptionsListUtils.js
Labels: automerge

#18760 [Manual Requests] Create thread for Manual Request when opening IOUPreview
  src/components/ReportActionItem/MoneyRequestAction.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItemParentAction.js
Labels: CP Staging

#18965 Update version to 1.3.14-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18966 🍒 Cherry pick PR #18760 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/MoneyRequestAction.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItemParentAction.js
Labels: automerge

#18902 Fix send money show "$0.00" in preview card
  src/components/ReportActionItem/IOUPreview.js
  src/libs/ReportUtils.js
Labels: CP Staging

#17348 Allow money request deletion
  src/languages/en.js
  src/languages/es.js
  src/libs/IOUUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReportActionItem.js
Labels: CP Staging

#18998 Update version to 1.3.14-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18945 update report preview message to use workspace name, not admin name
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/ReportPreview.js
  src/pages/home/report/ReportActionItemSingle.js
Labels: CP Staging

#19008 Update version to 1.3.14-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18933 Corrected - IOU Description extends beyond the page if recipient name is long
  src/components/ReportActionItem/ReportPreview.js
Labels: CP Staging

#19013 Update version to 1.3.14-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19014 🍒 Cherry pick PR #18933 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/ReportPreview.js
Labels: automerge

#19019 prevent grouping created action message
  src/libs/ReportActionsUtils.js
Labels: CP Staging

#19025 Update version to 1.3.14-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19026 🍒 Cherry pick PR #19019 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportActionsUtils.js
Labels: automerge

#18775 UI MoneyRequestHeader Polish
  src/components/Avatar.js
  src/components/AvatarWithDisplayName.js
  src/components/MoneyRequestHeader.js
  src/components/MultipleAvatars.js
  src/components/SubscriptAvatar.js
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionItemCreated.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/ui/UnreadIndicatorsTest.js
Labels: CP Staging, Ready To Build

#19052 🍒 Cherry pick PR #18775 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Avatar.js
  src/components/AvatarWithDisplayName.js
  src/components/MoneyRequestHeader.js
  src/components/MultipleAvatars.js
  src/components/SubscriptAvatar.js
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionItemCreated.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#19055 🍒 Cherry pick PR #18521 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#18802 Change LHN header to Expensify
  assets/images/expensify-logo--dev.svg
  assets/images/expensify-logo--staging.svg
  src/components/Badge.js
  src/components/EnvironmentBadge.js
  src/components/Header.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/sidebar/SidebarLinks.js
  src/styles/styles.js
  src/styles/variables.js
Labels: CP Staging, Ready To Build

#19058 Update version to 1.3.14-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19059 🍒 Cherry pick PR #18604 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/MoneyRequestAction.js
  src/libs/actions/IOU.js
  src/pages/iou/IOUDetailsModal.js
  tests/actions/IOUTest.js
Labels: automerge

#19060 Update version to 1.3.14-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19061 🍒 Cherry pick PR #18802 to staging 🍒
  android/app/build.gradle
  assets/images/expensify-logo--dev.svg
  assets/images/expensify-logo--staging.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Badge.js
  src/components/EnvironmentBadge.js
  src/components/Header.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/sidebar/SidebarLinks.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#19085 Update version to 1.3.15-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19112 🍒 Cherry pick PR #18423 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/MoneyRequestAction.js
  src/components/ReportActionItem/ReportPreview.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/iou/IOUTransactions.js
  tests/actions/IOUTest.js
Labels: automerge

#19114 🍒 Cherry pick PR #18631 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DeeplinkWrapper/index.website.js
Labels: automerge

#19115 Update version to 1.3.15-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18695 Show transaction amount & description in report header for "transaction thread"
  src/components/MoneyRequestHeader.js
  src/libs/DateUtils.js
  src/pages/home/ReportScreen.js
Labels: CP Staging

#19127 Fallback on report
  src/pages/home/HeaderView.js
Labels: CP Staging

#19130 Update version to 1.3.15-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19131 🍒 Cherry pick PR #19127 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/HeaderView.js
Labels: automerge

#19106 Fix 0 Replies Bug FE
  src/pages/home/report/ReportActionItem.js
Labels: CP Staging

#19140 Update version to 1.3.15-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19141 🍒 Cherry pick PR #19106 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItem.js
Labels: automerge

#19148 using props reportID
  src/pages/home/ReportScreen.js
Labels: CP Staging

#19151 Update version to 1.3.15-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19152 🍒 Cherry pick PR #19148 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
Labels: automerge

#19033 Prevent additional requests on settled request reports
  src/components/MoneyRequestHeader.js
  src/components/ReportWelcomeText.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  tests/unit/ReportUtilsTest.js
Labels: CP Staging

#19158 Update version to 1.3.15-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19159 🍒 Cherry pick PR #19033 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestHeader.js
  src/components/ReportWelcomeText.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#18735 Allow policy admins to delete any message in rooms
  src/libs/ReportUtils.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
Labels: CP Staging

#18772 Update Details Page for Threads
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/ShareCodePage.js
Labels: CP Staging

#19160 Update version to 1.3.15-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19162 Update version to 1.3.15-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19163 🍒 Cherry pick PR #18772 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/ShareCodePage.js
Labels: automerge

#19164 Update version to 1.3.15-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19165 🍒 Cherry pick PR #18735 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
Labels: automerge

#18692 Add pay button to money request header
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AddPaymentMethodMenu.js
  src/components/AvatarWithImagePicker.js
  src/components/Button/index.js
  src/components/ButtonWithDropdown.js
  src/components/ButtonWithDropdownMenu.js
  src/components/ButtonWithMenu.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/HeaderWithCloseButton.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/KYCWall/kycWallPropTypes.js
  src/components/Modal/BaseModal.js
  src/components/MoneyRequestConfirmationList.js
  src/components/MoneyRequestHeader.js
  src/components/Popover/index.js
  src/components/PopoverMenu/index.js
  src/components/PopoverWithMeasuredContent.js
  src/components/ReportActionItem/ReportPreview.js
  src/components/SettlementButton.js
  src/components/withNavigationFallback.js
  src/components/withNavigationFocus.js
  src/hooks/useArrowKeyFocusManager.js
  src/hooks/useKeyboardShortcut.js
  src/hooks/useWindowDimensions.js
  src/libs/actions/IOU.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReactionList/PopoverReactionList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/stories/ButtonWithDropdownMenu.stories.js
  src/styles/styles.js
  tests/actions/IOUTest.js
Labels: CP Staging

#19168 Update version to 1.3.15-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19169 🍒 Cherry pick PR #18692 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AddPaymentMethodMenu.js
  src/components/AvatarWithImagePicker.js
  src/components/Button/index.js
  src/components/ButtonWithDropdown.js
  src/components/ButtonWithDropdownMenu.js
  src/components/ButtonWithMenu.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/HeaderWithCloseButton.js
  src/components/KYCWall/BaseKYCWall.js
  src/components/KYCWall/kycWallPropTypes.js
  src/components/Modal/BaseModal.js
  src/components/MoneyRequestConfirmationList.js
  src/components/MoneyRequestHeader.js
  src/components/Popover/index.js
  src/components/PopoverMenu/index.js
  src/components/PopoverWithMeasuredContent.js
  src/components/ReportActionItem/ReportPreview.js
  src/components/SettlementButton.js
  src/components/withNavigationFallback.js
  src/components/withNavigationFocus.js
  src/hooks/useArrowKeyFocusManager.js
  src/hooks/useKeyboardShortcut.js
  src/hooks/useWindowDimensions.js
  src/libs/actions/IOU.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReactionList/PopoverReactionList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/stories/ButtonWithDropdownMenu.stories.js
  src/styles/styles.js
  tests/actions/IOUTest.js
Labels: automerge

#19173 Update version to 1.3.16-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19174 Update version to 1.3.16-0 on staging
  android/app/build.gradle
  assets/images/expensify-logo-round-dark.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/HeaderWithCloseButton.js
  src/components/Pressable/PressableWithFeedback.js
  src/components/QRCode/index.js
  src/components/QRShare/index.js
  src/components/Reactions/ReportActionItemReactions.js
  src/components/Section.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/TwoFactorAuthActions.js
  src/libs/localFileDownload/index.android.js
  src/libs/localFileDownload/index.ios.js
  src/libs/localFileDownload/index.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReactionList/PopoverReactionList.js
  src/pages/home/report/ReactionList/ReactionList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Report/NotificationPreferencePage.js
  src/pages/settings/Report/ReportSettingsPage.js
  src/pages/settings/Report/RoomNamePage.js
  src/pages/settings/Security/SecuritySettingsPage.js
  src/pages/settings/Security/TwoFactorAuth/CodesPage.js
  src/pages/settings/Security/TwoFactorAuth/DisablePage.js
  src/pages/settings/Security/TwoFactorAuth/IsEnabledPage.js
  src/pages/settings/Security/TwoFactorAuth/SuccessPage.js
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.js
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/index.android.js
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/index.js
  src/pages/settings/Security/TwoFactorAuth/VerifyPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/tasks/NewTaskPage.js
  src/pages/workspace/WorkspaceInviteMessagePage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  tests/unit/OptionsListUtilsTest.js
  web/index.html
Labels: automerge

#19176 Update version to 1.3.16-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19177 Update version to 1.3.16-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#19179 Update version to 1.3.16-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Notification/LocalNotification/BrowserNotifications.js
  src/libs/Notification/LocalNotification/index.desktop.js
  src/libs/Notification/LocalNotification/index.website.js
  src/libs/actions/Report.js
Labels: automerge

#19021 Revert "Fix/large images android"
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/components/ImageView/index.native.js
Labels: CP Staging

#19192 Update version to 1.3.16-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19193 🍒 Cherry pick PR #19021 to staging 🍒
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/components/ImageView/index.native.js
Labels: automerge

#17477 Animate splash screen
  __mocks__/react-native.js
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashDialog.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashModule.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashQueue.java
  android/app/src/main/res/anim/fade_out.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/new-expensify-dark.svg
  config/webpack/webpack.common.js
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/NewExpensify/RCTBootSplash.m
  package-lock.json
  package.json
  src/Expensify.js
  src/components/SplashScreenHider/index.js
  src/components/SplashScreenHider/index.native.js
  src/libs/BootSplash/index.js
  src/libs/BootSplash/index.native.js
  src/libs/Navigation/NavigationRoot.js
  src/styles/styles.js
  src/styles/themes/default.js
  web/index.html
  web/splash/splash.css
  web/splash/splash.js
Labels: Ready To Build

#19219 Fix LHN undefined reports
  src/libs/SidebarUtils.js
Labels: CP Staging

#19245 Update version to 1.3.16-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19246 🍒 Cherry pick PR #19219 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/SidebarUtils.js
Labels: automerge

#19194 Fix couple of manual request bugs
  src/components/MoneyRequestHeader.js
  src/components/ReportActionItem/ReportPreview.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/pages/home/report/ReportActionItem.js
Labels: CP Staging

#19261 Update version to 1.3.16-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19262 🍒 Cherry pick PR #19194 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestHeader.js
  src/components/ReportActionItem/ReportPreview.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/pages/home/report/ReportActionItem.js
Labels: automerge

#19339 Fix: `Add attachments` and `Delete workspace` buttons are not responsive
  src/components/PopoverMenu/index.js
Labels: CP Staging

#19353 Update version to 1.3.16-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19354 🍒 Cherry pick PR #19339 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/PopoverMenu/index.js
Labels: automerge

#19402 Revert "fix: double click compose box and select placeholder"
  src/pages/home/report/ReportActionCompose.js
  src/styles/styles.js
  web/index.html
Labels: CP Staging
