Repository Expensify/App, pull requests merged in 2023-10, with the labels that each got.

#28123 refactor: migrated IdologyQuestions to the function component
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/styles/utilities/spacing.ts
Labels: InternalQA

#28725 [No QA] Upgrade react-native-onyx to 1.0.98
  package-lock.json
  package.json
Labels: Ready To Build

#23737 Gyroscope-driven animations of empty chats
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  src/components/ReportActionItem/MoneyReportView.js
  src/components/ReportActionItem/MoneyRequestView.js
  src/libs/NumberUtils.ts
  src/pages/home/report/AnimatedEmptyStateBackground.js
  src/pages/home/report/ReportActionItemCreated.js
  src/styles/StyleUtils.ts
Labels: Ready To Build

#28794 Revert "Handle suggestions only on selection change"
  src/pages/home/report/ReportActionCompose/SuggestionMention.js
Labels: Ready To Build

#28955 [CP Staging] Revert "Merge pull request #27836 from Expensify/dangrous-roomwelcomemessages"
  src/components/ValuePicker/ValueSelectorModal.js
  src/components/ValuePicker/index.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: Ready To Build

#28968 🍒 Cherry pick PR #28955 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ValuePicker/ValueSelectorModal.js
  src/components/ValuePicker/index.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: Engineering, Hourly

#28277 @swm/global nav menu v1
  src/App.js
  src/CONST.ts
  src/GLOBAL_NAVIGATION_MAPPING.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/EnvironmentBadge.js
  src/components/FloatingActionButton.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Navigation/getTopMostCentralPaneRouteName.js
  src/libs/Navigation/linkTo.js
  src/pages/home/sidebar/GlobalNavigation/GlobalNavigationMenuItem.js
  src/pages/home/sidebar/GlobalNavigation/index.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarLinksData.js
  src/pages/home/sidebar/SidebarNavigationContext.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/home/sidebar/SubNavigation/SubNavigation.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/themes/light.js
  src/styles/utilities/spacing.ts
  src/styles/variables.ts
  tests/utils/LHNTestUtils.js
Labels: Design, Ready To Build

#26358 Fix Chat - Notification is NOT received in the main device after Control policy was created
  src/libs/Notification/LocalNotification/BrowserNotifications.js
Labels: Ready To Build

#29059 Edit Message Box Style Fixes
  src/pages/home/report/ReportActionItemMessageEdit.js
Labels: Design

#28710 Add `Scan` to `Split Bill` and implement IOU action startSplitBill
  src/components/MoneyRequestConfirmationList.js
  src/components/MoneyRequestHeaderStatusBar.js
  src/components/ReportActionItem/MoneyRequestPreview.js
  src/libs/actions/IOU.js
  src/pages/iou/MoneyRequestSelectorPage.js
  src/pages/iou/SplitBillDetailsPage.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/types/onyx/IOU.ts
Labels: InternalQA

#28312 add “Report virtual card fraud” page and route
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/Card.js
  src/pages/settings/Wallet/ExpensifyCardPage.js
  src/pages/settings/Wallet/ReportVirtualCardFraudPage.js
  src/styles/styles.js
Labels: InternalQA

#28619 Fix Android camera permission prompt
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/pages/iou/ReceiptSelector/index.native.js
Labels: Ready To Build

#28267 Upgrade lottie-react-native to 6.3.1
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/IllustratedHeaderPageLayout.js
  src/components/Lottie/Lottie.tsx
  src/components/Lottie/index.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/pages/signin/SignInHeroImage.js
  src/styles/styles.js
Labels: Ready To Build

#28411 Make Mobile Web and Native App Scanning Consistent
  package-lock.json
  package.json
  src/libs/fileDownload/FileUtils.js
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.js
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.native.js
  src/pages/iou/ReceiptSelector/index.js
  src/styles/styles.js
  src/styles/utilities/objectFit.ts
Labels: Ready To Build

#29075 [NoQA] [Wave 8 - ECard Transactions] Create `eReceiptThumbnail` and `eReceipt` components
  .storybook/fonts.css
  assets/images/MCCGroupIcons/MCC-Airlines.svg
  assets/images/MCCGroupIcons/MCC-Commuter.svg
  assets/images/MCCGroupIcons/MCC-Gas.svg
  assets/images/MCCGroupIcons/MCC-Goods.svg
  assets/images/MCCGroupIcons/MCC-Groceries.svg
  assets/images/MCCGroupIcons/MCC-Hotel.svg
  assets/images/MCCGroupIcons/MCC-Mail.svg
  assets/images/MCCGroupIcons/MCC-Meals.svg
  assets/images/MCCGroupIcons/MCC-Misc.svg
  assets/images/MCCGroupIcons/MCC-RentalCar.svg
  assets/images/MCCGroupIcons/MCC-Services.svg
  assets/images/MCCGroupIcons/MCC-Taxi.svg
  assets/images/MCCGroupIcons/MCC-Utilities.svg
  assets/images/eReceiptBGs/eReceiptBG_blue.png
  assets/images/eReceiptBGs/eReceiptBG_green.png
  assets/images/eReceiptBGs/eReceiptBG_navy.png
  assets/images/eReceiptBGs/eReceiptBG_pink.png
  assets/images/eReceiptBGs/eReceiptBG_tangerine.png
  assets/images/eReceiptBGs/eReceiptBG_yellow.png
  assets/images/eReceiptIcon.svg
  src/CONST.ts
  src/components/EReceipt.js
  src/components/EReceiptThumbnail.js
  src/components/Icon/EReceiptBGs.js
  src/components/Icon/MCCIcons.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/libs/ReportUtils.js
  src/libs/TransactionUtils.ts
  src/stories/EReceipt.stories.js
  src/stories/EReceiptThumbail.stories.js
  src/styles/StyleUtils.ts
  src/styles/styles.js
  src/styles/utilities/spacing.ts
  src/styles/variables.ts
  src/types/onyx/Transaction.ts
Labels: Design

#29064 Allow split actions to be edited and implement IOU action completeSplitBill
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/components/MoneyRequestConfirmationList.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/TransactionUtils.ts
  src/libs/actions/IOU.js
  src/pages/EditRequestAmountPage.js
  src/pages/EditRequestPage.js
  src/pages/EditSplitBillPage.js
  src/pages/iou/SplitBillDetailsPage.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
Labels: Ready To Build

#29383 Changed inconmark color for adhoc build loading screen
  assets/images/new-expensify-adhoc.svg
Labels: Ready To Build

#27820 Update `react-native-vision-camera`
  package-lock.json
  package.json
  patches/react-native-vision-camera+2.15.4.patch
Labels: Ready To Build

#29525 [CP Staging] Fix crash on navigation aware camera
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.js
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.native.js
  src/pages/iou/ReceiptSelector/TabNavigationAwareCamera.js
  src/pages/iou/ReceiptSelector/index.native.js
Labels: Ready To Build

#29524 fixes: invalid file modal and delete option shown for setted IOU
  src/components/AttachmentModal.js
Labels: Ready To Build

#27819 Minimal server search / enable improved focus mode
  src/CONST.ts
  src/ONYXKEYS.ts
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsList/optionsListPropTypes.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/App.js
  src/libs/actions/Report.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
Labels: InternalQA, Ready To Build

#29431 [Wave 8- ECard Transactions] Update `ReportPreview` styling (`ReportActionItemImages`)
  src/components/ReportActionItem/MoneyRequestPreview.js
  src/components/ReportActionItem/ReportActionItemImages.js
  src/stories/ReportActionItemImages.stories.js
  src/styles/styles.js
  src/styles/variables.ts
Labels: Design

#25446 Improve Google Sign In error logging
  src/components/SignInButtons/GoogleSignIn/index.native.js
Labels: Ready To Build

#28644 Fix splash screen logo size jump on Samsung OneUI v4
  __mocks__/react-native.js
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashDialog.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashModule.java
  android/app/src/main/res/drawable-hdpi/bootsplash_logo.png
  android/app/src/main/res/drawable-mdpi/bootsplash_logo.png
  android/app/src/main/res/drawable-xhdpi/bootsplash_logo.png
  android/app/src/main/res/drawable-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/drawable-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/drawable/bootsplash_samsung_oneui_4.xml
  android/app/src/main/res/values/styles.xml
  assets/images/new-expensify-dark.svg
  src/components/SplashScreenHider/index.native.js
  src/libs/BootSplash/index.native.ts
  src/libs/BootSplash/index.ts
  src/libs/BootSplash/types.ts
Labels: Ready To Build

#28907 feat 22876 allow users to update the card address via update address link
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Wallet/ActivatePhysicalCardPage.js
  src/pages/settings/Wallet/ExpensifyCardPage.js
  src/pages/settings/Wallet/ReportVirtualCardFraudPage.js
  src/pages/settings/Wallet/WalletPage/CardDetails.js
Labels: InternalQA

#29708 🍒 Cherry pick PR #29706 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/SCREENS.ts
  src/libs/Navigation/Navigation.js
  src/libs/actions/Report.js
Labels: Engineering, Hourly

#29395 Allow platinum wallets to transact
  src/CONST.ts
  src/components/KYCWall/BaseKYCWall.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/settings/Wallet/TransferBalancePage.js
Labels: InternalQA, Ready To Build

#29655 Add deep link for send money
  .well-known/apple-app-site-association
  android/app/src/main/AndroidManifest.xml
Labels: Ready To Build

#28141 Add report card lost or damaged
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/components/SelectCircle.js
  src/components/SingleOptionSelector.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/Card.js
  src/pages/settings/Wallet/ExpensifyCardPage.js
  src/pages/settings/Wallet/ReportCardLostPage.js
  src/styles/styles.ts
Labels: InternalQA

#27966 UI for room invitations/removals
  src/CONST.ts
  src/ROUTES.ts
  src/components/FormAlertWrapper.js
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js
  src/libs/Navigation/linkingConfig.js
  src/libs/PolicyUtils.js
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/RoomInvitePage.js
  src/pages/RoomMembersPage.js
  src/pages/home/ReportScreen.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: Ready To Build

#29897 Optimize getLastVisibleAction
  src/libs/ReportActionsUtils.ts
Labels: Ready To Build

#30097 Prevent useEffect from happening incorrectly for deleted IOU reports
  src/pages/home/ReportScreen.js
Labels: Ready To Build

#29491 added manifest to web to prompt app install in chrome
  config/webpack/webpack.common.js
  web/index.html
  web/manifest.json
Labels: InternalQA, Ready To Build

#28792 Fix: Android-Scan camera preview in Scan becomes blank
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.native.js
  src/pages/iou/ReceiptSelector/index.native.js
Labels: Ready To Build

#30114 [CP staging] Prevent second attempts to activate wallet when Onfido checks fail
  src/languages/en.ts
  src/languages/es.ts
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/userWalletPropTypes.js
  src/pages/settings/Wallet/WalletPage/WalletPage.js
  src/types/onyx/UserWallet.ts
Labels: InternalQA

#30299 [No QA]Move to M1 MacOS Runners (`macos-13-xlarge`) for building iOS and Desktop apps
  .github/actionlint.yaml
  .github/actions/composite/buildAndroidAPK/action.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#30221 Create receipt-breakdown
  docs/articles/expensify-classic/billing-and-subscriptions/Receipt-Breakdown.md
Labels: Daily

#28887 Create Domain-Settings-Overview.md
  docs/articles/new-expensify/workspace-and-domain-settings/Domain-Settings-Overview.md
Labels: Weekly, Task

#30402 Build MacOS Desktop from Intel machines in order to support x86
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#30397 [CP staging] fix/30373 - regression fix for NavigationAwareCamera
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.js
  src/pages/iou/ReceiptSelector/NavigationAwareCamera.native.js
Labels: Ready To Build

#30461 Add autoScrollToTopThreshold to main chat list
  src/components/InvertedFlatList/BaseInvertedFlatList.js
Labels: Ready To Build

#23702 Show info about workspace members added by secondary logins
  src/components/MessagesRow.js
  src/components/OfflineWithFeedback.js
  src/components/SelectionList/BaseListItem.js
  src/components/SelectionList/BaseSelectionList.js
  src/components/SelectionList/selectionListPropTypes.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/Policy.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/utilities/spacing.ts
Labels: Design

#27994 Add subscribe to parent comment action menu
  assets/images/bell.svg
  assets/images/bellSlash.svg
  src/components/Icon/Expensicons.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
Labels: Ready To Build

#30599 Migrate MacOS desktop to use `notarytool` to notarize
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/postTestBuildComment/postTestBuildComment.js
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  config/electronBuilder.config.js
  contributingGuides/APPLE_GOOGLE_SIGNIN.md
  desktop/notarize.js
  package-lock.json
  package.json
  tests/unit/postTestBuildComment.js
Labels: Ready To Build
