Repository Expensify/App, pull requests merged in 2023-02, with the labels that each got.

#14730 Only show `passwordless` flow if user is on `passwordless` or `all` betas
  src/libs/Permissions.js
Labels: CP Staging, InternalQA

#14653 Class Android notifications as a Message to improve delivery speed
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
Labels: InternalQA

#13501 [Form Refactor] ACHContractStep
  contributingGuides/FORMS.md
  src/components/Form.js
  src/libs/ReimbursementAccountUtils.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js
Labels: InternalQA

#14740 Update version to 1.2.63-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
  src/components/AutoUpdateTime.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/OptionRow.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/actions/PersistedRequests.js
  src/libs/actions/Report.js
  src/libs/actions/Welcome.js
  src/libs/fileDownload/getAttachmentDetails.js
  src/libs/tryResolveUrlFromApiRoot.js
  src/libs/willBlurTextInputOnTapOutside/index.js
  src/libs/willBlurTextInputOnTapOutside/index.native.js
  src/pages/DetailsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#14741 Update version to 1.2.64-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14749 Update version to 1.2.64-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14750 Update version to 1.2.64-1 on staging
  android/app/build.gradle
  assets/images/simple-illustrations/simple-illustration__shield.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Icon/Illustrations.js
  src/languages/en.js
  src/languages/es.js
  src/pages/LogOutPreviousUserPage.js
  src/pages/ReimbursementAccount/Enable2FAPrompt.js
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: automerge

#14754 Update version to 1.2.64-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14755 Update version to 1.2.64-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Modal/BaseModal.js
Labels: automerge

#14759 Update version to 1.2.64-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14585 Show Domain Rooms to Domains that have at least one Approved! Accountant
  src/libs/ReportUtils.js
  src/pages/DetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
Labels: InternalQA

#14775 Update version to 1.2.64-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14776 Update version to 1.2.64-4 on staging
  .github/actions/composite/announceFailedWorkflowInSlack/action.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/pages/DetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
Labels: automerge

#14791 Fix OptionRow shouldComponentUpdate
  src/components/OptionRow.js
Labels: CP Staging

#14792 Update version to 1.2.64-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14793 🍒 Cherry pick PR #14791 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionRow.js
Labels: automerge

#14823 correct file uri set order
  src/components/AttachmentPicker/index.js
Labels: CP Staging

#14824 Update version to 1.2.64-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14825 🍒 Cherry pick PR #14823 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.js
Labels: automerge

#14826 Revert 'fix: Timezone changes to some 1st option in the list while pressing the enter key'
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: CP Staging

#14828 Update version to 1.2.64-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14829 🍒 Cherry pick PR #14826 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#14831 Update version to 1.2.65-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14832 Update version to 1.2.65-0 on staging
  .github/actions/composite/announceFailedWorkflowInSlack/action.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/OptionRow.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/CompanyStep.js
  tests/utils/TestHelper.js
Labels: automerge

#14856 Check whether option row changed focus before re-rendering
  src/components/OptionRow.js
Labels: CP Staging

#14850 Make sure amount is string before trimming
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: CP Staging

#14860 Update version to 1.2.65-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14861 🍒 Cherry pick PR #14856 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionRow.js
Labels: automerge

#14863 Update version to 1.2.65-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14864 🍒 Cherry pick PR #14850 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/ValidationStep.js
Labels: automerge

#14868 Update version to 1.2.65-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14880 Update version to 1.2.65-2 on production
  .github/actions/composite/announceFailedWorkflowInSlack/action.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/OptionRow.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Report.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  tests/utils/TestHelper.js
Labels: automerge

#14881 Update version to 1.2.66-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14882 Update version to 1.2.66-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/LocalePicker.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsList/optionsListPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/User.js
  src/pages/GetAssistancePage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Preferences/LanguagePage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Preferences/PriorityModePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm.js
  src/styles/utilities/spacing.js
Labels: automerge

#12983 Preload web fonts
  config/webpack/webpack.common.js
  package-lock.json
  package.json
  web/splash/splash.js
Labels: InternalQA

#14908 Update version to 1.2.66-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/LocalePicker.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsList/optionsListPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/User.js
  src/pages/GetAssistancePage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Preferences/LanguagePage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Preferences/PriorityModePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm.js
  src/styles/utilities/spacing.js
Labels: automerge

#14909 Update version to 1.2.67-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14910 Update version to 1.2.67-0 on staging
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/CountryPicker.js
  src/components/Form.js
  src/components/PDFView/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Welcome.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/home/ReportScreen.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/ValidateCodeForm.js
  tests/ui/UnreadIndicatorsTest.js
  web/splash/splash.js
Labels: automerge

#14915 Update version to 1.2.67-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14916 Update version to 1.2.67-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
Labels: automerge

#14917 Update version to 1.2.67-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14919 Update version to 1.2.67-2 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/PROPOSAL_TEMPLATE.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14922 Update version to 1.2.67-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14923 Update version to 1.2.67-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14924 Update version to 1.2.67-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14925 Update version to 1.2.67-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#14921 change maxInputLength default value to undefined from -1
  src/components/AddressSearch.js
Labels: CP Staging

#14927 Update version to 1.2.67-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14928 🍒 Cherry pick PR #14921 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch.js
Labels: automerge

#14930 Update version to 1.2.67-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14931 Update version to 1.2.67-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
Labels: automerge

#14779 Check if policy room is archived because of merging
  src/CONST.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionItemSingle.js
Labels: InternalQA

#14955 [CP Staging] Get route.params.openOnAdminRoom if exists
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
Labels: CP Staging

#14959 Update version to 1.2.67-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14960 🍒 Cherry pick PR #14955 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
Labels: automerge

#14974 Update version to 1.2.67-7 on production
  android/app/build.gradle
  config/webpack/webpack.common.js
  contributingGuides/CONTRIBUTING.md
  contributingGuides/PROPOSAL_TEMPLATE.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/CountryPicker.js
  src/components/Form.js
  src/components/PDFView/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Welcome.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/signin/ValidateCodeForm.js
  tests/ui/UnreadIndicatorsTest.js
  web/splash/splash.js
Labels: automerge

#14975 Update version to 1.2.68-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14976 Update version to 1.2.68-0 on staging
  .github/scripts/verifyPodfile.sh
  .github/workflows/test.yml
  android/app/build.gradle
  babel.config.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest.config.js
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/libs/Environment/betaChecker/index.android.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/AppUpdate.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/settings/Preferences/LanguagePage.js
  src/pages/settings/Preferences/PreferencesPage.js
  tests/actions/ReportTest.js
  tests/actions/SessionTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/MigrationTest.js
  tests/unit/NetworkTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#15015 Update version to 1.2.68-0 on production
  .github/scripts/verifyPodfile.sh
  .github/workflows/test.yml
  android/app/build.gradle
  babel.config.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  jest.config.js
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/libs/Environment/betaChecker/index.android.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  src/libs/actions/AppUpdate.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/settings/Preferences/LanguagePage.js
  src/pages/settings/Preferences/PreferencesPage.js
  tests/actions/ReportTest.js
  tests/actions/SessionTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/MigrationTest.js
  tests/unit/NetworkTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#15016 Update version to 1.2.69-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15017 Update version to 1.2.69-0 on staging
  .storybook/fonts.css
  .storybook/main.js
  .storybook/manager-head.html
  .storybook/preview.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/KeyboardShortcutsModal.js
  src/components/Modal/BaseModal.js
  src/components/Modal/modalPropTypes.js
  src/components/PasswordPopover/BasePasswordPopover.js
  src/components/withViewportOffsetTop.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/ReportScreen.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/styles/getModalStyles/getBaseModalStyles.js
  src/styles/getModalStyles/index.android.js
Labels: automerge

#15023 Update version to 1.2.69-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15025 Update version to 1.2.69-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
Labels: automerge

#15027 Update version to 1.2.69-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15028 Update version to 1.2.69-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15067 Update version to 1.2.69-2 on production
  .storybook/fonts.css
  .storybook/main.js
  .storybook/manager-head.html
  .storybook/preview.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/components/KeyboardShortcutsModal.js
  src/components/Modal/BaseModal.js
  src/components/Modal/modalPropTypes.js
  src/components/PasswordPopover/BasePasswordPopover.js
  src/components/withViewportOffsetTop.js
  src/languages/en.js
  src/languages/es.js
  src/pages/home/ReportScreen.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/styles/getModalStyles/getBaseModalStyles.js
  src/styles/getModalStyles/index.android.js
Labels: automerge

#15068 Update version to 1.2.70-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15069 Update version to 1.2.70-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/CONST.js
  src/components/Composer/index.js
  src/components/TextInput/BaseTextInput.js
  src/languages/es.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionsView.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/styles.js
Labels: automerge

#15073 Update version to 1.2.70-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15074 Update version to 1.2.70-1 on staging
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Picker.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  src/styles/themes/default.js
  web/index.html
Labels: automerge

#15081 Autofill code from SMS magic code
  src/pages/signin/ValidateCodeForm.js
Labels: InternalQA

#14726 Fix blank screen when showing the WorkspaceResetBankAccount modal
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
Labels: Ready To Build

#15091 Update version to 1.2.70-1 on production
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/CONST.js
  src/components/Composer/index.js
  src/components/Picker.js
  src/components/TextInput/BaseTextInput.js
  src/languages/es.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionsView.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  src/styles/themes/default.js
  web/index.html
Labels: automerge

#15092 Update version to 1.2.71-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15101 Autofocus magic code input
  src/pages/signin/ValidateCodeForm.js
Labels: CP Staging, InternalQA

#15102 Update version to 1.2.71-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15172 Update version to 1.2.71-1 on production
  android/app/build.gradle
  assets/emojis.js
  assets/images/emojiCategoryIcons/add-emoji.svg
  assets/images/emojiCategoryIcons/calendar.svg
  assets/images/emojiCategoryIcons/car.svg
  assets/images/emojiCategoryIcons/flag.svg
  assets/images/emojiCategoryIcons/hamburger.svg
  assets/images/emojiCategoryIcons/heart.svg
  assets/images/emojiCategoryIcons/light-bulb.svg
  assets/images/emojiCategoryIcons/peace-sign.svg
  assets/images/emojiCategoryIcons/plane.svg
  assets/images/emojiCategoryIcons/plant.svg
  assets/images/emojiCategoryIcons/soccer-ball.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Composer/index.js
  src/components/CopySelectionHelper.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/CategoryShortcutButton.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/libs/EmojiUtils.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/signin/ValidateCodeForm.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#15217 Revert "Conditionally require password for adding a debit card"
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: CP Staging

#15218 Update version to 1.2.72-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15219 🍒 Cherry pick PR #15217 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Payments/AddDebitCardPage.js
Labels: automerge

#15221 Update version to 1.2.73-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15222 Update version to 1.2.73-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/components/LocalePicker.js
  src/components/RoomNameInput/index.native.js
  src/components/RoomNameInput/roomNameInputPropTypes.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/libs/Notification/PushNotification/index.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/Permissions.js
  src/libs/actions/Session/index.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#15226 Update version to 1.2.73-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15258 Update version to 1.2.73-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AttachmentModal.js
  src/components/LocalePicker.js
  src/components/RoomNameInput/index.native.js
  src/components/RoomNameInput/roomNameInputPropTypes.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/libs/Notification/PushNotification/index.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/Permissions.js
  src/libs/actions/Session/index.js
  src/libs/actions/Wallet.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/IdologyQuestions.js
  src/pages/EnablePayments/OnfidoPrivacy.js
  src/pages/EnablePayments/OnfidoStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/AddSecondaryLoginPage.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#15257 Update version to 1.2.74-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15327 Update version to 1.2.75-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15224 [Expensify Help] Sync LHN scroll with article scroll
  docs/_layouts/default.html
  docs/_sass/_main.scss
  docs/assets/js/main.js
Labels: InternalQA

#15334 Revert "Don't show empty chat"
  src/libs/ReportUtils.js
  tests/unit/SidebarFilterTest.js
Labels: CP Staging

#15387 Update version to 1.2.76-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15388 Update version to 1.2.76-0 on staging
  .github/workflows/test.yml
  SmallbusinessPlaybook
  android/app/build.gradle
  docs/_layouts/default.html
  docs/_sass/_main.scss
  docs/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.md
  docs/assets/js/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/components/TestToolMenu.js
  src/components/TestToolRow.js
  src/components/TestToolsModal.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/App.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Session/index.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUTransactions.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/signin/ValidateCodeForm/index.android.js
  src/pages/signin/ValidateCodeForm/index.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/getModalStyles/getBaseModalStyles.js
  src/styles/styles.js
  src/styles/utilities/sizing.js
  src/styles/variables.js
  tests/unit/ReportActionsUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/utils/TestHelper.js
Labels: automerge

#15395 Update version to 1.2.76-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15396 Update version to 1.2.76-1 on staging
  SmallbusinessPlaybook
  android/app/build.gradle
  docs/_data/routes.yml
  docs/_layouts/default.html
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md
  docs/assets/js/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15397 Update version to 1.2.76-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15398 Update version to 1.2.76-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15406 Update version to 1.2.76-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15408 Update version to 1.2.76-3 on staging
  android/app/build.gradle
  android/gradle.properties
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14393 Setup Lottie
  assets/animations/Fireworks.json
  assets/animations/ReviewingBankInfo.json
  assets/images/confetti-pop.gif
  config/webpack/webpack.common.js
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/pages/EnablePayments/ActivateStep.js
Labels: Ready To Build

#15418 Update version to 1.2.76-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15419 🍒 Cherry pick PR #15417 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/components/TestToolMenu.js
  src/components/TestToolRow.js
  src/components/TestToolsModal.js
  src/libs/actions/App.js
  src/styles/getModalStyles/getBaseModalStyles.js
  src/styles/utilities/sizing.js
Labels: automerge

#15454 Update version to 1.2.76-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15455 Update version to 1.2.76-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15456 Update version to 1.2.76-5 on staging
  android/app/build.gradle
  assets/animations/Fireworks.json
  assets/animations/ReviewingBankInfo.json
  assets/images/confetti-pop.gif
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/settings/Profile/TimezoneSelectPage.js
Labels: automerge

#15457 Update version to 1.2.76-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15458 Update version to 1.2.76-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15459 Update version to 1.2.76-7 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15518 Update version to 1.2.76-7 on production
  .github/workflows/test.yml
  SmallbusinessPlaybook
  android/app/build.gradle
  android/gradle.properties
  assets/animations/Fireworks.json
  assets/animations/ReviewingBankInfo.json
  assets/images/confetti-pop.gif
  config/webpack/webpack.common.js
  docs/_data/routes.yml
  docs/_layouts/default.html
  docs/_sass/_main.scss
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md
  docs/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.md
  docs/assets/js/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/ConfirmationPage.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Session/index.js
  src/libs/actions/User.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUTransactions.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/signin/ValidateCodeForm/index.android.js
  src/pages/signin/ValidateCodeForm/index.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/styles.js
  src/styles/variables.js
  tests/unit/ReportActionsUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/utils/TestHelper.js
Labels: automerge

#15519 Update version to 1.2.77-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15520 Update version to 1.2.77-0 on staging
  android/app/build.gradle
  contributingGuides/TestRail_Navigation_C+.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HeaderWithCloseButton.js
  src/components/ImageView/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/MenuItem.js
  src/components/Modal/BaseModal.js
  src/components/Modal/index.web.js
  src/components/OptionRow.js
  src/components/Popover/index.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/components/optionPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/Modal.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItem.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Preferences/PriorityModePage.js
  src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Profile/TimezoneInitialPage.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/SignInPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/styles.js
  tests/unit/SidebarFilterTest.js
Labels: automerge

#15535 Update version to 1.2.77-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15539 Update version to 1.2.77-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/Navigation.js
Labels: automerge

#15542 Update version to 1.2.77-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15474 Always show the last closed report action
  src/libs/ReportActionsUtils.js
  src/pages/home/report/ReportFooter.js
Labels: InternalQA

#15566 Update version to 1.2.77-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15567 🍒 Cherry pick PR #15563 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Modal/BaseModal.js
  src/components/Modal/index.web.js
Labels: automerge
