Repository Expensify/App, pull requests merged in 2023-08, with the labels that each got.

#20179 Setup App for TypeScript
  .eslintignore
  .eslintrc.js
  .github/actions/javascript/bumpVersion/index.js
  .github/workflows/preDeploy.yml
  .github/workflows/typecheck.yml
  .gitignore
  babel.config.js
  config/webpack/webpack.common.js
  config/webpack/webpack.desktop.js
  metro.config.js
  package-lock.json
  package.json
  src/components/ConfirmationPage.js
  src/components/LottieAnimations.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/global.d.ts
  src/libs/actions/Device/getDeviceInfo/getOSAndName/index.js
  src/pages/EnablePayments/ActivateStep.js
  src/pages/settings/Security/TwoFactorAuth/SuccessPage.js
  src/pages/signin/SignInHeroImage.js
  tsconfig.json
Labels: Daily, Typescript Migration

#18507 Update App to React Native 0.72 version
  .gitignore
  .ruby-version
  .watchmanconfig
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  metro.config.js
  package-lock.json
  package.json
  patches/@oguzhnatly+react-native-image-manipulator+1.0.5.patch
  patches/@onfido+react-native-sdk+7.4.0.patch
  patches/react-native+0.72.1+001+initial.patch
  patches/react-native+0.72.1+002+NumberOfLines.patch
  patches/react-native+0.72.1+003+VerticalScrollBarPosition.patch
  scripts/postInstall.sh
  src/components/Composer/index.android.js
  src/components/Composer/index.ios.js
  src/pages/settings/Preferences/PriorityModePage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/workspace/bills/WorkspaceBillsFirstSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
Labels: Ready To Build

#23046 Add ability to Take/Upload Receipts
  android/gradle.properties
  assets/images/hand.svg
  assets/images/receipt-doc.png
  assets/images/receipt-generic.png
  assets/images/receipt-html.png
  assets/images/receipt-svg.png
  assets/images/receipt-upload.svg
  assets/images/shutter.svg
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-vision-camera+2.15.4.patch
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AttachmentModal.js
  src/components/MoneyRequestConfirmationList.js
  src/components/TabSelector/TabSelector.js
  src/components/TabSelector/TabSelectorItem.js
  src/components/participantPropTypes.js
  src/hooks/useDragAndDrop.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js
  src/libs/Navigation/OnyxTabNavigator.js
  src/libs/Navigation/linkingConfig.js
  src/libs/ReceiptUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Receipt.js
  src/libs/actions/Tab.js
  src/pages/iou/MoneyRequestDescriptionPage.js
  src/pages/iou/MoneyRequestSelectorPage.js
  src/pages/iou/ReceiptDropUI.js
  src/pages/iou/ReceiptSelector/index.js
  src/pages/iou/ReceiptSelector/index.native.js
  src/pages/iou/steps/MoneyRequestAmount.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/utilities/spacing.js
Labels: Ready To Build

#24166 🍒 Cherry pick PR #24091 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: Engineering, Hourly

#24072 [No QA] Log when notifications are received and processed in the background
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
Labels: Ready To Build

#19011 Add popovers without overlay
  src/App.js
  src/components/AddPaymentMethodMenu.js
  src/components/AvatarWithImagePicker.js
  src/components/ButtonWithDropdownMenu.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/FloatingActionButton.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/Popover/index.js
  src/components/Popover/popoverPropTypes.js
  src/components/PopoverMenu/index.js
  src/components/PopoverMenu/popoverMenuPropTypes.js
  src/components/PopoverProvider/index.js
  src/components/PopoverProvider/index.native.js
  src/components/PopoverWithMeasuredContent.js
  src/components/PopoverWithoutOverlay/index.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/ThreeDotsMenu/index.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ReactionList/PopoverReactionList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
Labels: Ready To Build

#23825 Persist notification cache to internal storage
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationListener.java
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  android/app/src/main/java/com/expensify/chat/customairshipextender/NotificationCache.java
Labels: Ready To Build

#20798 Fix: Find solution to low resolution large images on Android, and the Canvas crash
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/AttachmentCarousel/createInitialState.js
  src/components/AttachmentCarousel/index.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/Attachments/AttachmentCarousel/CarouselActions.js
  src/components/Attachments/AttachmentCarousel/CarouselButtons.js
  src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPage.js
  src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPagerContext.js
  src/components/Attachments/AttachmentCarousel/Pager/ImageTransformer.js
  src/components/Attachments/AttachmentCarousel/Pager/ImageWrapper.js
  src/components/Attachments/AttachmentCarousel/Pager/index.js
  src/components/Attachments/AttachmentCarousel/attachmentCarouselPropTypes.js
  src/components/Attachments/AttachmentCarousel/extractAttachmentsFromReport.js
  src/components/Attachments/AttachmentCarousel/index.js
  src/components/Attachments/AttachmentCarousel/index.native.js
  src/components/Attachments/AttachmentCarousel/useCarouselArrows.js
  src/components/Attachments/AttachmentView/AttachmentViewImage/index.js
  src/components/Attachments/AttachmentView/AttachmentViewImage/index.native.js
  src/components/Attachments/AttachmentView/AttachmentViewImage/propTypes.js
  src/components/Attachments/AttachmentView/AttachmentViewPdf/index.js
  src/components/Attachments/AttachmentView/AttachmentViewPdf/index.native.js
  src/components/Attachments/AttachmentView/AttachmentViewPdf/propTypes.js
  src/components/Attachments/AttachmentView/index.js
  src/components/Attachments/AttachmentView/propTypes.js
  src/components/Attachments/propTypes.js
  src/components/Image/index.native.js
  src/styles/styles.js
Labels: Ready To Build

#24128 [No QA] Background refresh for Android
  src/libs/Notification/PushNotification/backgroundRefresh/index.android.js
  src/libs/Notification/PushNotification/backgroundRefresh/index.js
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
Labels: Ready To Build

#24299 Improvement: Search Feature for help expensify
  docs/_includes/search-toggle.html
  docs/_includes/sidebar-search.html
  docs/_layouts/default.html
  docs/_sass/_colors.scss
  docs/_sass/_main.scss
  docs/_sass/_search-bar.scss
  docs/annotations.xml
  docs/assets/images/close.svg
  docs/assets/images/search.svg
  docs/assets/js/main.js
  docs/context.xml
Labels: Design

#23703 Enable editing of money requests
  src/CONST.js
  src/ONYXKEYS.js
  src/components/CurrencySymbolButton.js
  src/components/MoneyRequestDetails.js
  src/components/ReportActionItem/MoneyRequestView.js
  src/components/TextInputWithCurrencySymbol.js
  src/languages/en.js
  src/languages/es.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/TransactionUtils.js
  src/libs/actions/IOU.js
  src/pages/EditRequestAmountPage.js
  src/pages/EditRequestCreatedPage.js
  src/pages/EditRequestDescriptionPage.js
  src/pages/EditRequestPage.js
  src/pages/home/report/ReportActionItem.js
  src/pages/iou/steps/MoneyRequestAmountForm.js
Labels: Ready To Build

#24353 fix: invoke useWindowDimensions
  src/components/Attachments/AttachmentCarousel/CarouselButtons.js
Labels: Ready To Build

#24021 Display NVP-enabled Control policies in NewDot
  src/libs/PolicyUtils.js
  src/libs/actions/Policy.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
Labels: Internal

#23626 Allow any admin to see workspace settings
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceInviteMessagePage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspacePageWithSections.js
Labels: InternalQA

#24629 Resolve AdHoc build issues
  .github/workflows/testBuild.yml
  README.md
Labels: Ready To Build

#24058 Adapt Split Bill to workspace chats
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/MoneyRequestAction.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/pages/iou/SplitBillDetailsPage.js
Labels: Internal

#25497 🍒 Cherry pick PR #25492 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DistanceRequest.js
  src/languages/en.js
  src/languages/es.js
Labels: Engineering, Hourly

#25468 Request money - The app crashes when user deleted the request money
  src/components/MenuItem.js
  src/components/ReportActionItem/MoneyRequestView.js
Labels: Ready To Build

#25426 Bump Onyx to 1.0.61
  package-lock.json
  package.json
  src/components/EmojiPicker/EmojiPicker.js
  src/components/Form.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/actions/IOU.js
  src/libs/actions/QueuedOnyxUpdates.js
Labels: Ready To Build

#25628 [No QA] Consolidate mapbox SDK setup in with setupNode
  .github/actions/composite/buildAndroidAPK/action.yml
  .github/actions/composite/setupNode/action.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#25630 Pass required secrets to setupNode
  .github/actions/composite/buildAndroidAPK/action.yml
  .github/actions/composite/setupNode/action.yml
  .github/workflows/deployExpensifyHelp.yml
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/lint.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/reassurePerformanceTests.yml
  .github/workflows/test.yml
  .github/workflows/testBuild.yml
  .github/workflows/typecheck.yml
  .github/workflows/validateDocsRoutes.yml
  .github/workflows/validateGithubActions.yml
  .github/workflows/verifyPodfile.yml
Labels: Ready To Build

#25161 Display single waypoint
  package-lock.json
  package.json
  src/CONST.js
  src/components/DistanceRequest.js
Labels: Design

#25655 [No QA] Configure MapBox before running pod install
  .github/workflows/testBuild.yml
Labels: Ready To Build

#25418 Add Download Banner to mWeb
  assets/images/expensify-app-icon.svg
  src/Expensify.js
  src/ONYXKEYS.ts
  src/components/ConfirmContent.js
  src/components/ConfirmModal.js
  src/components/DownloadAppModal.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/DownloadAppModal.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
Labels: Ready To Build

#25827 [CP Stag] Remove unneeded SaaStr & SBE account consts
  .env.example
  src/CONST.js
Labels: InternalQA

#25565 Performance: Onyx new storage wrapper (idk-keyval)
  package-lock.json
  package.json
Labels: Ready To Build

#25758 Performance: chat input
  src/components/AutoCompleteSuggestions/autoCompleteSuggestionsPropTypes.js
  src/components/EmojiSuggestions.js
  src/components/ExceededCommentLength.js
  src/components/MentionSuggestions.js
  src/libs/ComposerUtils/debouncedSaveReportComment.js
  src/libs/ComposerUtils/getDraftComment.js
  src/libs/SuggestionUtils.js
  src/libs/getModalState.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js
  src/pages/home/report/ReportActionCompose/ReportActionCompose.js
  src/pages/home/report/ReportActionCompose/SendButton.js
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater.js
  src/pages/home/report/ReportActionCompose/SuggestionEmoji.js
  src/pages/home/report/ReportActionCompose/SuggestionMention.js
  src/pages/home/report/ReportActionCompose/Suggestions.js
  src/pages/home/report/ReportActionCompose/composerWithSuggestionsProps.js
  src/pages/home/report/ReportActionCompose/suggestionProps.js
  src/pages/home/report/ReportFooter.js
  src/styles/StyleUtils.js
Labels: Ready To Build

#24639 Implement report approvals
  src/CONST.ts
  src/components/AvatarWithDisplayName.js
  src/components/HeaderWithBackButton/headerWithBackButtonPropTypes.js
  src/components/HeaderWithBackButton/index.js
  src/components/MoneyReportHeader.js
  src/components/MoneyRequestHeader.js
  src/components/ReportActionItem/MoneyRequestPreview.js
  src/components/ReportActionItem/ReportPreview.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionItem.js
Labels: InternalQA

#26296 [NO QA] Provide default launcher asset for production builds
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
Labels: Ready To Build

#26292 [CP Staging] Change isSettled to check for status only
  src/libs/ReportUtils.js
Labels: InternalQA
