Repository Expensify/App, pull requests merged in 2023-04, with the labels that each got.

#16877 Update version to 1.2.93-4 on production
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  __mocks__/@react-native-camera-roll/camera-roll.js
  __mocks__/@ua/react-native-airship.js
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  android/build.gradle
  desktop/main.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/BigNumberPad.js
  src/components/CalendarPicker/index.js
  src/components/HTMLEngineProvider/applyStrikethrough/index.js
  src/components/HTMLEngineProvider/applyStrikethrough/index.native.js
  src/components/OptionRow.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/ReportWelcomeText.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/ReportUtils.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.ios.js
  src/libs/fileDownload/index.android.js
  src/libs/fileDownload/index.ios.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/iou/steps/IOUAmountPage.js
  src/styles/getTooltipStyles.js
  tests/unit/GithubUtilsTest.js
  tests/unit/ReportUtilsTest.js
  tests/unit/createOrUpdateStagingDeployTest.js
Labels: automerge

#16878 Update version to 1.2.94-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16879 Update version to 1.2.94-0 on staging
  android/app/build.gradle
  contributingGuides/NAVIGATION.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/CopySelectionHelper.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/IOUBadge.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/NewDatePicker/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Authentication.js
  src/libs/EmojiUtils.js
  src/libs/GooglePlacesUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/Session/index.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
Labels: automerge

#16906 Update version to 1.2.94-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16907 🍒 Cherry pick PR #16902 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/EmojiUtils.js
Labels: automerge

#16918 [CP Staging] Fix infinity loading display for inaccessible report
  src/libs/actions/Report.js
Labels: CP Staging

#16933 Update version to 1.2.94-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16934 🍒 Cherry pick PR #16918 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#16922 show compose box before report is ready after logout
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
Labels: CP Staging

#16947 Update version to 1.2.94-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16948 🍒 Cherry pick PR #16922 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#16953 Update version to 1.2.94-3 on production
  android/app/build.gradle
  contributingGuides/NAVIGATION.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/CopySelectionHelper.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/IOUBadge.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/NewDatePicker/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Authentication.js
  src/libs/EmojiUtils.js
  src/libs/GooglePlacesUtils.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SelectionScraper/index.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
Labels: automerge

#16954 Update version to 1.2.95-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16955 Update version to 1.2.95-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AttachmentCarousel/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/Form.js
  src/components/FormSubmit/formSubmitPropTypes.js
  src/components/FormSubmit/index.js
  src/components/FormSubmit/index.native.js
  src/components/FullNameInputRow.js
  src/components/IOUConfirmationList.js
  src/components/Picker/BasePicker.js
  src/components/Picker/index.js
  src/components/Picker/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/SidebarUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/libs/getIsReportFullyVisible.js
  src/pages/YearPickerPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUBillPage.js
  src/pages/iou/IOUModal.js
  src/pages/iou/IOURequestPage.js
  src/pages/iou/IOUSendPage.js
  src/pages/iou/ModalHeader.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  tests/unit/getIsReportFullyVisibleTest.js
Labels: automerge

#16992 Update version to 1.2.95-0 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/ROUTES.js
  src/components/AttachmentCarousel/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/Form.js
  src/components/FormSubmit/formSubmitPropTypes.js
  src/components/FormSubmit/index.js
  src/components/FormSubmit/index.native.js
  src/components/FullNameInputRow.js
  src/components/IOUConfirmationList.js
  src/components/Picker/BasePicker.js
  src/components/Picker/index.js
  src/components/Picker/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/SidebarUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/libs/getIsReportFullyVisible.js
  src/pages/YearPickerPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionsView.js
  src/pages/iou/IOUBillPage.js
  src/pages/iou/IOUModal.js
  src/pages/iou/IOURequestPage.js
  src/pages/iou/IOUSendPage.js
  src/pages/iou/ModalHeader.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  tests/unit/getIsReportFullyVisibleTest.js
Labels: automerge

#16994 Update version to 1.2.96-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16995 Update version to 1.2.96-0 on staging
  android/app/build.gradle
  contributingGuides/API.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/AvatarCropModal/Slider.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/dismissKeyboardGoingBack/index.android.js
  src/libs/Navigation/dismissKeyboardGoingBack/index.js
  src/libs/actions/PersonalDetails.js
  src/pages/ReportParticipantsPage.js
  src/pages/settings/Profile/PronounsPage.js
  src/styles/styles.js
Labels: automerge

#17065 Update version to 1.2.96-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17066 Update version to 1.2.96-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/styles/styles.js
Labels: automerge

#17070 Update version to 1.2.96-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17071 Update version to 1.2.96-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17074 Update version to 1.2.96-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17075 Update version to 1.2.96-3 on staging
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplash.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashActivity.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashDialog.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashModule.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashPackage.java
  android/app/src/main/res/anim/fade_out.xml
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values-v31/styles.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/ids.xml
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17088 Update Expensify-Playbook-for-US-Based-SMBs.md
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Small-Businesses.md
Labels: Daily, Design

#16949 Create Expensify-Lounge
  docs/articles/other/Expensify-Lounge
Labels: Daily

#17141 Fix automatic authentication with magic link on mobile native
  src/libs/actions/Session/index.js
Labels: CP Staging

#17145 Update version to 1.2.96-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17146 🍒 Cherry pick PR #17141 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
Labels: automerge

#17157 Update version to 1.2.96-4 on production
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplash.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashActivity.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashDialog.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashModule.java
  android/app/src/main/java/com/expensify/chat/bootsplash/BootSplashPackage.java
  android/app/src/main/res/anim/fade_out.xml
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values-v31/styles.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/ids.xml
  android/app/src/main/res/values/styles.xml
  contributingGuides/API.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/AvatarCropModal/Slider.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/dismissKeyboardGoingBack/index.android.js
  src/libs/Navigation/dismissKeyboardGoingBack/index.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session/index.js
  src/pages/ReportParticipantsPage.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/styles/styles.js
Labels: automerge

#17158 Update version to 1.2.97-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17159 Update version to 1.2.97-0 on staging
  __mocks__/react-native-localize.js
  android/app/build.gradle
  desktop/main.js
  docs/articles/other/Expensify-Lounge
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Small-Businesses.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddressSearch.js
  src/components/CalendarPicker/generateMonthMatrix.js
  src/components/EmojiSuggestions.js
  src/components/Form.js
  src/components/IOUConfirmationList.js
  src/components/LocalePicker.js
  src/components/MenuItem.js
  src/components/ReportWelcomeText.js
  src/components/withLocalize.js
  src/libs/API.js
  src/libs/IntlPolyfill/shouldPolyfill.js
  src/libs/Localize/LocaleListener/BaseLocaleListener.js
  src/libs/Localize/index.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/NameValuePair.js
  src/libs/actions/Session/index.js
  src/libs/actions/Welcome.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/exampleCheckImage.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUSendPage.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/wallet/WalletStatementPage.js
  src/styles/utilities/spacing.js
  tests/actions/SessionTest.js
  tests/unit/CalendarPickerTest.js
  tests/unit/CurrencySymbolUtilsTest.js
  tests/unit/DateUtilsTest.js
  tests/unit/IOUUtilsTest.js
  tests/unit/LocalePhoneNumberTest.js
  tests/unit/NetworkTest.js
  tests/unit/ReportUtilsTest.js
  tests/unit/TranslateTest.js
Labels: automerge

#17169 Update version to 1.2.97-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17170 Update version to 1.2.97-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#17171 Update version to 1.2.97-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17172 Update version to 1.2.97-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#15858 Hide notifications for the currently open report
  __mocks__/@ua/react-native-airship.js
  android/app/build.gradle
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.android.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.ios.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/Notification/PushNotification/shouldShowPushNotification.js
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/setup/platformSetup/index.native.js
Labels: Ready To Build

#17227 Update version to 1.2.97-2 on production
  __mocks__/react-native-localize.js
  android/app/build.gradle
  desktop/main.js
  docs/articles/other/Expensify-Lounge
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Small-Businesses.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddressSearch.js
  src/components/CalendarPicker/generateMonthMatrix.js
  src/components/EmojiSuggestions.js
  src/components/Form.js
  src/components/IOUConfirmationList.js
  src/components/LocalePicker.js
  src/components/MenuItem.js
  src/components/ReportWelcomeText.js
  src/components/withLocalize.js
  src/libs/API.js
  src/libs/IntlPolyfill/shouldPolyfill.js
  src/libs/Localize/LocaleListener/BaseLocaleListener.js
  src/libs/Localize/index.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/NameValuePair.js
  src/libs/actions/Session/index.js
  src/libs/actions/Welcome.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/exampleCheckImage.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUSendPage.js
  src/pages/iou/MoneyRequestModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
  src/pages/settings/Profile/DisplayNamePage.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/wallet/WalletStatementPage.js
  src/styles/utilities/spacing.js
  tests/actions/SessionTest.js
  tests/unit/CalendarPickerTest.js
  tests/unit/CurrencySymbolUtilsTest.js
  tests/unit/DateUtilsTest.js
  tests/unit/IOUUtilsTest.js
  tests/unit/LocalePhoneNumberTest.js
  tests/unit/NetworkTest.js
  tests/unit/ReportUtilsTest.js
  tests/unit/TranslateTest.js
Labels: automerge

#17228 Update version to 1.2.98-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17229 Update version to 1.2.98-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  __mocks__/@ua/react-native-airship.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithImagePicker.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.android.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.ios.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/Notification/PushNotification/shouldShowPushNotification.js
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/setup/platformSetup/index.native.js
Labels: automerge

#17232 Update version to 1.2.98-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17233 Update version to 1.2.98-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#17235 Update version to 1.2.98-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/pages/ReportDetailsPage.js
Labels: automerge

#15130 Upgrade the react native dependency to v0.71.2-alpha.3
  android/app/build.gradle
  android/app/src/debug/java/com/expensify/chat/ReactNativeFlipper.java
  android/app/src/internalRelease/java/com/expensify/chat/ReactNativeFlipper.java
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/java/com/expensify/chat/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/com/expensify/chat/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/com/expensify/chat/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/app/src/release/java/com/expensify/chat/ReactNativeFlipper.java
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/AppDelegate.h
  ios/NewExpensify/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  package-lock.json
  package.json
  src/components/Composer/index.js
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/Preferences/PriorityModePage.js
Labels: Ready To Build

#17251 Fix Airship PushReceived handler
  src/libs/Notification/PushNotification/index.native.js
Labels: InternalQA

#17295 Update version to 1.2.98-2 on production
  .github/PULL_REQUEST_TEMPLATE.md
  __mocks__/@ua/react-native-airship.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarWithImagePicker.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.android.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.ios.js
  src/libs/Notification/PushNotification/configureForegroundNotifications/index.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/Notification/PushNotification/shouldShowPushNotification.js
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/pages/ReportDetailsPage.js
  src/setup/platformSetup/index.native.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#17296 Update version to 1.2.99-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17299 Update version to 1.2.99-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17301 Update version to 1.2.99-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17304 Update version to 1.2.99-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17305 Update version to 1.2.99-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17309 Update Gemfile.lock as it's out of date with Gemfile
  Gemfile.lock
Labels: CP Staging, Ready To Build

#17311 Update version to 1.2.99-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17312 🍒 Cherry pick PR #17309 to staging 🍒
  Gemfile.lock
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17315 Update version to 1.2.99-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17317 Update version to 1.2.99-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17350 Update version to 1.2.99-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16932 Invert bootsplash colors + fade splash screen on web
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/BootSplash.storyboard
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  web/splash/splash.css
  web/splash/splash.js
Labels: Ready To Build

#17358 Update version to 1.2.99-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17359 🍒 Cherry pick PR #17352 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
Labels: automerge

#17377 Update version to 1.3.0-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17378 Update version to 1.3.0-0 on staging
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  contributingGuides/API.md
  docs/articles/other/Expensify-Lounge.md
  ios/NewExpensify/BootSplash.storyboard
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/Avatar.js
  src/components/DatePicker/datepickerPropTypes.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/index.js
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/ImageView/index.native.js
  src/components/PlaidLink/index.native.js
  src/libs/ReportActionsUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/deprecatedAPI.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/ReportActionCompose/index.js
  src/pages/home/report/ReportActionCompose/keyDownAction.js
  src/pages/home/report/ReportActionCompose/keyDownAction.native.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsList.js
  src/setup/index.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  web/splash/splash.css
  web/splash/splash.js
Labels: automerge

#17448 Fix expensify devportal url replacement
  src/CONFIG.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
Labels: InternalQA

#14767 Allow keyboard shortcuts to work on native devices
  __mocks__/react-native-key-command.js
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/Button/index.js
  src/components/Button/validateSubmitShortcut/index.js
  src/components/Button/validateSubmitShortcut/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/ScreenWrapper/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.native.js
  src/libs/KeyboardShortcut/getKeyEventModifiers.js
  src/libs/KeyboardShortcut/index.js
  src/libs/KeyboardShortcut/index.native.js
  src/pages/home/report/ReportActionCompose/index.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/styles/styles.js
Labels: Ready To Build

#17507 Update version to 1.3.0-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17508 🍒 Cherry pick PR #17494 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Tooltip/TooltipRenderedOnPageBody.js
Labels: automerge

#17475 Revert: 17138 17360 listen keydown from user
  src/components/EmojiPicker/EmojiPickerButton.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionCompose/keyDownAction.js
  src/pages/home/report/ReportActionCompose/keyDownAction.native.js
Labels: CP Staging

#17526 Update version to 1.3.0-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17528 🍒 Cherry pick PR #17475 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/EmojiPicker/EmojiPickerButton.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionCompose/keyDownAction.js
  src/pages/home/report/ReportActionCompose/keyDownAction.native.js
Labels: automerge, Engineering, Hourly

#17543 Update version to 1.3.0-2 on production
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  contributingGuides/API.md
  docs/articles/other/Expensify-Lounge.md
  ios/NewExpensify/BootSplash.storyboard
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/NewExpensify/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  patches/react-native-fast-image+8.6.3.patch
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/Avatar.js
  src/components/DatePicker/datepickerPropTypes.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/index.js
  src/components/ImageView/index.native.js
  src/components/PlaidLink/index.native.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/libs/ReportActionsUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/deprecatedAPI.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/IdentityForm.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportActionsList.js
  src/setup/index.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  web/splash/splash.css
  web/splash/splash.js
Labels: automerge

#17544 Update version to 1.3.1-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17592 Revert "Allow keyboard shortcuts to work on native devices"
  __mocks__/react-native-key-command.js
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/Button.js
  src/components/Button/validateSubmitShortcut/index.js
  src/components/Button/validateSubmitShortcut/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/ScreenWrapper/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.native.js
  src/libs/KeyboardShortcut/getKeyEventModifiers.js
  src/libs/KeyboardShortcut/index.js
  src/libs/KeyboardShortcut/index.native.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/styles/styles.js
Labels: CP Staging

#17595 Update version to 1.3.1-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17596 🍒 Cherry pick PR #17592 to staging 🍒
  __mocks__/react-native-key-command.js
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/Button.js
  src/components/Button/validateSubmitShortcut/index.js
  src/components/Button/validateSubmitShortcut/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/ScreenWrapper/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.native.js
  src/libs/KeyboardShortcut/getKeyEventModifiers.js
  src/libs/KeyboardShortcut/index.js
  src/libs/KeyboardShortcut/index.native.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/styles/styles.js
Labels: automerge

#17586 Fix/17212: Also update html message and get last message in LHN when edit offline
  src/libs/actions/Report.js
Labels: CP Staging

#17605 Update version to 1.3.1-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17608 🍒 Cherry pick PR #17586 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#17618 Revert "Merge pull request #17310 from akinwale/task-16946"
  src/components/MenuItem.js
  src/components/MenuItemList.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/components/menuItemPropTypes.js
  src/libs/actions/Link.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/Enable2FAPrompt.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/bills/WorkspaceBillsFirstSection.js
  src/pages/workspace/bills/WorkspaceBillsVBAView.js
  src/pages/workspace/card/WorkspaceCardVBAWithECardView.js
  src/pages/workspace/invoices/WorkspaceInvoicesFirstSection.js
  src/pages/workspace/invoices/WorkspaceInvoicesVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelVBAView.js
  src/styles/stylePropTypes.js
Labels: CP Staging

#17622 Update version to 1.3.1-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17623 🍒 Cherry pick PR #17618 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MenuItem.js
  src/components/MenuItemList.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/components/menuItemPropTypes.js
  src/libs/actions/Link.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/Enable2FAPrompt.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/bills/WorkspaceBillsFirstSection.js
  src/pages/workspace/bills/WorkspaceBillsVBAView.js
  src/pages/workspace/card/WorkspaceCardVBAWithECardView.js
  src/pages/workspace/invoices/WorkspaceInvoicesFirstSection.js
  src/pages/workspace/invoices/WorkspaceInvoicesVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelVBAView.js
  src/styles/stylePropTypes.js
Labels: automerge

#17669 Update version to 1.3.2-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17672 Update version to 1.3.2-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17673 Update version to 1.3.2-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17675 Update version to 1.3.2-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17676 Update version to 1.3.2-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/es.js
Labels: automerge

#17697 Revert "Use local SVG for concierge icon"
  src/CONST.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
Labels: CP Staging, Ready To Build

#17701 Update version to 1.3.2-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17702 🍒 Cherry pick PR #17697 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
Labels: automerge

#16735 Add PR number badge for internal builds
  .github/workflows/testBuild.yml
  assets/images/new-expensify-adhoc.svg
  config/electronBuilder.config.js
  config/webpack/webpack.common.js
  desktop/icon-adhoc.png
  desktop/main.js
  fastlane/Fastfile
  package.json
  scripts/build-desktop.sh
  src/CONST.js
  src/components/Badge.js
  src/components/EnvironmentBadge.js
  src/components/ExpensifyCashLogo.js
  src/libs/ApiUtils.js
  src/libs/Environment/Environment.js
  src/libs/Environment/getEnvironment/index.native.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/styles/StyleUtils.js
  src/styles/colors.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: Ready To Build

#17694 [NO QA] Show archived rooms without participants in the LHN
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
Labels: CP Staging

#17727 Update version to 1.3.2-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17728 🍒 Cherry pick PR #17694 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
Labels: automerge, Engineering, Hourly

#17739 Revert "Merge pull request #17321 from allroundexperts/fix-16521"
  src/components/MenuItem.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.native.js
  src/styles/styles.js
Labels: CP Staging

#17740 Update version to 1.3.2-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17741 🍒 Cherry pick PR #17739 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MenuItem.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.js
  src/pages/home/report/ContextMenu/ContextMenuUtils/index.native.js
  src/styles/styles.js
Labels: automerge, Engineering, Hourly

#17745 Update version to 1.3.3-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17749 Update version to 1.3.3-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17750 Update version to 1.3.3-1 on staging
  android/app/build.gradle
  contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Onfido/index.css
Labels: automerge

#17792 Remove this so it doesn't crash after building it
  src/libs/ReportUtils.js
Labels: CP Staging

#17793 Update version to 1.3.3-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17794 🍒 Cherry pick PR #17792 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#17802 Update version to 1.3.4-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16581 [Navigation Reboot] Swap the DrawerNavigator for the ResponsiveNavigator (WIP)
  src/App.js
  src/CONST.js
  src/NAVIGATORS.js
  src/ROUTES.js
  src/components/BlockingViews/BlockingView.js
  src/components/FlatList/index.android.js
  src/components/FlatList/index.js
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/components/LHNOptionsList/LHNOptionsList.js
  src/components/withCurrentReportId.js
  src/components/withDrawerState.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/AppNavigator/ClickAwayHandler.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js
  src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.js
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.js
  src/libs/Navigation/AppNavigator/createCustomModalStackNavigator.js
  src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/CustomRouter.js
  src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/ThreePaneView.js
  src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/index.js
  src/libs/Navigation/AppNavigator/defaultModalScreenOptions.js
  src/libs/Navigation/DeprecatedCustomActions.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/Navigation/getTopmostReportId.js
  src/libs/Navigation/linkTo.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
  src/libs/actions/App.js
  src/libs/getIsReportFullyVisible.js
  src/pages/ConciergePage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/styles/StyleUtils.js
  src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
  src/styles/getNavigationModalCardStyles/index.js
  src/styles/getNavigationModalCardStyles/index.website.js
  src/styles/styles.js
  src/styles/variables.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/getIsReportFullyVisibleTest.js
  tests/utils/LHNTestUtils.js
Labels: Ready To Build

#17706 Fix GH Actions comment when mobile build fails
  .github/workflows/testBuild.yml
Labels: Ready To Build

#17708 Allow keyboard shortcuts to work on native devices
  __mocks__/react-native-key-command.js
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  ios/NewExpensify/AppDelegate.mm
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/Button/index.js
  src/components/Button/validateSubmitShortcut/index.js
  src/components/Button/validateSubmitShortcut/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/ScreenWrapper/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.js
  src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.native.js
  src/libs/KeyboardShortcut/getKeyEventModifiers.js
  src/libs/KeyboardShortcut/index.js
  src/libs/KeyboardShortcut/index.native.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/AboutPage/AboutPage.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.js
  src/pages/settings/AboutPage/getPlatformSpecificMenuItems/index.native.js
  src/styles/styles.js
Labels: Ready To Build

#17946 Update version to 1.3.5-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17954 Update version to 1.3.5-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17955 Update version to 1.3.5-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Section.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#17957 Update version to 1.3.5-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17958 Update version to 1.3.5-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
Labels: automerge

#17959 Update version to 1.3.5-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17960 Update version to 1.3.5-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionItemMessageEdit.js
Labels: automerge

#17986 🍒 Cherry pick PR #17984 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
Labels: automerge

#17988 Fix undefined personal details access causing crash when calling getOptions
  src/libs/OptionsListUtils.js
Labels: CP Staging

#17989 Update version to 1.3.5-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#17990 🍒 Cherry pick PR #17988 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
Labels: automerge

#18015 Update version to 1.3.6-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18016 Update version to 1.3.6-0 on staging
  .storybook/public/index.css
  .storybook/public/logo.png
  .storybook/public/logomark.svg
  .storybook/theme.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses.md
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md
  docs/assets/images/playbook-existing-corporate-card.png
  docs/assets/images/playbook-expense-basics.png
  docs/assets/images/playbook-expenses.png
  docs/assets/images/playbook-impoort-employees.png
  docs/assets/images/playbook-new-bill.png
  docs/assets/images/playbook-scheduled-submit.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch/index.js
  src/components/AddressSearch/resetDisplayListViewBorderOnBlur.js
  src/components/AddressSearch/resetDisplayListViewBorderOnBlur.native.js
  src/components/CopyTextToClipboard.js
  src/components/OnyxProvider.js
  src/components/Reactions/ReportActionItemReactions.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/components/ValidateCode/ExpiredValidateCodeModal.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/createOnyxContext.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Visibility/index.js
  src/libs/actions/User.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/NewContactMethodPage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/styles/getReportActionContextMenuStyles.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#18060 Update version to 1.3.6-0 on production
  .storybook/public/index.css
  .storybook/public/logo.png
  .storybook/public/logomark.svg
  .storybook/theme.js
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses.md
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md
  docs/assets/images/playbook-existing-corporate-card.png
  docs/assets/images/playbook-expense-basics.png
  docs/assets/images/playbook-expenses.png
  docs/assets/images/playbook-impoort-employees.png
  docs/assets/images/playbook-new-bill.png
  docs/assets/images/playbook-scheduled-submit.png
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AddressSearch/index.js
  src/components/AddressSearch/resetDisplayListViewBorderOnBlur.js
  src/components/AddressSearch/resetDisplayListViewBorderOnBlur.native.js
  src/components/CopyTextToClipboard.js
  src/components/OnyxProvider.js
  src/components/Reactions/ReportActionItemReactions.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/components/ValidateCode/ExpiredValidateCodeModal.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/createOnyxContext.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Visibility/index.js
  src/libs/actions/User.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/NewContactMethodPage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/styles/getReportActionContextMenuStyles.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#18061 Update version to 1.3.7-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18062 Update version to 1.3.7-0 on staging
  android/app/build.gradle
  assets/animations/Hands.json
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/EmojiSuggestions/BaseEmojiSuggestions.js
  src/components/EmojiSuggestions/emojiSuggestionsPropTypes.js
  src/components/EmojiSuggestions/index.js
  src/components/EmojiSuggestions/index.native.js
  src/components/ImageView/index.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/Localize/index.js
  src/libs/ValidationUtils.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session/index.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/SetPasswordPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/signin/SignInHeroImage.js
  src/pages/workspace/WorkspacesListPage.js
  src/stories/MenuItem.stories.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/cursor/index.js
  src/styles/utilities/cursor/index.native.js
  src/styles/utilities/userSelect/index.js
  src/styles/utilities/userSelect/index.native.js
  tests/unit/ValidationUtilsTest.js
Labels: automerge

#18075 Update version to 1.3.7-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18077 Update version to 1.3.7-1 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#12033 fix "Downloaded photo is not appearing in the photo album" in android
  ios/Podfile.lock
  package-lock.json
  package.json
  src/libs/fileDownload/index.android.js
Labels: Ready To Build

#18079 Update version to 1.3.7-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/libs/fileDownload/index.android.js
Labels: automerge

#18070 [No-QA] Create referral-program help page on ExpensifyHelp
  docs/articles/other/referral-program
Labels: Daily

#18114 Allow navigating to public announce rooms as the initial report after signing in/signing up
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  tests/actions/SessionTest.js
  tests/unit/NetworkTest.js
Labels: CP Staging

#18127 Update version to 1.3.7-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18128 🍒 Cherry pick PR #18114 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/ReportUtils.js
  src/libs/actions/App.js
  tests/actions/SessionTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#18129 Update version to 1.3.7-3 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  assets/animations/Hands.json
  contributingGuides/REVIEWER_CHECKLIST.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/AttachmentView.js
  src/components/EmojiSuggestions/BaseEmojiSuggestions.js
  src/components/EmojiSuggestions/emojiSuggestionsPropTypes.js
  src/components/EmojiSuggestions/index.js
  src/components/EmojiSuggestions/index.native.js
  src/components/ImageView/index.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/Localize/index.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/App.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Session/index.js
  src/libs/fileDownload/index.android.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/SetPasswordPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/signin/SignInHeroImage.js
  src/pages/workspace/WorkspacesListPage.js
  src/stories/MenuItem.stories.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/cursor/index.js
  src/styles/utilities/cursor/index.native.js
  src/styles/utilities/userSelect/index.js
  src/styles/utilities/userSelect/index.native.js
  tests/actions/SessionTest.js
  tests/unit/NetworkTest.js
  tests/unit/ValidationUtilsTest.js
Labels: automerge

#18130 Update version to 1.3.8-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18131 Update version to 1.3.8-0 on staging
  .github/scripts/createDocsRoutes.js
  .github/scripts/createDocsRoutes.sh
  .github/workflows/deployExpensifyHelp.yml
  .github/workflows/validateDocsRoutes.yml
  android/app/build.gradle
  docs/.gitignore
  docs/README.md
  docs/_data/_routes.yml
  docs/_data/routes.yml
  docs/_includes/hub.html
  docs/_includes/lhn-template.html
  docs/articles/other/referral-program.md
  docs/articles/send-money/paying-friends/Request-and-Send-Money.md
  docs/articles/send-money/workspaces/The-Free-Plan.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentCarousel/index.js
  src/components/MenuItem.js
  src/components/OpacityView.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/Pressable/GenericPressable/BaseGenericPressable.js
  src/components/Pressable/GenericPressable/PropTypes.js
  src/components/Pressable/GenericPressable/index.js
  src/components/Pressable/GenericPressable/index.native.js
  src/components/Pressable/PressableWithFeedback.js
  src/components/Pressable/PressableWithoutFeedback.js
  src/components/Pressable/index.js
  src/libs/Accessibility/index.js
  src/libs/Accessibility/moveAccessibilityFocus/index.js
  src/libs/Accessibility/moveAccessibilityFocus/index.native.js
  src/pages/NewChatPage.js
  src/pages/SearchPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/StyleUtils.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  src/styles/utilities/cursor/index.js
  src/styles/utilities/cursor/index.native.js
  src/styles/utilities/positioning.js
  src/styles/variables.js
Labels: automerge

#18133 Update version to 1.3.8-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18134 Update version to 1.3.8-1 on staging
  android/app/build.gradle
  contributingGuides/FORMS.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/App.js
  src/components/Form.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspacePageWithSections.js
Labels: automerge

#18135 Update version to 1.3.8-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18136 Update version to 1.3.8-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/Navigation.js
Labels: automerge

#18138 Update version to 1.3.8-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18139 Update version to 1.3.8-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
Labels: automerge

#18142 Update version to 1.3.8-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/pages/workspace/WorkspaceInvitePage.js
Labels: automerge

#18155 fix: re-add placeholder text inside base option selector
  src/components/OptionsSelector/BaseOptionsSelector.js
Labels: CP Staging

#18161 Update version to 1.3.8-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18164 🍒 Cherry pick PR #18155 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector/BaseOptionsSelector.js
Labels: automerge

#18159 Add falsey checks and `_.compact()` to places where we access SMS logins from personal details
  src/libs/LocalePhoneNumber.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/PersonalDetails.js
  src/pages/DetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/home/report/ReportActionItemSingle.js
Labels: CP Staging, Ready To Build

#18174 Update version to 1.3.8-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18175 🍒 Cherry pick PR #18159 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/LocalePhoneNumber.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/PersonalDetails.js
  src/pages/DetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/home/report/ReportActionItemSingle.js
Labels: automerge

#18173 Remove unnecessary participants filtering
  src/pages/ReportParticipantsPage.js
Labels: CP Staging, Ready To Build

#18177 Update version to 1.3.8-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18178 🍒 Cherry pick PR #18173 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReportParticipantsPage.js
Labels: automerge

#18153 Fix applying styling when it want to apply opacity on OpacityView
  src/components/OpacityView.js
  src/components/Pressable/GenericPressable/BaseGenericPressable.js
  src/styles/styles.js
Labels: CP Staging

#18185 Update version to 1.3.8-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#18187 🍒 Cherry pick PR #18153 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OpacityView.js
  src/components/Pressable/GenericPressable/BaseGenericPressable.js
  src/styles/styles.js
Labels: automerge
