Repository Expensify/App, pull requests merged in 2023-01, with the labels that each got.

#13930 Update version to 1.2.46-0 on production
  .github/workflows/testBuild.yml
  .gitignore
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  scripts/android-repackage-app-bundle-and-sign.sh
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/DragAndDrop/index.js
  src/components/ReportActionItem/IOUAction.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportFooter.js
  src/pages/iou/IOUDetailsModal.js
  tests/e2e/ADDING_TESTS.md
  tests/e2e/README.md
  tests/e2e/config.js
  tests/e2e/config.local.js
  tests/e2e/testRunner.js
  tests/e2e/utils/androidReversePort.js
  tests/e2e/utils/getCurrentBranchName.js
  tests/e2e/utils/installApp.js
  tests/e2e/utils/logger.js
Labels: automerge

#13931 Update version to 1.2.47-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13932 Update version to 1.2.47-0 on staging
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/libs/EmojiUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/ReportUtils.js
  src/libs/UnreadIndicatorUpdater/index.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js
  src/libs/actions/Session/index.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/signin/SignInPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/unit/EmojiTest.js
  web/index.html
Labels: automerge

#13952 Update CODEOWNERS so that we don't accidentally deploy a new version of react-native-onyx
  .github/CODEOWNERS
Labels: InternalQA

#13973 Update version to 1.2.47-0 on production
  android/app/build.gradle
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/res/values/styles.xml
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/libs/EmojiUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/ReportUtils.js
  src/libs/UnreadIndicatorUpdater/index.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js
  src/libs/actions/Session/index.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/signin/SignInPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  tests/unit/EmojiTest.js
  web/index.html
Labels: automerge

#13974 Update version to 1.2.48-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13975 Update version to 1.2.48-0 on staging
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentPicker/index.native.js
  src/components/AutoUpdateTime.js
  src/components/AvatarWithImagePicker.js
  src/components/CheckboxWithLabel.js
  src/components/UnreadActionIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/DateUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/fileDownload/getImageResolution.js
  src/libs/fileDownload/getImageResolution.native.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/reportPropTypes.js
  src/pages/settings/Profile/TimezoneInitialPage.js
  src/pages/signin/PasswordForm.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/unit/ValidationUtilsTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#13979 Update version to 1.2.48-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13980 Update version to 1.2.48-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/pages/ReportSettingsPage.js
Labels: automerge

#13982 Update version to 1.2.48-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13983 Update version to 1.2.48-2 on staging
  android/app/build.gradle
  contributingGuides/PERFORMANCE.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Composer/index.js
  src/components/PlaidLink/plaidLinkPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PusherConnectionManager.js
  src/libs/actions/Policy.js
  src/libs/actions/Wallet.js
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#14020 Update version to 1.2.48-2 on production
  .github/workflows/testBuild.yml
  android/app/build.gradle
  contributingGuides/PERFORMANCE.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AttachmentPicker/index.native.js
  src/components/AutoUpdateTime.js
  src/components/AvatarWithImagePicker.js
  src/components/CheckboxWithLabel.js
  src/components/Composer/index.js
  src/components/PlaidLink/plaidLinkPropTypes.js
  src/components/UnreadActionIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/DateUtils.js
  src/libs/PusherConnectionManager.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/Wallet.js
  src/libs/fileDownload/getImageResolution.js
  src/libs/fileDownload/getImageResolution.native.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/reportPropTypes.js
  src/pages/settings/Profile/TimezoneInitialPage.js
  src/pages/signin/PasswordForm.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/unit/ValidationUtilsTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#14021 Update version to 1.2.49-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14064 Update version to 1.2.50-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14066 Update version to 1.2.50-0 on staging
  .github/ISSUE_TEMPLATE/Standard.md
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/RoomNameInput/index.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/E2E/API.mock.js
  src/libs/E2E/apiMocks/authenticatePusher.js
  src/libs/E2E/apiMocks/authenticatePusher.json
  src/libs/E2E/apiMocks/beginSignin.js
  src/libs/E2E/apiMocks/beginSignin.json
  src/libs/E2E/apiMocks/openApp.js
  src/libs/E2E/apiMocks/openApp.json
  src/libs/E2E/apiMocks/openReport.js
  src/libs/E2E/apiMocks/openReport.json
  src/libs/E2E/apiMocks/signinUser.js
  src/libs/E2E/apiMocks/signinUser.json
  src/libs/RoomNameInputUtils.js
  src/libs/ValidationUtils.js
  src/pages/DetailsPage.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
  tests/e2e/README.md
  tests/e2e/TestSpec.yml
  tests/e2e/testRunner.js
  tests/unit/ValidationUtilsTest.js
Labels: automerge

#14069 Update version to 1.2.50-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14070 Update version to 1.2.50-1 on staging
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#13714 Add new header font
  android/app/src/main/assets/fonts/ExpensifyNewKansas-Medium.otf
  android/app/src/main/assets/fonts/ExpensifyNewKansas-MediumItalic.otf
  android/link-assets-manifest.json
  assets/css/fonts.css
  assets/fonts/native/ExpensifyNewKansas-Medium.otf
  assets/fonts/native/ExpensifyNewKansas-MediumItalic.otf
  assets/fonts/web/ExpensifyNewKansas-Medium.otf
  assets/fonts/web/ExpensifyNewKansas-Medium.woff
  assets/fonts/web/ExpensifyNewKansas-Medium.woff2
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.otf
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.woff
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.woff2
  config/webpack/webpack.common.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/link-assets-manifest.json
  src/components/Banner.js
  src/components/BlockingViews/BlockingView.js
  src/components/ConfirmationPage.js
  src/components/CurrentWalletBalance.js
  src/components/EnvironmentBadge.js
  src/components/Header.js
  src/components/PDFView/PDFInfoMessage.js
  src/components/Section.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/ReportDropUI.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/styles/fontFamily/index.js
  src/styles/styles.js
  src/styles/variables.js
Labels: Ready To Build

#14071 Update version to 1.2.50-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14072 Update version to 1.2.50-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14073 Update version to 1.2.50-2 on staging
  android/app/build.gradle
  android/app/src/main/assets/fonts/ExpensifyNewKansas-Medium.otf
  android/app/src/main/assets/fonts/ExpensifyNewKansas-MediumItalic.otf
  android/link-assets-manifest.json
  assets/css/fonts.css
  assets/fonts/native/ExpensifyNewKansas-Medium.otf
  assets/fonts/native/ExpensifyNewKansas-MediumItalic.otf
  assets/fonts/web/ExpensifyNewKansas-Medium.otf
  assets/fonts/web/ExpensifyNewKansas-Medium.woff
  assets/fonts/web/ExpensifyNewKansas-Medium.woff2
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.otf
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.woff
  assets/fonts/web/ExpensifyNewKansas-MediumItalic.woff2
  config/webpack/webpack.common.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/link-assets-manifest.json
  package-lock.json
  package.json
  src/components/Banner.js
  src/components/BlockingViews/BlockingView.js
  src/components/ConfirmationPage.js
  src/components/CurrentWalletBalance.js
  src/components/EnvironmentBadge.js
  src/components/Header.js
  src/components/PDFView/PDFInfoMessage.js
  src/components/Section.js
  src/pages/DetailsPage.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/ReportDropUI.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/styles/fontFamily/index.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#14075 Update version to 1.2.50-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14076 Update version to 1.2.50-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14077 Update version to 1.2.50-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14078 Update version to 1.2.50-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14079 Update version to 1.2.50-5 on staging
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/GithubUtilsTest.js
  tests/unit/createOrUpdateStagingDeployTest.js
Labels: automerge

#14081 Update version to 1.2.50-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14083 Update version to 1.2.50-6 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Hoverable/hoverablePropTypes.js
  src/components/Hoverable/index.js
  src/components/Modal/BaseModal.js
  src/components/Tooltip/index.js
  src/libs/DomUtils/index.js
  src/libs/DomUtils/index.native.js
  src/libs/Navigation/NavigationRoot.js
  src/pages/ReportSettingsPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: automerge

#14086 Update version to 1.2.50-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14087 Update version to 1.2.50-7 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/pages/settings/Security/CloseAccountPage.js
Labels: automerge

#14092 Update version to 1.2.50-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14093 Update version to 1.2.50-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14094 Update version to 1.2.50-8 on staging
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#14095 Update version to 1.2.50-9 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14096 Update version to 1.2.50-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14097 Update version to 1.2.50-10 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14101 Update version to 1.2.50-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14102 Update version to 1.2.50-11 on staging
  android/app/build.gradle
  docs/Gemfile.lock
  docs/_config.yml
  docs/_data/routes.yml
  docs/_layouts/default.html
  docs/_sass/_colors.scss
  docs/_sass/_fonts.scss
  docs/_sass/_main.scss
  docs/assets/fonts/ExpensifyNeue-Bold.woff
  docs/assets/fonts/ExpensifyNeue-Bold.woff2
  docs/assets/fonts/ExpensifyNeue-Regular.woff
  docs/assets/fonts/ExpensifyNeue-Regular.woff2
  docs/assets/images/expensify-help.svg
  docs/assets/images/expensify-logo-round.png
  docs/assets/images/lightbulb.svg
  docs/assets/images/money-case.svg
  docs/assets/images/paper-airplane.svg
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14104 Update version to 1.2.50-12 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14105 Update version to 1.2.50-12 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/libs/E2E/actions/e2eLogin.js
  src/libs/E2E/reactNativeLaunchingTest.js
  src/libs/E2E/tests/appStartTimeTest.e2e.js
  src/libs/E2E/tests/openSearchPageTest.e2e.js
  src/libs/Performance.js
  src/pages/SearchPage.js
  tests/e2e/config.js
  tests/e2e/testRunner.js
Labels: automerge

#14065 Add User-Agent to proxy
  web/proxy.js
Labels: InternalQA

#14112 Update version to 1.2.50-13 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14113 Update version to 1.2.50-13 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  web/proxy.js
Labels: automerge

#14115 Removed forgotten code that is not required after removing onFocus
  src/components/Modal/BaseModal.js
Labels: CP Staging

#14132 Update version to 1.2.50-14 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14133 🍒 Cherry pick PR #14115 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Modal/BaseModal.js
Labels: automerge

#14143 Update version to 1.2.51-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14144 Update version to 1.2.51-0 on staging
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/HTMLEngineProvider/index.js
  src/components/ImageView/index.js
  src/components/OptionsList/index.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/components/Tooltip/index.js
  src/libs/DeviceCapabilities/canUseTouchScreen/index.js
  src/libs/DeviceCapabilities/canUseTouchScreen/index.native.js
  src/libs/DeviceCapabilities/hasHoverSupport/index.js
  src/libs/DeviceCapabilities/hasHoverSupport/index.native.js
  src/libs/DeviceCapabilities/index.js
  src/libs/canFocusInputOnScreenFocus/index.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/AppDownloadLinks.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#13967 Migrate to react-native-quick-sqlite / Update react-native-onyx to 1.0.32
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/NetworkTest.js
Labels: Ready To Build

#14050 [PROD QA] Navigate to Concierge chat from Statement
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
Labels: InternalQA

#14183 Update version to 1.2.51-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14184 🍒 Cherry pick PR #14171 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Tooltip/TooltipRenderedOnPageBody.js
Labels: automerge

#14185 Update version to 1.2.51-1 on production
  .github/workflows/cherryPick.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/HTMLEngineProvider/index.js
  src/components/ImageView/index.js
  src/components/OptionsList/index.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/components/Tooltip/index.js
  src/libs/DeviceCapabilities/canUseTouchScreen/index.js
  src/libs/DeviceCapabilities/canUseTouchScreen/index.native.js
  src/libs/DeviceCapabilities/hasHoverSupport/index.js
  src/libs/DeviceCapabilities/hasHoverSupport/index.native.js
  src/libs/DeviceCapabilities/index.js
  src/libs/canFocusInputOnScreenFocus/index.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/AppDownloadLinks.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#14187 Update version to 1.2.52-0 on staging
  android/app/build.gradle
  assets/images/expensify-wordmark.svg
  assets/images/product-illustrations/rocket--blue.svg
  config/electronBuilder.config.js
  contributingGuides/CONTRIBUTING.md
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/Composer/index.js
  src/components/DeeplinkWrapper/deeplinkRoutes.js
  src/components/DeeplinkWrapper/index.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/Icon/Expensicons.js
  src/components/Icon/Illustrations.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/SelectionScraper/index.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/styles/styles.js
  tests/e2e/compare/output/format.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#14189 Update version to 1.2.52-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14190 Update version to 1.2.52-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14192 Update version to 1.2.52-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14193 Update version to 1.2.52-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14197 Update version to 1.2.52-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14198 Update version to 1.2.52-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/SidebarUtils.js
Labels: automerge

#13778 Clean up Localize.js
  src/libs/Localize/index.js
Labels: Ready To Build

#14239 Update version to 1.2.52-4 on production
  android/app/build.gradle
  assets/images/expensify-wordmark.svg
  assets/images/product-illustrations/rocket--blue.svg
  config/electronBuilder.config.js
  contributingGuides/CONTRIBUTING.md
  desktop/main.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  jest/setup.js
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/components/Composer/index.js
  src/components/DeeplinkWrapper/deeplinkRoutes.js
  src/components/DeeplinkWrapper/index.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/HeaderWithCloseButton.js
  src/components/Icon/Expensicons.js
  src/components/Icon/Illustrations.js
  src/components/OfflineWithFeedback.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/SelectionScraper/index.js
  src/libs/SidebarUtils.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/iou/IOUModal.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/styles/styles.js
  tests/e2e/compare/output/format.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/NetworkTest.js
Labels: automerge

#14241 Update version to 1.2.53-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/AttachmentModal.js
  src/components/Form.js
  src/components/ImageView/index.js
  src/components/OptionRow.js
  src/components/RoomHeaderAvatars.js
  src/components/optionPropTypes.js
  src/libs/Localize/index.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/libs/actions/Wallet.js
  src/libs/fileDownload/index.ios.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/ReimbursementAccount/AddressForm.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/actions/SessionTest.js
  tests/unit/ReportActionsUtilsTest.js
  web/index.html
Labels: automerge

#14274 Update version to 1.2.53-0 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/AddressSearch.js
  src/components/AttachmentModal.js
  src/components/Form.js
  src/components/ImageView/index.js
  src/components/OptionRow.js
  src/components/RoomHeaderAvatars.js
  src/components/optionPropTypes.js
  src/libs/Localize/index.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/actions/Session/index.js
  src/libs/actions/Wallet.js
  src/libs/fileDownload/index.ios.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/ReimbursementAccount/AddressForm.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/actions/SessionTest.js
  tests/unit/ReportActionsUtilsTest.js
  web/index.html
Labels: automerge

#14275 Update version to 1.2.54-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14276 Update version to 1.2.54-0 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/Gemfile.lock
  docs/_includes/lhn-article-link.html
  docs/_includes/lhn-template.html
  docs/_sass/_colors.scss
  docs/_sass/_fonts.scss
  docs/_sass/_main.scss
  docs/assets/fonts/ExpensifyNewKansas-Medium.woff
  docs/assets/fonts/ExpensifyNewKansas-Medium.woff2
  docs/assets/fonts/ExpensifyNewKansas-MediumItalic.woff
  docs/assets/fonts/ExpensifyNewKansas-MediumItalic.woff2
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/AnchorForAttachmentsOnly/index.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js
  src/components/PDFView/index.native.js
  src/components/PDFView/pdfViewPropTypes.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithoutFocus.js
  src/components/ReportActionItem/IOUAction.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/ShowContextMenuContext.js
  src/libs/PolicyUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItem.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspacesListPage.js
Labels: automerge

#13645 [Core Branding] Fix Compose Bar Text Alignment
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemSingle.js
  src/styles/styles.js
  src/styles/variables.js
Labels: Ready To Build

#14281 Update version to 1.2.54-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14284 Update version to 1.2.54-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14285 Update version to 1.2.54-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#14330 Update version to 1.2.54-2 on production
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/Gemfile.lock
  docs/_includes/lhn-article-link.html
  docs/_includes/lhn-template.html
  docs/_sass/_colors.scss
  docs/_sass/_fonts.scss
  docs/_sass/_main.scss
  docs/assets/fonts/ExpensifyNewKansas-Medium.woff
  docs/assets/fonts/ExpensifyNewKansas-Medium.woff2
  docs/assets/fonts/ExpensifyNewKansas-MediumItalic.woff
  docs/assets/fonts/ExpensifyNewKansas-MediumItalic.woff2
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/AnchorForAttachmentsOnly/index.js
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js
  src/components/PDFView/index.native.js
  src/components/PDFView/pdfViewPropTypes.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithoutFocus.js
  src/components/ReportActionItem/IOUAction.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/ShowContextMenuContext.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PolicyUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#14331 Update version to 1.2.55-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14332 Update version to 1.2.55-0 on staging
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  assets/emojis.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/AutoUpdateTime.js
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/index.js
  src/components/IOUConfirmationList.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/RNTextInput.js
  src/components/RoomHeaderAvatars.js
  src/components/TestToolMenu.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/SignInRedirect.js
  src/libs/actions/User.js
  src/pages/DetailsPage.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/LoginField.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/bills/WorkspaceBillsFirstSection.js
  src/pages/workspace/bills/WorkspaceBillsVBAView.js
  src/pages/workspace/card/WorkspaceCardVBAWithECardView.js
  src/pages/workspace/invoices/WorkspaceInvoicesFirstSection.js
  src/pages/workspace/invoices/WorkspaceInvoicesVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelVBAView.js
  src/stories/Composer.stories.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: automerge

#14386 Update version to 1.2.55-0 on production
  .github/PULL_REQUEST_TEMPLATE.md
  android/app/build.gradle
  assets/emojis.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AddPlaidBankAccount.js
  src/components/AutoUpdateTime.js
  src/components/DatePicker/index.ios.js
  src/components/DatePicker/index.js
  src/components/IOUConfirmationList.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/RNTextInput.js
  src/components/RoomHeaderAvatars.js
  src/components/TestToolMenu.js
  src/components/TextInput/BaseTextInput.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/libs/actions/SignInRedirect.js
  src/libs/actions/User.js
  src/pages/DetailsPage.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Payments/TransferBalancePage.js
  src/pages/settings/PreferencesPage.js
  src/pages/settings/Profile/LoginField.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/pages/workspace/bills/WorkspaceBillsFirstSection.js
  src/pages/workspace/bills/WorkspaceBillsVBAView.js
  src/pages/workspace/card/WorkspaceCardVBAWithECardView.js
  src/pages/workspace/invoices/WorkspaceInvoicesFirstSection.js
  src/pages/workspace/invoices/WorkspaceInvoicesVBAView.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/pages/workspace/travel/WorkspaceTravelVBAView.js
  src/stories/Composer.stories.js
  src/styles/styles.js
  tests/actions/ReportTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: automerge

#14387 Update version to 1.2.56-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14421 Update version to 1.2.57-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14422 Update version to 1.2.57-0 on staging
  .github/ISSUE_TEMPLATE/DesignDoc.md
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarCropModal/ImageCropView.js
  src/components/AvatarCropModal/Slider.js
  src/components/CurrentWalletBalance.js
  src/components/Form.js
  src/components/FormAlertWithSubmitButton.js
  src/components/Hoverable/index.js
  src/components/Onfido/BaseOnfidoWeb.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ControlSelection/index.js
  src/libs/ControlSelection/index.native.js
  src/libs/ReportUtils.js
  src/libs/RoomNameInputUtils.js
  src/libs/actions/Policy.js
  src/pages/DetailsPage.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#14428 Update version to 1.2.57-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14429 Update version to 1.2.57-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/FullscreenLoadingIndicator.js
  src/components/ReportActionItem/IOUPreview.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/NavigationRoot.js
Labels: automerge

#14433 Update version to 1.2.57-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14434 Update version to 1.2.57-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ButtonWithMenu.js
  src/components/IOUConfirmationList.js
Labels: automerge

#14450 [CP Staging] Fix crash after log out
  package-lock.json
  package.json
Labels: CP Staging

#14464 Update version to 1.2.57-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14465 🍒 Cherry pick PR #14450 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14468 Update version to 1.2.58-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14470 Update version to 1.2.58-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/AddPaymentMethodMenu.js
  src/components/AddPlaidBankAccount.js
  src/components/DatePicker/index.ios.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/RoomNameInput/index.native.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/RoomNameInputUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Plaid.js
  src/libs/actions/Policy.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorOnfidoStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/StepPropTypes.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/plaidDataPropTypes.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/Payments/ChooseTransferAccountPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#14469 Update version to 1.2.57-3 on production
  .github/ISSUE_TEMPLATE/DesignDoc.md
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AvatarCropModal/ImageCropView.js
  src/components/AvatarCropModal/Slider.js
  src/components/ButtonWithMenu.js
  src/components/CurrentWalletBalance.js
  src/components/Form.js
  src/components/FormAlertWithSubmitButton.js
  src/components/FullscreenLoadingIndicator.js
  src/components/Hoverable/index.js
  src/components/IOUConfirmationList.js
  src/components/Onfido/BaseOnfidoWeb.js
  src/components/ReportActionItem/IOUPreview.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ControlSelection/index.js
  src/libs/ControlSelection/index.native.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/ReportUtils.js
  src/libs/RoomNameInputUtils.js
  src/libs/actions/Policy.js
  src/pages/DetailsPage.js
  src/pages/ErrorPage/GenericErrorPage.js
  src/pages/iou/IOUDetailsModal.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Security/CloseAccountPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#14474 Update version to 1.2.58-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14475 Update version to 1.2.58-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/settings/Profile/LoginField.js
Labels: automerge

#14480 Update version to 1.2.58-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14481 🍒 Cherry pick PR #14455 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportActionsUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: automerge

#14484 Revert "[No QA] Filter out reportActionID-keyed Onyx updates"
  src/libs/ReportActionsUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: CP Staging

#14485 Update version to 1.2.58-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14486 🍒 Cherry pick PR #14484 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportActionsUtils.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  tests/actions/ReportTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: automerge

#14508 Fix missing import preventing opening Plaid modal
  src/libs/actions/BankAccounts.js
Labels: CP Staging

#14509 Update version to 1.2.58-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14510 🍒 Cherry pick PR #14508 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/BankAccounts.js
Labels: automerge

#14534 Update version to 1.2.58-4 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ONYXKEYS.js
  src/components/AddPaymentMethodMenu.js
  src/components/AddPlaidBankAccount.js
  src/components/DatePicker/index.ios.js
  src/components/ReimbursementAccountLoadingIndicator.js
  src/components/RoomNameInput/index.native.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/RoomNameInputUtils.js
  src/libs/actions/BankAccounts.js
  src/libs/actions/PaymentMethods.js
  src/libs/actions/Plaid.js
  src/libs/actions/Policy.js
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/navigation.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountForm.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorOnfidoStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/StepPropTypes.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReimbursementAccount/plaidDataPropTypes.js
  src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/AppDownloadLinks.js
  src/pages/settings/Payments/ChooseTransferAccountPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Profile/LoginField.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspaceResetBankAccountModal.js
  src/pages/workspace/reimburse/WorkspaceReimburseSection.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/styles.js
  tests/ui/UnreadIndicatorsTest.js
Labels: automerge

#14535 Update version to 1.2.59-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14536 Update version to 1.2.59-0 on staging
  android/app/build.gradle
  contributingGuides/FORMS.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Form.js
  src/components/Hoverable/index.js
  src/components/ReportTransaction.js
  src/components/RoomHeaderAvatars.js
  src/components/ScrollViewWithContext.js
  src/libs/E2E/apiMocks/openApp.js
  src/libs/E2E/apiMocks/openReport.js
  src/libs/IOUUtils.js
  src/libs/NumberUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/migrateOnyx.js
  src/libs/migrations/AddLastActionCreated.js
  src/libs/migrations/KeyReportActionsByReportActionID.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/reportActionPropTypes.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/reportPropTypes.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/IOUUtilsTest.js
  tests/unit/MigrationTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#14539 Update version to 1.2.59-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14540 Update version to 1.2.59-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/withLocalize.js
  src/libs/DateUtils.js
Labels: automerge

#12447 Text & Dropdown Input Styles
  src/components/LocalePicker.js
  src/components/Picker.js
  src/components/Picker/pickerStyles/index.android.js
  src/components/Picker/pickerStyles/index.ios.js
  src/components/Picker/pickerStyles/index.js
  src/styles/styles.js
  src/styles/variables.js
Labels: Ready To Build

#14600 Update version to 1.2.59-1 on production
  android/app/build.gradle
  contributingGuides/FORMS.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Form.js
  src/components/Hoverable/index.js
  src/components/ReportTransaction.js
  src/components/RoomHeaderAvatars.js
  src/components/ScrollViewWithContext.js
  src/components/withLocalize.js
  src/libs/DateUtils.js
  src/libs/E2E/apiMocks/openApp.js
  src/libs/E2E/apiMocks/openReport.js
  src/libs/IOUUtils.js
  src/libs/NumberUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/ReportActions.js
  src/libs/migrateOnyx.js
  src/libs/migrations/AddLastActionCreated.js
  src/libs/migrations/KeyReportActionsByReportActionID.js
  src/pages/AddPersonalBankAccountPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/reportActionPropTypes.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/iou/IOUCurrencySelection.js
  src/pages/iou/IOUModal.js
  src/pages/reportPropTypes.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/PaymentMethodList.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/IOUUtilsTest.js
  tests/unit/MigrationTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/SidebarOrderTest.js
  tests/utils/LHNTestUtils.js
  tests/utils/TestHelper.js
Labels: automerge

#14601 Update version to 1.2.60-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14603 Update version to 1.2.60-0 on staging
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  react-native.config.js
  src/components/AddressSearch.js
  src/components/Form.js
  src/components/FormAlertWithSubmitButton.js
  src/components/FormSubmit/formSubmitPropTypes.js
  src/components/FormSubmit/index.js
  src/components/FormSubmit/index.native.js
  src/components/LocalePicker.js
  src/components/PDFView/index.js
  src/components/Picker.js
  src/components/Picker/pickerStyles/index.android.js
  src/components/Picker/pickerStyles/index.ios.js
  src/components/Picker/pickerStyles/index.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/libs/ReportUtils.js
  src/pages/EnablePayments/TermsPage/LongTermsForm.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/SetPasswordPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#14628 Remove left padding for prefix
  src/styles/styles.js
Labels: CP Staging

#14629 Update version to 1.2.60-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14630 🍒 Cherry pick PR #14628 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/styles/styles.js
Labels: automerge

#14633 Update version to 1.2.60-1 on production
  android/app/build.gradle
  config/webpack/webpack.common.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  react-native.config.js
  src/components/AddressSearch.js
  src/components/Form.js
  src/components/FormAlertWithSubmitButton.js
  src/components/FormSubmit/formSubmitPropTypes.js
  src/components/FormSubmit/index.js
  src/components/FormSubmit/index.native.js
  src/components/LocalePicker.js
  src/components/PDFView/index.js
  src/components/Picker.js
  src/components/Picker/pickerStyles/index.android.js
  src/components/Picker/pickerStyles/index.ios.js
  src/components/Picker/pickerStyles/index.js
  src/components/TextInput/BaseTextInput.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/libs/ReportUtils.js
  src/pages/EnablePayments/TermsPage/LongTermsForm.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/SetPasswordPage.js
  src/pages/settings/NewPasswordForm.js
  src/pages/workspace/WorkspaceInvitePage.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#14634 Update version to 1.2.61-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14635 Update version to 1.2.61-0 on staging
  .github/actions/composite/announceFailedWorkflowInSlack/action.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/Button.js
  src/components/ConfirmModal.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/MenuItem.js
  src/libs/Clipboard/index.js
  src/libs/E2E/apiMocks/openApp.js
  src/libs/E2E/apiMocks/openReport.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/Download.js
  src/libs/actions/IOU.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#14638 [No QA] LocalePicker Styles - fix small picker height
  src/components/LocalePicker.js
Labels: Ready To Build

#14658 Update version to 1.2.61-0 on production
  .github/actions/composite/announceFailedWorkflowInSlack/action.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/Button.js
  src/components/ConfirmModal.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/MenuItem.js
  src/libs/Clipboard/index.js
  src/libs/E2E/apiMocks/openApp.js
  src/libs/E2E/apiMocks/openReport.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/Download.js
  src/libs/actions/IOU.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#14659 Update version to 1.2.62-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14660 Update version to 1.2.62-0 on staging
  android/app/build.gradle
  contributingGuides/KSv2.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/LocalePicker.js
  src/components/ScreenWrapper/index.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/VideoChatButtonAndMenu/videoChatButtonAndMenuPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Pusher/EventType.js
  src/libs/actions/App.js
  src/libs/actions/Report.js
  src/libs/actions/Timing.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
Labels: automerge

#14663 fix typo when measure time on ReportActionsView
  src/pages/home/report/ReportActionsView.js
Labels: CP Staging

#14671 Update version to 1.2.62-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14672 🍒 Cherry pick PR #14663 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionsView.js
Labels: automerge

#14706 Update version to 1.2.62-1 on production
  android/app/build.gradle
  contributingGuides/KSv2.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/LocalePicker.js
  src/components/ScreenWrapper/index.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/components/VideoChatButtonAndMenu/videoChatButtonAndMenuPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/MainDrawerNavigator.js
  src/libs/Pusher/EventType.js
  src/libs/actions/App.js
  src/libs/actions/Report.js
  src/libs/actions/Timing.js
  src/pages/GetAssistancePage.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
Labels: automerge

#14707 Update version to 1.2.63-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#14708 Update version to 1.2.63-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.js
  src/components/AutoUpdateTime.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/OptionRow.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/PDFView/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/actions/PersistedRequests.js
  src/libs/actions/Report.js
  src/libs/actions/Welcome.js
  src/libs/fileDownload/getAttachmentDetails.js
  src/libs/tryResolveUrlFromApiRoot.js
  src/libs/willBlurTextInputOnTapOutside/index.js
  src/libs/willBlurTextInputOnTapOutside/index.native.js
  src/pages/DetailsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge
