Repository Expensify/App, pull requests merged in 2023-03, with the labels that each got.

#15578 Decode transaction messages because they may have HTML Entities
  src/components/ReportTransaction.js
Labels: CP Staging

#15587 Update version to 1.2.77-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15588 🍒 Cherry pick PR #15578 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportTransaction.js
Labels: automerge

#15546 Use policyName sent back with public rooms for people who aren't in the workspace
  src/libs/ReportUtils.js
Labels: CP Staging, InternalQA

#15615 Update version to 1.2.77-4 on production
  android/app/build.gradle
  contributingGuides/TestRail_Navigation_C+.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/DatePicker/index.android.js
  src/components/DatePicker/index.ios.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HeaderWithCloseButton.js
  src/components/ImageView/index.native.js
  src/components/KeyboardShortcutsModal.js
  src/components/MenuItem.js
  src/components/Modal/BaseModal.js
  src/components/OptionRow.js
  src/components/Popover/index.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/components/ReportTransaction.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/components/optionPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/libs/ValidationUtils.js
  src/libs/actions/Modal.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionItem.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Preferences/PriorityModePage.js
  src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Profile/TimezoneInitialPage.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/SignInPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/styles.js
  tests/unit/SidebarFilterTest.js
Labels: automerge

#15616 Update version to 1.2.78-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15617 Update version to 1.2.78-0 on staging
  .github/actions/composite/buildAndroidAPK/action.yml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  contributingGuides/KSv2.md
  contributingGuides/TestRail_Navigation_C+.md
  desktop/main.js
  docs/_data/routes.yml
  docs/_includes/footer.html
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Small-Businesses.md
  docs/assets/js/main.js
  ios/ExpensifyCash-Bridging-Header.h
  ios/ExpensifyCash.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  scripts/set-pusher-suffix.sh
  src/CONST.js
  src/components/Composer/index.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/ExceededCommentLength.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js
  src/components/IOUConfirmationList.js
  src/components/LocalePicker.js
  src/components/Onfido/BaseOnfidoWeb.js
  src/components/ReportActionItem/IOUAction.js
  src/components/ReportActionItem/IOUQuote.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportFooter.js
  src/pages/home/report/withReportOrNotFound.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/reportPropTypes.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/emojiHeaderContainerPlatformStyles/index.js
  src/styles/emojiHeaderContainerPlatformStyles/index.native.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#15022 Add SEO Footer to New Dot (All Platforms)
  assets/images/expensify-footer-logo-vertical.svg
  assets/images/expensify-footer-logo.svg
  assets/images/social-facebook.svg
  assets/images/social-instagram.svg
  assets/images/social-linkedin.svg
  assets/images/social-podcast.svg
  assets/images/social-twitter.svg
  assets/images/social-youtube.svg
  src/CONST.js
  src/components/Icon/Expensicons.js
  src/components/LocalePicker.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/defaultScreenOptions.js
  src/pages/signin/Licenses.js
  src/pages/signin/LoginForm.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/signin/SignInPage.js
  src/pages/signin/SignInPageLayout/Footer.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/SignInPageLayout/SignInPageGraphics.js
  src/pages/signin/SignInPageLayout/index.js
  src/pages/signin/SignInPageLayout/signInPageStyles/index.ios.js
  src/pages/signin/SignInPageLayout/signInPageStyles/index.js
  src/pages/signin/SignInPageLayout/signInPageStyles/index.native.js
  src/pages/signin/Socials.js
  src/pages/signin/Terms.js
  src/pages/signin/TermsAndLicenses.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/utilities/sizing.js
  src/styles/variables.js
Labels: Ready To Build

#15681 Update version to 1.2.78-0 on production
  .github/actions/composite/buildAndroidAPK/action.yml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/preDeploy.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  contributingGuides/KSv2.md
  contributingGuides/TestRail_Navigation_C+.md
  desktop/main.js
  docs/_data/routes.yml
  docs/_includes/footer.html
  docs/articles/playbooks/Expensify-Playbook-for-US-Based-Small-Businesses.md
  docs/assets/js/main.js
  ios/ExpensifyCash-Bridging-Header.h
  ios/ExpensifyCash.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  scripts/set-pusher-suffix.sh
  src/CONST.js
  src/components/Composer/index.js
  src/components/DeeplinkWrapper/index.website.js
  src/components/ExceededCommentLength.js
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js
  src/components/IOUConfirmationList.js
  src/components/LocalePicker.js
  src/components/Onfido/BaseOnfidoWeb.js
  src/components/ReportActionItem/IOUAction.js
  src/components/ReportActionItem/IOUQuote.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/pages/ReportDetailsPage.js
  src/pages/ReportParticipantsPage.js
  src/pages/ReportSettingsPage.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportFooter.js
  src/pages/home/report/withReportOrNotFound.js
  src/pages/iou/steps/IOUConfirmPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsPage.js
  src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
  src/pages/reportPropTypes.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/settings/Profile/TimezoneSelectPage.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/emojiHeaderContainerPlatformStyles/index.js
  src/styles/emojiHeaderContainerPlatformStyles/index.native.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#15716 Update version to 1.2.80-0 on staging
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  assets/emojis.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/AvatarWithIndicator.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/CategoryShortcutButton.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/LocalePicker.js
  src/components/MenuItem.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/components/Tooltip/index.js
  src/components/Tooltip/tooltipPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/Network/enhanceParameters.js
  src/libs/OptionsListUtils.js
  src/libs/UserUtils.js
  src/libs/actions/User.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportFooter.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/stories/Tooltip.stories.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/nativeVersionUpdaterTest.js
Labels: automerge

#15392 Add leaveRoom action
  src/CONST.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/pages/ReportDetailsPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: CP Staging, InternalQA

#15738 Update version to 1.2.80-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15739 🍒 Cherry pick PR #15392 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/pages/ReportDetailsPage.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: automerge

#15761 Revert "Show all Expensify logins in Contact Methods page & view each in new Contact Method Details page"
  src/ROUTES.js
  src/components/AvatarWithIndicator.js
  src/components/MenuItem.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/UserUtils.js
  src/libs/actions/User.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: CP Staging

#15762 Update version to 1.2.80-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15763 🍒 Cherry pick PR #15761 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AvatarWithIndicator.js
  src/components/MenuItem.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/UserUtils.js
  src/libs/actions/User.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#15764 Update version to 1.2.80-2 on production
  .github/workflows/platformDeploy.yml
  android/app/build.gradle
  assets/emojis.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/CategoryShortcutButton.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/LocalePicker.js
  src/components/Tooltip/TooltipRenderedOnPageBody.js
  src/components/Tooltip/index.js
  src/components/Tooltip/tooltipPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/Network/enhanceParameters.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/libs/deprecatedAPI.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReportDetailsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/home/report/ReportFooter.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/stories/Tooltip.stories.js
  src/styles/getTooltipStyles.js
  src/styles/styles.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/nativeVersionUpdaterTest.js
Labels: automerge

#15773 Update version to 1.2.81-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15774 🍒 Cherry pick PR #15771 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CustomStatusBar/index.android.js
Labels: automerge

#15502 Add the ability to remove OOO events by clicking on a button
  src/CONST.js
  src/components/ReportActionItem/ChronosOOOListActions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Chronos.js
  src/pages/home/report/ReportActionItem.js
  src/styles/utilities/spacing.js
Labels: InternalQA

#15834 Update version to 1.2.82-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15835 Update version to 1.2.82-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/BigNumberPad.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/PlaidLink/index.js
  src/components/ReportActionItem/ChronosOOOListActions.js
  src/components/SignInPageForm/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Environment/Environment.js
  src/libs/actions/Chronos.js
  src/libs/actions/Link.js
  src/pages/SetPasswordPage.js
  src/pages/home/report/ReportActionItem.js
  src/pages/iou/IOUModal.js
  src/pages/iou/steps/IOUAmountPage.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#15838 Update version to 1.2.82-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15839 Update version to 1.2.82-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/languages/en.js
  src/languages/es.js
Labels: automerge

#15841 Update version to 1.2.82-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15842 Update version to 1.2.82-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/BlockingViews/BlockingView.js
  src/components/BlockingViews/FullPageNotFoundView.js
  src/languages/en.js
  src/languages/es.js
  src/pages/ErrorPage/NotFoundPage.js
Labels: automerge

#15843 Update version to 1.2.82-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15844 Update version to 1.2.82-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/es.js
Labels: automerge

#15803 clarify on mobile specific file extensions
  README.md
Labels: Improvement

#15709 Remove accountID param when signing with SigninUser command
  src/libs/actions/Session/index.js
  src/pages/ValidateLoginPage/index.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
Labels: CP Staging

#15881 Update version to 1.2.82-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15882 🍒 Cherry pick PR #15709 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Session/index.js
  src/pages/ValidateLoginPage/index.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
Labels: automerge

#15886 Update version to 1.2.83-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15888 Update version to 1.2.83-0 on staging
  README.md
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  docs/_layouts/default.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/ArrowKeyFocusManager.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/EmojiSuggestions.js
  src/components/Form.js
  src/languages/en.js
  src/languages/es.js
  src/libs/EmojiUtils.js
  src/libs/GetStyledTextArray.js
  src/libs/ReportUtils.js
  src/libs/actions/Policy.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReportSettingsPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionsView.js
  src/pages/settings/Payments/AddDebitCardPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/styles/StyleUtils.js
  src/styles/emojiHeaderContainerPlatformStyles/index.js
  src/styles/emojiHeaderContainerPlatformStyles/index.native.js
  src/styles/styles.js
  tests/unit/getStyledArratTest.js
Labels: automerge

#15871 Fix Static emoji autosuggestion issues
  src/libs/GetStyledTextArray.js
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#15890 Update version to 1.2.83-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15891 🍒 Cherry pick PR #15871 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/GetStyledTextArray.js
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#15897 Always call OpenReport when deeplinking within the app
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/pages/home/ReportScreen.js
Labels: CP Staging

#15901 Update version to 1.2.83-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15902 🍒 Cherry pick PR #15897 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/pages/home/ReportScreen.js
Labels: automerge

#15930 Update version to 1.2.83-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15931 🍒 Cherry pick PR #15923 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Link.js
Labels: automerge

#15936 Update version to 1.2.84-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15937 Update version to 1.2.84-0 on staging
  android/app/build.gradle
  contributingGuides/FORMS.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ErrorUtils.js
  src/pages/settings/Profile/DisplayNamePage.js
Labels: automerge

#15904 [NO QA] Fix leftover review comments on App/pull/15897
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
Labels: CP Staging

#15943 Update version to 1.2.84-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15944 🍒 Cherry pick PR #15904 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
Labels: automerge

#15980 Update version to 1.2.84-1 on production
  android/app/build.gradle
  contributingGuides/FORMS.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/libs/ErrorUtils.js
  src/pages/settings/Profile/DisplayNamePage.js
Labels: automerge

#15981 Update version to 1.2.85-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15982 Update version to 1.2.85-0 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/Picker/Picker.js
  src/components/Picker/index.js
  src/components/Picker/index.native.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/Reactions/ReactionTooltipContent.js
  src/components/Reactions/ReportActionItemReactions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PersonalDetailsUtils.js
  src/libs/actions/Report.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#15994 Ensure OpenReport is always called when deeplinking from an outside source
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/pages/home/ReportScreen.js
Labels: CP Staging

#15997 Update version to 1.2.85-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15999 🍒 Cherry pick PR #15994 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/pages/home/ReportScreen.js
Labels: automerge

#16025 Update version to 1.2.85-1 on production
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/Picker/Picker.js
  src/components/Picker/index.js
  src/components/Picker/index.native.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/Reactions/ReactionTooltipContent.js
  src/components/Reactions/ReportActionItemReactions.js
  src/languages/en.js
  src/languages/es.js
  src/libs/PersonalDetailsUtils.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: automerge

#16026 Update version to 1.2.86-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16027 Update version to 1.2.86-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ValidationUtils.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
Labels: automerge

#16029 Update version to 1.2.86-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16069 Update version to 1.2.86-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentModal.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/KeyboardDismissingFlatList/index.js
  src/components/KeyboardDismissingFlatList/index.native.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ValidationUtils.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge

#16070 Update version to 1.2.87-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16073 Update version to 1.2.87-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/components/AddressSearch.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/TestToolMenu.js
  src/libs/ApiUtils.js
  src/libs/HttpUtils.js
  src/libs/LoginUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/shouldUseStagingServer/index.js
  src/libs/shouldUseStagingServer/index.native.js
  src/libs/tryResolveUrlFromApiRoot.js
  src/pages/iou/IOUDetailsModal.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  web/index.html
Labels: automerge

#16077 Update root AASA content-type
  .github/workflows/platformDeploy.yml
Labels: InternalQA

#15788 Fix navigation to Concierge chat after sign-up/sign-in
  src/Expensify.js
  src/ROUTES.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  tests/unit/ReportUtilsTest.js
Labels: CP Staging

#16334 Update version to 1.2.87-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16335 🍒 Cherry pick PR #15788 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/Expensify.js
  src/ROUTES.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#16342 Update version to 1.2.87-1 on production
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/Expensify.js
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/TestToolMenu.js
  src/libs/ApiUtils.js
  src/libs/HttpUtils.js
  src/libs/LoginUtils.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/Navigation.js
  src/libs/NetworkConnection.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/libs/shouldUseStagingServer/index.js
  src/libs/shouldUseStagingServer/index.native.js
  src/libs/tryResolveUrlFromApiRoot.js
  src/pages/home/ReportScreen.js
  src/pages/iou/IOUDetailsModal.js
  tests/actions/ReportTest.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/ReportUtilsTest.js
  web/index.html
Labels: automerge

#16343 Update version to 1.2.88-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16397 fix/15438: regression test
  src/components/DisplayNames/index.js
Labels: CP Staging

#16400 Update version to 1.2.88-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16401 🍒 Cherry pick PR #16397 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/DisplayNames/index.js
Labels: automerge

#16441 Fix getSmallSizeAvatar to block url is not from cloudfront
  src/CONST.js
  src/libs/ReportUtils.js
Labels: CP Staging

#16480 Update version to 1.2.88-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16482 🍒 Cherry pick PR #16441 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/ReportUtils.js
Labels: automerge

#16487 Update version to 1.2.89-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16535 Update version to 1.2.90-0 on staging
  android/app/build.gradle
  assets/emojis.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/Composer/index.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/Form.js
  src/components/Modal/BaseModal.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/actions/Modal.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
Labels: automerge

#16537 Update version to 1.2.90-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16538 Update version to 1.2.90-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16542 Update version to 1.2.90-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/Form.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/libs/ReimbursementAccountUtils.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
Labels: automerge

#16544 Update version to 1.2.90-3 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#15942 Make optimistic reportActions appear last
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  tests/unit/ReportActionsUtilsTest.js
Labels: Ready To Build

#16546 Update version to 1.2.90-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16547 Update version to 1.2.90-4 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  tests/unit/ReportActionsUtilsTest.js
Labels: automerge

#16559 Revert "Make optimistic reportActions appear last"
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  tests/unit/ReportActionsUtilsTest.js
Labels: CP Staging

#16565 Update version to 1.2.90-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16540 [No QA] Update xcode version
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  ios/NewExpensify.xcodeproj/project.pbxproj
Labels: CP Staging

#16568 Update version to 1.2.90-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16570 🍒 Cherry pick PR #16540 to staging 🍒
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16616 Update version to 1.2.90-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16617 🍒 Cherry pick PR #16607 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
Labels: automerge

#16628 Update version to 1.2.90-7 on production
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  assets/emojis.js
  contributingGuides/CONTRIBUTING.md
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ONYXKEYS.js
  src/components/Composer/index.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/Form.js
  src/components/Modal/BaseModal.js
  src/components/TextInput/baseTextInputPropTypes.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/ReimbursementAccountUtils.js
  src/libs/actions/Modal.js
  src/libs/actions/Report.js
  src/libs/actions/Session/index.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
Labels: automerge

#16630 Update version to 1.2.91-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16659 Revert "Emoji search on mobile"
  src/CONST.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/KeyboardAvoidingView/index.android.js
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/Modal/BaseModal.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: CP Staging

#16661 Update version to 1.2.91-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16662 🍒 Cherry pick PR #16659 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPicker.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/KeyboardAvoidingView/index.android.js
  src/components/KeyboardAvoidingView/index.ios.js
  src/components/Modal/BaseModal.js
  src/styles/StyleUtils.js
  src/styles/styles.js
Labels: automerge

#16684 Update version to 1.2.91-1 on production
  .github/actions/composite/setupNode/action.yml
  android/app/build.gradle
  config/proxyConfig.js
  config/webpack/webpack.dev.js
  docs/_layouts/default.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONFIG.js
  src/CONST.js
  src/components/AddressSearch.js
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.js
  src/components/AttachmentCarousel/index.js
  src/components/Form.js
  src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
  src/components/Hoverable/index.js
  src/components/Icon/index.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/OptionRow.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/Reactions/ReactionTooltipContent.js
  src/components/ReportActionItem/IOUQuote.js
  src/components/ReportTransaction.js
  src/components/TestToolMenu.js
  src/components/Tooltip/index.js
  src/components/UnreadActionIndicator.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ApiUtils.js
  src/libs/Notification/LocalNotification/BrowserNotifications.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/pages/DetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/FloatingMessageCounter/index.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/Profile/PronounsPage.js
  src/pages/signin/LoginForm.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/ReportActionsUtilsTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  web/proxy.js
Labels: automerge

#16698 Update version to 1.2.92-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16700 Update version to 1.2.92-0 on staging
  .eslintrc.js
  android/app/build.gradle
  contributingGuides/STYLE.md
  docs/_includes/footer.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/chat_expensify_adhoc.mobileprovision.gpg
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/AvatarWithIndicator.js
  src/components/BlockingViews/BlockingView.js
  src/components/EmojiPicker/CategoryShortcutButton.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/MenuItem.js
  src/components/Picker/Picker.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/index.native.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/ScreenWrapper/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/UserUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/stories/Button.stories.js
  src/stories/Picker.stories.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#16360 Migrate to Airship v15.2.0
  __mocks__/@react-native-camera-roll/camera-roll.js
  __mocks__/@ua/react-native-airship.js
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  android/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/libs/Notification/PushNotification/index.native.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.ios.js
  src/libs/fileDownload/index.android.js
  src/libs/fileDownload/index.ios.js
Labels: InternalQA, Ready To Build

#16554 fix: show workspace name in search preview for policy expense chats
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
Labels: CP Staging

#16741 Update version to 1.2.92-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16778 Fix propsRef initialization in native PlaidLink component
  src/components/PlaidLink/index.native.js
Labels: CP Staging

#16780 Update version to 1.2.92-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16784 Update version to 1.2.92-2 on production
  .eslintrc.js
  android/app/build.gradle
  contributingGuides/STYLE.md
  docs/_includes/footer.html
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/chat_expensify_adhoc.mobileprovision.gpg
  package-lock.json
  package.json
  src/ROUTES.js
  src/components/AddressSearch.js
  src/components/AvatarCropModal/AvatarCropModal.js
  src/components/AvatarWithIndicator.js
  src/components/BlockingViews/BlockingView.js
  src/components/EmojiPicker/CategoryShortcutButton.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/MenuItem.js
  src/components/Picker/Picker.js
  src/components/PlaidLink/index.js
  src/components/PlaidLink/index.native.js
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/EmojiReactionBubble.js
  src/components/ScreenWrapper/index.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ErrorUtils.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/Navigation.js
  src/libs/Navigation/linkingConfig.js
  src/libs/OptionsListUtils.js
  src/libs/PolicyUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
  src/libs/UserUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/libs/actions/User.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Profile/Contacts/AddSecondaryLoginPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodsPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/pages/workspace/WorkspaceSettingsPage.js
  src/stories/Button.stories.js
  src/stories/Picker.stories.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
Labels: automerge

#16785 Update version to 1.2.93-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16786 Update version to 1.2.93-0 on staging
  __mocks__/@react-native-camera-roll/camera-roll.js
  __mocks__/@ua/react-native-airship.js
  __mocks__/urbanairship-react-native.js
  android/app/build.gradle
  android/build.gradle
  desktop/main.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/CalendarPicker/index.js
  src/components/HTMLEngineProvider/applyStrikethrough/index.js
  src/components/HTMLEngineProvider/applyStrikethrough/index.native.js
  src/components/OptionRow.js
  src/components/ReportWelcomeText.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Notification/PushNotification/index.native.js
  src/libs/ReportUtils.js
  src/libs/UnreadIndicatorUpdater/updateUnread/index.ios.js
  src/libs/fileDownload/index.android.js
  src/libs/fileDownload/index.ios.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionItemMessage.js
  src/styles/getTooltipStyles.js
  tests/unit/ReportUtilsTest.js
Labels: automerge

#16789 Update version to 1.2.93-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16790 Update version to 1.2.93-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Reactions/AddReactionBubble.js
  src/components/Reactions/MiniQuickEmojiReactions.js
Labels: automerge

#16791 Update version to 1.2.93-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16792 Update version to 1.2.93-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16798 Update version to 1.2.93-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/BigNumberPad.js
  src/pages/iou/steps/IOUAmountPage.js
Labels: automerge

#16802 Update version to 1.2.93-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#16803 Update version to 1.2.93-4 on staging
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/createOrUpdateStagingDeploy.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/libs/GithubUtils.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  tests/unit/GithubUtilsTest.js
  tests/unit/createOrUpdateStagingDeployTest.js
Labels: automerge
