Repository Expensify/App, pull requests merged in 2023-07, with the labels that each got.

#20708 Migrate SignInPage to function component ... again
  src/components/OnyxProvider.js
  src/hooks/usePermissions.js
  src/pages/signin/SignInPage.js
Labels: Ready To Build

#22265 Fix - magic input loses focus when clicked on didn't receive magic code
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
Labels: Ready To Build

#20828 feat: support Spanish emojis
  assets/emojis/common.js
  assets/emojis/en.js
  assets/emojis/es.js
  assets/emojis/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
  src/components/Reactions/MiniQuickEmojiReactions.js
  src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
  src/components/Reactions/ReportActionItemReactions.js
  src/libs/EmojiTrie.js
  src/libs/EmojiUtils.js
  src/libs/actions/Report.js
  src/pages/home/report/ReactionList/HeaderReactionList.js
  src/pages/home/report/ReactionList/PopoverReactionList.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  tests/unit/EmojiTest.js
Labels: Ready To Build

#22775 Bump Onyx version to 1.0.51
  package-lock.json
  package.json
Labels: Ready To Build

#22801 Update the Android app name to 'Expensify Chat'
  android/app/src/main/res/values/strings.xml
Labels: Ready To Build

#22590 Send isDevRequest parameter with FlagComment
  src/libs/actions/Report.js
Labels: InternalQA

#22847 Adding Supportal Access v0
  src/App.js
  src/libs/Network/NetworkStore.js
  src/libs/Network/enhanceParameters.js
  src/libs/Request.js
  src/libs/actions/Session/index.js
Labels: Internal, InternalQA

#19509 persist: true -> retry: true
  src/libs/Network/index.js
  tests/unit/APITest.js
  tests/unit/NetworkTest.js
  tests/unit/RequestTest.js
Labels: Ready To Build

#22836 Fix: Attachments not shown for sender, stuck at 'Uploading attachment...'
  src/libs/actions/Report.js
Labels: Ready To Build

#23155 Revert Android app name to 'New Expensify'
  android/app/src/main/res/values/strings.xml
Labels: Ready To Build

#16723 Apple sign-in
  assets/images/signIn/apple-logo.svg
  assets/images/signIn/google-logo.svg
  contributingGuides/TESTING_APPLE_GOOGLE_SIGNIN.md
  ios/NewExpensify/Chat.entitlements
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.js
  src/Expensify.js
  src/ROUTES.js
  src/components/Icon/Expensicons.js
  src/components/SignInButtons/AppleAuthWrapper/index.ios.js
  src/components/SignInButtons/AppleAuthWrapper/index.js
  src/components/SignInButtons/AppleSignIn/index.android.js
  src/components/SignInButtons/AppleSignIn/index.desktop.js
  src/components/SignInButtons/AppleSignIn/index.ios.js
  src/components/SignInButtons/AppleSignIn/index.website.js
  src/components/SignInButtons/GetUserLanguage.js
  src/components/SignInButtons/IconButton.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/PublicScreens.js
  src/libs/Navigation/AppNavigator/index.js
  src/libs/Navigation/linkingConfig.js
  src/libs/actions/Session/index.js
  src/pages/signin/AppleSignInDesktopPage/index.js
  src/pages/signin/AppleSignInDesktopPage/index.website.js
  src/pages/signin/LoginForm.js
  src/pages/signin/SignInPage.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/ThirdPartySignInPage.js
  src/styles/styles.js
  tests/ui/UnreadIndicatorsTest.js
  web/index.html
Labels: Design, Ready To Build

#23110 Fix the settled preview message
  src/CONST.js
  src/languages/en.js
  src/languages/es.js
  src/libs/ReportUtils.js
Labels: InternalQA

#23061 Implement animated WorkspacesListPage and LoungeAccessPage
  assets/animations/ExpensifyLounge.json
  assets/animations/WorkspacePlanet.json
  src/CONST.js
  src/SCREENS.js
  src/components/Avatar.js
  src/components/FeatureList.js
  src/components/IllustratedHeaderPageLayout.js
  src/components/LottieAnimations.js
  src/components/MagicCodeInput.js
  src/components/MenuItem.js
  src/components/MenuItemWithTopDescription.js
  src/components/ScreenWrapper/index.js
  src/components/ScreenWrapper/propTypes.js
  src/hooks/useNetwork.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/pages/settings/Profile/LoungeAccessPage.js
  src/pages/workspace/WorkspacePageWithSections.js
  src/pages/workspace/WorkspacesListPage.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: Ready To Build

#23749 [NoQA] Perf/onyx upgrade use cache directly
  package-lock.json
  package.json
  src/libs/actions/QueuedOnyxUpdates.js
  tests/unit/EmojiTest.js
  tests/unit/SidebarOrderTest.js
Labels: Ready To Build

#23589 Migrate DragNDrop
  .storybook/preview.js
  .storybook/webpack.config.js
  __mocks__/@react-navigation/native/index.js
  src/CONST.js
  src/components/DragAndDrop/Consumer/dragAndDropConsumerPropTypes.js
  src/components/DragAndDrop/Consumer/index.js
  src/components/DragAndDrop/Consumer/index.native.js
  src/components/DragAndDrop/DropZone/index.js
  src/components/DragAndDrop/DropZone/index.native.js
  src/components/DragAndDrop/NoDropZone/index.js
  src/components/DragAndDrop/Provider/dragAndDropProviderPropTypes.js
  src/components/DragAndDrop/Provider/index.js
  src/components/DragAndDrop/Provider/index.native.js
  src/components/DragAndDrop/dragAndDropPropTypes.js
  src/components/DragAndDrop/index.js
  src/components/DragAndDrop/index.native.js
  src/hooks/useDragAndDrop.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportDropUI.js
  src/pages/home/report/ReportFooter.js
  src/stories/DragAndDrop.stories.js
  src/styles/styles.js
  src/styles/themes/default.js
Labels: Ready To Build

#23776 Upload optimized lottie JSON files
  assets/animations/ExpensifyLounge.json
  assets/animations/Fireworks.json
  assets/animations/Hands.json
  assets/animations/PreferencesDJ.json
  assets/animations/ReviewingBankInfo.json
  assets/animations/WorkspacePlanet.json
Labels: Ready To Build
