Repository Expensify/App, pull requests merged in 2023-11, with the labels that each got.

#30019 Allow requesting money when expensify account owns workspace
  src/libs/ReportUtils.js
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js
  src/pages/tasks/TaskShareDestinationSelectorModal.js
Labels: InternalQA

#30263 perf: improve performance when opening Search with cmd+k
  src/pages/SearchPage.js
Labels: Ready To Build

#28469 perf: refactor heavy operations when user starts to type
  src/components/LHNOptionsList/OptionRowLHNData.js
  src/libs/OptionsListUtils.js
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.ts
  src/libs/UnreadIndicatorUpdater/index.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js
  src/pages/home/sidebar/SidebarLinksData.js
Labels: Ready To Build

#29169 [NoQA] Bump onyx - Fix out of order updates
  package-lock.json
  package.json
Labels: Ready To Build

#29561 Composer - optimise rendering behaviour for onKeyPress & onSubmit
  src/hooks/useDebounce.js
  src/pages/home/report/ReportActionCompose/SuggestionMention.js
Labels: Ready To Build

#30875 Disable logs for staging and production native apps
  babel.config.js
Labels: InternalQA

#30811 Update and rename Everything-About-Chat.md to get-to-know-expensify-chat
  docs/articles/new-expensify/getting-started/chat/Everything-About-Chat.md
  docs/articles/new-expensify/getting-started/chat/get-to-know-expensify-chat
Labels: Daily

#30864 fixes the issue #29379
  src/components/EmojiPicker/EmojiPickerButton.js
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js
Labels: Ready To Build

#30424 add selectTextOnFocus for GooglePlacesAutoComplete
  src/components/AddressSearch/index.js
Labels: Ready To Build

#26498 Improve goBack function
  src/components/InvertedFlatList/BaseInvertedFlatList.js
  src/libs/Navigation/Navigation.js
  src/libs/actions/IOU.js
  tests/actions/IOUTest.js
Labels: Ready To Build

#30094 Chrome mWeb - scan button provides no feedback
  src/components/withTabAnimation.js
  src/hooks/useTabNavigatorFocus/index.js
  src/libs/DomUtils/index.native.ts
  src/libs/DomUtils/index.ts
  src/pages/iou/ReceiptSelector/NavigationAwareCamera/index.js
  src/pages/iou/ReceiptSelector/NavigationAwareCamera/index.native.js
  src/pages/iou/ReceiptSelector/index.js
  src/pages/iou/ReceiptSelector/index.native.js
Labels: Ready To Build

#31144 fix: ensure pusher events are processed in the same order they were received
  src/libs/actions/OnyxUpdates.ts
Labels: Ready To Build

#31457 fix "Chat - Keyboard is displayed on header menu screen after sending a file larger than 24 MB"
  src/components/EmojiPicker/EmojiPickerButton.js
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js
Labels: StagingDeployCash

#28408 Add join and leave to user created rooms
  src/languages/en.ts
  src/languages/es.ts
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
Labels: Ready To Build

#31642 Revert "Migrate LHNOptionsList to Flashlist"
  src/components/LHNOptionsList/LHNOptionsList.js
  src/pages/home/sidebar/SidebarLinks.js
  src/styles/styles.ts
  tests/perf-test/SidebarLinks.perf-test.js
Labels: Ready To Build

#31663 [CP Staging] Fix notification click through
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js
Labels: Ready To Build

#31711 [perf] Migrate LHNOptionList to FlashList
  src/components/LHNOptionsList/LHNOptionsList.js
  src/pages/home/sidebar/SidebarLinks.js
  src/styles/styles.ts
  tests/perf-test/SidebarLinks.perf-test.js
Labels: Ready To Build

#31102 [TS migration] Migrate 'Button' component to TypeScript
  src/components/Button/index.tsx
  src/components/Button/validateSubmitShortcut/index.js
  src/components/Button/validateSubmitShortcut/index.native.js
  src/components/Button/validateSubmitShortcut/index.native.ts
  src/components/Button/validateSubmitShortcut/index.ts
  src/components/Button/validateSubmitShortcut/types.ts
  src/hooks/useKeyboardShortcut.ts
Labels: Ready To Build

#31824 [TS Migration] Update EnvironmentContext default value
  src/components/EnvironmentBadge.tsx
  src/components/ExpensifyWordmark.tsx
  src/components/withEnvironment.tsx
  src/hooks/useEnvironment.ts
  src/styles/StyleUtils.ts
Labels: Ready To Build

#32198 Always publish in desktop-build.sh script
  scripts/build-desktop.sh
Labels: Ready To Build

#32157 Create Draft reports optimistically
  src/CONST.ts
  src/components/MoneyReportHeader.js
  src/components/ReportActionItem/ReportPreview.js
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.js
Labels: Ready To Build

#31776 Optimization of mobile startup time
  src/CONST.ts
  src/components/Icon/BankIcons.ts
  src/libs/EmojiTrie.ts
  src/libs/EmojiUtils.ts
  src/libs/PaymentUtils.ts
  src/types/onyx/AccountData.ts
  src/types/onyx/Bank.ts
  src/types/onyx/Fund.ts
Labels: Ready To Build
