Repository Expensify/App, pull requests merged in 2023-06, with the labels that each got.

#19925 Update version to 1.3.21-2 on production
  .gitignore
  android/app/build.gradle
  assets/images/flag.svg
  assets/images/flag_level_01.svg
  assets/images/flag_level_02.svg
  assets/images/flag_level_03.svg
  dangerfile.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/ROUTES.js
  src/components/AttachmentCarousel/index.js
  src/components/AttachmentModal.js
  src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js
  src/components/Composer/index.js
  src/components/EmojiPicker/EmojiSkinToneList.js
  src/components/ExceededCommentLength.js
  src/components/Form.js
  src/components/Icon/Expensicons.js
  src/components/ImageView/index.js
  src/components/MagicCodeInput.js
  src/components/MenuItem.js
  src/components/ReportActionItem/IOUPreview.js
  src/components/ReportTransaction.js
  src/components/menuItemPropTypes.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/linkingConfig.js
  src/libs/ReportUtils.js
  src/libs/actions/IOU.js
  src/libs/actions/Report.js
  src/libs/isReportMessageAttachment.js
  src/pages/FlagCommentPage.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessage.js
  src/pages/home/report/ReportActionItemParentAction.js
  src/pages/home/report/ReportActionItemSingle.js
  src/pages/home/report/ReportActionsList.js
  src/pages/iou/IOUTransactions.js
  src/pages/signin/ChangeExpensifyLoginLink.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/tasks/NewTaskPage.js
  src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js
  src/styles/StyleUtils.js
  src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
  src/styles/getNavigationModalCardStyles/index.website.js
  src/styles/styles.js
  tests/perf-test/SidebarLinks.perf-test.js
  tests/utils/LHNTestUtils.js
Labels: automerge

#19926 Update version to 1.3.22-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#19927 Update version to 1.3.22-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/Tooltip/index.js
  src/components/ValidateCode/ValidateCodeModal.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/Session/index.js
  src/pages/ReportDetailsPage.js
  src/pages/ValidateLoginPage/index.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/stories/CheckboxWithLabel.stories.js
Labels: automerge

#20015 [No QA]Speed up deploys by turning on large runners
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20026 Update version to 1.3.22-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20027 🍒 Cherry pick PR #20015 to staging 🍒
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20039 Update version to 1.3.22-1 on production
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/CheckboxWithLabel.js
  src/components/Tooltip/index.js
  src/components/ValidateCode/ValidateCodeModal.js
  src/libs/ReportActionsUtils.js
  src/libs/actions/Session/index.js
  src/pages/ReportDetailsPage.js
  src/pages/ValidateLoginPage/index.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/stories/CheckboxWithLabel.stories.js
Labels: automerge

#20040 Update version to 1.3.23-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20041 Update version to 1.3.23-0 on staging
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  dangerfile.js
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/HeaderWithCloseButton.js
  src/components/ImageWithSizeCalculation.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/MagicCodeInput.js
  src/components/MoneyRequestHeader.js
  src/components/PinButton.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/libs/Permissions.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionsList.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
  src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
  tests/actions/ReportTest.js
Labels: automerge

#20043 Update version to 1.3.23-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20044 Update version to 1.3.23-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CalendarPicker/index.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/Pressable/PressableWithFeedback.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge

#20046 Update version to 1.3.23-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20047 Update version to 1.3.23-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20048 Update version to 1.3.23-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20049 Update version to 1.3.23-3 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/settings/Security/TwoFactorAuth/CodesPage.js
  src/pages/settings/Security/TwoFactorAuth/VerifyPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
  tests/unit/ValidationUtilsTest.js
Labels: automerge

#20056 [No-QA]Use large runners for deploys
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20057 Update version to 1.3.23-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20058 🍒 Cherry pick PR #20056 to staging 🍒
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, Engineering, Hourly

#20096 Try to use `labels:` to get large runner to start
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20101 Update version to 1.3.23-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20103 🍒 Cherry pick PR #20096 to staging 🍒
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20104 [No QA]Revert Ubuntu large runner testing
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20108 Update version to 1.3.23-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20110 🍒 Cherry pick PR #20104 to staging 🍒
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20155 Add null check before react effect
  src/components/LHNOptionsList/OptionRowLHN.js
Labels: CP Staging

#20160 Update version to 1.3.23-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20161 🍒 Cherry pick PR #20155 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/LHNOptionsList/OptionRowLHN.js
Labels: automerge

#20190 Update version to 1.3.23-7 on production
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  contributingGuides/CONTRIBUTING.md
  dangerfile.js
  fastlane/Fastfile
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/CalendarPicker/index.js
  src/components/EmojiPicker/CategoryShortcutBar.js
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/HeaderWithCloseButton.js
  src/components/ImageWithSizeCalculation.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/MagicCodeInput.js
  src/components/MoneyRequestHeader.js
  src/components/PinButton.js
  src/components/Pressable/PressableWithFeedback.js
  src/components/PressableWithSecondaryInteraction/index.js
  src/components/PressableWithSecondaryInteraction/index.native.js
  src/components/PressableWithSecondaryInteraction/pressableWithSecondaryInteractionPropTypes.js
  src/components/withWindowDimensions.js
  src/languages/en.js
  src/libs/Permissions.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/ReportDetailsPage.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ContextMenuActions.js
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js
  src/pages/home/report/ContextMenu/ReportActionContextMenu.js
  src/pages/home/report/ParticipantLocalTime.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemFragment.js
  src/pages/home/report/ReportActionsList.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
  src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/settings/Security/TwoFactorAuth/CodesPage.js
  src/pages/settings/Security/TwoFactorAuth/VerifyPage.js
  src/pages/signin/PasswordForm.js
  src/pages/signin/SignInPageLayout/SignInPageContent.js
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/utilities/spacing.js
  src/styles/variables.js
  tests/actions/ReportTest.js
  tests/unit/ValidationUtilsTest.js
Labels: automerge

#20191 Update version to 1.3.24-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20199 [No QA]Update `electron-builder` to latest to try to fix hdiutil error
  package-lock.json
  package.json
Labels: CP Staging

#20204 Update version to 1.3.24-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20205 🍒 Cherry pick PR #20199 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20210 [No QA] Fix electron notary
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  desktop/README.md
  desktop/notarize.js
  package-lock.json
  package.json
Labels: CP Staging

#20213 🍒 Cherry pick PR #20210 to staging 🍒
  .github/actions/javascript/authorChecklist/index.js
  .github/actions/javascript/awaitStagingDeploys/index.js
  .github/actions/javascript/checkDeployBlockers/index.js
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/actions/javascript/getPullRequestDetails/index.js
  .github/actions/javascript/getReleaseBody/index.js
  .github/actions/javascript/isPullRequestMergeable/index.js
  .github/actions/javascript/isStagingDeployLocked/index.js
  .github/actions/javascript/markPullRequestsAsDeployed/index.js
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/reopenIssueWithComment/index.js
  .github/actions/javascript/reviewerChecklist/index.js
  .github/actions/javascript/triggerWorkflowAndWait/index.js
  .github/actions/javascript/verifySignedCommits/index.js
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  desktop/README.md
  desktop/notarize.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20218 [No QA] Update electron-notarize package name
  desktop/notarize.js
Labels: CP Staging

#20221 Update version to 1.3.24-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20222 🍒 Cherry pick PR #20218 to staging 🍒
  android/app/build.gradle
  desktop/notarize.js
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20220 Revert PERSONAL_DETAILS_LIST Onyx changes
  src/ONYXKEYS.js
  src/components/withCurrentUserPersonalDetails.js
  src/libs/DateUtils.js
  src/libs/PersonalDetailsUtils.js
  src/libs/actions/App.js
  tests/unit/DateUtilsTest.js
Labels: CP Staging

#20224 Update version to 1.3.24-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20225 🍒 Cherry pick PR #20220 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/ONYXKEYS.js
  src/components/withCurrentUserPersonalDetails.js
  src/libs/DateUtils.js
  src/libs/PersonalDetailsUtils.js
  src/libs/actions/App.js
  tests/unit/DateUtilsTest.js
Labels: automerge

#20014 Move task reportActions onto the task report
  src/components/ReportActionItem/TaskAction.js
  src/components/ReportActionItem/TaskPreview.js
  src/components/TaskHeader.js
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/Task.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionItem.js
Labels: CP Staging

#20294 Update version to 1.3.24-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20295 🍒 Cherry pick PR #20014 to staging 🍒
  .eslintrc.js
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/AttachmentCarousel/index.js
  src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js
  src/components/DotIndicatorMessage.js
  src/components/FormHelpMessage.js
  src/components/Modal/BaseModal.js
  src/components/OptionRow.js
  src/components/ReportActionItem/TaskAction.js
  src/components/ReportActionItem/TaskPreview.js
  src/components/TaskHeader.js
  src/components/TaskSelectorLink.js
  src/languages/en.js
  src/languages/es.js
  src/libs/Localize/index.js
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/libs/actions/Task.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/ValidateLoginPage/index.js
  src/pages/ValidateLoginPage/index.website.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemMessageEdit.js
  src/pages/settings/PasswordPage.js
  src/pages/settings/Payments/AddPayPalMePage.js
  src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js
  src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js
  src/pages/signin/ResendValidationForm.js
  src/pages/signin/UnlinkLoginForm.js
  src/pages/tasks/NewTaskPage.js
  src/pages/workspace/WorkspaceMembersPage.js
  src/styles/StyleUtils.js
Labels: automerge, Engineering, Hourly

#20310 Update version to 1.3.25-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20311 Update version to 1.3.25-0 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/EmojiPicker/EmojiPickerMenuItem.js
  src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportActionCompose.js
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
Labels: automerge

#20315 Update version to 1.3.25-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20319 Update version to 1.3.25-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20291 [No QA] Use macos-13 runners for desktop builds
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20322 Update version to 1.3.25-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/components/MentionSuggestions.js
  src/styles/StyleUtils.js
  src/styles/styles.js
  src/styles/variables.js
Labels: automerge

#20327 Update version to 1.3.25-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20331 Revert "[No QA] Use macos-13 runners for desktop builds"
  .github/actionlint.yaml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20332 Update version to 1.3.25-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20329 🍒 Cherry pick PR #20291 to staging 🍒
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, Engineering, Hourly

#20355 [navigation-refactor] fix: currency and date picker selection
  src/components/CalendarPicker/index.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/pages/YearPickerPage.js
  src/pages/tasks/TaskDescriptionPage.js
  src/pages/tasks/TaskTitlePage.js
Labels: CP Staging

#20417 Update version to 1.3.25-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20419 🍒 Cherry pick PR #20355 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/CalendarPicker/index.js
  src/libs/Navigation/Navigation.js
  src/libs/ReportUtils.js
  src/pages/YearPickerPage.js
  src/pages/tasks/TaskDescriptionPage.js
  src/pages/tasks/TaskTitlePage.js
Labels: automerge

#20418 [No QA] Skip reassure tests for OSBotify
  .github/workflows/reassurePerformanceTests.yml
Labels: CP Staging

#20425 🍒 Cherry pick PR #20418 to staging 🍒
  .github/workflows/reassurePerformanceTests.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, Engineering, Hourly

#20421 Add Back Button to Group IOU Details Page
  src/components/ReportActionItem/IOUPreview.js
  src/pages/iou/SplitBillDetailsPage.js
Labels: CP Staging

#20429 Update version to 1.3.25-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20430 🍒 Cherry pick PR #20421 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportActionItem/IOUPreview.js
  src/pages/iou/SplitBillDetailsPage.js
Labels: automerge

#20442 Dont hide the context menu from the LHN if Sidebar not in focus
  src/components/LHNOptionsList/OptionRowLHN.js
Labels: CP Staging

#20450 Update version to 1.3.25-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20452 🍒 Cherry pick PR #20442 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/LHNOptionsList/OptionRowLHN.js
Labels: automerge

#20464 Update version to 1.3.26-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20468 Update version to 1.3.26-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20436 [No QA] Cache node modules in GitHub Actions
  .github/actions/composite/setupNode/action.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#20553 fix: show cursor pointer for option row where no press function is given
  src/components/MoneyRequestConfirmationList.js
  src/components/OptionRow.js
  src/components/OptionsList/optionsListPropTypes.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: CP Staging

#20594 Update version to 1.3.26-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20483 Add a check for Concierge default avatar
  src/CONST.js
  src/libs/UserUtils.js
Labels: CP Staging

#20595 🍒 Cherry pick PR #20553 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestConfirmationList.js
  src/components/OptionRow.js
  src/components/OptionsList/optionsListPropTypes.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge

#20596 Update version to 1.3.26-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20598 🍒 Cherry pick PR #20483 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.js
  src/libs/UserUtils.js
Labels: automerge

#20616 Update version to 1.3.26-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20617 🍒 Cherry pick PR #20612 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/ReportWelcomeText.js
Labels: automerge

#20637 Update version to 1.3.27-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20646 Update version to 1.3.27-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20647 Update version to 1.3.27-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Composer/index.android.js
  src/components/Composer/index.ios.js
  src/components/Pressable/GenericPressable/BaseGenericPressable.js
  src/pages/home/HeaderView.js
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#20648 Update version to 1.3.27-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20651 Update version to 1.3.27-2 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20692 Update version to 1.3.27-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20693 🍒 Cherry pick PR #20677 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OnyxProvider.js
  src/components/withLocalize.js
  src/hooks/useLocalize.js
  src/hooks/usePermissions.js
  src/pages/signin/SignInPage.js
  src/pages/signin/UnlinkLoginForm.js
Labels: automerge

#20696 Update version to 1.3.27-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20697 🍒 Cherry pick PR #20695 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
  src/components/AnchorForCommentsOnly/index.js
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
  src/components/PressableWithSecondaryInteraction/index.js
Labels: automerge

#20718 Update version to 1.3.27-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20720 🍒 Cherry pick PR #20704 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/Pressable/PressableWithFeedback.js
  src/pages/home/report/ReportActionItemMessageEdit.js
Labels: automerge

#20654 Fix App does not navigate to last opened public room in small screen devices after Sign in from a public room link
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.js
  src/libs/actions/Report.js
Labels: CP Staging

#20728 Update version to 1.3.27-6 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20729 🍒 Cherry pick PR #20654 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.js
  src/libs/actions/Report.js
Labels: automerge

#20773 Update version to 1.3.27-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20779 Update version to 1.3.28-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20786 Update version to 1.3.28-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20787 Update version to 1.3.28-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/BaseMiniContextMenuItem.js
  src/libs/actions/User.js
  src/pages/ReportWelcomeMessagePage.js
Labels: automerge

#20788 Update version to 1.3.28-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20789 🍒 Cherry pick PR #20784 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge, Engineering, Hourly

#20740 fix: 20412 new user is not navigating to concierge chat after tab on link
  src/libs/Navigation/Navigation.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: CP Staging

#20795 🍒 Cherry pick PR #20740 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/Navigation/Navigation.js
  src/libs/SidebarUtils.js
  src/libs/actions/Report.js
  src/pages/home/ReportScreen.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: automerge

#20845 Fix: Wrong text color for our mention
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js
Labels: CP Staging

#20876 Update version to 1.3.28-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#20877 🍒 Cherry pick PR #20845 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js
Labels: automerge

#21023 Fix: Error message "Can't remove admin" isn't shown when selecting workspace admins
  src/pages/workspace/WorkspaceMembersPage.js
Labels: CP Staging

#21027 Update version to 1.3.29-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21028 🍒 Cherry pick PR #21023 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge

#21031 Update version to 1.3.29-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21033 🍒 Cherry pick PR #21026 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestConfirmationList.js
  src/components/MultipleAvatars.js
  src/libs/OptionsListUtils.js
  src/libs/ReportUtils.js
  src/pages/ReportParticipantsPage.js
Labels: automerge

#20951 [CP Staging] Make sure that we first check the PersonalDetails we already have before creating fake optimistic personal details
  src/libs/actions/Report.js
Labels: CP Staging

#21069 Update version to 1.3.29-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21071 🍒 Cherry pick PR #20951 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
Labels: automerge

#21030 Fix Mentions crash
  src/pages/home/report/ReportActionCompose.js
Labels: CP Staging

#21029 Fix "user is typing..." indicator - key by accountID
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportTypingIndicator.js
Labels: CP Staging, InternalQA

#21072 [Fix] New Room participants list is empty
  src/libs/actions/Report.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: CP Staging

#21089 Update version to 1.3.29-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21090 Update version to 1.3.29-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21091 🍒 Cherry pick PR #21029 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/languages/en.js
  src/languages/es.js
  src/libs/actions/PersonalDetails.js
  src/libs/actions/Report.js
  src/pages/home/report/ReportTypingIndicator.js
Labels: automerge, Engineering, Hourly

#21093 🍒 Cherry pick PR #21072 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/pages/workspace/WorkspaceNewRoomPage.js
Labels: automerge

#21096 🍒 Cherry pick PR #21030 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/home/report/ReportActionCompose.js
Labels: automerge

#21128 Update version to 1.3.29-7 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21130 🍒 Cherry pick PR #21081 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ShareCodePage.js
Labels: automerge

#21132 Update version to 1.3.29-8 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21134 🍒 Cherry pick PR #21113 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/MoneyRequestConfirmationList.js
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/libs/OptionsListUtils.js
  src/pages/iou/MoneyRequestModal.js
Labels: automerge

#21148 Fix: Search - Group chat displays blank in Search results
  src/components/OptionRow.js
Labels: CP Staging

#21151 Update version to 1.3.29-9 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21152 🍒 Cherry pick PR #21148 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/components/OptionRow.js
Labels: automerge

#21150 personalDetails.login can be missing for new accounts
  src/pages/workspace/WorkspaceMembersPage.js
Labels: CP Staging

#21164 Update version to 1.3.29-10 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21165 🍒 Cherry pick PR #21150 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/workspace/WorkspaceMembersPage.js
Labels: automerge, Engineering, Hourly

#21159 Only consider personal details with logins set in `OptionsListUtils.getOptions`
  src/libs/OptionsListUtils.js
  src/libs/actions/Task.js
Labels: CP Staging

#21166 Update version to 1.3.29-11 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21167 🍒 Cherry pick PR #21159 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/OptionsListUtils.js
  src/libs/actions/Task.js
Labels: automerge

#21170 Update version to 1.3.30-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21232 [No QA]Use `ubuntu-latest-xl` and `macos-12-xl` large runners to speed up deploys
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: CP Staging

#21250 Update version to 1.3.30-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21251 🍒 Cherry pick PR #21232 to staging 🍒
  .github/actionlint.yaml
  .github/scripts/validateActionsAndWorkflows.sh
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21263 Update version to 1.3.30-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21264 🍒 Cherry pick PR #21256 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21252 Account number fix
  src/pages/ReimbursementAccount/BankAccountManualStep.js
Labels: CP Staging

#21267 Update version to 1.3.30-3 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21269 🍒 Cherry pick PR #21252 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/ReimbursementAccount/BankAccountManualStep.js
Labels: automerge

#21265 Fix duplicate chats being created
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
Labels: CP Staging

#21272 Update version to 1.3.30-4 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21273 🍒 Cherry pick PR #21265 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
Labels: automerge

#21231 Allow DM'ing from profile even if you don't "know" the user
  src/libs/actions/Report.js
  src/pages/ProfilePage.js
Labels: CP Staging

#21274 Update version to 1.3.30-5 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21275 🍒 Cherry pick PR #21231 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/libs/actions/Report.js
  src/pages/ProfilePage.js
Labels: automerge

#21328 Update version to 1.3.31-0 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21331 Update version to 1.3.31-1 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21332 Update version to 1.3.31-1 on staging
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21335 [No QA] Update react-native-image-size
  package-lock.json
  package.json
Labels: CP Staging

#21340 Update version to 1.3.31-2 on main
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge

#21342 🍒 Cherry pick PR #21335 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
Labels: automerge
