Repository Expensify/App, pull requests merged in 2023-09, with the labels that each got.

#25989 [CP Staging] Fixing the race condition on `history.go` due to buggy queue async callbacks
  patches/@react-navigation+native+6.1.6.patch
Labels: Ready To Build

#26536 Fix - Distance Request Optimistic Data (26518)
  src/components/MoneyRequestConfirmationList.js
  src/libs/TransactionUtils.js
  src/libs/actions/IOU.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
Labels: Ready To Build

#26704 Fix displaying distance receipt images
  src/components/ReportActionItem/MoneyRequestPreview.js
  src/components/ReportActionItem/ReportActionItemImages.js
  src/components/ReportActionItem/ReportPreview.js
  src/libs/actions/IOU.js
  src/styles/styles.js
Labels: Ready To Build

#26891 Make payment flow independent on existance of report preview
  src/libs/actions/IOU.js
Labels: Ready To Build

#26890 [NO QA] Update App Review credentials/notes in TestFlight script
  fastlane/Fastfile
Labels: Ready To Build

#26215 [No QA] Rotate provisioning profiles with updated cert
  ios/chat_expensify_adhoc.mobileprovision.gpg
  ios/expensify_chat_adhoc.mobileprovision.gpg
  ios/expensify_chat_dev.mobileprovision.gpg
Labels: Ready To Build

#26856 Fix Deeplinks except chat reports are not working on web
  src/libs/Navigation/NavigationRoot.js
Labels: Ready To Build

#26295 Update checklist for cherry-picked PRs
  .github/actions/javascript/createOrUpdateStagingDeploy/index.js
  .github/actions/javascript/getDeployPullRequestList/index.js
  .github/libs/GitUtils.js
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/preDeploy.yml
Labels: InternalQA

#24245 Rename Card-Rev-Share-for-Approved-Partners.md to Card-Revenue-Share-…
  docs/articles/other/Card-Revenue-Share-for-ExpensifyApproved!-Partners.md
Labels: Daily

#26172 Add /workspaces/* path into universal_link
  .well-known/apple-app-site-association
Labels: Ready To Build

#27213 Use correct app icon colour bg for notifications
  android/app/src/development/assets/airshipconfig.properties
  android/app/src/main/assets/airshipconfig.properties
Labels: Ready To Build

#26157 Flavors support follow ups
  android/app/build.gradle
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcodeproj/xcshareddata/xcschemes/New Expensify AdHoc.xcscheme
  ios/NewExpensify.xcodeproj/xcshareddata/xcschemes/New Expensify Dev.xcscheme
  ios/NewExpensify.xcodeproj/xcshareddata/xcschemes/New Expensify.xcscheme
  ios/Podfile
  ios/Podfile.lock
  package.json
Labels: Ready To Build

#22986 Add Light Theme `light.js` and clean up `colors.js`
  .storybook/theme.js
  src/components/DeeplinkWrapper/DeeplinkRedirectLoadingIndicator.js
  src/components/DotIndicatorMessage.js
  src/components/FormHelpMessage.js
  src/components/GrowlNotification/index.js
  src/components/LHNOptionsList/OptionRowLHN.js
  src/components/MentionSuggestions.js
  src/components/MenuItem.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsListSkeletonView.js
  src/components/QRShare/index.js
  src/components/ReportActionItem/MoneyReportView.js
  src/components/ReportActionItem/MoneyRequestPreview.js
  src/components/ReportActionItem/ReportPreview.js
  src/components/ReportActionsSkeletonView/SkeletonViewLines.js
  src/components/ValidateCode/ExpiredValidateCodeModal.js
  src/components/ValidateCode/JustSignedInModal.js
  src/components/ValidateCode/ValidateCodeModal.js
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/home/HeaderView.js
  src/pages/home/report/LinkPreviewer.js
  src/pages/home/sidebar/SidebarLinks.js
  src/styles/StyleUtils.ts
  src/styles/colors.js
  src/styles/getTooltipStyles.ts
  src/styles/styles.js
  src/styles/themes/default.js
  src/styles/themes/light.js
Labels: Ready To Build

#25564 Simplify Global Create menu
  src/CONST.ts
  src/ROUTES.ts
  src/components/OptionRow.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/OptionsSelector/optionsSelectorPropTypes.js
  src/components/RoomNameInput/index.js
  src/components/RoomNameInput/index.native.js
  src/components/RoomNameInput/roomNameInputPropTypes.js
  src/components/TabSelector/TabSelector.js
  src/components/TextInput/BaseTextInput.js
  src/components/WalletStatementModal/index.js
  src/components/WalletStatementModal/index.native.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/AuthScreens.js
  src/libs/Navigation/AppNavigator/ModalStackNavigators.js
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js
  src/libs/Navigation/linkingConfig.js
  src/pages/NewChatPage.js
  src/pages/NewChatSelectorPage.js
  src/pages/NewGroupPage.js
  src/pages/SearchPage.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/iou/steps/MoneyRequestConfirmPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js
  src/pages/workspace/WorkspaceNewRoomPage.js
  src/styles/styles.js
  src/styles/variables.ts
Labels: Ready To Build

#27628 🍒 Cherry pick PR #27476 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/pages/SearchPage.js
Labels: Engineering, Hourly

#27236 perf: disable hover when scrolling on web and desktop
  src/CONST.ts
  src/components/Hoverable/hoverablePropTypes.js
  src/components/Hoverable/index.js
  src/components/InvertedFlatList/index.js
  src/components/Tooltip/index.js
  src/components/Tooltip/tooltipPropTypes.js
  src/components/UserDetailsTooltip/index.web.js
  src/pages/home/report/ReportActionItem.js
Labels: Ready To Build

#26447 Improvement: Sidebar Links Performance
  src/libs/ReportActionsUtils.js
  src/libs/ReportUtils.js
  src/libs/SidebarUtils.js
Labels: Ready To Build

#27230 Adjust tests to the batching updates feature
  jest.config.js
  jest/setupAfterEnv.js
  package-lock.json
  package.json
  src/libs/RequestThrottle.ts
  src/libs/actions/PersistedRequests.ts
  tests/README.md
  tests/actions/IOUTest.js
  tests/actions/ReportTest.js
  tests/actions/SessionTest.js
  tests/perf-test/SidebarLinks.perf-test.js
  tests/ui/UnreadIndicatorsTest.js
  tests/unit/APITest.js
  tests/unit/CurrencyUtilsTest.js
  tests/unit/DateUtilsTest.js
  tests/unit/EmojiTest.js
  tests/unit/FileUtilsTest.js
  tests/unit/IOUUtilsTest.js
  tests/unit/LocalePhoneNumberTest.js
  tests/unit/LocalizeTests.js
  tests/unit/MigrationTest.js
  tests/unit/NetworkTest.js
  tests/unit/OptionsListUtilsTest.js
  tests/unit/ReportUtilsTest.js
  tests/unit/RequestTest.js
  tests/unit/SidebarFilterTest.js
  tests/unit/SidebarOrderTest.js
  tests/unit/SidebarTest.js
  tests/unit/enhanceParametersTest.js
  tests/utils/TestHelper.js
  tests/utils/getIsUsingFakeTimers.js
  tests/utils/waitForBatchedUpdates.js
  tests/utils/waitForBatchedUpdatesWithAct.js
  tests/utils/waitForNetworkPromises.js
  tests/utils/waitForPromisesToResolve.js
  tests/utils/wrapOnyxWithWaitForBatchedUpdates.js
Labels: Ready To Build

#27844 [CP Staging] Fix typo comparing report.statusNum with CONST.REPORT.STATE_NUM
  src/libs/ReportUtils.js
Labels: InternalQA

#26727 [No QA] Prevent double translation of hint
  src/components/AddressSearch/index.js
  src/pages/iou/WaypointEditor.js
Labels: Ready To Build

#28229 Revert PR 27340
  src/components/EmojiPicker/EmojiPickerMenu/index.js
  src/components/EmojiPicker/EmojiPickerMenu/index.native.js
Labels: Ready To Build

#26772 Use initialValue in withOnyx and other optimizations for ReportScreen
  src/ONYXKEYS.ts
  src/components/ExceededCommentLength.js
  src/components/Reactions/ReportActionItemEmojiReactions.js
  src/components/ReportActionItem/TaskPreview.js
  src/components/ReportActionsSkeletonView/index.js
  src/components/withLocalize.js
  src/hooks/useReportScrollManager/index.js
  src/hooks/useReportScrollManager/index.native.js
  src/libs/DateUtils.js
  src/libs/Navigation/AppNavigator/ReportScreenIDSetter.js
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.js
  src/libs/Navigation/NavigationRoot.js
  src/libs/actions/Policy.js
  src/libs/actions/Report.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/ReportScreenContext.js
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportFooter.js
  src/pages/home/report/ReportTypingIndicator.js
  src/pages/home/report/withReportAndReportActionOrNotFound.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/reportMetadataPropTypes.js
  src/pages/reportPropTypes.js
  src/types/onyx/Report.ts
  src/types/onyx/ReportMetadata.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#27748 Move all header buttons to overflow menu
  assets/images/chatbubbles.svg
  assets/images/google-meet.svg
  assets/images/zoom-icon.svg
  src/components/Icon/Expensicons.js
  src/components/PopoverMenu/index.js
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ReportUtils.js
  src/libs/actions/Report.js
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/settings/Report/NotificationPreferencePage.js
Labels: Ready To Build

#28236 Refactor/16232/migration enable payments page to function component
  src/pages/EnablePayments/EnablePaymentsPage.js
Labels: InternalQA

#28447 🍒 Cherry pick PR #28433 to staging 🍒
  android/app/build.gradle
  ios/NewExpensify/Info.plist
  ios/NewExpensifyTests/Info.plist
  package-lock.json
  package.json
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/pages/EnablePayments/EnablePaymentsPage.js
  src/pages/EnablePayments/TermsPage/ShortTermsForm.js
  src/pages/EnablePayments/TermsStep.js
  src/pages/EnablePayments/userWalletPropTypes.js
  src/types/onyx/UserWallet.ts
Labels: Engineering, Hourly
