Repository Expensify/App, pull requests merged in 2024-09, with the labels that each got.

#48339 [NoQA] feat: bump flashlist to newest version and remove unnecessary patches
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@shopify+flash-list++recyclerlistview+4.2.0.patch
  patches/@shopify+flash-list+1.6.3.patch
Labels: Ready To Build

#48067 chore: bump formatJS libraries
  package-lock.json
  package.json
Labels: Ready To Build

#48344 [NoQA] feat: bump document-picker to newest version and remove unnecessary p…
  __mocks__/react-native-document-picker.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-document-picker+9.1.1.patch
  src/components/AttachmentPicker/index.native.tsx
Labels: Ready To Build

#47991 Fix bugs connected to changed modal logic
  src/components/AttachmentModal.tsx
  src/components/AvatarWithImagePicker.tsx
  src/components/ButtonWithDropdownMenu/index.tsx
  src/components/PopoverMenu.tsx
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/actions/Modal.ts
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/iou/request/step/IOURequestStepWaypoint.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
Labels: Ready To Build

#47478 fix: Message and Notification Swapping in IOU
  src/libs/Network/SequentialQueue.ts
Labels: Ready To Build

#48428 Fix: iOS chat view to be hidden if the user clicks away/navigate to two screens or more.
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#47738 iOS: Enable App Groups
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/NewExpensifyDebugAdHoc.entitlements
  ios/NewExpensify/NewExpensifyDebugDevelopment.entitlements
  ios/NewExpensify/NewExpensifyDebugProduction.entitlements
  ios/NewExpensify/NewExpensifyReleaseAdHoc.entitlements
  ios/NewExpensify/NewExpensifyReleaseDevelopment.entitlements
  ios/NewExpensify/NewExpensifyReleaseProduction.entitlements
Labels: Ready To Build

#47827 Add CSV import flow to Categories page
  assets/images/spreadsheet-computer.svg
  assets/images/table.svg
  package-lock.json
  package.json
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Button/index.tsx
  src/components/ButtonWithDropdownMenu/index.tsx
  src/components/ButtonWithDropdownMenu/types.ts
  src/components/FilePicker/index.native.tsx
  src/components/FilePicker/index.tsx
  src/components/FilePicker/types.ts
  src/components/Icon/Expensicons.ts
  src/components/ImportColumn.tsx
  src/components/ImportSpreadsheet.tsx
  src/components/ImportSpreadsheetColumns.tsx
  src/components/MenuItem.tsx
  src/components/OfflineWithFeedback.tsx
  src/components/PopoverMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/ImportCategoriesSpreadsheet.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/ImportSpreadsheet.ts
  src/libs/actions/Policy/Category.ts
  src/libs/importSpreadsheetUtils.ts
  src/pages/iou/ReceiptDropUI.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/workspace/categories/ImportCategoriesPage.tsx
  src/pages/workspace/categories/ImportedCategoriesPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
  src/styles/utils/index.ts
  src/styles/utils/spacing.ts
  src/types/onyx/ImportedSpreadsheet.ts
  src/types/onyx/index.ts
  vendor/xlsx-0.20.3.tgz
Labels: Ready To Build

#48413 feat: bump react-native-svg to newest version and remove unnecessary …
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-svg+15.4.0+001+rn75-delegate.patch
Labels: Ready To Build

#48151 [NoQA] Perf: getStateFromPath config calculations caching
  patches/@react-navigation+core+6.4.11+001+getStateFromPath-getPathFromState-configs-caching.patch
Labels: Ready To Build

#48510 [FIX] "iOS - Composer - Add attachment modal is hidden behind the keyboard"
  src/components/PopoverMenu.tsx
Labels: Ready To Build

#48233 Bump ruby version
  .github/actions/composite/buildAndroidE2EAPK/action.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: Ready To Build

#48169 [NoQa] Bump react native pager view
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-pager-view+6.3.4+001+add-view.patch
  patches/react-native-pager-view+6.3.4+002+rn-75-fixes.patch
  patches/react-native-pager-view+6.3.4+003+position-absolute.patch
  patches/react-native-pager-view+6.3.4+004+hybrid-app.patch
Labels: Ready To Build

#48514 add check for identical src and dest urls
  .github/scripts/verifyRedirect.sh
Labels: InternalQA

#48235 [No QA] Bump setup-java to v4
  .github/actions/composite/buildAndroidE2EAPK/action.yml
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#48539 [CP Staging] fix undefined is displayed for GL code
  src/pages/workspace/categories/ImportedCategoriesPage.tsx
Labels: Ready To Build

#48629 [CP Staging] [FIX] Categories - GL code data disappears after importing same file that does not have GL code
  src/pages/workspace/categories/ImportedCategoriesPage.tsx
Labels: Ready To Build

#48008 Attendee Tracking: Created AttendeeSelectionPage
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/IOUUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/pages/iou/request/MoneyRequestAttendeeSelector.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepAttendees.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/iou/request/step/withWritableReportOrNotFound.tsx
  src/pages/workspace/accounting/qbo/advanced/QuickbooksAdvancedPage.tsx
  src/stories/ReportActionItemImages.stories.tsx
  src/types/onyx/IOU.ts
  src/types/onyx/OriginalMessage.ts
  src/types/onyx/Transaction.ts
  tests/actions/IOUTest.ts
  tests/unit/ViolationUtilsTest.ts
  tests/utils/collections/transaction.ts
Labels: Ready To Build

#48609 [CP Staging] Fix app crash when clicking on got it button
  src/components/ImportColumn.tsx
Labels: Ready To Build

#48575 Bold list item title by default
  src/libs/OptionsListUtils.ts
Labels: Ready To Build

#48639 [CP Staging] Revert "Revert "Revert "Consolidate options on settlement "Pay" button"""
  src/components/ButtonWithDropdownMenu/index.tsx
  src/components/ButtonWithDropdownMenu/types.ts
  src/components/KYCWall/BaseKYCWall.tsx
  src/components/MoneyRequestConfirmationList.tsx
  src/components/SettlementButton.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/pages/iou/MoneyRequestAmountForm.tsx
  src/types/onyx/OriginalMessage.ts
Labels: Ready To Build

#48708 [CP Staging] Select subcategory as the default spend category
  src/pages/workspace/categories/SpendCategorySelectorListItem.tsx
  src/pages/workspace/categories/WorkspaceCategoriesSettingsPage.tsx
Labels: Ready To Build

#47468 [OldDot Rules Migration] Expense report rules
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AmountForm.tsx
  src/components/BulletList.tsx
  src/components/Form/types.ts
  src/components/PercentageForm.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/EnablePolicyAutoApprovalOptions.ts
  src/libs/API/parameters/EnablePolicyAutoReimbursementLimit.ts
  src/libs/API/parameters/EnablePolicyDefaultReportTitle.ts
  src/libs/API/parameters/SetPolicyAutoReimbursementLimit.ts
  src/libs/API/parameters/SetPolicyAutomaticApprovalLimit.ts
  src/libs/API/parameters/SetPolicyAutomaticApprovalRate.ts
  src/libs/API/parameters/SetPolicyDefaultReportTitle.ts
  src/libs/API/parameters/SetPolicyPreventMemberCreatedTitleParams.ts
  src/libs/API/parameters/SetPolicyPreventSelfApproval.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/MoneyRequestUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/rules/ExpenseReportRulesSection.tsx
  src/pages/workspace/rules/PolicyRulesPage.tsx
  src/pages/workspace/rules/RulesAutoApproveReportsUnderPage.tsx
  src/pages/workspace/rules/RulesAutoPayReportsUnderPage.tsx
  src/pages/workspace/rules/RulesCustomNamePage.tsx
  src/pages/workspace/rules/RulesRandomReportAuditPage.tsx
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
  src/styles/utils/spacing.ts
  src/types/form/RulesAutoApproveReportsUnderModalForm.ts
  src/types/form/RulesAutoPayReportsUnderModalForm.ts
  src/types/form/RulesCustomNameModalForm.ts
  src/types/form/RulesRandomReportAuditModalForm.ts
  src/types/form/index.ts
  src/types/onyx/Policy.ts
Labels: Ready To Build

#48723 [CP Staging] Fix useResponsiveLayout bugs
  src/components/SelectionListWithModal/index.tsx
  src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx
Labels: Ready To Build

#47577 Migrate notification preference
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/libs/actions/Task.ts
  src/libs/actions/User.ts
  src/pages/ProfilePage.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/RoomInvitePage.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/settings/Report/NotificationPreferencePage.tsx
  src/pages/settings/Report/ReportSettingsPage.tsx
  src/types/onyx/Report.ts
  tests/actions/IOUTest.ts
  tests/actions/PolicyTest.ts
  tests/actions/ReportTest.ts
  tests/ui/PaginationTest.tsx
  tests/ui/UnreadIndicatorsTest.tsx
  tests/unit/OptionsListUtilsTest.ts
  tests/unit/ReportUtilsTest.ts
  tests/unit/UnreadIndicatorUpdaterTest.ts
Labels: Ready To Build

#48628 add validate code modal
  src/ONYXKEYS.ts
  src/components/ValidateCodeActionModal/ValidateCodeForm/BaseValidateCodeForm.tsx
  src/components/ValidateCodeActionModal/ValidateCodeForm/index.android.tsx
  src/components/ValidateCodeActionModal/ValidateCodeForm/index.tsx
  src/components/ValidateCodeActionModal/index.tsx
  src/components/ValidateCodeActionModal/type.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/RevealExpensifyCardDetailsParams.ts
  src/libs/actions/Card.ts
  src/libs/actions/User.ts
  src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/types/onyx/ValidateMagicCodeAction.ts
  src/types/onyx/index.ts
Labels: InternalQA, Ready To Build

#48171 [OldDot Rules Migration] Category Rules
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/WorkspaceMembersSelectionList.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/RemovePolicyCategoryReceiptsRequiredParams.ts
  src/libs/API/parameters/SetPolicyCategoryApproverParams.ts
  src/libs/API/parameters/SetPolicyCategoryDescriptionRequiredParams.ts
  src/libs/API/parameters/SetPolicyCategoryMaxAmountParams.ts
  src/libs/API/parameters/SetPolicyCategoryReceiptsRequiredParams.ts
  src/libs/API/parameters/SetPolicyCategoryTaxParams.ts
  src/libs/API/parameters/SetWorkspaceCategoryDescriptionHintParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/CategoryUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy/Category.ts
  src/pages/workspace/categories/CategoryApproverPage.tsx
  src/pages/workspace/categories/CategoryDefaultTaxRatePage.tsx
  src/pages/workspace/categories/CategoryDescriptionHintPage.tsx
  src/pages/workspace/categories/CategoryFlagAmountsOverPage.tsx
  src/pages/workspace/categories/CategoryRequireReceiptsOverPage.tsx
  src/pages/workspace/categories/CategorySettingsPage.tsx
  src/pages/workspace/categories/ExpenseLimitTypeSelector/ExpenseLimitTypeSelector.tsx
  src/pages/workspace/categories/ExpenseLimitTypeSelector/ExpenseLimitTypeSelectorModal.tsx
  src/types/form/WorkspaceCategoryDescriptionHintForm.ts
  src/types/form/WorkspaceCategoryFlagAmountsOverForm.ts
  src/types/form/index.ts
  src/types/onyx/Policy.ts
  src/types/onyx/PolicyCategory.ts
Labels: Ready To Build

#48754 [No QA] Separate build and upload Fastlane lanes
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  fastlane/Fastfile
  package.json
Labels: Ready To Build

#48780 [HybridApp] Add shortcut support in HybridApp
  src/ROUTES.ts
  src/libs/Navigation/AppNavigator/index.native.tsx
  src/libs/Navigation/AppNavigator/index.tsx
  src/libs/Navigation/Navigation.ts
Labels: Ready To Build

#48936 [fix]: Allow 0 as input and show 2 decimal card limit in members detail page
  src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
Labels: Ready To Build

#48786 Fix `WalletPage` scrollbar
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/settings/Wallet/WalletPage/types.ts
Labels: Ready To Build

#48342 [NoQA] feat: bump expo to newest version and remove unnecessary patches
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@expo+cli+0.18.21+001+rn-75-fixes.patch
  patches/expo+51.0.31+001+hybrid-app.patch
  patches/expo+51.0.31+002+rn-75-fixes.patch
  patches/expo-av+14.0.6+002+rn-75-fixes.patch
  patches/expo-av+14.0.7+001+hybrid-app.patch
  patches/expo-image+1.12.12+001+rn-75-fixes.patch
  patches/expo-modules-autolinking+1.11.2+001+hybrid-app.patch
  patches/expo-modules-core+1.12.18+002+rn75-fixes.patch
  patches/expo-modules-core+1.12.23+001+disableViewRecycling.patch
  patches/expo-modules-core+1.12.23+002+hybrid-app.patch
Labels: Ready To Build

#47561 Bring auditor role to NewDot
  assets/images/user-eye.svg
  src/CONST.ts
  src/components/Icon/Expensicons.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/PolicyUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Policy/Member.ts
  src/libs/actions/Task.ts
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionModal.tsx
Labels: Ready To Build

#48566 [Search v2.3] [App] Implement Saved Search feature
  assets/images/bookmark.svg
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Expensicons.ts
  src/components/MenuItemList.tsx
  src/components/PopoverMenu.tsx
  src/hooks/useDeleteSavedSearch.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/DeleteSavedSearch.ts
  src/libs/API/parameters/SaveSearch.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/SearchUtils.ts
  src/libs/actions/Search.ts
  src/pages/Search/AdvancedSearchFilters.tsx
  src/pages/Search/SavedSearchRenamePage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/styles/index.ts
  src/types/form/SearchSavedSearchRenameForm.ts
  src/types/form/index.ts
  src/types/onyx/SaveSearch.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#45557 Create deel.md
  docs/articles/expensify-classic/integrations/HR-integrations/Deel.md
Labels: Daily

#48047 Fix validation code not sending on initial page load.
  src/components/ValidateAccountMessage.tsx
  src/libs/actions/User.ts
  src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.tsx
  src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx
  src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
Labels: Ready To Build

#48417 [NoQA] feat: bump react-native-pdf to newest version, remove unnecessary pat…
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-pdf+6.7.3.patch
  patches/react-native-pdf+6.7.5.patch
Labels: Ready To Build

#48410 [NoQA] feat: bump haptic-feedback, remove old patch and add new one
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-haptic-feedback+2.2.0.patch
  patches/react-native-haptic-feedback+2.3.1.patch
Labels: Ready To Build

#48870 Create Attendees item row for editing requests
  src/CONST.ts
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/libs/ModifiedExpenseMessage.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/Violations/ViolationsUtils.ts
  src/libs/actions/IOU.ts
  src/pages/iou/request/step/IOURequestStepAttendees.tsx
  tests/unit/TransactionUtilsTest.ts
Labels: Ready To Build

#47626 Add conversation styling and shortcuts for Android 🤖
  android/app/src/main/java/com/expensify/chat/MainApplication.kt
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  android/app/src/main/java/com/expensify/chat/shortcutManagerModule/ShortcutManagerModule.java
  android/app/src/main/java/com/expensify/chat/shortcutManagerModule/ShortcutManagerPackage.java
  android/app/src/main/java/com/expensify/chat/shortcutManagerModule/ShortcutManagerUtils.java
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/RCTShortcutManagerModule.h
  ios/RCTShortcutManagerModule.m
  src/libs/Notification/PushNotification/index.native.ts
  src/libs/ShortcutManager/index.ts
  src/types/modules/react-native.d.ts
Labels: Ready To Build

#47036 Fix: The pressed state of menu items uses a very dark BG color
  src/components/BaseMiniContextMenuItem.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/components/MenuItem.tsx
  src/components/OpacityView.tsx
  src/components/Pressable/PressableWithFeedback.tsx
  src/components/PressableWithSecondaryInteraction/index.tsx
  src/components/PressableWithSecondaryInteraction/types.ts
  src/components/ReportActionItem/MoneyReportView.tsx
  src/components/ReportActionItem/TripDetailsView.tsx
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/home/sidebar/AllSettingsScreen.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#49021 Add the `setupTags` task for MANAGE_TEAM choice
  src/CONST.ts
Labels: Ready To Build

#49339 [Internal QA]: Refactor ChooseTransferAccountPage to use Selection List
  src/pages/settings/Wallet/ChooseTransferAccountPage.tsx
Labels: InternalQA, Ready To Build

#45481 Debug Mode - Report and Report Actions
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AccountSwitcher.tsx
  src/components/DatePicker/index.tsx
  src/components/Form/FormProvider.tsx
  src/components/Form/types.ts
  src/components/TabSelector/TabSelector.tsx
  src/components/TestToolMenu.tsx
  src/components/TimePicker/TimePicker.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/DateUtils.ts
  src/libs/DebugUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Debug.ts
  src/libs/actions/User.ts
  src/pages/Debug/ConstantSelector.tsx
  src/pages/Debug/DateTimeSelector.tsx
  src/pages/Debug/DebugDetails.tsx
  src/pages/Debug/DebugDetailsConstantPickerPage.tsx
  src/pages/Debug/DebugDetailsDateTimePickerPage.tsx
  src/pages/Debug/DebugJSON.tsx
  src/pages/Debug/Report/DebugReportActions.tsx
  src/pages/Debug/Report/DebugReportPage.tsx
  src/pages/Debug/ReportAction/DebugReportActionCreatePage.tsx
  src/pages/Debug/ReportAction/DebugReportActionPage.tsx
  src/pages/Debug/ReportAction/DebugReportActionPreview.tsx
  src/pages/Debug/const.ts
  src/pages/ProfilePage.tsx
  src/pages/ReportDetailsPage.tsx
  src/styles/utils/spacing.ts
  src/types/form/DebugReportActionForm.ts
  src/types/form/DebugReportForm.ts
  src/types/form/index.ts
  src/types/onyx/Report.ts
  src/types/onyx/ReportAction.ts
  src/types/onyx/User.ts
  tests/unit/DebugUtilsTest.ts
Labels: Ready To Build

#49471 [CP Staging] deploy blocker fix: private personal details infinite loading
  src/pages/settings/Profile/ProfilePage.tsx
Labels: CP Staging

#48040 fix: Update Wallet and Generic Folder empty state to use lottie animations.
  assets/animations/BankVault.lottie
  assets/animations/GenericEmptyState.lottie
  assets/animations/TripsEmptyState.lottie
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/components/LottieAnimations/index.tsx
  src/pages/Search/EmptySearchView.tsx
  src/pages/Travel/ManageTrips.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
  src/styles/index.ts
  src/styles/utils/spacing.ts
Labels: Ready To Build

#48422 fix: Description review appears when distance expenses are created without description
  src/libs/TransactionUtils/index.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
Labels: Ready To Build

#48060 feat: update trips empty state view
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/TripReservationUtils.ts
  src/pages/Search/EmptySearchView.tsx
  src/pages/Travel/ManageTrips.tsx
  src/styles/index.ts
Labels: Ready To Build

#48522 fix: Use new ResolveDuplicates when approver is resolving duplicates
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestPreview/index.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/libs/API/parameters/ResolveDuplicatesParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/IOU.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
Labels: Ready To Build

#49647 [NoQA] feat: bump react-native-haptic-feedback to newest version and remove …
  __mocks__/react-native-haptic-feedback.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-haptic-feedback+2.3.1.patch
Labels: Ready To Build

#49188 Fix - Approve button not disappear after approving report offline if advanced approval set
  src/libs/NextStepUtils.ts
  src/libs/actions/IOU.ts
Labels: Ready To Build

#49748 [No QA] Update NewApp_AdHoc.mobileprovision
  ios/NewApp_AdHoc.mobileprovision.gpg
  ios/NewApp_AdHoc_Notification_Service.mobileprovision.gpg
Labels: Ready To Build

#49320 Use float instead of int for auditRate percentage. Fix incorrect params in `SetPolicyAutoReimbursementLimitParams`
  src/CONST.ts
  src/libs/API/parameters/SetPolicyAutoReimbursementLimit.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/rules/ExpenseReportRulesSection.tsx
  src/pages/workspace/rules/RulesRandomReportAuditPage.tsx
Labels: Ready To Build

#49569 Fix icon color for saved search popup menu
  assets/images/table.svg
  src/components/MenuItem.tsx
  src/components/MenuItemList.tsx
  src/components/ThreeDotsMenu/index.tsx
  src/components/ThreeDotsMenu/types.ts
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/home/sidebar/AllSettingsScreen.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Security/SecuritySettingsPage.tsx
  src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
  src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx
Labels: Ready To Build

#48415 Do not focus input after other interactions
  src/libs/willBlurTextInputOnTapOutside/index.ts
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
Labels: Ready To Build

#49759 Don't apply failure data for 460 jsonCode
  src/libs/actions/OnyxUpdates.ts
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
Labels: Ready To Build

#48258 Hide mobile Search nav button + status tabs on scrollDown, but reveal on scrollUp
  src/components/Search/SearchContext.tsx
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/SearchStatusBar.tsx
  src/components/Search/index.tsx
  src/components/Search/types.ts
  src/components/SectionList/AnimatedSectionList.tsx
  src/components/SectionList/index.android.tsx
  src/components/SectionList/index.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/index.tsx
  src/components/SelectionList/types.ts
  src/components/Skeletons/SearchRowSkeleton.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/Search/SearchSelectedNarrow.tsx
  src/pages/Search/SearchSelectionModeHeader.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#49586 Refactor NewDot and HybridApp onboarding flow
  src/Expensify.tsx
  src/components/ExplanationModal.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/hooks/useOnboardingFlow.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/actions/Report.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/Welcome/index.ts
  src/libs/hasCompletedGuidedSetupFlowSelector.ts
  src/libs/onboardingSelectors.ts
  src/styles/variables.ts
Labels: Ready To Build

#49953 Revert "fix: Use new ResolveDuplicates when approver is resolving duplicates"
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestPreview/index.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/libs/API/parameters/ResolveDuplicatesParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/IOU.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
Labels: CP Staging

#49945 Revert "Merge pull request #49172 from Expensify/georgia-fixIOUpreview"
  src/CONST.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/home/report/ReportActionsListItemRenderer.tsx
Labels: CP Staging
