Repository Expensify/App, pull requests merged in 2024-01, with the labels that each got.

#33896 Revert "Fix/26946: Reset amount when edit waypoint"
  src/CONST.ts
  src/libs/actions/IOU.js
  src/libs/actions/Transaction.ts
Labels: Ready To Build

#33900 [No QA] Set DEVELOPER_DIR for iOS only
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#32799 fix/28562: text input in the Composer disappears
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.android.js
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.js
Labels: Ready To Build

#33387 Dont show hidden notif pref in profile page
  src/pages/ProfilePage.js
Labels: Ready To Build

#33607 Fixed icon fill colors
  src/components/AddPlaidBankAccount.js
  src/components/AvatarCropModal/ImageCropView.js
  src/components/DeeplinkWrapper/DeeplinkRedirectLoadingIndicator.tsx
  src/components/MenuItem.tsx
  src/components/ValidateCode/ValidateCodeModal.tsx
  src/pages/LogInWithShortLivedAuthTokenPage.js
  src/pages/home/report/ReportDropUI.js
  src/pages/settings/Wallet/TransferBalancePage.js
Labels: Ready To Build

#34078 Revert "Android-Attachments-App crashes on uploading specific PDF"
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#33257 Refactor Hoverable component v2
  src/components/Hoverable/ActiveHoverable.tsx
  src/components/Hoverable/index.tsx
  src/components/Hoverable/types.ts
  src/components/OfflineWithFeedback.tsx
  src/components/Tooltip/BaseTooltip/index.tsx
  src/libs/ValueUtils.ts
  src/libs/mapChildrenFlat.ts
  src/libs/mergeRefs.ts
Labels: Ready To Build

#31354 perf: search transition smoother on slower devices
  src/components/LHNOptionsList/LHNOptionsList.js
  src/components/OptionsList/BaseOptionsList.js
  src/components/OptionsList/index.js
  src/components/OptionsList/index.native.js
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/pages/SearchPage.js
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
  tests/perf-test/OptionsSelector.perf-test.js
Labels: Ready To Build

#33966 Fix/33760 doubled display name on search page
  src/libs/OptionsListUtils.js
Labels: Ready To Build

#34170 [No QA] Bump NotificationServiceExtension version on deploy
  .github/actions/javascript/bumpVersion/index.js
  .github/libs/nativeVersionUpdater.js
  ios/NotificationServiceExtension/Info.plist
Labels: Ready To Build

#34040 Only show Physical Card row on Expensify Card Page if the card is in the open state
  src/pages/settings/Wallet/ExpensifyCardPage.js
Labels: InternalQA

#33605 fix: treat certain US numbers as invalid
  .eslintrc.js
  src/libs/LocalePhoneNumber.ts
  src/libs/LoginUtils.ts
  src/libs/OptionsListUtils.js
  src/libs/PhoneNumber.ts
  src/libs/ValidationUtils.ts
  src/pages/DetailsPage.js
  src/pages/EnablePayments/AdditionalDetailsStep.js
  src/pages/ProfilePage.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/settings/Wallet/Card/GetPhysicalCardPhone.js
  src/pages/signin/LoginForm/BaseLoginForm.js
  tests/unit/PhoneNumberTest.js
Labels: Ready To Build

#33055 perf: optimise transition on Desktop when click on start chat
  src/components/Button/index.tsx
  src/components/PopoverMenu.tsx
  src/components/SelectionList/BaseSelectionList.js
  src/hooks/useActiveElement/index.native.ts
  src/hooks/useActiveElement/types.ts
  src/hooks/useActiveElementRole/index.native.ts
  src/hooks/useActiveElementRole/index.ts
  src/hooks/useActiveElementRole/types.ts
  src/pages/NewChatPage.js
Labels: Ready To Build

#33841 Fix OnyxTab Navigator performance issues on web
  src/libs/Navigation/OnyxTabNavigator.tsx
  src/libs/Navigation/OnyxTabNavigatorConfig/index.ts
  src/libs/Navigation/OnyxTabNavigatorConfig/index.website.ts
Labels: Ready To Build

#30605 Reopened/Fix: User experienced big delay when posting the messages
  src/libs/DateUtils.ts
  src/libs/HttpUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Network.ts
  src/libs/actions/Report.ts
  src/types/onyx/Network.ts
Labels: Ready To Build

#31558 chore: Update React Native to 0.73.2
  .github/actions/javascript/authorChecklist/index.js
  Gemfile
  Gemfile.lock
  __mocks__/react-native-webview.js
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/expensify/chat/ReactNativeFlipper.java
  android/app/src/main/java/com/expensify/chat/MainActivity.java
  android/app/src/main/java/com/expensify/chat/MainActivity.kt
  android/app/src/main/java/com/expensify/chat/MainApplication.java
  android/app/src/main/java/com/expensify/chat/MainApplication.kt
  android/app/src/release/java/com/expensify/chat/ReactNativeFlipper.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  babel.config.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/AppDelegate.mm
  ios/NewExpensify/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@onfido+react-native-sdk+8.3.0.patch
  patches/@react-native+virtualized-lists+0.72.8.patch
  patches/expo-image+1.10.1+001+applyFill.patch
  patches/expo-image+1.10.1+002+TintFix.patch
  patches/react-native+0.72.4+001+initial.patch
  patches/react-native+0.72.4+005+fix-boost-dependency.patch
  patches/react-native+0.73.2+001+NumberOfLines.patch
  patches/react-native+0.73.2+001+initial.patch
  patches/react-native-vision-camera+2.16.2.patch
  src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.js
  src/components/EnvironmentBadge.tsx
  src/libs/Performance.tsx
  src/types/modules/react-native.d.ts
  tests/perf-test/OptionsSelector.perf-test.js
  tests/perf-test/SelectionList.perf-test.js
Labels: Ready To Build

#34155 Decrease line height for a message sender
  src/styles/index.ts
Labels: Design

#34396 [CP Staging] Revert "Merge pull request #32422 from tienifr/fix/31503"
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/index.native.tsx
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/index.tsx
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/types.ts
  src/libs/getIsSmallScreenWidth.ts
Labels: Ready To Build

#33665 New Feature: Create the UI for Actionable Mention Whispers
  src/CONST.ts
  src/components/ReportActionItem/ActionableItemButtons.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/Report.ts
  src/pages/home/report/ReportActionItem.js
  src/types/onyx/OriginalMessage.ts
  src/types/onyx/ReportAction.ts
Labels: Ready To Build

#34588 [CP Staging] fix crash when download attachment on android 14
  patches/react-native-blob-util+0.17.3.patch
Labels: Ready To Build

#34596 [CP Staging] Revert "Bump Onyx (Fix Replay effect)"
  package-lock.json
  package.json
  tests/unit/MigrationTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: Ready To Build

#34888 [CP Staging] fix crash when download attachment in android
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#32154 Add full screen engagement modal to NewDot
  assets/images/scan.svg
  src/CONST.ts
  src/ONYXKEYS.ts
  src/components/AttachmentModal.js
  src/components/HeaderWithBackButton/headerWithBackButtonPropTypes.js
  src/components/HeaderWithBackButton/index.tsx
  src/components/HeaderWithBackButton/types.ts
  src/components/Icon/Expensicons.ts
  src/components/Modal/BaseModal.tsx
  src/components/Modal/types.ts
  src/components/PurposeForUsingExpensifyModal.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/Navigators/Overlay.tsx
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Welcome.ts
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/index.native.js
  src/styles/index.ts
  src/types/onyx/IntroSelected.ts
  src/types/onyx/index.ts
  tests/unit/CalendarPickerTest.js
Labels: Ready To Build

#30968 Fix: Attachment modal is not closed when click notification
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts
  src/libs/actions/Report.ts
Labels: Ready To Build

#34995 [CP Staging] Update fastlane
  Gemfile.lock
Labels: Ready To Build

#34870 [TS Migration] Adjustments on KYCWall
  src/components/KYCWall/BaseKYCWall.tsx
  src/components/KYCWall/types.ts
  src/libs/actions/PaymentMethods.ts
Labels: InternalQA, Ready To Build

#33779 Don't treat muted reports as unread in LHN
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/pages/home/sidebar/SidebarLinksData.js
Labels: Ready To Build

#35044 [CP Staging] Fix reggression after LHNOptionsList TS migration
  src/components/LHNOptionsList/OptionRowLHN.tsx
Labels: Ready To Build

#34930 Add logging and loading checks for short lived authToken sign-ins
  src/pages/LogInWithShortLivedAuthTokenPage.tsx
  src/pages/LogOutPreviousUserPage.js
  src/pages/signin/SAMLSignInPage/index.native.js
Labels: InternalQA

#32992 [TS migration] Migrate 'Form' component to TypeScript
  src/ONYXKEYS.ts
  src/components/AmountTextInput.tsx
  src/components/Composer/index.android.tsx
  src/components/Composer/index.ios.tsx
  src/components/Composer/index.tsx
  src/components/Form/FormContext.js
  src/components/Form/FormContext.tsx
  src/components/Form/FormProvider.js
  src/components/Form/FormProvider.tsx
  src/components/Form/FormWrapper.js
  src/components/Form/FormWrapper.tsx
  src/components/Form/InputWrapper.js
  src/components/Form/InputWrapper.tsx
  src/components/Form/errorsPropType.js
  src/components/Form/types.ts
  src/components/FormAlertWithSubmitButton.tsx
  src/components/RNTextInput.tsx
  src/components/SafeAreaConsumer/types.ts
  src/components/ScrollViewWithContext.tsx
  src/components/TextInput/BaseTextInput/index.native.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextInput/BaseTextInput/types.ts
  src/components/TextInput/index.native.tsx
  src/components/TextInput/index.tsx
  src/libs/ErrorUtils.ts
  src/libs/FormUtils.ts
  src/libs/ValidationUtils.ts
  src/libs/actions/FormActions.ts
  src/libs/actions/Plaid.ts
  src/libs/actions/ReimbursementAccount/index.js
  src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
  src/libs/actions/Report.ts
  src/pages/EditReportFieldDatePage.tsx
  src/pages/EditReportFieldTextPage.tsx
  src/pages/PrivateNotes/PrivateNotesEditPage.tsx
  src/pages/ReimbursementAccount/ACHContractStep.js
  src/pages/ReimbursementAccount/BankAccountManualStep.js
  src/pages/ReimbursementAccount/BankAccountPlaidStep.js
  src/pages/ReimbursementAccount/CompanyStep.js
  src/pages/ReimbursementAccount/ReimbursementAccountPage.js
  src/pages/ReimbursementAccount/RequestorStep.js
  src/pages/ReimbursementAccount/ValidationStep.js
  src/pages/TeachersUnite/IntroSchoolPrincipalPage.tsx
  src/pages/TeachersUnite/KnowATeacherPage.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.js
  src/types/onyx/Form.ts
  src/types/onyx/ReimbursementAccountDraft.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#31483 TextInput `numberOfLines`/`maxNumberOfLines` workaround (manually calculating `maxHeight` of TextInput
  android/settings.gradle
  ios/Podfile.lock
  patches/react-native+0.73.2+001+NumberOfLines.patch
  src/components/Composer/index.android.tsx
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#34218 perf: reduce APK size with ProGuard enabled
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/res/raw/keep.xml
Labels: Ready To Build

#34754 Fix Overflow menu from keyboard and show left-out options only
  src/libs/calculateAnchorPosition.ts
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ReportActionContextMenu.ts
Labels: Ready To Build

#33928 Fix: Duplicate phone number can be invited
  src/libs/OptionsListUtils.ts
  src/pages/RoomInvitePage.js
Labels: Ready To Build

#34624 Add filtering to the reports data in the Focus mode switch logic
  src/libs/ReportUtils.ts
  src/libs/actions/PriorityMode.ts
Labels: Ready To Build

#35272 [No QA] Bump node to 20.10.0
  .nvmrc
  package-lock.json
  package.json
Labels: Ready To Build

#34760 Fix overriden CFBundleVersion and CFBundleShortVersionString
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NotificationServiceExtension/Info.plist
Labels: Ready To Build

#34801 Bump onyx to fix replay effect (after revert)
  config/webpack/webpack.desktop.js
  jest/setup.js
  package-lock.json
  package.json
  src/ONYXKEYS.ts
  src/components/AnonymousReportFooter.tsx
  src/components/BigNumberPad.tsx
  src/components/ConfirmedRoute.tsx
  src/components/Indicator.tsx
  src/components/WalletStatementModal/types.ts
  src/libs/E2E/utils/NetworkInterceptor.ts
  src/libs/Navigation/OnyxTabNavigator.tsx
  src/libs/ReportActionsUtils.ts
  src/libs/Timers.ts
  src/libs/actions/FormActions.ts
  src/libs/actions/IOU.js
  src/libs/actions/MemoryOnlyKeys/MemoryOnlyKeys.ts
  src/libs/actions/PaymentMethods.ts
  src/libs/actions/Policy.ts
  src/libs/actions/Report.ts
  src/libs/actions/User.ts
  src/libs/migrations/RenameReceiptFilename.ts
  src/pages/GetAssistancePage.tsx
  src/pages/TeachersUnite/IntroSchoolPrincipalPage.tsx
  src/pages/TeachersUnite/KnowATeacherPage.tsx
  src/pages/workspace/WorkspacePageWithSections.tsx
  tests/unit/MigrationTest.js
  tests/unit/ReportActionsUtilsTest.js
Labels: Ready To Build

#35335 [CP Staging] Revert "Fix: Duplicate phone number can be invited"
  src/libs/OptionsListUtils.ts
  src/pages/RoomInvitePage.js
Labels: Ready To Build

#35336 Add missing `CFBundleExecutable` key and value in Info.plist
  ios/NotificationServiceExtension/Info.plist
Labels: Ready To Build

#35249 Bump up Expo SDK to 50.0.3
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-reanimated+3.6.1+001+fix-boost-dependency.patch
Labels: Ready To Build

#34872 Refactor/34411 lhn previews refactor
  src/libs/OptionsListUtils.ts
  src/libs/SidebarUtils.ts
  tests/unit/SidebarTest.js
Labels: Ready To Build

#35440 [CP Staging] fix crash on tapping enable wallet in android
  android/app/proguard-rules.pro
Labels: Ready To Build

#34505 Image Web/Desktop: Add support for http headers
  patches/react-native-web+0.19.9+005+image-header-support.patch
  src/components/Image/BaseImage.native.tsx
  src/components/Image/BaseImage.tsx
  src/components/Image/index.js
  src/components/Image/index.native.js
  src/components/Image/types.ts
  src/pages/DetailsPage.js
Labels: Ready To Build

#30168 perf: optimise composer send behaviour
  src/components/AnonymousReportFooter.tsx
  src/components/AttachmentModal.tsx
  src/components/AvatarWithDisplayName.tsx
  src/components/EmojiPicker/EmojiPickerButton.js
  src/components/ExceededCommentLength.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.js
  src/libs/PersonalDetailsUtils.ts
  src/pages/ReportDetailsPage.js
  src/pages/home/HeaderView.js
  src/pages/home/ReportScreen.js
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/composerWithSuggestionsProps.js
  src/pages/home/report/ReportActionCompose/ReportActionCompose.js
  src/pages/home/report/ReportActionCompose/SendButton.js
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.js
  src/pages/home/report/ReportActionItem.js
  src/pages/home/report/ReportActionItemCreated.tsx
  src/pages/home/report/ReportActionItemMessageEdit.tsx
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsListItemRenderer.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportFooter.js
  src/pages/home/report/ReportTypingIndicator.js
  tests/unit/ReportActionItemSingleTest.js
Labels: Ready To Build

#35511 [CP Staging] Revert "fix: changed color on splash screen"
  assets/images/new-expensify.svg
  web/index.html
Labels: Ready To Build
