Repository Expensify/App, pull requests merged in 2024-05, with the labels that each got.

#40497 Add "Connection Complete" page
  assets/images/connection-complete.svg
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Expensicons.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/ConnectionCompletePage.tsx
Labels: Ready To Build

#41218 Fix missing video action bar on Safari
  src/components/VideoPlayerPreview/index.tsx
  src/styles/index.ts
Labels: Design

#41214 Rename GPS points parameter
  src/libs/API/parameters/RequestMoneyParams.ts
  src/libs/API/parameters/TrackExpenseParams.ts
  src/libs/actions/IOU.ts
Labels: Internal

#41193 Use new `avatarURL` key for workspace avatars
  src/components/MoneyRequestConfirmationList.tsx
  src/components/WorkspaceSwitcherButton.tsx
  src/hooks/useReportIDs.tsx
  src/libs/ReportUtils.ts
  src/libs/actions/Policy.ts
  src/pages/WorkspaceSwitcherPage/index.tsx
  src/pages/home/report/ReportActionItemCreated.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/iou/request/step/IOURequestStepSendFrom.tsx
  src/pages/workspace/WorkspaceAvatar.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspaceProfileSharePage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/types/onyx/Policy.ts
  tests/utils/LHNTestUtils.tsx
  tests/utils/collections/policies.ts
Labels: Ready To Build

#41155 Fix account type name constants
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectCardPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#41234 Fixed terms visualization on mweb android
  src/components/Onfido/index.tsx
Labels: Ready To Build

#41530 Fix Preferred exporter page + country crash
  src/ROUTES.ts
  src/libs/actions/connections/index.ts
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksPreferredExporterConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/import/QuickbooksImportPage.tsx
Labels: Ready To Build

#40757 Improve UX of modifying single line text inputs
  assets/images/x-circle.svg
  src/components/Icon/Expensicons.ts
  src/components/TextInput/BaseTextInput/index.native.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextInput/BaseTextInput/types.ts
  src/components/TextInput/TextInputClearButton/index.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/GroupChatNameEditPage.tsx
Labels: Ready To Build

#41381 fix: Can't drag mouse to select text in input.
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/pages/NewChatPage.tsx
Labels: Ready To Build

#41493 [VIP-Travel] Create a New Travel Page and Terms and Conditions Modal (NewDot)
  assets/animations/Plane.lottie
  assets/images/simple-illustrations/simple-illustration__alert.svg
  assets/images/simple-illustrations/simple-illustration__piggybank.svg
  assets/images/suitcase.svg
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/FeatureList.tsx
  src/components/Icon/Expensicons.ts
  src/components/Icon/Illustrations.ts
  src/components/LottieAnimations/index.tsx
  src/components/Section/index.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Travel.ts
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/pages/Travel/ManageTrips.tsx
  src/pages/Travel/MyTripsPage.tsx
  src/pages/Travel/TravelTerms.tsx
  src/pages/Travel/getTripIllustrationStyle/index.native.ts
  src/pages/Travel/getTripIllustrationStyle/index.ts
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
  src/styles/variables.ts
  src/types/onyx/Account.ts
  src/types/onyx/Policy.ts
  src/types/onyx/TravelSettings.ts
  tests/utils/collections/userAccount.ts
Labels: Ready To Build

#40777 Save logs data in downloads and show meaningful path
  src/CONST.ts
  src/components/ClientSideLoggingToolMenu/BaseClientSideLoggingToolMenu.tsx
  src/components/ClientSideLoggingToolMenu/index.android.tsx
  src/components/ClientSideLoggingToolMenu/index.ios.tsx
  src/components/ProfilingToolMenu/BaseProfilingToolMenu.tsx
  src/components/ProfilingToolMenu/index.android.tsx
  src/components/ProfilingToolMenu/index.ios.tsx
  src/libs/getDownloadFolderPathSuffixForIOS.ts
Labels: Ready To Build

#41612 [CP Staging] Roll back `react-native-onyx` to version `2.0.32`
  package-lock.json
  package.json
Labels: Ready To Build

#41477 Add support for MERGED_WITH_CASH_TRANSACTION system message
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/home/report/ReportActionItem.tsx
  src/types/onyx/OriginalMessage.ts
Labels: InternalQA

#40253 feature: silently update desktop app
  desktop/ELECTRON_EVENTS.ts
  desktop/contextBridge.ts
  desktop/main.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/AppUpdate/updateApp/index.desktop.ts
Labels: Ready To Build

#41615 Fix layout on ios
  src/components/Search.tsx
  src/components/SelectionList/TransactionListItem.tsx
  src/pages/Search/SearchPageBottomTab.tsx
Labels: Ready To Build

#41208 [QAB] Store GPS coordinate when using the QAB to scan a receipt
  src/CONST.ts
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: InternalQA

#41644 Fix getContinuousReportActionChain with optimistic actions
  src/libs/ReportActionsUtils.ts
Labels: Ready To Build

#41558 [WIP] Ignore optimistic actions both ways
  src/libs/ReportActionsUtils.ts
Labels: Ready To Build

#41360 Fix iOS Privacy Manifest issues
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile.lock
  ios/PrivacyInfo.xcprivacy
  package-lock.json
  package.json
  patches/@rnmapbox+maps+10.1.20.patch
Labels: Ready To Build

#40386 [HOLD] Implement Uneven Splits
  src/CONST.ts
  src/components/AmountTextInput.tsx
  src/components/MoneyRequestAmountInput.tsx
  src/components/MoneyRequestConfirmationList.tsx
  src/components/OptionRow.tsx
  src/components/OptionsList/BaseOptionsList.tsx
  src/components/OptionsList/types.ts
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextInputWithCurrencySymbol/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/libs/CurrencyUtils.ts
  src/libs/MoneyRequestUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/types/onyx/Transaction.ts
Labels: Ready To Build

#41856 [CP Staging] Use `whisperedTo` instead of `whisperedToAccountIDs`
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionsListItemRenderer.tsx
  src/pages/home/report/reportActionPropTypes.js
  src/types/onyx/OriginalMessage.ts
  src/types/onyx/ReportAction.ts
  tests/unit/ReportUtilsTest.ts
  tests/utils/LHNTestUtils.tsx
  tests/utils/ReportTestUtils.ts
  tests/utils/collections/reportActions.ts
Labels: Ready To Build

#41920 [CP Staging] Make sure to resolve the promise to unpause the sequential queue
  src/libs/actions/OnyxUpdateManager/utils/index.ts
Labels: Ready To Build

#41765 Fix dismissing Onboarding on iOS
  src/libs/Navigation/getOnboardingModalScreenOptions/index.native.ts
Labels: Ready To Build

#40020 [Pending/Scanning pattern] Update the UI for Pending and Scanning in Single Transaction ReportPreview / MoneyRequestAction
  assets/images/credit-card-hourglass.svg
  assets/images/receipt-scan.svg
  src/components/Icon/Expensicons.ts
  src/components/MoneyRequestHeader.tsx
  src/components/MoneyRequestHeaderStatusBar.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/home/report/ReportActionItem.tsx
Labels: Ready To Build

#42089 Use padding in table head only in multi-select mode
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
Labels: Ready To Build

#41861 Support money request push notifications
  src/libs/Notification/PushNotification/NotificationType.ts
  src/libs/Notification/PushNotification/index.native.ts
  src/libs/Notification/PushNotification/shouldShowPushNotification.ts
  src/libs/Notification/PushNotification/subscribePushNotification/index.ts
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts
  src/libs/Notification/clearReportNotifications/index.native.ts
  src/libs/actions/Report.ts
  src/setup/platformSetup/index.native.ts
Labels: Ready To Build

#42127 Fix footer moves down and up a bit when keyboard show/close
  src/components/FixedFooter.tsx
  src/components/SelectionList/BaseSelectionList.tsx
Labels: Ready To Build

#41485 fix: regressions related to workspace avatars
  src/components/Avatar.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/MentionSuggestions.tsx
  src/components/MenuItem.tsx
  src/components/MoneyRequestConfirmationList.tsx
  src/components/MultipleAvatars.tsx
  src/components/RoomHeaderAvatars.tsx
  src/components/SelectionList/TransactionListItem.tsx
  src/components/SubscriptAvatar.tsx
  src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx
  src/pages/ReportAvatar.tsx
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/iou/request/step/IOURequestStepSendFrom.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
Labels: Ready To Build

#41221 Patch for search lhn no results found padding
  src/components/SelectionList/BaseSelectionList.tsx
  src/pages/ChatFinderPage/index.tsx
Labels: Ready To Build

#41520 Handle the error with journal entry when tax is enabled
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
  src/pages/workspace/accounting/qbo/import/QuickbooksTaxesPage.tsx
Labels: Ready To Build

#41731 add possibility of excluding styles in useMarkdownStyles
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/components/Composer/types.ts
  src/hooks/useMarkdownStyle.ts
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
Labels: Ready To Build

#41627 Use new multi config edit command
  src/ROUTES.ts
  src/SCREENS.ts
  src/libs/API/parameters/UpdateManyPolicyConnectionConfigurationsParams.ts
  src/libs/API/parameters/UpdatePolicyConnectionConfigParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/connections/index.ts
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountPayableSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectCardPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
Labels: Ready To Build

#42057 Bump Onyx to 2.0.41
  package-lock.json
  package.json
  src/components/AddressForm.tsx
  src/components/AttachmentModal.tsx
  src/components/AvatarWithDisplayName.tsx
  src/components/KeyboardAvoidingView/index.ios.tsx
  src/components/KeyboardAvoidingView/index.tsx
  src/components/KeyboardAvoidingView/types.ts
  src/components/SelectionList/BaseSelectionList.tsx
  src/languages/types.ts
  src/libs/EmojiUtils.ts
  src/libs/ErrorUtils.ts
  src/libs/PolicyUtils.ts
  src/libs/Pusher/pusher.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils.ts
  src/libs/actions/BankAccounts.ts
  src/libs/actions/FormActions.ts
  src/libs/actions/IOU.ts
  src/libs/actions/OnyxUpdates.ts
  src/libs/actions/Policy.ts
  src/libs/actions/Report.ts
  src/libs/actions/ReportActions.ts
  src/libs/migrations/RenameReceiptFilename.ts
  src/libs/migrations/TransactionBackupsToCollection.ts
  src/pages/GroupChatNameEditPage.tsx
  src/pages/NewChatPage.tsx
  src/pages/PrivateNotes/PrivateNotesEditPage.tsx
  src/pages/PrivateNotes/PrivateNotesListPage.tsx
  src/pages/ReimbursementAccount/ConnectBankAccount/components/BankAccountValidationForm.tsx
  src/pages/ReimbursementAccount/utils/getValuesForBeneficialOwner.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/home/sidebar/ProfileAvatarWithIndicator.tsx
  src/pages/settings/Profile/PersonalDetails/AddressPage.tsx
  src/types/utils/isLoadingOnyxValue.ts
  src/utils/arraysEqual.ts
  tests/actions/IOUTest.ts
Labels: Ready To Build

#41220 Remove report screen logs
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionsView.tsx
Labels: Emergency

#42447 Unsubscribe from pusher channels if there are no more events subscribed
  src/libs/Pusher/pusher.ts
Labels: InternalQA

#42599 [CP staging] Revert "add possibility of excluding styles in useMarkdownStyles"
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/components/Composer/types.ts
  src/hooks/useMarkdownStyle.ts
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
Labels: Ready To Build

#40872 fix android com.facebook.jni.CppException crash
  package-lock.json
  package.json
Labels: Ready To Build

#42046 Fullstory integration Update.
  android/app/build.gradle
  android/build.gradle
  babel.config.js
  config/webpack/webpack.common.ts
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  jest/setup.ts
  jest/setupMockFullstoryLib.ts
  package-lock.json
  package.json
  src/ONYXKEYS.ts
  src/components/FullstoryNative.tsx
  src/components/VideoPlayer/BaseVideoPlayer.tsx
  src/libs/Fullstory/index.native.ts
  src/libs/Fullstory/index.ts
  src/libs/Fullstory/types.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/actions/Session/index.ts
  src/types/onyx/UserMetadata.ts
  src/types/onyx/index.ts
  web/gtm.js
  web/index.html
  web/thirdPartyScripts.js
Labels: Ready To Build

#42593 Fix tracking categories not dynamic
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ConnectionLayout.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/connections/ConnectToXero.ts
  src/pages/workspace/accounting/xero/XeroMapRegionsToConfigurationPage.tsx
  src/pages/workspace/accounting/xero/XeroMapTrackingCategoryConfigurationPage.tsx
  src/pages/workspace/accounting/xero/XeroTrackingCategoryConfigurationPage.tsx
Labels: Ready To Build

#42332 Fix canShowHeader logic
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#41846 Use fallback user avatar in cases where the user is unknown to us
  src/components/Avatar.tsx
  src/components/AvatarWithImagePicker.tsx
  src/components/AvatarWithIndicator.tsx
  src/components/MenuItem.tsx
  src/components/ReportActionItem/TaskView.tsx
  src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx
  src/libs/OptionsListUtils.ts
  src/libs/PersonalDetailsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/UserUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/libs/actions/Task.ts
  src/pages/DetailsPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/ReportParticipantDetailsPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/RoomMembersPage.tsx
  src/pages/home/report/ReactionList/BaseReactionList.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
  src/pages/home/report/ReportActionItemFragment.tsx
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/home/sidebar/ProfileAvatarWithIndicator.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/workspace/WorkspaceAvatar.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsApproverPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPayerPage.tsx
  src/types/onyx/OnyxCommon.ts
  tests/unit/ReportUtilsTest.ts
Labels: Ready To Build

#42707 Bump iOS deployment target to 15
  ios/NewExpensify.xcodeproj/project.pbxproj
Labels: Ready To Build

#42410 [No QA][Search v1] Create ReportListItem
  src/CONST.ts
  src/components/Search.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TextWithIconCell.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/components/SelectionList/TransactionListItem.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/SearchUtils.ts
  src/pages/Search/SearchPage.tsx
  src/styles/index.ts
  src/styles/variables.ts
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#41378 fix: Android - Distance - Waypoint does not change position correctly by dragging.
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepWaypoint.tsx
  src/types/onyx/RecentWaypoint.ts
  src/types/onyx/Transaction.ts
Labels: Ready To Build

#38449 Fix: There's a lot of extra space above the report actions
  src/CONST.ts
  src/components/ReportActionItem/MoneyReportView.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/pages/home/report/AnimatedEmptyStateBackground.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionItemCreated.tsx
  src/pages/home/report/ReportActionItemParentAction.tsx
  src/styles/index.ts
  src/styles/utils/chatContentScrollViewPlatformStyles/index.native.ts
  src/styles/utils/chatContentScrollViewPlatformStyles/index.ts
  src/styles/utils/chatContentScrollViewPlatformStyles/types.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#41957 Add receipt thumbnail to Search
  assets/images/receipt-plus.svg
  src/CONST.ts
  src/components/EReceiptThumbnail.tsx
  src/components/Icon/Expensicons.ts
  src/components/ReceiptImage.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/SearchTableHeader.tsx
  src/components/SelectionList/SearchTableHeaderColumn.tsx
  src/components/SelectionList/types.ts
  src/components/ThumbnailImage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/variables.ts
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#40182 Bank account and Authorized payer buttons displayed instead of Connect bank account
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#42725 [CP Staging] Revert "Merge pull request #42057 from margelo/@chrispader/bump-onyx-…
  package-lock.json
  package.json
  src/components/AddressForm.tsx
  src/components/AttachmentModal.tsx
  src/components/AvatarWithDisplayName.tsx
  src/components/KeyboardAvoidingView/index.ios.tsx
  src/components/KeyboardAvoidingView/index.tsx
  src/components/KeyboardAvoidingView/types.ts
  src/languages/types.ts
  src/libs/EmojiUtils.ts
  src/libs/ErrorUtils.ts
  src/libs/PolicyUtils.ts
  src/libs/Pusher/pusher.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils.ts
  src/libs/actions/BankAccounts.ts
  src/libs/actions/FormActions.ts
  src/libs/actions/IOU.ts
  src/libs/actions/OnyxUpdates.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Report.ts
  src/libs/actions/ReportActions.ts
  src/libs/migrations/RenameReceiptFilename.ts
  src/libs/migrations/TransactionBackupsToCollection.ts
  src/pages/GroupChatNameEditPage.tsx
  src/pages/NewChatPage.tsx
  src/pages/PrivateNotes/PrivateNotesEditPage.tsx
  src/pages/PrivateNotes/PrivateNotesListPage.tsx
  src/pages/ReimbursementAccount/ConnectBankAccount/components/BankAccountValidationForm.tsx
  src/pages/ReimbursementAccount/utils/getValuesForBeneficialOwner.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/home/sidebar/ProfileAvatarWithIndicator.tsx
  src/pages/settings/Profile/PersonalDetails/AddressPage.tsx
  src/types/utils/isLoadingOnyxValue.ts
  tests/actions/IOUTest.ts
Labels: Ready To Build

#41972 feat: add PromotedActionsBar
  assets/images/comment-bubbles.svg
  assets/images/stopwatch.svg
  src/components/ChatDetailsQuickActionsBar.tsx
  src/components/Icon/Expensicons.ts
  src/components/PromotedActionsBar.tsx
  src/libs/actions/Report.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/home/HeaderView.tsx
  src/stories/PromotedActionBar.stories.tsx
Labels: Ready To Build

#42615 Fix emoji’s are cut in half when in Edit message mode
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
Labels: Ready To Build

#42249 [No QA][TS migration] Remove all remaining prop-types from the project
  package-lock.json
  package.json
  src/components/Image/sourcePropTypes/index.js
  src/components/Image/sourcePropTypes/index.native.js
  src/components/Tooltip/BaseTooltip/index.tsx
  src/components/avatarPropTypes.js
  src/components/categoryPropTypes.js
  src/components/optionPropTypes.js
  src/components/participantPropTypes.js
  src/components/tagPropTypes.js
  src/components/withCurrentReportID.tsx
  src/components/withKeyboardState.tsx
  src/components/withLocalize.tsx
  src/components/withStyleUtils.tsx
  src/components/withTheme.tsx
  src/components/withThemeStyles.tsx
  src/components/withWindowDimensions/index.native.tsx
  src/components/withWindowDimensions/index.tsx
  src/libs/Localize/index.ts
  src/libs/Violations/propTypes.ts
  src/pages/home/report/reportActionFragmentPropTypes.js
  src/pages/home/report/reportActionPropTypes.js
  src/pages/workspace/withPolicy.tsx
  src/styles/stylePropTypes.js
Labels: Ready To Build

#42783 [CP Staging] Revert "Merge pull request #42426 from bernhardoj/fix/42084-limi-amount-to-8-digit"
  src/libs/MoneyRequestUtils.ts
Labels: Ready To Build

#36292 [No QA] Replace usages of useWindowDimensions with useResponsiveLayout in components folder
  src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.tsx
  src/components/AttachmentModal.tsx
  src/components/AttachmentPicker/index.native.tsx
  src/components/Attachments/AttachmentCarousel/CarouselButtons.tsx
  src/components/Attachments/AttachmentView/AttachmentViewVideo/index.tsx
  src/components/AvatarCropModal/AvatarCropModal.tsx
  src/components/BigNumberPad.tsx
  src/components/ConfirmModal.tsx
  src/components/DatePicker/index.tsx
  src/components/EmojiPicker/EmojiPicker.tsx
  src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.tsx
  src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx
  src/components/EmojiPicker/EmojiPickerMenu/index.tsx
  src/components/GrowlNotification/GrowlNotificationContainer/index.tsx
  src/components/HTMLEngineProvider/index.tsx
  src/components/HeaderPageLayout.tsx
  src/components/LHNOptionsList/LHNOptionsList.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/components/MenuItem.tsx
  src/components/Modal/BaseModal.tsx
  src/components/OfflineIndicator.tsx
  src/components/PDFView/PDFPasswordForm.tsx
  src/components/PDFView/index.native.tsx
  src/components/PDFView/index.tsx
  src/components/Popover/index.tsx
  src/components/PopoverMenu.tsx
  src/components/Reactions/EmojiReactionBubble.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportHeaderSkeletonView.tsx
  src/components/ScreenWrapper.tsx
  src/components/Section/index.tsx
  src/components/TimePicker/TimePicker.tsx
  src/components/VideoPlayerPreview/index.tsx
  src/components/WorkspaceEmptyStateSection.tsx
  src/hooks/useResponsiveLayout.ts
  src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx
  src/pages/settings/Wallet/ActivatePhysicalCardPage.tsx
  src/styles/utils/generators/ModalStyleUtils.ts
  tests/perf-test/ChatFinderPage.perf-test.tsx
  tests/perf-test/ReportScreen.perf-test.tsx
  tests/perf-test/SidebarLinks.perf-test.tsx
Labels: Ready To Build

#42248 [Search v1] Add sorting
  assets/images/arrow-down-long.svg
  assets/images/arrow-up-long.svg
  src/CONST.ts
  src/ROUTES.ts
  src/components/Icon/Expensicons.ts
  src/components/Search.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/components/SelectionList/SearchTableHeader.tsx
  src/components/SelectionList/SearchTableHeaderColumn.tsx
  src/components/SelectionList/SortableHeaderText.tsx
  src/components/SelectionList/types.ts
  src/libs/API/parameters/Search.ts
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/types.ts
  src/libs/SearchUtils.ts
  src/libs/actions/Search.ts
  src/pages/Search/SearchPage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#42805 [CP Staging] fix: Chat - Display Name Appears Black and Members Not Ticked in Group Preview
  src/components/SelectionList/BaseSelectionList.tsx
  src/libs/ReportUtils.ts
Labels: Ready To Build

#42843 Revert "upgrade react-native-live-markdown to 0.1.76"
  package-lock.json
  package.json
Labels: Ready To Build

#42471 Add cancel function when you select an option in search and navigate away from the optionList
  src/hooks/useCancelSearchOnModalClose.ts
  src/libs/API/parameters/SearchForReportsParams.ts
  src/libs/HttpUtils.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/actions/Report.ts
  src/pages/ChatFinderPage/index.tsx
  src/pages/RoomInvitePage.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/pages/tasks/TaskAssigneeSelectorModal.tsx
  src/pages/tasks/TaskShareDestinationSelectorModal.tsx
  src/pages/workspace/WorkspaceInvitePage.tsx
Labels: Ready To Build

#42883 Remove outdated conditions
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx
Labels: Ready To Build

#42914 [CP Staging] Revert "Bump expensify-common version"
  package-lock.json
  package.json
Labels: Ready To Build

#42543 QBO freeze branch
  src/components/BlockingViews/BlockingView.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/components/SelectionScreen.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/WorkspaceNewRoomPage.tsx
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
  src/pages/workspace/accounting/qbo/advanced/QuickbooksAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/advanced/QuickbooksInvoiceAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportInvoiceAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksNonReimbursableDefaultVendorSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
  src/pages/workspace/accounting/qbo/import/QuickbooksLocationsPage.tsx
  src/pages/workspace/accounting/qbo/import/QuickbooksTaxesPage.tsx
  src/pages/workspace/accounting/xero/advanced/XeroBillPaymentAccountSelectorPage.tsx
  src/pages/workspace/accounting/xero/advanced/XeroInvoiceAccountSelectorPage.tsx
  src/pages/workspace/accounting/xero/export/XeroBankAccountSelectPage.tsx
  src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx
  src/styles/utils/spacing.ts
  src/styles/variables.ts
Labels: Ready To Build
