Repository Expensify/App, pull requests merged in 2024-06, with the labels that each got.

#42746 Add bottom margin below header in Onfido step
  src/pages/ReimbursementAccount/VerifyIdentity/VerifyIdentity.tsx
Labels: Ready To Build

#42154 feat: add Down Caret to Report Titles
  src/components/AvatarWithDisplayName.tsx
  src/components/CaretWrapper.tsx
  src/pages/home/HeaderView.tsx
Labels: Ready To Build

#42423 [phase2] fix delete modal flicker
  src/components/ConfirmModal.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/types.ts
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/components/PopoverMenu.tsx
  src/components/PopoverWithMeasuredContent.tsx
  src/components/ThreeDotsMenu/index.tsx
  src/libs/ComposerFocusManager.ts
  src/pages/home/HeaderView.tsx
Labels: Ready To Build

#42184 Add canned searches
  assets/images/check-circle.svg
  assets/images/simple-illustrations/simple-illustration__checkmarkcircle.svg
  assets/images/simple-illustrations/simple-illustration__sendmoney.svg
  src/CONST.ts
  src/components/Icon/Expensicons.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/Search/SearchFilters.tsx
  src/pages/Search/SearchPage.tsx
Labels: Ready To Build

#42188 feat: update ProfilePage
  src/components/PromotedActionsBar.tsx
  src/pages/ProfilePage.tsx
Labels: Ready To Build

#42728 [fix]: Incorrect padding in group invite flow in RHP
  src/pages/InviteReportParticipantsPage.tsx
Labels: Ready To Build

#42385 cleanup: remove DetailsPage.tsx
  src/ROUTES.ts
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
  src/components/PromotedActionsBar.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/DetailsPage.tsx
  src/pages/ProfilePage.tsx
Labels: Ready To Build

#40293 [Search v1] Implement Bottom Tab Bar Changes
  assets/images/inbox.svg
  assets/images/money-search.svg
  src/components/Icon/Expensicons.ts
  src/components/TestToolMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx
Labels: Ready To Build

#43085 prevent autoscroll to bottom on android when last track expense whisper is unresolved
  src/hooks/useReportScrollManager/index.native.ts
  src/hooks/useReportScrollManager/index.ts
  src/pages/home/report/ReportActionItem.tsx
Labels: Ready To Build

#43340 [CP Staging] Bump live-markdown to 0.1.83
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#43431 Revert "chore: remove all selection ranges during navigation"
  src/libs/Navigation/NavigationRoot.tsx
Labels: Ready To Build

#43447 Revert "Immediately show file size message for large attachments"
  src/components/AttachmentPicker/index.native.tsx
Labels: Ready To Build

#43122 feat: subscription size action
  src/languages/en.ts
  src/languages/es.ts
  src/pages/settings/Subscription/SubscriptionDetails/index.tsx
  src/pages/settings/Subscription/SubscriptionSize/substeps/Size.tsx
  src/styles/index.ts
Labels: Ready To Build

#42581 Show all group policies in the workspace list
  src/libs/PolicyUtils.ts
  src/pages/workspace/AccessOrNotFoundWrapper.tsx
Labels: Ready To Build

#41343 Feature/38774 expensify persona
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/libs/API/parameters/CompleteGuidedSetupParams.ts
  src/libs/AccountUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/actions/Report.ts
  src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx
Labels: Ready To Build

#43500 [CP Staging] [Search v1] Fix for workspace switcher and back to search tab on Android
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/Navigation/linkTo/index.ts
  src/libs/Navigation/linkingConfig/getMatchingBottomTabRouteForState.ts
  src/libs/Navigation/setupCustomAndroidBackHandler/index.android.ts
  src/libs/Navigation/setupCustomAndroidBackHandler/index.ts
  src/libs/Navigation/types.ts
  src/pages/Search/SearchPage.tsx
  src/pages/Search/useCustomBackHandler/index.android.ts
  src/pages/Search/useCustomBackHandler/index.ts
Labels: Ready To Build

#42589 Refactor/36648 wallet enablement flow connect steps
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AddPlaidBankAccount.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/actions/BankAccounts.ts
  src/libs/actions/Wallet.ts
  src/pages/AddPersonalBankAccountPage.tsx
  src/pages/EnablePayments/AddBankAccount/AddBankAccount.tsx
  src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx
  src/pages/EnablePayments/AddBankAccount/substeps/ConfirmationStep.tsx
  src/pages/EnablePayments/EnablePayments.tsx
  src/pages/EnablePayments/FeesAndTerms/FeesAndTerms.tsx
  src/pages/EnablePayments/FeesAndTerms/substeps/FeesStep.tsx
  src/pages/EnablePayments/FeesAndTerms/substeps/TermsStep.tsx
  src/pages/EnablePayments/PersonalInfo/PersonalInfo.tsx
  src/pages/EnablePayments/PersonalInfo/substeps/AddressStep.tsx
  src/pages/EnablePayments/PersonalInfo/substeps/ConfirmationStep.tsx
  src/pages/EnablePayments/TermsPage/ShortTermsForm.tsx
  src/pages/EnablePayments/VerifyIdentity/VerifyIdentity.tsx
  src/pages/ReimbursementAccount/BankInfo/substeps/Plaid.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/types/form/PersonalBankAccountForm.ts
Labels: Ready To Build

#43099 Fix Slow Chat Switcher issue
  src/components/SelectionList/BaseSelectionList.tsx
  src/pages/ChatFinderPage/index.tsx
Labels: Ready To Build

#42516 Fix: add spacing between comment and Uploading attachment...
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/libs/ReportUtils.ts
Labels: Ready To Build

#43606 [CP Staging] Fix crash on vbba flow
  src/components/Modal/index.tsx
Labels: Ready To Build

#43384 Opening a transaction thread can be slow to load sometimes
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
Labels: Ready To Build

#43321 Update en.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/categories/WorkspaceCategoriesSettingsPage.tsx
Labels: Ready To Build

#41830 Fix status bar of mWeb Safari doesn't match the splash screen background color
  src/components/CustomStatusBarAndBackground/index.tsx
  src/libs/getSplashBackgroundColor/index.native.ts
  src/libs/getSplashBackgroundColor/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  web/index.html
Labels: Ready To Build

#42572 fix Password-protected PDF not handled correctly
  src/libs/isPdfFilePasswordProtected/index.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build

#43693 Integrate ReportActionItemContentCreated
  src/components/ShowContextMenuContext.ts
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionItemContentCreated.tsx
Labels: Ready To Build

#42818 Block Onboarding modal dismiss on android
  src/pages/OnboardingPurpose/index.native.tsx
Labels: Ready To Build

#44006 Revert "Revert "Fullstory plugin update. Annotation plugin fix.""
  android/build.gradle
  babel.config.js
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  web/index.html
Labels: Ready To Build

#43669 fix workspace empty state
  src/pages/workspace/WorkspacesListPage.tsx
Labels: Ready To Build

#43627 [NoQA] Change modal border radius to 16px
  src/styles/index.ts
  src/styles/utils/generators/ModalStyleUtils.ts
  src/styles/utils/generators/ReportActionContextMenuStyleUtils.ts
Labels: Ready To Build

#43993 fix: do not show domain chats in focus mode
  src/libs/SidebarUtils.ts
Labels: Ready To Build

#44117 [CP Staging] Add icon style for the Center map button
  src/components/MapView/MapView.tsx
Labels: Ready To Build

#43733 Feat: Update font
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TextWithIconCell.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/utils/sizing.ts
  src/styles/variables.ts
Labels: Ready To Build

#43951 Display Done and Paid badges in Search
  src/CONST.ts
  src/components/Search.tsx
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/SearchTableHeader.tsx
  src/components/SelectionList/SortableHeaderText.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx
  src/libs/Navigation/switchPolicyID.ts
  src/libs/SearchUtils.ts
  src/pages/Search/SearchFilters.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/styles/utils/index.ts
  src/styles/variables.ts
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#43652 Feat: Implement loading skeleton small screen width
  src/CONST.ts
  src/components/Skeletons/ItemListSkeletonView.tsx
  src/components/Skeletons/TableListItemSkeleton.tsx
Labels: Ready To Build

#43855 [Free trial] Implement Restricted Action screen
  assets/images/simple-illustrations/simple-illustration__lockclosed_orange.svg
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/ReportUtils.ts
  src/pages/RestrictedAction/Workspace/WorkspaceAdminRestrictedAction.tsx
  src/pages/RestrictedAction/Workspace/WorkspaceOwnerRestrictedAction.tsx
  src/pages/RestrictedAction/Workspace/WorkspaceRestrictedActionPage.tsx
  src/pages/RestrictedAction/Workspace/WorkspaceUserRestrictedAction.tsx
  src/styles/variables.ts
Labels: Ready To Build

#42287 [NoQA] feat: react-compiler
  .eslintrc.js
  .github/actions/javascript/authorChecklist/index.js
  .prettierignore
  babel.config.js
  lib/react-compiler-runtime/index.js
  lib/react-compiler-runtime/package.json
  package-lock.json
  package.json
  patches/eslint-plugin-react-compiler+0.0.0-experimental-53bb89e-20240515.patch
  src/pages/ShareCodePage.tsx
Labels: Ready To Build

#42582 Simplify the RootNavigator structure
  src/ROUTES.ts
  src/components/ScreenWrapper.tsx
  src/components/Search.tsx
  src/components/withPrepareCentralPaneScreen/index.native.tsx
  src/components/withPrepareCentralPaneScreen/index.tsx
  src/hooks/useActiveRoute.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/CENTRAL_PANE_SCREENS.tsx
  src/libs/Navigation/AppNavigator/Navigators/ActiveRouteContext.ts
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/index.native.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/index.tsx
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/index.tsx
  src/libs/Navigation/AppNavigator/getActionsFromPartialDiff.ts
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/dismissModalWithReport.ts
  src/libs/Navigation/getTopmostCentralPaneRoute.ts
  src/libs/Navigation/getTopmostReportActionID.ts
  src/libs/Navigation/getTopmostReportId.ts
  src/libs/Navigation/linkTo/index.ts
  src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Navigation/linkingConfig/getMatchingCentralPaneRouteForState.ts
  src/libs/Navigation/setupCustomAndroidBackHandler/index.android.ts
  src/libs/Navigation/switchPolicyID.ts
  src/libs/Navigation/types.ts
  src/libs/NavigationUtils.ts
  src/libs/SearchUtils.ts
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportActionsView.tsx
  src/pages/home/report/UserTypingEventListener.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/workspace/withPolicy.tsx
  tests/perf-test/ReportScreen.perf-test.tsx
  tests/ui/UnreadIndicatorsTest.tsx
Labels: Ready To Build

#43765 Fix: System message about adding tag in Parent: Child
  src/libs/SidebarUtils.ts
  src/pages/home/report/ReportActionItem.tsx
Labels: Ready To Build

#44389 Fix Android builds failing often on CI
  android/app/build.gradle
Labels: Ready To Build

#43893 Fix: Implement skeleton view in workspace member page
  src/components/OptionsListSkeletonView.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/pages/workspace/WorkspaceMembersPage.tsx
Labels: Ready To Build

#42592 Enable React concurrent mode
  patches/@react-navigation+core+6.4.11+001+fix-react-strictmode.patch
  patches/react-native-reanimated+3.8.1+003+fix-strict-mode.patch
  src/App.tsx
  src/CONFIG.ts
  src/setup/platformSetup/index.website.ts
Labels: Ready To Build

#43919 Marking as read when coming from notification
  src/libs/actions/navigateFromNotification/index.native.ts
  src/libs/actions/navigateFromNotification/index.ts
Labels: InternalQA

#44456 add extra check before accessing whisperedTo
  src/libs/ReportActionsUtils.ts
Labels: InternalQA, Ready To Build

#44544 [CP Staging] Add freezeScreenWithLazyLoading function
  src/components/withPrepareCentralPaneScreen/index.native.tsx
  src/components/withPrepareCentralPaneScreen/index.tsx
  src/libs/Navigation/AppNavigator/CENTRAL_PANE_SCREENS.tsx
  src/libs/freezeScreenWithLazyLoading.tsx
Labels: Ready To Build

#44562 [CP Staging] Default to -1 in report header details
  src/pages/ReportDetailsPage.tsx
  src/pages/home/report/ReportActionItem.tsx
Labels: Ready To Build

#44559 [CP Stg] Replace ReportScreenIDSetter with useLastAccessedReportID
  src/components/ScreenWrapper.tsx
  src/hooks/useLastAccessedReportID.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/CENTRAL_PANE_SCREENS.tsx
  src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts
  src/libs/Navigation/AppNavigator/ReportScreenWrapper.tsx
  src/libs/ValidationUtils.ts
  src/pages/home/ReportScreen.tsx
Labels: Ready To Build

#44457 [NoQA] chore: bump onyx to 2.0.54
  package-lock.json
  package.json
Labels: Ready To Build

#44501 Remove old logic as we don't reposition the report preview anymore
  src/pages/home/report/ReportActionsView.tsx
Labels: Ready To Build

#44605 fix: "Scanning" appears in Description field
  src/components/SelectionList/Search/TransactionListItemRow.tsx
Labels: Ready To Build

#44390 fix: Android - Downloaded pop-up appears if download Word, missing Attachment successfully download.
  src/libs/fileDownload/FileUtils.ts
Labels: Ready To Build
