Repository Expensify/App, pull requests merged in 2024-03, with the labels that each got.

#36278 Styling fixes for ReportPreview/MoneyRequestPreview
  src/components/HeaderWithBackButton/index.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/styles/index.ts
  src/styles/utils/spacing.ts
  src/styles/variables.ts
Labels: Ready To Build

#37209 feat: category settings page
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SetWorkspaceCategoriesEnabledParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/categories/CategorySettingsPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesSettingsPage.tsx
  src/types/onyx/PolicyCategory.ts
Labels: Design

#37199 Feature/35713 bulk actions
  assets/images/make-admin.svg
  assets/images/remove-members.svg
  src/CONST.ts
  src/components/Button/index.tsx
  src/components/ButtonWithDropdownMenu/index.tsx
  src/components/ButtonWithDropdownMenu/types.ts
  src/components/Icon/Expensicons.ts
  src/components/MoneyTemporaryForRefactorRequestConfirmationList.js
  src/components/SelectionList/BaseListItem.tsx
  src/components/SelectionList/RadioListItem.tsx
  src/components/SelectionList/TableListItem.tsx
  src/components/SelectionList/UserListItem.tsx
  src/components/SettlementButton.tsx
  src/components/TextWithTooltip/index.native.tsx
  src/components/TextWithTooltip/index.tsx
  src/components/TextWithTooltip/types.ts
  src/hooks/useHover.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/UpdateWorkspaceMembersRoleParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
Labels: Design

#37122 FIx downloading video crash
  src/components/VideoPlayer/BaseVideoPlayer.js
  src/components/VideoPlayerContexts/VideoPopoverMenuContext.js
Labels: Ready To Build

#37621 Create WorkspaceTagsPage
  assets/images/simple-illustrations/simple-illustration__tag.svg
  assets/images/tag.svg
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Expensicons.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
Labels: Design

#35410 Add supportal navigation
  src/CONST.ts
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SignInWithSupportAuthTokenParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/types.ts
  src/libs/Network/NetworkStore.ts
  src/libs/Network/enhanceParameters.ts
  src/libs/ReportUtils.ts
  src/libs/Request.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/SignInRedirect.ts
  src/pages/LogInWithShortLivedAuthTokenPage.tsx
  src/pages/LogOutPreviousUserPage.tsx
  src/pages/home/report/ReportActionsView.js
  src/pages/home/report/ReportFooter.js
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/signin/SignInModal.tsx
  src/types/onyx/Session.ts
Labels: InternalQA

#37316 Fix displaying error message when image has been downloaded
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@react-native-camera-roll+camera-roll+5.4.0.patch
  patches/@react-native-camera-roll+camera-roll+7.4.0.patch
  src/libs/fileDownload/index.ios.ts
Labels: Ready To Build

#37457 Call OpenPolicyCategoriesPage
  src/libs/API/parameters/OpenPolicyCategoriesPageParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
Labels: Design

#37108 adds haptic feedback on long press
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx
  src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
  src/components/FloatingActionButton.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer.tsx
  src/components/Pressable/GenericPressable/BaseGenericPressable.tsx
  src/components/Pressable/PressableWithoutFeedback.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportActionItem/TaskPreview.tsx
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.js
Labels: Ready To Build

#37804 [CP Staging] Point to the onyx hotfix branch
  package-lock.json
  package.json
Labels: Ready To Build

#37700 Make members page read only
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
Labels: Design

#37668 Fix: add spacing between long category name and category status
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
Labels: Design

#36047 Apply onyx updates from push notifications reliably
  src/CONST.ts
  src/libs/Notification/PushNotification/NotificationType.ts
  src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts
  src/libs/actions/OnyxUpdateManager.ts
  src/libs/actions/OnyxUpdates.ts
  src/libs/actions/User.ts
  src/types/onyx/OnyxUpdatesFromServer.ts
Labels: InternalQA

#37704 Create CreateCategoryPage
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateWorkspaceCategoriesParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/categories/CreateCategoryPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/types/form/WorkspaceCategoryCreateForm.ts
  src/types/form/index.ts
Labels: Design

#37528 Add delete btn to workspace profile page
  src/pages/workspace/WorkspaceProfilePage.tsx
Labels: Ready To Build

#37812 Fix Investigate App Crash MainActivity.onCreate
  android/build.gradle
Labels: InternalQA

#35497 fix: Closing receipt view using device navigation redirects user to expense report
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AttachmentModal.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/ReportActionItem/ReportActionItemImage.tsx
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/TransactionReceiptPage.tsx
Labels: Ready To Build

#37821 Fix Weekly submission frequency not selected by default
  src/libs/actions/Policy.ts
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
Labels: Daily

#36414 Release profiler
  README.md
  ios/Podfile.lock
  jest/setup.ts
  package-lock.json
  package.json
  scripts/release-profile.js
  src/ONYXKEYS.ts
  src/components/ProfilingToolMenu/index.native.tsx
  src/components/ProfilingToolMenu/index.tsx
  src/components/ScreenWrapper.tsx
  src/components/TestToolsModal.tsx
  src/libs/actions/ProfilingTool.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#37441 Implement WorkspaceMoreFeaturesPage
  assets/images/simple-illustrations/simple-illustration__accounting.svg
  assets/images/simple-illustrations/simple-illustration__car.svg
  assets/images/simple-illustrations/simple-illustration__coins.svg
  assets/images/simple-illustrations/simple-illustration__pencil.svg
  assets/images/simple-illustrations/simple-illustration__workflows.svg
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/EnablePolicyCategoriesParams.ts
  src/libs/API/parameters/EnablePolicyConnectionsParams.ts
  src/libs/API/parameters/EnablePolicyDistanceRatesParams.ts
  src/libs/API/parameters/EnablePolicyReportFieldsParams.ts
  src/libs/API/parameters/EnablePolicyTagsParams.ts
  src/libs/API/parameters/EnablePolicyTaxesParams.ts
  src/libs/API/parameters/EnablePolicyWorkflowsParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
Labels: Design, Ready To Build

#38071 [CP Staging] Revert "Merge pull request #32336 from callstack-internal/hur/perf/ch…
  src/components/FlatList/index.android.tsx
  src/components/HeaderWithBackButton/types.ts
  src/components/InvertedFlatList/BaseInvertedFlatList.tsx
  src/components/LHNOptionsList/LHNOptionsList.tsx
  src/components/LHNOptionsList/OptionRowLHNData.tsx
  src/components/LHNOptionsList/types.ts
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/libs/Pusher/pusher.ts
  src/libs/actions/Report.ts
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportActionsView.tsx
  src/pages/home/sidebar/SidebarLinks.js
Labels: Ready To Build

#38081 [NoQA] Revert lhn order
  src/CONST.ts
  src/components/LHNOptionsList/LHNOptionsList.tsx
  src/components/LHNOptionsList/OptionRowLHNData.tsx
  src/components/LHNOptionsList/types.ts
  src/libs/OptionsListUtils.ts
  src/libs/SidebarUtils.ts
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarLinksData.js
  tests/perf-test/SidebarUtils.perf-test.ts
Labels: Ready To Build

#37421 Ideal nav v2 workspaces
  patches/@react-navigation+stack+6.3.16+002+dontDetachScreen.patch
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AvatarSkeleton.tsx
  src/components/AvatarWithIndicator.tsx
  src/components/FloatingActionButton.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/HeaderWithBackButton/types.ts
  src/components/Indicator.tsx
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/components/WorkspaceSwitcherButton.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/AppNavigator/Navigators/BottomTabNavigator.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/index.tsx
  src/libs/Navigation/AppNavigator/createCustomFullScreenNavigator/CustomFullScreenRouter.tsx
  src/libs/Navigation/AppNavigator/createCustomFullScreenNavigator/index.tsx
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/getTopmostWorkspacesCentralPaneName.ts
  src/libs/Navigation/linkTo.ts
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/linkingConfig/customGetPathFromState.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Navigation/linkingConfig/getMatchingBottomTabRouteForState.ts
  src/libs/Navigation/linkingConfig/getMatchingCentralPaneRouteForState.ts
  src/libs/Navigation/switchPolicyID.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/pages/WorkspaceSwitcherPage.tsx
  src/pages/home/sidebar/AvatarWithOptionalStatus.js
  src/pages/home/sidebar/BottomTabAvatar.tsx
  src/pages/home/sidebar/PressableAvatarWithIndicator.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SignInOrAvatarWithOptionalStatus.js
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/WorkspacePageWithSections.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/bills/WorkspaceBillsPage.tsx
  src/pages/workspace/card/WorkspaceCardPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx
  src/pages/workspace/invoices/WorkspaceInvoicesPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
  src/pages/workspace/travel/WorkspaceTravelPage.tsx
  src/pages/workspace/withPolicy.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#38134 Fix missing emojis in suggestion after changing skin color
  src/libs/EmojiUtils.ts
Labels: Ready To Build

#37966 Updated button specification with Icon
  assets/images/qrcode.svg
  src/components/AttachmentModal.tsx
  src/components/Attachments/AttachmentCarousel/CarouselButtons.js
  src/components/AvatarCropModal/AvatarCropModal.tsx
  src/components/Button/index.tsx
  src/components/ConfirmContent.tsx
  src/components/ConfirmationPage.tsx
  src/components/ConnectBankAccountButton.tsx
  src/components/DistanceRequest/index.tsx
  src/components/FeatureList.tsx
  src/components/FormAlertWithSubmitButton.tsx
  src/components/Icon/index.tsx
  src/components/OptionsSelector/BaseOptionsSelector.js
  src/components/PDFView/PDFPasswordForm.js
  src/components/ProcessMoneyRequestHoldMenu.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/TimePicker/TimePicker.js
  src/pages/OnboardEngagement/ExpensifyClassicPage.tsx
  src/pages/OnboardEngagement/ManageTeamsExpensesPage.tsx
  src/pages/ProcessMoneyRequestHoldPage.tsx
  src/pages/ReimbursementAccount/BankAccountStep.js
  src/pages/ReimbursementAccount/BankInfo/substeps/Confirmation.tsx
  src/pages/ReimbursementAccount/BeneficialOwnerInfo/substeps/BeneficialOwnerDetailsFormSubsteps/ConfirmationUBO.tsx
  src/pages/ReimbursementAccount/BeneficialOwnerInfo/substeps/CompanyOwnersListUBO.tsx
  src/pages/ReimbursementAccount/ConnectBankAccount/components/FinishChatCard.tsx
  src/pages/ReimbursementAccount/ContinueBankAccountSetup.js
  src/pages/ReimbursementAccount/EnableBankAccount/EnableBankAccount.tsx
  src/pages/ReimbursementAccount/PersonalInfo/substeps/Confirmation.tsx
  src/pages/TeachersUnite/ImTeacherUpdateEmailPage.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js
  src/pages/iou/request/step/IOURequestStepDistance.js
  src/pages/iou/steps/MoneyRequestAmountForm.tsx
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/settings/AboutPage/ConsolePage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx
  src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx
  src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
  src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx
  src/pages/settings/Security/TwoFactorAuth/Steps/DisabledStep.tsx
  src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx
  src/pages/settings/Wallet/ActivatePhysicalCardPage.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/signin/ChooseSSOOrMagicCode.tsx
  src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/WorkspaceNewRoomPage.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/card/WorkspaceCardVBANoECardView.tsx
  src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#38325 get rid of PR check that always fails for help dot
  .github/workflows/deployExpensifyHelp.yml
Labels: InternalQA

#38340 [CP Staging] Revert "[TS migration] Migrate 'Sidebar' page to TypeScript"
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/actions/Policy.ts
  src/libs/actions/Task.ts
  src/pages/home/sidebar/AvatarWithOptionalStatus.js
  src/pages/home/sidebar/BottomTabBarFloatingActionButton/index.tsx
  src/pages/home/sidebar/PressableAvatarWithIndicator.js
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/home/sidebar/SidebarLinksData.js
  src/pages/home/sidebar/SidebarNavigationContext.js
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/home/sidebar/SidebarScreen/index.js
  src/pages/home/sidebar/SidebarScreen/sidebarPropTypes.js
  src/pages/home/sidebar/SignInButton.js
  tests/utils/LHNTestUtils.tsx
Labels: Ready To Build

#38145 [New architecture] Replace `@oguzhnatly/react-native-image-manipulator` with `expo-image-manipulator` [v2]
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@oguzhnatly+react-native-image-manipulator+1.0.5.patch
  src/CONST.ts
  src/libs/cropOrRotateImage/getSaveFormat.ts
  src/libs/cropOrRotateImage/index.native.ts
  src/libs/cropOrRotateImage/index.ts
  src/libs/cropOrRotateImage/types.ts
Labels: Ready To Build

#37615 [TS migration] Migrate 'Desktop' files to TypeScript
  config/webpack/webpack.desktop.js
  desktop/ELECTRON_EVENTS.ts
  desktop/README.md
  desktop/contextBridge.js
  desktop/contextBridge.ts
  desktop/main.ts
  desktop/start.ts
  package-lock.json
  package.json
  src/types/modules/electron.d.ts
Labels: Ready To Build

#38228 [NoQA][Audit][Implementation] - Remove Intl Polyfills which are supported by Hermes on native platforms
  src/libs/IntlPolyfill/index.native.ts
Labels: Ready To Build

#38190 Incorrect animation direction on Wallet, Save The World, Exit Survey, Profile Contact and Troubleshooting page
  src/pages/TeachersUnite/ImTeacherUpdateEmailPage.tsx
  src/pages/TeachersUnite/IntroSchoolPrincipalPage.tsx
  src/pages/TeachersUnite/KnowATeacherPage.tsx
  src/pages/settings/AboutPage/TroubleshootPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx
  src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
Labels: InternalQA

#30460 Fix: App uses ultra-wide camera by default in Scan receipt page
  src/pages/iou/request/step/IOURequestStepScan/index.js
Labels: Ready To Build

#37872 Fix/37098: In app sound is played if user not viewing chat
  src/libs/actions/User.ts
Labels: Ready To Build

#37282 Track Expense flow
  assets/images/document-plus.svg
  src/CONST.ts
  src/components/AvatarWithDisplayName.tsx
  src/components/Icon/Expensicons.ts
  src/components/MoneyRequestHeader.tsx
  src/components/MoneyTemporaryForRefactorRequestConfirmationList.js
  src/components/OptionRow.tsx
  src/components/ReportActionItem/MoneyRequestAction.tsx
  src/components/ReportActionItem/MoneyRequestPreview/index.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/components/ReportWelcomeText.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/TrackExpenseParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/IOUUtils.ts
  src/libs/OptionsListUtils.ts
  src/libs/Permissions.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/iou/request/IOURequestStartPage.js
  src/pages/iou/request/step/IOURequestStepConfirmation.js
  src/pages/iou/request/step/IOURequestStepScan/index.js
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
  src/pages/iou/request/step/IOURequestStepTaxAmountPage.js
Labels: Ready To Build

#35355 Room settings-Members added/deleted in a room in offline mode are not grayed out/crossed
  src/libs/actions/Report.ts
  src/libs/mapChildrenFlat.ts
Labels: Waiting for copy

#30269 HIGH: (Comment linking: Step 4) Main "glue" PR for Comment Linking
  src/CONST.ts
  src/components/FlatList/MVCPFlatList.js
  src/components/InvertedFlatList/BaseInvertedFlatList.tsx
  src/components/InvertedFlatList/index.tsx
  src/libs/API/parameters/OpenReportParams.ts
  src/libs/NumberUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/actions/Policy.ts
  src/libs/actions/Report.ts
  src/libs/migrateOnyx.ts
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportActionsView.tsx
  src/pages/home/report/getInitialNumReportActionsToRender/index.native.ts
  src/pages/home/report/getInitialNumReportActionsToRender/index.ts
  src/pages/home/report/getInitialPaginationSize/index.native.ts
  src/pages/home/report/getInitialPaginationSize/index.ts
  tests/actions/IOUTest.js
  tests/ui/UnreadIndicatorsTest.tsx
  tests/unit/ReportActionsUtilsTest.ts
  tests/utils/TestHelper.js
Labels: Ready To Build

#38703 [CP STAGING]Fix: Infinite loading after denying camera access
  src/pages/iou/request/step/IOURequestStepScan/index.js
Labels: Ready To Build

#38671 resolve crash for high resolution images
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/expo-image+1.10.1+001+applyFill.patch
  patches/expo-image+1.10.1+002+TintFix.patch
  src/components/Lightbox/index.tsx
Labels: Ready To Build

#38693 35756 close emoji when navigation back
  src/components/EmojiPicker/EmojiPicker.js
  src/components/Modal/index.tsx
  src/components/Modal/types.ts
  src/components/Popover/index.tsx
  src/components/Popover/types.ts
  src/components/PopoverWithMeasuredContent.tsx
Labels: Ready To Build

#38710 Fix: remove border bug on report previews with 3+ receipts
  src/components/ReportActionItem/ReportActionItemImages.tsx
  src/styles/index.ts
Labels: Design, Ready To Build

#37773 Fix the incorrect payer name on the non-reimbursable transaction
  src/components/ReportActionItem/ReportPreview.tsx
  src/libs/ReportUtils.ts
Labels: Ready To Build

#38669 Display Quick Action Button
  src/components/MenuItem.tsx
  src/components/MultipleAvatars.tsx
  src/components/PopoverMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Task.ts
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/styles/utils/spacing.ts
  src/types/onyx/QuickAction.ts
Labels: Ready To Build

#38953 make gcp environment variable available to electron main process
  scripts/build-desktop.sh
Labels: Ready To Build

#37672 Fix issues with the bold (unread) status on Workspace Item
  src/libs/WorkspacesSettingsUtils.ts
Labels: Ready To Build

#33434 Connect react-fast-pdf
  package-lock.json
  package.json
  src/CONST.ts
  src/components/PDFView/WebPDFDocument.js
  src/components/PDFView/WebPDFPageRenderer.js
  src/components/PDFView/constants.js
  src/components/PDFView/index.js
  src/styles/index.ts
Labels: Ready To Build

#37817 Fix immediately prompt for Camera permission in scan request flow
  src/pages/iou/request/step/IOURequestStepScan/index.js
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
Labels: Ready To Build

#38152 Enable Live Markdown Preview on web
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Composer/index.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
Labels: Ready To Build

#39084 Extract WorkspaceSettingsModalStackNavigator
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/WorkspaceSettingsModalStackNavigator.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/useModalScreenOptions.ts
Labels: Ready To Build

#37483 feat: Upgrade VisionCamera to V4
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-vision-camera+2.16.8.patch
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.native.js
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
Labels: Ready To Build

#37458 Create Group Chats + Splits.
  assets/images/avatars/group/default-avatar_1.svg
  assets/images/avatars/group/default-avatar_10.svg
  assets/images/avatars/group/default-avatar_11.svg
  assets/images/avatars/group/default-avatar_12.svg
  assets/images/avatars/group/default-avatar_13.svg
  assets/images/avatars/group/default-avatar_14.svg
  assets/images/avatars/group/default-avatar_15.svg
  assets/images/avatars/group/default-avatar_16.svg
  assets/images/avatars/group/default-avatar_17.svg
  assets/images/avatars/group/default-avatar_18.svg
  assets/images/avatars/group/default-avatar_2.svg
  assets/images/avatars/group/default-avatar_3.svg
  assets/images/avatars/group/default-avatar_4.svg
  assets/images/avatars/group/default-avatar_5.svg
  assets/images/avatars/group/default-avatar_6.svg
  assets/images/avatars/group/default-avatar_7.svg
  assets/images/avatars/group/default-avatar_8.svg
  assets/images/avatars/group/default-avatar_9.svg
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/GroupDefaultAvatars.ts
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/OpenReportParams.ts
  src/libs/API/parameters/SplitBillParams.ts
  src/libs/GroupChatUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/pages/NewChatConfirmPage.tsx
  src/pages/NewChatPage.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/settings/Report/ReportSettingsPage.tsx
  src/types/onyx/NewGroupChatDraft.ts
  src/types/onyx/Report.ts
  src/types/onyx/index.ts
  tests/actions/IOUTest.ts
Labels: Ready To Build
