Repository Expensify/App, pull requests merged in 2024-11, with the labels that each got.

#51744 [No QA] feat: add convert.com to web
  web/index.html
Labels: Ready To Build

#51600 [Create Expense A/B] Tweak Onboarding Copy for Combined Track/Submit
  src/CONST.ts
  src/libs/actions/Report.ts
Labels: Ready To Build

#48772 Feature: add loading indicator when ReconnectApp is running
  src/CONST.ts
  src/components/LoadingBar.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx
  src/styles/index.ts
Labels: Ready To Build

#52112 [CP Staging] Revert "Feature: add loading indicator when ReconnectApp is running"
  src/CONST.ts
  src/components/LoadingBar.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx
  src/styles/index.ts
Labels: Ready To Build

#51232 Enable/disable per diem rates
  assets/images/simple-illustrations/simple-illustration__perdiem.svg
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/FocusTrap/WIDE_LAYOUT_INACTIVE_SCREENS.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/OpenPolicyPerDiemRatesPageParams.ts
  src/libs/API/parameters/TogglePolicyPerDiemParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/DistanceRequestUtils.ts
  src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/actions/Policy/PerDiem.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx
  src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#52016 Redirect to feed after completing the bank connection
  src/pages/workspace/companyCards/WorkspaceCompanyCardsList.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsListHeaderButtons.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
  src/types/onyx/CardFeeds.ts
Labels: InternalQA, Ready To Build

#52042 Workspace Feed - add Search for more than 8 export rows
  src/CONST.ts
  src/components/SelectionScreen.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
Labels: InternalQA

#52028 [Workspace Feeds] Card name field on confirmation page
  src/CONST.ts
  src/libs/API/parameters/AssignCompanyCardParams.ts
  src/libs/CardUtils.ts
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/assignCard/AssignCardFeedPage.tsx
  src/pages/workspace/companyCards/assignCard/AssigneeStep.tsx
  src/pages/workspace/companyCards/assignCard/CardNameStep.tsx
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/companyCards/assignCard/ConfirmationStep.tsx
  src/types/onyx/AssignCard.ts
Labels: InternalQA

#52109 Fix: Change offline pattern for unassigning cards
  src/libs/API/parameters/UnassignCompanyCard.ts
  src/libs/API/parameters/UpdateCompanyCard.ts
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
Labels: InternalQA

#51147 Require validateCode when requesting replacement cards
  src/components/ValidateCodeActionModal/index.tsx
  src/libs/API/parameters/ReportVirtualExpensifyCardFraudParams.ts
  src/libs/API/parameters/RequestReplacementExpensifyCardParams.ts
  src/libs/actions/Card.ts
  src/pages/settings/Wallet/ReportCardLostPage.tsx
  src/pages/settings/Wallet/ReportVirtualCardFraudPage.tsx
Labels: Ready To Build

#51955 [Workspace feeds] Add search bar if cards assignment list has 8+ cards
  src/CONST.ts
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/companyCards/assignCard/ConfirmationStep.tsx
Labels: InternalQA

#52152 Workspace Feed - Use full cardsList instead of user cardList
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
Labels: InternalQA

#52150 Workspace Feed - remove unneeded extractDate from the startDate step
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/assignCard/TransactionStartDateStep.tsx
Labels: InternalQA

#52255 Fix API requests on the HybridApp
  src/libs/HttpUtils.ts
Labels: Ready To Build

#50324 Use small icon in tabs
  src/components/Button/index.tsx
  src/components/TabSelector/TabIcon.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#52273 [CP Staging] Updated Background Color Condition
  src/styles/utils/index.ts
Labels: CP Staging

#51445 Show search action buttons
  src/CONST.ts
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/types.ts
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/SearchTableHeaderColumn.tsx
  src/libs/API/parameters/PayMoneyRequestOnSearchParams.ts
  src/libs/PolicyUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SearchUIUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Search.ts
  src/types/onyx/Report.ts
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#52180 Workspace Feed - Fix export item issues
  src/CONST.ts
  src/components/CategoryPicker.tsx
  src/components/TagPicker/index.tsx
  src/components/TaxPicker.tsx
  src/libs/API/parameters/SetCompanyCardExportAccountParams.ts
  src/libs/OptionsListUtils.ts
  src/libs/actions/CompanyCards.ts
  src/pages/ReportParticipantsPage.tsx
  src/pages/RoomMembersPage.tsx
  src/pages/WorkspaceSwitcherPage/index.tsx
  src/pages/workspace/accounting/netsuite/import/NetSuiteImportCustomFieldNew/NetSuiteCustomListSelectorModal.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/utils.tsx
  src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx
  src/types/onyx/Card.ts
Labels: InternalQA

#50800 Enable copilot in HybridApp
  src/libs/actions/Delegate.ts
  src/libs/actions/Session/index.ts
  src/types/modules/react-native.d.ts
Labels: Ready To Build

#52357 fix: use pattern B for unassigning cards
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/WorkspaceCompanyCardsList.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsListRow.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
Labels: InternalQA

#51921 Fix image moves permanently when swipe down
  src/components/Attachments/AttachmentCarousel/index.tsx
  src/components/AvatarCropModal/AvatarCropModal.tsx
  src/components/Lightbox/index.tsx
  src/components/MultiGestureCanvas/index.tsx
  src/components/MultiGestureCanvas/usePanGesture.ts
  src/components/MultiGestureCanvas/usePinchGesture.ts
  src/components/MultiGestureCanvas/useTapGestures.ts
Labels: Ready To Build

#52166 Upgrade react-native-pager-view to 6.5.0
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-pager-view+6.4.1.patch
  patches/react-native-pager-view+6.5.0.patch
Labels: Ready To Build

#52048 [NoQA] Bump reanimated to v3.16.1
  package-lock.json
  package.json
  patches/react-native-reanimated+3.15.3+003+fixNullViewTag.patch
  patches/react-native-reanimated+3.16.1+001+hybrid-app.patch
  patches/react-native-reanimated+3.16.1+002+dontWhitelistTextProp.patch
Labels: Ready To Build

#52389 update images, update paymentList cardNumber view, update maskCardNumber
  assets/images/companyCards/large/card-amex-large.svg
  assets/images/companyCards/large/card-bofa-large.svg
  assets/images/companyCards/large/card-brex-large.svg
  assets/images/companyCards/large/card-capital_one-large.svg
  assets/images/companyCards/large/card-chase-large.svg
  assets/images/companyCards/large/card-citi-large.svg
  assets/images/companyCards/large/card-expensify-large.svg
  assets/images/companyCards/large/card-generic-large.svg
  assets/images/companyCards/large/card-mastercard-large.svg
  assets/images/companyCards/large/card-stripe-large.svg
  assets/images/companyCards/large/card-visa-large.svg
  assets/images/companyCards/large/card-wellsfargo-large.svg
  src/components/Icon/Illustrations.ts
  src/libs/CardUtils.ts
  src/pages/settings/Wallet/PaymentMethodList.tsx
Labels: InternalQA

#52504 Revert "fix: prevent open search when onboarding is not completed"
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
Labels: Ready To Build

#52522 fix: apply pattern B for cards in wallet
  src/pages/settings/Wallet/PaymentMethodList.tsx
Labels: InternalQA

#52553 fix: do not show expensify card in the selector when not enabled
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
Labels: InternalQA

#52587 [No QA][ADHOC builds] Add a comment when the build begins
  .github/workflows/testBuild.yml
Labels: Ready To Build

#52627 [CP Staging][No QA] fix: reanimated missing headers
  patches/react-native-reanimated+3.16.1+003+include-missing-header.patch
Labels: Ready To Build

#52630 Remove old Fastlane Action workaround fix
  .github/workflows/buildAndroid.yml
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#51709 fix: Update second Allow location access modal on web
  src/components/LocationPermissionModal/index.android.tsx
  src/components/LocationPermissionModal/index.tsx
  src/components/LocationPermissionModal/types.ts
  src/languages/en.ts
  src/languages/es.ts
Labels: Ready To Build

#52752 [CP] Fix: Context Menu Remains Open on Mweb
  src/pages/home/report/ContextMenu/ReportActionContextMenu.ts
Labels: Ready To Build

#52578 [Company Cards] Update the Amex cards format
  src/libs/CardUtils.ts
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsList.tsx
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/companyCards/assignCard/ConfirmationStep.tsx
  tests/unit/CardUtilsTest.ts
Labels: InternalQA

#52625 [Internal QA]: Show card name instead of Bank for Company cards search
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCardPage.tsx
Labels: InternalQA

#52615 [Internal QA]: Add a loader to the cards page while waiting for cards collection and feed settings
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
Labels: InternalQA

#50387 Feat: Implement to use a 👍icon next to approved report preview
  src/components/ProcessMoneyReportHoldMenu.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/SettlementButton/AnimatedSettlementButton.tsx
  src/libs/actions/IOU.ts
Labels: Ready To Build

#52794 Fix submit expense on internal Expensify policy
  .env.example
  src/CONST.ts
Labels: InternalQA, Ready To Build

#52732 Add patch to enable allowRecursiveCommitsWithSynchronousMountOnAndroid feature flag
  patches/react-native+0.75.2+021+allow-recursive-commits-with-synchronous-mount-on-android.patch
Labels: Ready To Build

#52734 PATCH: Android - Fix caret resetting to the beginning of the input
  patches/react-native+0.75.2+021+ReactEditText.patch
Labels: Ready To Build

#52708 [Internal QA]: Update copy on custom feed details page
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/companyCards/addNew/CardInstructionsStep.tsx
Labels: InternalQA

#52703 [No QA] Update force upgrade modal
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/AppUpdate/updateApp/index.android.ts
  src/libs/actions/AppUpdate/updateApp/index.desktop.ts
  src/libs/actions/AppUpdate/updateApp/index.ios.ts
  src/libs/actions/AppUpdate/updateApp/index.ts
  src/pages/ErrorPage/UpdateRequiredView.tsx
Labels: InternalQA, Ready To Build

#52890 [Internal QA]: Add amex custom feed new option
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/companyCards/addNew/AmexCustomFeed.tsx
Labels: InternalQA

#52799 fix statement modal being broken on staging environment
  src/libs/Environment/Environment.ts
  src/pages/wallet/WalletStatementPage.tsx
Labels: InternalQA

#52934 Cleanup errors for Google Tag Manager
  web/index.html
  web/thirdPartyScripts.js
Labels: InternalQA

#52575 [Internal QA]: Fix default card with export type
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/PolicyUtils.ts
  src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
  src/pages/workspace/companyCards/utils.tsx
Labels: InternalQA

#52949 [Workspace Feeds]: Update isLoading both for expensify and company cards
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
Labels: InternalQA

#53122 Amex direct feeds polish
  src/libs/CardUtils.ts
  src/pages/workspace/companyCards/addNew/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
  tests/unit/CardUtilsTest.ts
Labels: InternalQA

#52758 Show category / tag in Expense preview view
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
Labels: Ready To Build

#53102 update: Update workspace switcher to look and act more like a filter.
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/WorkspaceSwitcherPage/index.tsx
Labels: Ready To Build

#52825 [NoQA] [Chore] Bump reanimated & update API to comply with react-compiler
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-reanimated+3.16.1+003+include-missing-header.patch
  patches/react-native-reanimated+3.16.3+001+hybrid-app.patch
  patches/react-native-reanimated+3.16.3+002+dontWhitelistTextProp.patch
  src/components/Attachments/AttachmentCarousel/Pager/index.tsx
  src/components/Attachments/AttachmentCarousel/index.tsx
  src/components/Attachments/AttachmentCarousel/useCarouselContextEvents.ts
  src/components/Attachments/AttachmentView/AttachmentViewPdf/BaseAttachmentViewPdf.tsx
  src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.tsx
  src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
  src/components/AvatarCropModal/AvatarCropModal.tsx
  src/components/AvatarCropModal/ImageCropView.tsx
  src/components/AvatarCropModal/Slider.tsx
  src/components/CustomStatusBarAndBackground/index.tsx
  src/components/FloatingActionButton.tsx
  src/components/KeyboardAvoidingView/index.android.tsx
  src/components/MultiGestureCanvas/index.tsx
  src/components/MultiGestureCanvas/usePanGesture.ts
  src/components/MultiGestureCanvas/usePinchGesture.ts
  src/components/MultiGestureCanvas/useTapGestures.ts
  src/components/OpacityView.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/SettlementButton/AnimatedSettlementButton.tsx
  src/components/SpacerView.tsx
  src/components/SplashScreenHider/index.native.tsx
  src/components/VideoPlayer/BaseVideoPlayer.tsx
  src/components/VideoPlayer/VideoPlayerControls/ProgressBar/index.tsx
  src/components/VideoPlayer/VideoPlayerControls/VolumeButton/index.tsx
  src/components/VideoPlayerContexts/VolumeContext.tsx
  src/hooks/useAnimatedHighlightStyle/index.ts
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/home/report/AnimatedEmptyStateBackground.tsx
  src/pages/home/report/FloatingMessageCounter.tsx
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionItemMessageEdit.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.tsx
  src/types/modules/react-native-reanimated.d.ts
Labels: Ready To Build

#53200 Follow-up: Improve getFilteredCardList function
  src/libs/CardUtils.ts
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/assignCard/AssignCardFeedPage.tsx
  src/pages/workspace/companyCards/assignCard/AssigneeStep.tsx
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
  tests/unit/CardUtilsTest.ts
Labels: InternalQA

#53227 fix: do not call submit function twice if user clicks fast
  src/components/Form/FormProvider.tsx
  src/hooks/useDebounceNonReactive.ts
Labels: Ready To Build

#51913 Add bulk actions
  src/CONST.ts
  src/components/Search/SearchContext.tsx
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/index.tsx
  src/components/Search/types.ts
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/Search.ts
Labels: Ready To Build

#52682 Update chat with account manager banner
  src/components/Banner.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/pages/home/ReportScreen.tsx
  src/styles/index.ts
Labels: Ready To Build

#52880 Upgrade react-native-vision-camera
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-vision-camera+4.0.0-beta.13+001+rn75-compatibility.patch
  patches/react-native-vision-camera+4.0.0-beta.13+002+native-stack-unmount-recycle-camera-session.patch
  patches/react-native-vision-camera+4.6.1.patch
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
Labels: Ready To Build

#53223 [CP Staging] Fix: Android edge-to-edge related inset/padding issues
  src/components/Attachments/AttachmentView/AttachmentViewVideo/index.tsx
  src/components/SafeAreaConsumer/index.android.tsx
  src/components/SafeAreaConsumer/index.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/hooks/useSafeAreaInsets.ts
  src/hooks/useSafeAreaInsets/index.ts
  src/hooks/useStyledSafeAreaInsets.ts
  src/pages/NewChatConfirmPage.tsx
  src/pages/NewChatPage.tsx
  src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepDescription.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepMerchant.tsx
  src/pages/workspace/WorkspaceNewRoomPage.tsx
  src/styles/utils/getSafeAreaInsets/defaultInsets.ts
  src/styles/utils/getSafeAreaInsets/index.android.ts
  src/styles/utils/getSafeAreaInsets/index.ts
  src/styles/utils/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#53201 [Performance] BottomTabBar: Changed to initializer function
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/AppNavigator/createCustomPlatformStackBottomTabNavigator/BottomTabBar.tsx
Labels: Ready To Build

#53244 feat: bump clipboard library to remove RN macos and windows
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build
