Repository Expensify/App, pull requests merged in 2024-02, with the labels that each got.

#34292 Live Markdown Preview
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Composer/index.native.tsx
  src/hooks/useMarkdownStyle.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
Labels: Ready To Build

#35624 Fix/35579: Leaving room issue
  src/pages/home/ReportScreen.js
Labels: Ready To Build

#35636 Revert "Image Web/Desktop: Add support for http headers"
  patches/react-native-web+0.19.9+005+image-header-support.patch
  src/components/Image/BaseImage.native.tsx
  src/components/Image/BaseImage.tsx
  src/components/Image/index.js
  src/components/Image/index.native.js
  src/components/Image/types.ts
  src/pages/DetailsPage.js
Labels: Ready To Build

#35852 Fix crash when tapping device back button to return from thread
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#35232 Pare back the parallax animation on empty chats
  src/CONST.ts
  src/libs/NumberUtils.ts
  src/pages/home/report/AnimatedEmptyStateBackground.tsx
  src/pages/home/report/ReportActionItem.js
  src/styles/utils/index.ts
  tests/ui/UnreadIndicatorsTest.js
Labels: Ready To Build

#32471 Add required changes to run Hybrid App
  android/app/src/main/res/values/colors.xml
  ios/NewExpensify/RCTBootSplash.h
  ios/NewExpensify/RCTBootSplash.m
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@oguzhnatly+react-native-image-manipulator+1.0.5.patch
  patches/@react-native-camera-roll+camera-roll+5.4.0.patch
  patches/@react-native-community+cli-platform-android+12.3.0.patch
  patches/@react-native-community+cli-platform-ios+12.3.0.patch
  patches/@react-native-firebase+analytics+12.9.3.patch
  patches/@react-native-firebase+app+12.9.3.patch
  patches/@react-native-firebase+crashlytics+12.9.3.patch
  patches/@react-native-firebase+perf+12.9.3.patch
  patches/expo+50.0.4.patch
  patches/expo-modules-autolinking+1.10.2.patch
  patches/expo-modules-core+1.11.8.patch
  patches/react-native-reanimated+3.6.1.patch
  patches/react-native-vision-camera+2.16.5+001+fix-boost-dependency.patch
  patches/react-native-vision-camera+2.16.5.patch
  src/App.js
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/InitialUrlContext/index.ts
  src/libs/Navigation/AppNavigator/index.tsx
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/types.ts
  src/pages/LogInWithShortLivedAuthTokenPage.tsx
  src/pages/LogOutPreviousUserPage.js
  src/pages/settings/InitialSettingsPage.js
Labels: Ready To Build

#35564 [Update Account Settings] Header: icons, height, and font changes
  assets/images/simple-illustrations/simple-illustration__gears.svg
  assets/images/simple-illustrations/simple-illustration__lockclosed.svg
  assets/images/simple-illustrations/simple-illustration__palmtree.svg
  assets/images/simple-illustrations/simple-illustration__profile.svg
  assets/images/simple-illustrations/simple-illustration__qr-code.svg
  src/components/Breadcrumbs.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/HeaderWithBackButton/types.ts
  src/components/Icon/Illustrations.ts
  src/pages/ShareCodePage.tsx
  src/pages/home/HeaderView.js
  src/pages/home/sidebar/AllSettingsScreen.tsx
  src/pages/home/sidebar/SidebarLinks.js
  src/pages/settings/AboutPage/AboutPage.tsx
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/settings/Security/SecuritySettingsPage.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.js
  src/pages/workspace/WorkspaceInitialPage.js
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/variables.ts
Labels: Ready To Build

#35837 Live Markdown Preview for web
  package-lock.json
  package.json
  src/components/Composer/index.tsx
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js
Labels: Ready To Build

#35019 feat: add additional full screen engagement modal to NewDot
  assets/images/olddot-wireframe.svg
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Expensicons.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/OnboardEngagement/ExpensifyClassicPage.tsx
  src/pages/OnboardEngagement/ManageTeamsExpensesPage.tsx
  src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/variables.ts
Labels: Ready To Build

#34254 33546 visual viewport deplay
  src/components/ScreenWrapper.tsx
  src/hooks/useWindowDimensions/index.ts
Labels: Ready To Build

#35662 Update account settings/profile
  contributingGuides/NAVIGATION.md
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/CountrySelector.tsx
  src/components/Section/index.tsx
  src/hooks/usePrivatePersonalDetails.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/PersonalDetails.ts
  src/pages/settings/Profile/PersonalDetails/AddressPage.js
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
  src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js
  src/pages/settings/Profile/ProfilePage.js
  src/pages/workspace/reimburse/WorkspaceReimburseView.js
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#36141 [CP Staging] SearchPage back button issue fix
  src/pages/SearchPage/index.js
Labels: Ready To Build

#36149 [CP Staging] fix: camera doesn't load on iou scan screen
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.native.js
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
Labels: Ready To Build

#35795 Add tooltip and change background color of subscription icon
  src/components/SubscriptAvatar.tsx
  src/components/WorkspaceSwitcherButton.tsx
Labels: Ready To Build

#36213 Fix #36098 Camera doesn't load when trying to smartscan a receipt
  package-lock.json
  package.json
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.native.js
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
Labels: Ready To Build

#36194 Update `@expensify/react-native-live-markdown` to 0.1.15 to fix iOS build issue
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#36120 Share Code page update
  src/components/ContextMenuItem.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/ShareCodePage.tsx
  src/pages/settings/Profile/ProfilePage.js
  src/styles/index.ts
Labels: Ready To Build

#36283 [CP Staging] Dismiss onboard flow when selecting option
  src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx
Labels: Ready To Build

#31055 feat: app sounds
  android/app/src/main/res/raw/attention.mp3
  android/app/src/main/res/raw/done.mp3
  android/app/src/main/res/raw/receive.mp3
  android/app/src/main/res/raw/success.mp3
  assets/sounds/attention.mp3
  assets/sounds/done.mp3
  assets/sounds/receive.mp3
  assets/sounds/success.mp3
  config/webpack/webpack.common.js
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest/setup.ts
  package-lock.json
  package.json
  patches/react-native-sound+0.11.2.patch
  src/components/MoneyTemporaryForRefactorRequestConfirmationList.js
  src/components/SettlementButton.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Notification/LocalNotification/BrowserNotifications.ts
  src/libs/Sound/config/index.native.ts
  src/libs/Sound/config/index.ts
  src/libs/Sound/index.ts
  src/libs/actions/Task.ts
  src/libs/actions/User.ts
  src/pages/home/report/ReportActionCompose/ReportActionCompose.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/tasks/NewTaskPage.js
  src/types/onyx/User.ts
Labels: Ready To Build

#36151 [New architecture] Upgrade `@react-native-clipboard/clipboard`
  __mocks__/@react-native-clipboard/clipboard.js
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#34303 Use error prop for violations for consistent styling
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/hooks/useViolations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/types.ts
  src/libs/Violations/ViolationsUtils.ts
  src/types/onyx/TransactionViolation.ts
Labels: Design

#35672 [Update Account Settings] Preferences, About, Security
  src/components/CustomStatusBarAndBackground/index.tsx
  src/components/Icon/Illustrations.ts
  src/components/LottieAnimations/index.tsx
  src/components/LottieAnimations/types.ts
  src/components/Section/index.tsx
  src/components/TestToolMenu.tsx
  src/components/TestToolRow.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/ShareCodePage.tsx
  src/pages/settings/AboutPage/AboutPage.tsx
  src/pages/settings/InitialSettingsPage.js
  src/pages/settings/Preferences/PreferencesPage.js
  src/pages/settings/Security/SecuritySettingsPage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/variables.ts
  tests/perf-test/SignInPage.perf-test.tsx
Labels: Ready To Build

#36220 Feature/35711 header invite remove button redesign
  assets/images/simple-illustrations/simple-illustration__receipt-wrangler.svg
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/WorkspaceMembersPage.js
Labels: Design

#34422 perf: smooth search transition
  src/components/LHNOptionsList/LHNOptionsList.tsx
  src/components/OptionsList/BaseOptionsList.tsx
  src/components/OptionsList/index.native.tsx
  src/pages/home/report/ReportActionsList.js
  src/pages/home/report/ReportActionsView.js
  src/pages/home/sidebar/SidebarLinks.js
Labels: Ready To Build

#35185 iOS - Login - The splash screen glitches and flashes on launch
  src/hooks/useIsSplashHidden.ts
  src/libs/Navigation/getTopmostReportId.ts
  src/pages/signin/SignInHeroImage.js
  src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.js
  tests/perf-test/SignInPage.perf-test.tsx
Labels: Ready To Build

#36280 [HybridApp] Fix NewDot internal links in HybridApp
  patches/react-native-config+1.4.6.patch
Labels: Ready To Build

#36475 [Android] Make notification content private when private mode is enabled
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
Labels: InternalQA, Ready To Build

#35544 fix: cretae seperated logo for icons
  assets/images/expensify-logo-new.svg
  assets/images/new-expensify.svg
  src/components/Icon/Expensicons.ts
  src/pages/settings/InitialSettingsPage.js
Labels: Ready To Build

#36637 Fix - display the home route when the app restarts on mobile platforms
  src/setup/index.ts
  src/setup/initializeLastVisitedPath/index.native.ts
  src/setup/initializeLastVisitedPath/index.ts
Labels: Ready To Build

#36318 Fix cursor moves to the left after pasting a number to the money request input
  src/pages/iou/steps/MoneyRequestAmountForm.js
Labels: Ready To Build

#36783 bump onfido native sdk version
  android/app/src/main/java/com/expensify/chat/MainApplication.kt
  android/build.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@onfido+react-native-sdk+10.6.0.patch
  patches/@onfido+react-native-sdk+8.3.0.patch
Labels: Ready To Build

#36565 [Audit][Implementation] getOrderedReportIDs - cache removal
  src/libs/SidebarUtils.ts
  src/pages/home/sidebar/SidebarLinksData.js
Labels: Ready To Build

#36761 Request location only when necessary in MapView
  src/components/MapView/MapView.tsx
  src/components/MapView/MapView.website.tsx
Labels: Ready To Build

#36848 Fix: When a user is mentioned, a sound is triggered. However, the current implementation plays the sound regardless of who is mentioned.
  src/libs/actions/User.ts
Labels: Ready To Build

#36056 [ECard Settings] Wallet - Clicking on Address does nothing after submitting empty phone number
  src/ROUTES.ts
  src/libs/GetPhysicalCardUtils.ts
  src/pages/settings/Wallet/Card/BaseGetPhysicalCard.tsx
  src/pages/settings/Wallet/Card/GetPhysicalCardPhone.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.js
Labels: Ready To Build

#29991 Perf/native stack navigation
  package-lock.json
  package.json
  patches/@react-navigation+native-stack+6.9.17.patch
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/AppNavigator/Navigators/Overlay/index.native.tsx
  src/libs/Navigation/AppNavigator/Navigators/Overlay/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/AppNavigator/defaultScreenOptions/index.native.ts
  src/libs/Navigation/AppNavigator/defaultScreenOptions/index.ts
  src/libs/Navigation/AppNavigator/getRightModalNavigatorOptions/index.native.ts
  src/libs/Navigation/AppNavigator/getRightModalNavigatorOptions/index.ts
  src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.ts
  src/libs/Navigation/AppNavigator/modalStackNavigatorOptions/index.native.ts
  src/libs/Navigation/AppNavigator/modalStackNavigatorOptions/index.ts
  src/libs/Navigation/PlatformStackNavigation/createPlatformStackNavigator.native.ts
  src/libs/Navigation/PlatformStackNavigation/createPlatformStackNavigator.ts
Labels: Ready To Build

#36914 fix: On full screen mode, when the video ends, the play button does nothing
  src/components/VideoPlayer/BaseVideoPlayer.js
  src/components/VideoPlayer/shouldReplayVideo.android.ts
  src/components/VideoPlayer/shouldReplayVideo.ios.ts
  src/components/VideoPlayer/shouldReplayVideo.ts
Labels: Ready To Build

#36907 Add Share page for Workspace Profile
  src/ROUTES.ts
  src/SCREENS.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/shouldAllowDownloadQRCode/index.native.ts
  src/libs/shouldAllowDownloadQRCode/index.ts
  src/libs/shouldAllowDownloadQRCode/types.ts
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspaceProfileSharePage.tsx
Labels: Ready To Build

#35931 fix: [35383] zoomed large image disappears from preview if triple tap on the bottom of the screen
  src/components/MultiGestureCanvas/index.tsx
Labels: Ready To Build

#36994 Fix: disabled tag is not displayed in the list as selected
  src/libs/OptionsListUtils.ts
Labels: Design

#36345 [Simplified Collect][Workflows] Create main workflow page (App)
  assets/images/simple-illustrations/simple-illustration__approval.svg
  assets/images/simple-illustrations/simple-illustration__receipt-envelope.svg
  assets/images/simple-illustrations/simple-illustration__wallet-alt.svg
  assets/images/simple-illustrations/simple-illustration__workflows.svg
  assets/images/workflows.svg
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Expensicons.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SetWorkspaceApprovalModeParams.ts
  src/libs/API/parameters/SetWorkspaceAutoReportingParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspacePageWithSections.tsx
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/utils/spacing.ts
  src/types/onyx/Policy.ts
Labels: Ready To Build

#36879 [NoQA] LocaleCompare util tests
  src/libs/LocaleCompare.ts
  tests/unit/LocaleCompareTest.js
Labels: Ready To Build

#34925 Mandatory exit survey for users going back to OldDot
  assets/images/product-illustrations/mushroom-top-hat.svg
  package-lock.json
  package.json
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Form/types.ts
  src/components/Icon/Illustrations.ts
  src/components/RadioButtonWithLabel.tsx
  src/components/RadioButtons.tsx
  src/components/SingleChoiceQuestion.tsx
  src/components/TextInput/BaseTextInput/types.ts
  src/components/withKeyboardState.tsx
  src/hooks/useNetwork.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SwitchToOldDotParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/NumberUtils.ts
  src/libs/actions/ExitSurvey.ts
  src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyOffline.tsx
  src/pages/settings/ExitSurvey/ExitSurveyReasonPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx
  src/pages/settings/InitialSettingsPage.js
  src/styles/variables.ts
  src/types/form/ExitSurveyReasonForm.ts
  src/types/form/ExitSurveyResponseForm.ts
  src/types/form/index.ts
Labels: Ready To Build

#35439 remove unnecessary concierge check
  src/libs/ReportUtils.ts
  src/pages/DetailsPage.tsx
Labels: InternalQA

#36807 [Android|iOS] overwrite system sound for push notifications via a custom one
  android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationProvider.java
  ios/NotificationServiceExtension/NotificationService.swift
  src/libs/Sound/playSoundExcludingMobile/index.native.ts
  src/libs/Sound/playSoundExcludingMobile/index.ts
  src/libs/actions/User.ts
Labels: InternalQA, Ready To Build

#37222 Revert "[New architecture] Upgrade `react-native-camera-roll`"
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/patches/@react-native-camera-roll+camera-roll+5.4.0.patch.patch
Labels: Ready To Build

#34409 Fix/status bar color on mweb
  src/components/CustomStatusBarAndBackground/CustomStatusBarAndBackgroundContext.tsx
  src/components/CustomStatusBarAndBackground/CustomStatusBarAndBackgroundContextProvider.tsx
  src/components/CustomStatusBarAndBackground/index.tsx
  src/libs/getSplashBackgroundColor/index.native.ts
  src/libs/getSplashBackgroundColor/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
Labels: Ready To Build

#37227 [No QA] Feature - Improve android build time
  package.json
Labels: Ready To Build

#37242 [No QA] Run pod install if firebase.json changed
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#37133 Feat/workspace categories settings
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SetWorkspaceRequiresCategoryParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesSettingsPage.tsx
Labels: Design

#37088 Improve flagging the users as texting Concierge from the OldDot on web
  src/CONST.ts
  src/libs/actions/Report.ts
Labels: InternalQA
