Repository Expensify/App, pull requests merged in 2024-04, with the labels that each got.

#36770 Fix/address page state navigation 2
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AddressForm.tsx
  src/components/Form/types.ts
  src/components/StatePicker/StateSelectorModal.tsx
  src/components/StatePicker/index.tsx
  src/components/StateSelector.tsx
  src/hooks/useGeographicalStateFromRoute.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Url.ts
  src/pages/ReimbursementAccount/AddressForm.js
  src/pages/ReimbursementAccount/BusinessInfo/substeps/IncorporationStateBusiness.tsx
  src/pages/settings/Profile/PersonalDetails/AddressPage.tsx
  src/pages/settings/Profile/PersonalDetails/StateSelectionPage.tsx
  src/pages/settings/Wallet/AddDebitCardPage.tsx
  src/stories/Form.stories.tsx
Labels: Ready To Build

#38207 perf: Cache search options
  src/App.tsx
  src/components/CategoryPicker.tsx
  src/components/OptionListContextProvider.tsx
  src/components/TagPicker/index.tsx
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/pages/NewChatPage.tsx
  src/pages/RoomInvitePage.tsx
  src/pages/SearchPage/index.tsx
  src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js
  src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
  src/pages/settings/AboutPage/ShareLogList/BaseShareLogList.tsx
  src/pages/tasks/TaskAssigneeSelectorModal.tsx
  src/pages/tasks/TaskShareDestinationSelectorModal.tsx
  src/pages/workspace/WorkspaceInvitePage.tsx
  tests/perf-test/OptionsListUtils.perf-test.ts
  tests/perf-test/SearchPage.perf-test.tsx
  tests/unit/OptionsListUtilsTest.js
Labels: Ready To Build

#39207 Fix: Indented text does not show in quotes
  package-lock.json
  package.json
Labels: Ready To Build

#39535 [CP Staging] Remove the requestIdleCallback from silentComposer
  src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx
Labels: Ready To Build

#38114 chore: bump react-native-onyx to 2.0.23
  package-lock.json
  package.json
  src/libs/Console/index.ts
  src/libs/ErrorUtils.ts
  src/libs/actions/ActiveClients.ts
  src/libs/actions/BankAccounts.ts
  src/libs/actions/CachedPDFPaths/types.ts
  src/libs/actions/Download.ts
  src/libs/actions/IOU.ts
  src/libs/actions/OnyxUpdates.ts
  src/libs/actions/ReimbursementAccount/index.ts
  src/libs/actions/Report.ts
  src/libs/actions/Transaction.ts
  src/libs/migrateOnyx.ts
  src/libs/migrations/CheckForPreviousReportActionID.ts
  src/libs/migrations/KeyReportActionsDraftByReportActionID.ts
  src/setup/index.ts
  tests/actions/IOUTest.ts
  tests/actions/PolicyTest.ts
  tests/unit/ReportActionsUtilsTest.ts
  tests/utils/wrapOnyxWithWaitForBatchedUpdates.ts
Labels: Ready To Build

#39177 Fix pasting text into main composer
  src/hooks/useHtmlPaste/index.ts
Labels: Ready To Build

#38546 feat: Add temporary focus to enabled option in workspace initial page
  src/CONST.ts
  src/components/HighlightableMenuItem.tsx
  src/components/MenuItem.tsx
  src/components/PressableWithSecondaryInteraction/index.tsx
  src/hooks/useAnimatedHighlightStyle/config.native.ts
  src/hooks/useAnimatedHighlightStyle/config.ts
  src/hooks/useAnimatedHighlightStyle/index.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
Labels: Ready To Build

#39621 [Fix] One character jumps "after" cursor when typing fast
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Composer/index.tsx
Labels: Ready To Build

#39400 fix: Fix playing Shutter Sound in Scan Receipt
  Gemfile.lock
  ios/Podfile.lock
  package-lock.json
  package.json
  src/pages/iou/request/step/IOURequestStepScan/index.native.js
Labels: Ready To Build

#39668 [CP Staging] Revert "Defer local updates if there are missing updates and only call `GetMissingOnyxMessages` once"
  src/libs/actions/OnyxUpdateManager.ts
Labels: Ready To Build

#35572 phase1: fix emoji picker refocus issue
  src/CONST.ts
  src/components/EmojiPicker/EmojiPicker.js
  src/components/Modal/BaseModal.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modal/index.android.tsx
  src/components/Modal/types.ts
  src/libs/ComposerFocusManager.ts
  src/libs/focusComposerWithDelay/index.ts
  src/libs/isWindowReadyToFocus/index.android.ts
  src/libs/isWindowReadyToFocus/index.ts
Labels: Ready To Build

#38674 Update Fallback Avatar to Support Themes
  assets/images/avatars/fallback-avatar.svg
  src/components/Avatar.tsx
  src/styles/utils/index.ts
  src/styles/utils/types.ts
Labels: Ready To Build

#37175 Remove `Save the World` from Global Create, and move it into Settings
  assets/images/simple-illustrations/simple-illustration__teachers-unite.svg
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Icon/Illustrations.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/TeachersUnite/SaveTheWorldPage.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js
  src/pages/settings/InitialSettingsPage.tsx
Labels: Ready To Build

#39896 [CP staging] fix Concierge chat flickers non-stop after redirecting from Old Dot
  src/pages/LogOutPreviousUserPage.tsx
Labels: Ready To Build

#38400 QBO import main page
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/UpdatePolicyConnectionConfigParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/pages/workspace/accounting/WorkspaceAccountingPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksChartOfAccountsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksClassesPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksCustomersPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksImportPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksLocationsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksTaxesPage.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#39854 Fix: IOU Request scan camera not displaying when permission first given
  patches/react-native-tab-view+3.5.2.patch
  src/hooks/useTabNavigatorFocus/index.ts
Labels: Ready To Build

#37909 perf: Implement filtering in search page
  src/libs/OptionsListUtils.ts
  src/libs/StringUtils.ts
  src/libs/filterArrayByMatch.ts
  src/pages/SearchPage/index.tsx
  tests/unit/OptionsListUtilsTest.ts
  tests/unit/StringUtilsTest.ts
Labels: Ready To Build

#36314 [TS migration] Migrate 'IOUEditRequestReceipt' page to TypeScript
  src/libs/Navigation/types.ts
  src/libs/actions/IOU.ts
  src/libs/fileDownload/types.ts
  src/pages/iou/ReceiptDropUI.tsx
  src/pages/iou/request/step/IOURequestStepScan/CameraPermission/index.android.tsx
  src/pages/iou/request/step/IOURequestStepScan/CameraPermission/index.ios.tsx
  src/pages/iou/request/step/IOURequestStepScan/CameraPermission/index.js
  src/pages/iou/request/step/IOURequestStepScan/CameraPermission/index.tsx
  src/pages/iou/request/step/IOURequestStepScan/CameraPermission/types.ts
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/index.tsx
  src/pages/iou/request/step/IOURequestStepScan/NavigationAwareCamera/types.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/iou/request/step/IOURequestStepScan/types.ts
  src/pages/iou/request/step/withFullTransactionOrNotFound.tsx
  src/pages/iou/request/step/withWritableReportOrNotFound.tsx
Labels: Ready To Build

#39997 Update splash theme for web
  assets/images/new-expensify-adhoc.svg
  assets/images/new-expensify-dev.svg
  assets/images/new-expensify-stg.svg
  config/webpack/webpack.common.ts
  web/index.html
Labels: Ready To Build

#40102 Fix Android build failing due to dependencies being built for wrong ABIs
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-quick-sqlite+8.0.0-beta.2.patch
Labels: Ready To Build

#37680 Clean up vbba code, save each substep and support vbbas on multiple workspaces
  src/hooks/useSubStep/index.ts
  src/hooks/useSubStep/types.ts
  src/libs/API/parameters/AcceptACHContractForBankAccount.ts
  src/libs/API/parameters/ConnectBankAccountParams.ts
  src/libs/API/parameters/OpenReimbursementAccountPageParams.ts
  src/libs/API/parameters/UpdateBeneficialOwnersForBankAccountParams.ts
  src/libs/API/parameters/UpdateCompanyInformationForBankAccountParams.ts
  src/libs/API/parameters/UpdatePersonalInformationForBankAccountParams.ts
  src/libs/API/parameters/VerifyIdentityForBankAccountParams.ts
  src/libs/actions/BankAccounts.ts
  src/pages/ReimbursementAccount/BusinessInfo/BusinessInfo.tsx
  src/pages/ReimbursementAccount/PersonalInfo/PersonalInfo.tsx
Labels: Ready To Build

#39697 [MentionsV2] Room mentions suggestions
  src/components/MentionSuggestions.tsx
  src/libs/ReportUtils.ts
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
  src/pages/home/report/ReportActionCompose/Suggestions.tsx
Labels: Ready To Build

#40180 Remove all request de-duping logic
  src/libs/API/index.ts
  src/libs/actions/App.ts
  src/libs/actions/PersistedRequests.ts
  src/libs/actions/Report.ts
  src/types/onyx/Request.ts
  tests/unit/PersistedRequests.ts
Labels: Ready To Build

#39757 [Group Chats] Add remaining features
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AvatarWithImagePicker.tsx
  src/components/ChatDetailsQuickActionsBar.tsx
  src/components/FormAlertWithSubmitButton.tsx
  src/components/Header.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/components/RoomHeaderAvatars.tsx
  src/components/SelectionList/InviteMemberListItem.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/InviteToGroupChatParams.ts
  src/libs/API/parameters/LeaveGroupChatParams.ts
  src/libs/API/parameters/OpenReportParams.ts
  src/libs/API/parameters/RemoveFromGroupChatParams.ts
  src/libs/API/parameters/UpdateGroupChatAvatarParams.ts
  src/libs/API/parameters/UpdateGroupChatMemberRolesParams.ts
  src/libs/API/parameters/UpdateGroupChatNameParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/OptionsListUtils.ts
  src/libs/PersonalDetailsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/ValidationUtils.ts
  src/libs/actions/Policy.ts
  src/libs/actions/Report.ts
  src/pages/GroupChatNameEditPage.tsx
  src/pages/InviteReportParticipantsPage.tsx
  src/pages/NewChatConfirmPage.tsx
  src/pages/NewChatPage.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/ReportParticipantDetailsPage.tsx
  src/pages/ReportParticipantRoleSelectionPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/ShareCodePage.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionItemCreated.tsx
  src/pages/home/report/ReportActionsView.tsx
  src/pages/home/report/withReportOrNotFound.tsx
  src/pages/settings/Report/ReportSettingsPage.tsx
  src/styles/index.ts
  src/types/form/NewChatNameForm.ts
  src/types/form/index.ts
  src/types/onyx/NewGroupChatDraft.ts
  src/types/onyx/Report.ts
Labels: Ready To Build

#39230 fix: move "Troubleshoot" out of About
  assets/images/simple-illustrations/simple-illustration__lightbulb.svg
  src/components/Icon/Illustrations.ts
  src/components/Section/index.tsx
  src/components/TestToolMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/settings/AboutPage/AboutPage.tsx
  src/pages/settings/AboutPage/TroubleshootPage.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Troubleshoot/TroubleshootPage.tsx
  src/styles/utils/spacing.ts
Labels: Ready To Build

#40302 [CP Staging] fix: remove sensor animation for now
  src/pages/home/report/AnimatedEmptyStateBackground.tsx
Labels: Ready To Build

#38709 Feat/track whispers
  src/CONST.ts
  src/ROUTES.ts
  src/components/MoneyTemporaryForRefactorRequestConfirmationList.tsx
  src/components/ReportActionItem/ActionableItemButtons.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CategorizeTrackedExpenseParams.ts
  src/libs/API/parameters/ConvertTrackedExpenseToRequestParams.ts
  src/libs/API/parameters/DismissTrackExpenseActionableWhisperParams.ts
  src/libs/API/parameters/ShareTrackedExpenseParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/IOUUtils.ts
  src/libs/Navigation/types.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/pages/RoomInvitePage.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js
  src/pages/iou/request/step/IOURequestStepCategory.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepDate.tsx
  src/pages/iou/request/step/IOURequestStepDescription.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/pages/iou/request/step/withFullTransactionOrNotFound.tsx
  src/pages/settings/Profile/PersonalDetails/CountrySelectionPage.tsx
  src/types/onyx/OriginalMessage.ts
  src/types/onyx/Transaction.ts
Labels: Ready To Build

#40191 feat: change new arch flash list to interop
  ios/Podfile.lock
  patches/@shopify+flash-list+1.6.3.patch
  react-native.config.js
Labels: Ready To Build

#40224 Enable live markdown in IOU request descriptions
  src/pages/iou/request/step/IOURequestStepDescription.tsx
Labels: Ready To Build

#40279 Room mentions composer
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/hooks/useMarkdownStyle.ts
Labels: Ready To Build

#39219 Authenticate with QBO
  src/CONFIG.ts
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ConnectToQuickbooksOnlineButton/index.native.tsx
  src/components/ConnectToQuickbooksOnlineButton/index.tsx
  src/components/ConnectToQuickbooksOnlineButton/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/ConnectPolicyToQuickbooksOnlineParams.ts
  src/libs/API/parameters/RemovePolicyConnectionParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/ApiUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/WorkspaceSettingsModalStackNavigator.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy.ts
  src/libs/actions/connections/QuickBooksOnline.ts
  src/libs/actions/connections/getQuickBooksOnlineSetupLink.ts
  src/libs/actions/connections/index.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksChartOfAccountsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksClassesPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksCustomersPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksImportPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksLocationsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksTaxesPage.tsx
  src/pages/workspace/accounting/qboConnectionButton/index.native.tsx
  src/pages/workspace/accounting/qboConnectionButton/index.tsx
  src/pages/workspace/accounting/qboConnectionButton/types.ts
  src/pages/workspace/withPolicyConnections.tsx
  src/types/onyx/Policy.ts
  src/types/onyx/Request.ts
Labels: Ready To Build

#40383 Revert "[CP Staging] feat: change new arch flash list to interop"
  ios/Podfile.lock
  patches/@shopify+flash-list+1.6.3.patch
  react-native.config.js
  src/pages/settings/Wallet/PaymentMethodList.tsx
Labels: Ready To Build

#39397 Block edit assignee and mark as complete simultaneously
  src/components/MenuItem.tsx
  src/components/TaskHeaderActionButton.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/settings/Profile/ProfilePage.tsx
Labels: Ready To Build

#40298 Exclude domain rooms check from canSeeDefaultRooms
  src/libs/ReportUtils.ts
Labels: Ready To Build

#40510 [CP Staging]Revert "Immediately show file size message for large attachments"
  src/components/AttachmentPicker/index.native.tsx
Labels: Ready To Build

#40547 Fix inverted flat list
  patches/react-native+0.73.4+014+fix-inverted-flatlist.patch
Labels: Ready To Build

#40560 fix: non-clickable elements on iOS
  patches/react-native-screens+3.30.1+001+fix-screen-type.patch
Labels: Ready To Build

#40599 [CP Staging] Fix: align badge in workspace list
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/styles/index.ts
Labels: Ready To Build

#39191 Export main page - initial
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/UpdatePolicyConnectionConfigParams.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/actions/connections/index.ts
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksChartOfAccountsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksClassesPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksCustomersPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksLocationsPage.tsx
  src/pages/workspace/accounting/qbo/QuickbooksTaxesPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksCompanyCardExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportDateSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportInvoiceAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseEntitySelectPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksPreferredExporterConfigurationPage.tsx
  src/styles/index.ts
  src/types/onyx/Policy.ts
Labels: Design, Ready To Build

#40760 [CP Staging] Revert "Fix here is your magic code shows briefly when login with magic link"
  src/pages/ValidateLoginPage/index.website.tsx
Labels: Ready To Build

#40390 Reusable and stylable money request amount input
  src/components/AmountForm.tsx
  src/components/AmountTextInput.tsx
  src/components/MoneyRequestAmountInput.tsx
  src/components/TextInput/BaseTextInput/index.native.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextInput/BaseTextInput/types.ts
  src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.tsx
  src/components/TextInputWithCurrencySymbol/types.ts
  src/components/TimePicker/TimePicker.tsx
  src/pages/iou/steps/MoneyRequestAmountForm.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#39944 Fix: style of page Transfer balance
  src/pages/settings/Wallet/ChooseTransferAccountPage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/settings/Wallet/TransferBalancePage.tsx
Labels: Ready To Build

#40101 Default badge style
  src/components/Badge.tsx
  src/components/EnvironmentBadge.tsx
  src/components/MenuItem.tsx
  src/pages/NewChatConfirmPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsApproverPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPayerPage.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#40501 Add logs to debug production chat loading issue
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionsView.tsx
Labels: Ready To Build

#40496 Display text on categories screen
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/withPolicyConnections.tsx
Labels: Ready To Build

#40286 [CP Staging] Chat is not scrolled to the new message on a newly created WS chat after whisper message
  src/hooks/useReportScrollManager/index.ts
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#39687 [Onboarding - Stage 2] Onboarding Flow - enabled
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/OnboardingWelcomeVideo.tsx
  src/components/TestToolMenu.tsx
  src/components/VideoPlayer/BaseVideoPlayer.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/Welcome.ts
  src/pages/OnboardEngagement/ExpensifyClassicPage.tsx
  src/pages/OnboardEngagement/ManageTeamsExpensesPage.tsx
  src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx
  src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/types/onyx/Onboarding.ts
Labels: Ready To Build

#40506 Fixes ability to mention reports for room invited users
  src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
Labels: Ready To Build

#40865 [CP Staging] Revert "Implement suggestion for edit composer"
  src/App.tsx
  src/CONST.ts
  src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.tsx
  src/components/AutoCompleteSuggestions/index.native.tsx
  src/components/AutoCompleteSuggestions/index.tsx
  src/components/AutoCompleteSuggestions/types.ts
  src/components/EmojiSuggestions.tsx
  src/libs/SuggestionUtils.ts
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
  src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/SuggestionsContext.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionCompose/SuggestionEmoji.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
  src/pages/home/report/ReportActionCompose/Suggestions.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionItemMessageEdit.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/styles/utils/index.ts
Labels: Ready To Build

#40807 [CP Staging] Changing properties being used by Fullstory
  src/ONYXKEYS.ts
  src/libs/actions/Session/index.ts
  src/libs/fullstory/index.native.ts
  src/libs/fullstory/index.ts
  src/libs/fullstory/types.ts
  src/types/onyx/UserMetadata.ts
  src/types/onyx/index.ts
Labels: Internal

#40905 fix: copy state in reanimated commit hook
  patches/react-native-reanimated+3.7.2+002+copy-state.patch
Labels: Ready To Build

#40894 [CP Staging] Revert Fullstory lib changes
  android/app/build.gradle
  android/build.gradle
  babel.config.js
  config/webpack/webpack.common.ts
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest/setup.ts
  jest/setupMockFullstoryLib.ts
  package-lock.json
  package.json
  src/ONYXKEYS.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/actions/Session/index.ts
  src/libs/fullstory/index.native.ts
  src/libs/fullstory/index.ts
  src/libs/fullstory/types.ts
  src/types/onyx/UserMetadata.ts
  src/types/onyx/index.ts
  web/gtm.js
  web/index.html
  web/thirdPartyScripts.js
Labels: Ready To Build

#40688 Onboarding fixes
  src/CONST.ts
  src/components/OnboardingWelcomeVideo.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/getOnboardingModalScreenOptions/index.native.ts
  src/libs/Navigation/getOnboardingModalScreenOptions/index.ts
  src/libs/actions/Report.ts
  src/styles/variables.ts
Labels: Ready To Build

#40924 [CP Staging] Don't include `X-Chat-Attachment-Token` header for static video thumbnails
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.tsx
Labels: Ready To Build

#40730 fix workspace list does not show
  src/components/OptionListContextProvider.tsx
Labels: Ready To Build

#40840 Update logic for categorising expenses
  src/CONST.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Policy.ts
  src/pages/OnboardingWork/BaseOnboardingWork.tsx
  src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
Labels: Ready To Build

#36420 perf: make switch between chat list and workspaces smoother
  src/App.tsx
  src/components/withCurrentReportID.tsx
  src/hooks/useReportIDs.tsx
  src/libs/SidebarUtils.ts
  src/pages/home/sidebar/SidebarLinksData.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  tests/perf-test/SidebarUtils.perf-test.ts
  tests/unit/SidebarOrderTest.ts
  tests/utils/LHNTestUtils.tsx
Labels: Ready To Build

#40570 [Search v1] Add ReportScreen to RHP
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/hooks/useIsReportOpenInRHP.ts
  src/hooks/useThumbnailDimensions.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/closeRHPFlow.ts
  src/libs/Navigation/getTopmostRouteName.ts
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Task.ts
  src/pages/home/HeaderView.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/iou/request/IOURequestStartPage.tsx
  src/styles/index.ts
  tests/perf-test/ReportActionCompose.perf-test.tsx
  tests/perf-test/ReportScreen.perf-test.tsx
Labels: Ready To Build

#40193 Improve getSearchText perf
  src/libs/OptionsListUtils.ts
Labels: Ready To Build

#40369 fix-39841: Finetune animation durations
  src/CONST.ts
  src/hooks/useAnimatedHighlightStyle/config.native.ts
  src/hooks/useAnimatedHighlightStyle/config.ts
  src/hooks/useAnimatedHighlightStyle/index.ts
  src/libs/actions/Policy.ts
Labels: Ready To Build

#41087 [CP Staging] Revert "Use fallback user avatar in cases where the user is unknown to us"
  src/components/Avatar.tsx
  src/components/AvatarWithIndicator.tsx
  src/components/MultipleAvatars.tsx
  src/components/ReportActionItem/TaskView.tsx
  src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx
  src/libs/OptionsListUtils.ts
  src/libs/PersonalDetailsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/UserUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/libs/actions/Task.ts
  src/pages/DetailsPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ReportParticipantDetailsPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/RoomMembersPage.tsx
  src/pages/home/report/ReactionList/BaseReactionList.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/home/sidebar/ProfileAvatarWithIndicator.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsApproverPage.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPayerPage.tsx
  src/types/onyx/OnyxCommon.ts
Labels: Ready To Build

#40553 fix update icons in global create and money request flows
  assets/images/coins.svg
  assets/images/receipt-scan.svg
  src/components/Icon/Expensicons.ts
  src/components/TabSelector/TabSelector.tsx
  src/libs/getIconForAction/index.ts
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
Labels: Ready To Build

#40323 Remove unnecessary platform sharding in FloatingMessageCounterContainer
  src/pages/home/report/FloatingMessageCounter.tsx
  src/pages/home/report/FloatingMessageCounter/FloatingMessageCounterContainer/index.android.tsx
  src/pages/home/report/FloatingMessageCounter/FloatingMessageCounterContainer/index.tsx
  src/pages/home/report/FloatingMessageCounter/FloatingMessageCounterContainer/types.ts
  src/styles/index.ts
Labels: Ready To Build

#38998 Update the Assigned Cards Section of the Wallet Page
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/libs/Navigation/types.ts
  src/libs/migrations/RenameCardIsVirtual.ts
  src/pages/settings/Wallet/ActivatePhysicalCardPage.tsx
  src/pages/settings/Wallet/Card/BaseGetPhysicalCard.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/settings/Wallet/ReportCardLostPage.tsx
  src/pages/settings/Wallet/ReportVirtualCardFraudPage.tsx
  src/styles/index.ts
Labels: Ready To Build

#41176 Revert "fix-39841: Finetune animation durations"
  src/CONST.ts
  src/hooks/useAnimatedHighlightStyle/config.native.ts
  src/hooks/useAnimatedHighlightStyle/config.ts
  src/hooks/useAnimatedHighlightStyle/index.ts
  src/libs/actions/Policy.ts
Labels: Ready To Build

#41258 [CP Staging] Re-add the missing changes in InitialURLContextProvider
  src/components/InitialURLContextProvider.tsx
Labels: Ready To Build

#39683 After revert: Defer local updates if there are missing updates and only call `GetMissingOnyxMessages` once
  src/libs/Network/SequentialQueue.ts
  src/libs/actions/OnyxUpdateManager/index.ts
  src/libs/actions/OnyxUpdateManager/types.ts
  src/libs/actions/OnyxUpdateManager/utils/__mocks__/applyUpdates.ts
  src/libs/actions/OnyxUpdateManager/utils/__mocks__/index.ts
  src/libs/actions/OnyxUpdateManager/utils/applyUpdates.ts
  src/libs/actions/OnyxUpdateManager/utils/deferredUpdates.ts
  src/libs/actions/OnyxUpdateManager/utils/index.ts
  src/libs/actions/__mocks__/App.ts
  src/types/onyx/OnyxUpdatesFromServer.ts
  src/utils/createProxyForObject.ts
  tests/actions/OnyxUpdateManagerTest.ts
  tests/unit/OnyxUpdateManagerTest.ts
  tests/utils/createOnyxMockUpdate.ts
Labels: Ready To Build

#39637 Generate Workspace Avatar Color based on PolicyID instead of Workspace Name
  src/components/Avatar.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/MentionSuggestions.tsx
  src/components/MultipleAvatars.tsx
  src/components/RoomHeaderAvatars.tsx
  src/components/SubscriptAvatar.tsx
  src/components/UserDetailsTooltip/types.tsx
  src/components/WorkspaceSwitcherButton.tsx
  src/libs/ReportUtils.ts
  src/pages/WorkspaceSwitcherPage/index.tsx
  src/pages/home/report/ReportActionItemFragment.tsx
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/styles/utils/index.ts
  src/types/onyx/OnyxCommon.ts
Labels: Ready To Build

#41023 Patch for WebView crash v2
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@rnmapbox+maps+10.1.11.patch
  patches/react-native+0.73.4+015+fixIOSWebViewCrash.patch
Labels: Ready To Build
