Repository Expensify/App, pull requests merged in 2024-12, with the labels that each got.

#53376 [CP Staging] fix: incorrect nav bar color
  src/App.tsx
Labels: Ready To Build

#53214 [NO QA] Update build.gradle for hybrid app adhoc builds
  .github/actions/javascript/postTestBuildComment/action.yml
  .github/actions/javascript/postTestBuildComment/index.js
  .github/actions/javascript/postTestBuildComment/postTestBuildComment.ts
  .github/workflows/testBuildHybrid.yml
  android/app/build.gradle
  fastlane/Fastfile
  tests/unit/postTestBuildComment.ts
Labels: Ready To Build

#52848 Feat: Add placeholder thumbnail to expenses with no receipt
  assets/images/receipt-placeholder-plus.svg
  src/components/Icon/Expensicons.ts
  src/components/ReceiptEmptyState.tsx
  src/components/ReceiptImage.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/ReportActionItemImage.tsx
  src/components/ReportActionItem/ReportActionItemImages.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/libs/ReceiptUtils.ts
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#53333 [Internal QA]: Fix: Logged-In Agents Can Appear to Delete Workspaces in NewDot Without Actual Deletion or Error Message
  src/components/SupportalActionRestrictedModal.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/WorkspacesListPage.tsx
Labels: InternalQA

#53388 (RN Patch) TextLayout: take full width if text wrapped
  patches/react-native+0.75.2+024+measureText-full-width-if-wraps.patch
Labels: Ready To Build

#53440 [CP Staging] fix: consume insets in Modals anyway because they are mounted in different native view hierarchy
  src/components/Modal/BaseModal.tsx
  src/components/Modal/ModalContext.ts
  src/components/ScreenWrapper.tsx
  src/components/TextPicker/TextSelectorModal.tsx
  src/components/ValidateCodeActionModal/index.tsx
  src/hooks/useStyledSafeAreaInsets.ts
Labels: Ready To Build

#53542 fix: incorrect paddings in Search popover
  src/components/PopoverMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
Labels: Ready To Build

#53536 Incorrect default feed name in feed selector
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsListHeaderButtons.tsx
Labels: InternalQA

#53550 Fix card assignment flow when members are changed
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
Labels: InternalQA

#53557 Fix going back from card provider in Company cards
  src/pages/workspace/companyCards/addNew/CardTypeStep.tsx
Labels: InternalQA

#53538 fix: remove cardList when showing assign card button
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
Labels: InternalQA, Ready To Build

#52103 Handle blocked copilot and Expensify card flows gracefully
  src/CONST.ts
  src/components/DelegateNoAccessModal.tsx
  src/components/DelegateNoAccessWrapper.tsx
  src/components/MoneyReportHeader.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/AddPersonalBankAccountPage.tsx
  src/pages/AddressPage.tsx
  src/pages/EnablePayments/EnablePayments.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/settings/ExitSurvey/ExitSurveyBookCall.tsx
  src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyReasonPage.tsx
  src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx
  src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.tsx
  src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx
  src/pages/settings/Profile/PersonalDetails/PhoneNumberPage.tsx
  src/pages/settings/Profile/ProfilePage.tsx
  src/pages/settings/Security/AddDelegate/AddDelegatePage.tsx
  src/pages/settings/Security/AddDelegate/ConfirmDelegatePage.tsx
  src/pages/settings/Security/AddDelegate/SelectDelegateRolePage.tsx
  src/pages/settings/Security/AddDelegate/UpdateDelegateRole/UpdateDelegateMagicCodePage.tsx
  src/pages/settings/Security/AddDelegate/UpdateDelegateRole/UpdateDelegateRolePage.tsx
  src/pages/settings/Security/CloseAccountPage.tsx
  src/pages/settings/Security/SecuritySettingsPage.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthPage.tsx
  src/pages/settings/Subscription/CardSection/CardSectionDataEmpty/index.tsx
  src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx
  src/pages/settings/Subscription/PaymentCard/index.tsx
  src/pages/settings/Subscription/RequestEarlyCancellationPage/index.tsx
  src/pages/settings/Subscription/SubscriptionDetails/index.tsx
  src/pages/settings/Subscription/SubscriptionSettings/index.tsx
  src/pages/settings/Subscription/SubscriptionSize/index.tsx
  src/pages/settings/Subscription/SubscriptionSize/substeps/Size.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardPageEmptyState.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/addNew/AddNewCardPage.tsx
  src/pages/workspace/companyCards/assignCard/AssignCardFeedPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardBankAccounts.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardPageEmptyState.tsx
  src/pages/workspace/expensifyCard/issueNew/IssueNewCardPage.tsx
Labels: Ready To Build

#53554 Tweak camera flash control to make it more obvious
  assets/images/bolt-slash.svg
  assets/images/bolt.svg
  src/components/Icon/Expensicons.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build

#52938 Add more search filters
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Search/SearchDateFilterBase.tsx
  src/components/Search/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/SearchParser/searchParser.js
  src/libs/SearchParser/searchParser.peggy
  src/libs/SearchQueryUtils.ts
  src/pages/Search/AdvancedSearchFilters.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersApprovedPage.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersDatePage.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersExportedPage.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersPaidPage.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersPostedPage.tsx
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersSubmittedPage.tsx
  src/types/form/SearchAdvancedFiltersForm.ts
Labels: Ready To Build

#52059 Fix - Search - When plenty of expenses are created already, haven't created expenses message shown
  src/components/Search/index.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/Search/EmptySearchView.tsx
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#52164 feat: Provide education/confirmation before creating workspaces in New Workspace flows
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/CurrencyPicker.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateWorkspaceParams.ts
  src/libs/CurrencyUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/App.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/WorkspaceSwitcherPage/WorkspaceCardCreateAWorkspace.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/workspace/WorkspaceConfirmationPage.tsx
  src/pages/workspace/WorkspaceNamePage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/types/form/WorkspaceConfirmationForm.ts
  src/types/form/index.ts
Labels: Ready To Build

#53751 Subscribe to Pusher only when it's initialized
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Pusher/pusher.ts
  tests/ui/UnreadIndicatorsTest.tsx
  tests/utils/PusherHelper.ts
Labels: Ready To Build

#53705 Incorrect default feed name in feed selector on the member details page
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
Labels: InternalQA

#53755 fix: change horizontal padding for physical card form default renderer
  src/pages/settings/Wallet/Card/BaseGetPhysicalCard.tsx
  src/pages/settings/Wallet/Card/GetPhysicalCardAddress.tsx
  src/pages/settings/Wallet/Card/GetPhysicalCardConfirm.tsx
  src/pages/settings/Wallet/Card/GetPhysicalCardName.tsx
  src/pages/settings/Wallet/Card/GetPhysicalCardPhone.tsx
Labels: Ready To Build

#53420 Prevent going back to participant page when categorizing
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/pages/iou/request/step/IOURequestStepCategory.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/workspace/upgrade/UpgradeConfirmation.tsx
Labels: Ready To Build

#53927 [NoQA] Fix createNewHybridVersion
  .github/workflows/createNewVersion.yml
Labels: CP Staging

#53385 Remove ReportConnection and ReportActionsConnection files
  src/libs/DistanceRequestUtils.ts
  src/libs/Firebase/utils.ts
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Notification/PushNotification/subscribePushNotification/index.ts
  src/libs/Parser.ts
  src/libs/ReportActionsConnection.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportConnection.ts
  src/libs/ReportUtils.ts
  src/libs/TaskUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Policy/ReportField.ts
  src/libs/actions/PriorityMode.ts
  src/libs/actions/Report.ts
  src/libs/actions/ReportActions.ts
  src/libs/actions/Task.ts
  src/libs/markAllPolicyReportsAsRead.ts
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#54028 [CP Staging] [No QA] Fix paths in deploy.yml
  .github/workflows/deploy.yml
Labels: CP Staging

#53735 Replace navigation blur listeners with `useFocusEffect`
  src/components/Button/index.tsx
  src/components/ConfirmationPage.tsx
  src/hooks/useWaitForNavigation.ts
  src/pages/workspace/upgrade/UpgradeIntro.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
  tests/ui/WorkspaceUpgradeTest.tsx
Labels: Ready To Build

#53953 Make the Create Expense flow our mainline flow
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
Labels: Ready To Build

#54064 New product training tooltips
  src/CONST.ts
  src/components/FloatingActionButton.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/components/ProductTrainingContext/PRODUCT_TRAINING_TOOLTIP_DATA.ts
  src/components/ProductTrainingContext/TOOLTIPS.ts
  src/components/ProductTrainingContext/index.tsx
  src/components/Search/SearchPageHeader.tsx
  src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx
  src/hooks/useBottomTabIsFocused.ts
  src/hooks/useOnboardingFlow.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Permissions.ts
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/variables.ts
  src/types/onyx/DismissedProductTraining.ts
Labels: Ready To Build

#53946 Fix - Adjust spacing in Global Create menu for Quick Action button
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
Labels: Ready To Build

#52483 Store receipts in stable directory on the native platforms
  src/CONST.ts
  src/libs/getReceiptsUploadFolderPath/index.android.ts
  src/libs/getReceiptsUploadFolderPath/index.ios.ts
  src/libs/getReceiptsUploadFolderPath/index.ts
  src/libs/getReceiptsUploadFolderPath/types.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
Labels: Ready To Build

#54249 Revert "fix: display all LHN options in Import state mode"
  src/ONYXKEYS.ts
  src/components/ImportOnyxState/index.native.tsx
  src/components/ImportOnyxState/index.tsx
  src/components/ImportOnyxState/types.ts
  src/components/ImportOnyxState/utils.ts
  src/libs/actions/App.ts
  src/pages/settings/Troubleshoot/TroubleshootPage.tsx
  tests/unit/ImportOnyxStateTest.ts
Labels: Ready To Build

#54244 Revert "Replace navigation blur listeners with `useFocusEffect`"
  src/components/Button/index.tsx
  src/components/ConfirmationPage.tsx
  src/hooks/useWaitForNavigation.ts
  src/pages/workspace/upgrade/UpgradeIntro.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
  tests/ui/WorkspaceUpgradeTest.tsx
Labels: Ready To Build

#53867 fix: clear previous data from Expensify Card flow
  src/libs/actions/Card.ts
  src/pages/workspace/expensifyCard/issueNew/ConfirmationStep.tsx
  src/pages/workspace/expensifyCard/issueNew/IssueNewCardPage.tsx
Labels: Ready To Build

#53754 [NoQA] fix: bottom tab transitions duration
  patches/react-native-screens+3.34.0+004+ios-custom-animations-native-transitions.patch
  src/libs/Navigation/AppNavigator/Navigators/BottomTabNavigator.tsx
  src/libs/Navigation/PlatformStackNavigation/navigationOptions/animation/fade/index.ts
  src/libs/Navigation/PlatformStackNavigation/navigationOptions/animation/index.ts
  src/libs/Navigation/PlatformStackNavigation/navigationOptions/animation/withAnimation.ts
Labels: Ready To Build

#53313 [No QA] Fix `CREATE` mutations being dropped by merging transactions
  patches/react-native+0.75.2+026+fix-dropping-mutations-in-transactions.patch
Labels: Ready To Build

#54030 fix: WS switcher blank screen, keep workspace history
  src/components/WorkspaceSwitcherButton.tsx
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/index.tsx
  src/libs/Navigation/PlatformStackNavigation/navigationOptions/animation/index.ts
  src/libs/Navigation/PlatformStackNavigation/navigationOptions/animation/none/index.native.ts
  src/libs/Navigation/switchPolicyID.ts
  src/pages/WorkspaceSwitcherPage/index.tsx
  src/pages/WorkspaceSwitcherPage/switchPolicyAfterInteractions/index.native.tsx
  src/pages/WorkspaceSwitcherPage/switchPolicyAfterInteractions/index.tsx
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx
Labels: Ready To Build

#54146 Replace all explicit `hidden` comparisons with `isHiddenParticipant()`
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/libs/actions/Report.ts
  src/libs/actions/Task.ts
  src/libs/actions/User.ts
  src/pages/ProfilePage.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/RoomInvitePage.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/settings/Report/NotificationPreferencePage.tsx
  src/pages/settings/Report/ReportSettingsPage.tsx
Labels: Ready To Build

#54250 Update react-fast-pdf to use modern pdfjs-dist
  config/webpack/webpack.common.ts
  package-lock.json
  package.json
  src/components/PDFThumbnail/index.tsx
  src/types/modules/pdf.worker.d.ts
Labels: Ready To Build

#54364 [CP Staging] fix - use the session private domain
  src/hooks/useOnboardingFlow.ts
  src/libs/Navigation/NavigationRoot.tsx
Labels: Ready To Build

#54402 [NO QA] Revert "[No QA] Adhoc builds follow ups"
  .github/workflows/testBuildHybrid.yml
  scripts/run-build.sh
Labels: CP Staging

#54392 Update SAML-SSO.md
  docs/articles/expensify-classic/domains/SAML-SSO.md
Labels: Daily

#54326 Bump react-native-live-markdown to 0.1.210
  package-lock.json
  package.json
Labels: Ready To Build

#54425 Improve feed removal flow offline
  src/libs/CardUtils.ts
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsPage.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
  src/types/onyx/CardFeeds.ts
  tests/unit/CardUtilsTest.ts
Labels: InternalQA

#54253 fix: auto insert OTP not working
  src/components/MagicCodeInput.tsx
Labels: Ready To Build

#42143 fix: messages content overlap when bottom sheet is shown
  patches/react-native-reanimated+3.16.4+001+mock-useDerivedValue-getter.patch
  src/App.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetAwareScrollViewContext.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetKeyboardSpace.tsx
  src/components/ActionSheetAwareScrollView/index.ios.tsx
  src/components/ActionSheetAwareScrollView/index.tsx
  src/components/EmojiPicker/EmojiPickerButton.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer.tsx
  src/components/KeyboardAvoidingView/index.android.tsx
  src/components/KeyboardAvoidingView/index.ios.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/PopoverMenu.tsx
  src/components/PopoverWithMeasuredContent.tsx
  src/components/ReportActionItem/MoneyRequestAction.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportActionItem/TaskPreview.tsx
  src/components/SelectionList/ChatListItem.tsx
  src/components/ShowContextMenuContext.ts
  src/components/ThreeDotsMenu/index.tsx
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.tsx
  src/hooks/useRestoreInputFocus/index.android.ts
  src/hooks/useRestoreInputFocus/index.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.native.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.ts
  src/hooks/useWorkletStateMachine/index.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build
