Repository Expensify/App, pull requests merged in 2024-10, with the labels that each got.

#49007 [A/B Testing - Create Expense] Implement Create Expense Flow under hidden Beta
  src/CONST.ts
  src/components/ReportWelcomeText.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/IOUUtils.ts
  src/libs/ReportUtils.ts
  src/libs/getIconForAction/index.ts
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/iou/request/IOURequestStartPage.tsx
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  tests/unit/IOUUtilsTest.ts
Labels: Ready To Build

#48003 feat: add labels to bottom tab bar
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/pages/home/sidebar/AvatarWithDelegateAvatar.tsx
  src/pages/home/sidebar/AvatarWithOptionalStatus.tsx
  src/pages/home/sidebar/BottomTabAvatar.tsx
  src/pages/home/sidebar/ProfileAvatarWithIndicator.tsx
  src/styles/index.ts
  src/styles/utils/positioning.ts
  src/styles/utils/spacing.ts
Labels: Ready To Build

#50038 [NoQA] fix(android): fix build issues with react-native-app-logs
  package-lock.json
  package.json
Labels: Ready To Build

#47913 De-dupe ReconnectApp in the persisted requests queue
  src/ONYXKEYS.ts
  src/libs/API/index.ts
  src/libs/Middleware/HandleUnusedOptimisticID.ts
  src/libs/Network/SequentialQueue.ts
  src/libs/ReportActionsUtils.ts
  src/libs/actions/App.ts
  src/libs/actions/PersistedRequests.ts
  src/types/onyx/Request.ts
  tests/actions/SessionTest.ts
  tests/unit/APITest.ts
  tests/unit/PersistedRequests.ts
  tests/unit/SequentialQueueTest.ts
Labels: Ready To Build

#50110 [CP Staging] fix wrong last message in LHN after message deletion
  src/libs/OptionsListUtils.ts
  src/libs/SidebarUtils.ts
Labels: Ready To Build

#50124 [CP Staging] Revert "feat: upload native logs"
  ios/NotificationServiceExtension/NotificationService.swift
  ios/Podfile
  ios/Podfile.lock
  jest/setup.ts
  package-lock.json
  package.json
  src/libs/Log.ts
Labels: Ready To Build

#49255 feat: Import onyx state
  src/ONYXKEYS.ts
  src/components/AttachmentPicker/index.native.tsx
  src/components/AttachmentPicker/types.ts
  src/components/ImportOnyxState/BaseImportOnyxState.tsx
  src/components/ImportOnyxState/index.native.tsx
  src/components/ImportOnyxState/index.tsx
  src/components/ImportOnyxState/types.ts
  src/components/ImportOnyxState/utils.ts
  src/components/ImportedStateIndicator.tsx
  src/components/ScreenWrapper.tsx
  src/components/TestToolMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ExportOnyxState/common.ts
  src/libs/actions/App.ts
  src/pages/NewChatPage.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/settings/Troubleshoot/TroubleshootPage.tsx
  src/pages/workspace/WorkspaceNewRoomPage.tsx
Labels: Ready To Build

#49434 [No QA] Callable buildAndroid workflow
  .github/actions/composite/buildAndroidE2EAPK/action.yml
  .github/workflows/buildAndroid.yml
  .github/workflows/deploy.yml
  .github/workflows/e2ePerformanceTests.yml
  .github/workflows/testBuild.yml
  fastlane/Fastfile
  package.json
Labels: Ready To Build

#49936 Fix: VisionCamera session is not deinitialized/recycled when screen gets unmounted on `native-stack`
  patches/react-native-vision-camera+4.0.0-beta.13+001+rn75-compatibility.patch
  patches/react-native-vision-camera+4.0.0-beta.13+002+native-stack-unmount-recycle-camera-session.patch
Labels: Ready To Build

#50123 [No QA] Callable buildIOS workflow
  .github/workflows/buildAndroid.yml
  .github/workflows/buildIOS.yml
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  fastlane/Fastfile
Labels: Ready To Build

#50139 disabling Jetifier
  android/app/build.gradle
  android/gradle.properties
Labels: Ready To Build

#49375 Fixes to delegate access reauthentication
  src/libs/Authentication.ts
  src/libs/actions/Delegate.ts
  src/libs/actions/Session/updateSessionUser.ts
  src/types/onyx/Response.ts
Labels: InternalQA

#50325 [NoQA] feat: bump react-native-keyboard-controller to 1.14.0 (to make it compliant with bridgeless mode)
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-keyboard-controller+1.14.0+001+disable-android.patch
Labels: Ready To Build

#48442 Add LHN debugging to Debug Mode
  src/CONST.ts
  src/components/TimePicker/TimePicker.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/DateUtils.ts
  src/libs/DebugUtils.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/actions/IOU.ts
  src/pages/Debug/DateTimeSelector.tsx
  src/pages/Debug/DebugDetails.tsx
  src/pages/Debug/Report/DebugReportPage.tsx
  src/types/form/DebugReportActionForm.ts
  src/types/form/DebugReportForm.ts
  src/types/onyx/ReportAction.ts
  tests/unit/DebugUtilsTest.ts
Labels: Ready To Build

#41242 Reduce bundle size by lazy loading map
  src/components/MapView/MapView.website.tsx
  src/components/MapView/MapViewImpl.website.tsx
  src/languages/en.ts
  src/languages/es.ts
Labels: Ready To Build

#48237 fix: Use local Onyx key to throttle location permission prompts.
  src/CONST.ts
  src/ONYXKEYS.ts
  src/libs/DateUtils.ts
  src/libs/actions/IOU.ts
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
Labels: Ready To Build

#50075 fix emoji styles
  src/pages/Search/SearchTypeMenuNarrow.tsx
Labels: Ready To Build

#50240 [No QA] perf: Resolve issues with long Android builds
  android/build.gradle
Labels: Ready To Build

#50216 [QBD] Handle the initial connection for QBD
  assets/images/integrationicons/qbd-icon-square.svg
  assets/images/laptop-with-second-screen-sync.svg
  assets/images/laptop-with-second-screen-x.svg
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ConnectToQuickbooksDesktopFlow/index.native.tsx
  src/components/ConnectToQuickbooksDesktopFlow/index.tsx
  src/components/ConnectToQuickbooksDesktopFlow/types.ts
  src/components/Icon/Expensicons.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/ConnectPolicyToQuickBooksDesktopParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/connections/QuickBooksDesktop.ts
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
  src/pages/workspace/accounting/qbd/QuickBooksDesktopSetupFlowSyncPage.tsx
  src/pages/workspace/accounting/qbd/QuickBooksDesktopSetupPage.tsx
  src/pages/workspace/accounting/qbd/RequireQuickBooksDesktopPage.tsx
  src/pages/workspace/accounting/utils.tsx
  src/styles/index.ts
  src/types/onyx/Policy.ts
  src/types/onyx/Response.ts
Labels: Ready To Build

#50206 [No QA] perf: exclude Fullstory from Android development build
  android/app/build.gradle
  src/libs/Fullstory/index.native.ts
Labels: Ready To Build

#49918 Adjust `useOnyx` selector for collections
  package-lock.json
  package.json
  src/hooks/useReportIDs.tsx
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/pages/ProfilePage.tsx
  src/utils/mapOnyxCollectionItems.ts
Labels: Ready To Build

#50047 Add inline images preview to the Live Markdown Input on the web
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Composer/index.tsx
  src/hooks/useMarkdownStyle.ts
  src/styles/variables.ts
Labels: Ready To Build

#50258 [NoQA] Request conflict resolution for OpenApp
  src/libs/actions/App.ts
  src/libs/actions/RequestConflictUtils.ts
  tests/actions/SessionTest.ts
  tests/unit/RequestConflictUtilsTest.ts
Labels: Ready To Build

#49984 Use SearchRouter everywhere and drop Chat finder
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/HeaderWithBackButton/index.tsx
  src/components/Search/SearchRouter/SearchButton.tsx
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/components/Search/SearchRouter/SearchRouterContext.tsx
  src/components/Search/SearchRouter/SearchRouterInput.tsx
  src/components/Search/SearchRouter/SearchRouterList.tsx
  src/components/Search/SearchRouter/SearchRouterModal.tsx
  src/libs/E2E/reactNativeLaunchingTest.ts
  src/libs/E2E/tests/openSearchRouterTest.e2e.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/Navigators/LeftModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/Navigation/AppNavigator/createCustomPlatformStackBottomTabNavigator/TopBar.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/Permissions.ts
  src/pages/ChatFinderPage/ChatFinderPageFooter.tsx
  src/pages/ChatFinderPage/index.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx
  src/styles/index.ts
  src/styles/utils/spacing.ts
  src/styles/variables.ts
  tests/e2e/config.ts
  tests/perf-test/SearchRouter.perf-test.tsx
Labels: Ready To Build

#50137 Add the Download option to the report details screen
  src/CONST.ts
  src/libs/API/parameters/ExportReportCSVParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Report.ts
  src/pages/ReportDetailsPage.tsx
Labels: Ready To Build

#51064 Fix android input focus in the search router component
  src/components/Search/SearchRouter/SearchRouterInput.tsx
Labels: Ready To Build

#51098 fix: do not show spinner if data is already there
  src/pages/home/ReportScreen.tsx
Labels: Ready To Build

#51226 [CP Staging] [Firebase] replace empty string with `'N/A'`
  src/libs/Firebase/utils.ts
Labels: Ready To Build, CP Staging

#45379 fix: Attachment - Press enter fullscreen mode in video player by Tab
  src/components/VideoPlayer/IconButton.tsx
Labels: Ready To Build

#51245 Revert "[A/B Testing][ESLint Clean Up] Use useOnyx cases for files in combinedTrackSubmit"
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/workspace/AccessOrNotFoundWrapper.tsx
Labels: Ready To Build, CP Staging

#50565 Update Invoices setting screen
  src/components/ConnectBankAccountButton.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/invoices/WorkspaceInvoiceBalanceSection.tsx
  src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx
  src/pages/workspace/invoices/WorkspaceInvoicesFirstSection.tsx
  src/pages/workspace/invoices/WorkspaceInvoicesNoVBAView.tsx
  src/pages/workspace/invoices/WorkspaceInvoicesPage.tsx
  src/pages/workspace/invoices/WorkspaceInvoicesVBAView.tsx
  src/pages/workspace/invoices/WorkspaceInvoicingDetailsSection.tsx
Labels: Ready To Build

#51225 Changed default visibility for caret - ListItemRightCaretWithLabel
  src/components/SelectionList/ListItemRightCaretWithLabel.tsx
  src/components/SelectionListWithModal/CustomListHeader.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx
  src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
  src/pages/workspace/taxes/WorkspaceTaxesPage.tsx
Labels: Ready To Build

#51169 Updated the height of the LHN navigation items from 56px to 52px.
  src/components/MenuItem.tsx
  src/pages/Search/SavedSearchItemThreeDotMenu.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/styles/index.ts
Labels: Ready To Build

#51288 Send `delegate` with every request if a user is logged in as one
  src/libs/Network/enhanceParameters.ts
Labels: InternalQA

#51590 Revert "Revert "Revert "Search suffix tree implementation"""
  src/CONST.ts
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/libs/FastSearch.ts
  src/libs/OptionsListUtils.ts
  src/libs/SuffixUkkonenTree/index.ts
  src/libs/SuffixUkkonenTree/utils.ts
  tests/unit/FastSearchTest.ts
  tests/unit/SuffixUkkonenTreeTest.ts
Labels: Ready To Build

#51456 Remove date time format polyfil
  src/libs/IntlPolyfill/index.ios.ts
Labels: Ready To Build

#51237 Provide autocomplete suggestions in SearchRouterList
  src/CONST.ts
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/components/Search/SearchRouter/SearchRouterInput.tsx
  src/components/Search/SearchRouter/SearchRouterList.tsx
  src/components/Search/types.ts
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/Search/SearchQueryListItem.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/SearchAutocompleteUtils.ts
  src/libs/SearchQueryUtils.ts
Labels: Ready To Build

#51202 Add regex to TextInput
  patches/react-native+0.75.2+018+Add-regex-to-TextInput.patch
  src/components/AmountForm.tsx
  src/components/AmountTextInput.tsx
  src/components/AmountWithoutCurrencyForm.tsx
  src/components/MoneyRequestAmountInput.tsx
  src/components/TextInputWithCurrencySymbol/types.ts
  src/libs/MoneyRequestUtils.ts
Labels: Ready To Build

#51180 fix owner tooltip for expense reports
  src/libs/ReportUtils.ts
  src/pages/home/report/ReportActionItemSingle.tsx
Labels: Ready To Build
