Repository Expensify/App, pull requests merged in 2024-07, with the labels that each got.

#43448 Fix last synced message
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/accounting/PolicyAccountingPage.tsx
Labels: Ready To Build

#44549 [NO QA]: Workspace Feed - Expensify Card
  src/CONST.ts
  src/ROUTES.ts
  src/components/FocusTrap/WIDE_LAYOUT_INACTIVE_SCREENS.ts
  src/components/Switch.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/EnablePolicyExpensifyCardsParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardPage.tsx
  src/pages/workspace/withPolicy.tsx
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#44427 Bump react-native-screens
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-screens+3.30.1+001+fix-screen-type.patch
Labels: Ready To Build

#44708 [CP Staging] Revert "Create usePaginatedReportActions hook"
  src/hooks/usePaginatedReportActions.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/home/ReportScreen.tsx
  tests/ui/UnreadIndicatorsTest.tsx
  tests/utils/TestHelper.ts
Labels: Ready To Build

#44469 [No QA] [Workspace Feeds] Create new Card List page
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/OpenPolicyExpensifyCardsPageParams.ts
  src/libs/API/parameters/RequestExpensifyCardLimitIncreaseParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceCardListHeader.tsx
  src/pages/workspace/expensifyCard/WorkspaceCardListRow.tsx
  src/pages/workspace/expensifyCard/WorkspaceCardsListLabel.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardPage.tsx
  src/styles/utils/flex.ts
  src/types/onyx/BankAccount.ts
  src/types/onyx/Card.ts
  src/types/onyx/ExpensifyCardSettings.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#43985 Fix RHP slide animation when opening sign in modal
  src/components/FocusTrap/FocusTrapForScreen/index.web.tsx
  src/components/FocusTrap/SCREENS_WITH_AUTOFOCUS.ts
  src/pages/signin/LoginForm/BaseLoginForm.tsx
Labels: Ready To Build

#44275 Implement the policy report fields creation flow
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ButtonWithDropdownMenu/types.ts
  src/components/Form/types.ts
  src/components/TextPicker/TextSelectorModal.tsx
  src/components/TextPicker/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateWorkspaceReportFieldParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/WorkspaceReportFieldsUtils.ts
  src/libs/actions/Policy/ReportFields.ts
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx
  src/pages/workspace/reportFields/InitialListValueSelector/InitialListValueSelectorModal.tsx
  src/pages/workspace/reportFields/InitialListValueSelector/index.tsx
  src/pages/workspace/reportFields/ReportFieldAddListValuePage.tsx
  src/pages/workspace/reportFields/ReportFieldEditValuePage.tsx
  src/pages/workspace/reportFields/ReportFieldListValuesPage.tsx
  src/pages/workspace/reportFields/ReportFieldTypePicker/index.tsx
  src/pages/workspace/reportFields/TypeSelector/TypeSelectorModal.tsx
  src/pages/workspace/reportFields/TypeSelector/index.tsx
  src/pages/workspace/reportFields/ValueSettingsPage.tsx
  src/pages/workspace/reportFields/WorkspaceCreateReportFieldPage.tsx
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
  src/pages/workspace/tags/WorkspaceViewTagsPage.tsx
  src/pages/workspace/taxes/WorkspaceTaxesPage.tsx
  src/pages/workspace/withPolicy.tsx
  src/styles/utils/spacing.ts
  src/types/form/WorkspaceReportFieldsForm.ts
  src/types/form/index.ts
  tests/actions/ReportFieldsTest.ts
Labels: Ready To Build

#43620 Image zoom for mobile browser apps
  src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPagerContext.ts
  src/components/Attachments/AttachmentCarousel/Pager/index.tsx
  src/components/Attachments/AttachmentCarousel/index.native.tsx
  src/components/Attachments/AttachmentCarousel/index.tsx
  src/components/Attachments/AttachmentCarousel/useCarouselArrows.ts
  src/components/Attachments/AttachmentCarousel/useCarouselContextEvents.ts
  src/components/ImageView/index.tsx
  src/components/MultiGestureCanvas/index.tsx
  src/components/MultiGestureCanvas/usePanGesture.ts
  src/styles/index.ts
Labels: Ready To Build

#44819 fix: list not scrolling to the linked report action
  src/CONST.ts
  src/libs/Permissions.ts
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
Labels: Ready To Build

#44671 [Details Revamp] Allow Editing Report Title from Details Page
  src/components/MenuItem.tsx
  src/components/ReportActionItem/MoneyReportView.tsx
  src/libs/ReportUtils.ts
  src/pages/ReportDetailsPage.tsx
Labels: Ready To Build

#44025 [Details Revamp] Remove the Three Dot Menu on Affected Reports
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/pages/ProfilePage.tsx
  src/pages/home/HeaderView.tsx
Labels: Ready To Build

#44891 [CP Staging] Revert "Add Pay as Business option for invoices sent to an individual who is admin of their primary workspace"
  src/components/MoneyReportHeader.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/SettlementButton.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/PayInvoiceParams.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/home/report/ReportActionItemSingle.tsx
Labels: Ready To Build

#44902 Add new read commands for the workspace profile and initial settings pages - v2
  src/libs/API/parameters/OpenPolicyInitialPageParams.ts
  src/libs/API/parameters/OpenPolicyProfilePageParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceProfilePage.tsx
  src/pages/workspace/withPolicy.tsx
Labels: Ready To Build

#44840 fix RHP animation on Safari
  src/libs/Navigation/AppNavigator/ModalStackNavigators/useModalScreenOptions.ts
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
Labels: Ready To Build

#43822 Add workspace upgrade flow
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ConfirmationPage.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/UpgradeToCorporateParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/upgrade/UpgradeConfirmation.tsx
  src/pages/workspace/upgrade/UpgradeIntro.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
  src/styles/index.ts
  src/types/onyx/Policy.ts
Labels: Ready To Build

#44529 One-expense-report old chat messages stays in chat
  src/libs/ReportActionsUtils.ts
  src/pages/home/report/ReportActionItemContentCreated.tsx
  src/pages/home/report/ReportActionsView.tsx
Labels: Ready To Build

#44068 perf: improve native apps startup
  .github/workflows/reassurePerformanceTests.yml
  src/hooks/useReportIDs.tsx
  src/libs/DistanceRequestUtils.ts
  src/libs/ModifiedExpenseMessage.ts
  src/libs/Navigation/Navigation.ts
  src/libs/Notification/PushNotification/subscribePushNotification/index.ts
  src/libs/OnyxAwareParser.ts
  src/libs/OptionsListUtils.ts
  src/libs/PersonalDetailsUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportConnection.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/TaskUtils.ts
  src/libs/TransactionUtils.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/libs/WorkspacesSettingsUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/PriorityMode.ts
  src/libs/actions/Report.ts
  src/libs/actions/ReportActions.ts
  src/libs/actions/Task.ts
  src/libs/actions/Welcome.ts
  src/libs/markAllPolicyReportsAsRead.ts
  src/libs/migrations/Participants.ts
  src/pages/home/sidebar/SidebarLinksData.tsx
  tests/perf-test/SidebarUtils.perf-test.ts
  tests/unit/SidebarOrderTest.ts
  tests/unit/UnreadIndicatorUpdaterTest.ts
Labels: Ready To Build

#44973 Fix missing title and details in report details page
  src/pages/ReportDetailsPage.tsx
Labels: Ready To Build

#44677 fix: Design updates to Search rows on mobile
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/libs/StringUtils.ts
Labels: Ready To Build

#44767 fix: render Mapbox.MapView when access token is correctly set
  src/components/MapView/MapView.tsx
Labels: Ready To Build

#44955 perf: remove `useLastAccessedReportID` hook and call `findLastAccessedReport` only when needed
  src/hooks/useLastAccessedReportID.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/pages/home/ReportScreen.tsx
  tests/perf-test/ReportUtils.perf-test.ts
Labels: Ready To Build

#44262 Bump expensify-common and react-native-live-markdown
  .github/actions/javascript/bumpVersion/index.js
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#44883 Fix smaller file preview when opening PDF attachment while keyboard is open
  package-lock.json
  package.json
Labels: Ready To Build

#41725 [Search v1] Add handling of actions and improve Search list items
  src/App.tsx
  src/CONST.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ReceiptImage.tsx
  src/components/Search/SearchContext.tsx
  src/components/Search/index.tsx
  src/components/Search/types.ts
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/SearchTableHeader.tsx
  src/components/SelectionList/SortableHeaderText.tsx
  src/components/ThumbnailImage.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/Search.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/SearchUtils.ts
  src/libs/actions/Search.ts
  src/pages/Search/SearchHoldReasonPage.tsx
  src/pages/iou/HoldReasonFormView.tsx
  src/pages/iou/HoldReasonPage.tsx
  src/types/onyx/SearchResults.ts
Labels: Ready To Build

#41667 fix: tapping assignee and mark as complete quickly navigates to not found page
  src/components/ReportActionItem/TaskView.tsx
  src/components/TaskHeaderActionButton.tsx
  src/libs/TaskUtils.ts
Labels: Ready To Build

#44137 Empty State Component for Search
  assets/images/simple-illustrations/simple-illustration__empty-state.svg
  src/CONST.ts
  src/components/AccountingListSkeletonView.tsx
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/components/Icon/Illustrations.ts
  src/components/OptionsListSkeletonView.tsx
  src/components/Search/index.tsx
  src/components/Skeletons/ItemListSkeletonView.tsx
  src/components/Skeletons/SearchRowSkeleton.tsx
  src/components/Skeletons/TableRowSkeleton.tsx
  src/pages/Search/EmptySearchView.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
Labels: Ready To Build

#45186 Filter out paycheck report on LHN
  src/CONST.ts
  src/libs/ReportUtils.ts
  tests/unit/SidebarFilterTest.ts
Labels: InternalQA

#45135 Fix some part of popover isn't clickable when near the desktop header
  src/components/PopoverWithoutOverlay/index.tsx
Labels: Ready To Build

#44820 [Search] Selection Mode for small screens
  src/components/Button/index.tsx
  src/components/Search/SearchListWithHeader.tsx
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/index.tsx
  src/components/SelectionList/BaseListItem.tsx
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/Search/SearchSelectedNarrow.tsx
Labels: Ready To Build

#44958 Bump react-native-live-markdown
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/@expensify+react-native-live-markdown+0.1.91.patch
  src/hooks/useHtmlPaste/index.ts
Labels: Ready To Build

#39875 Improve location permission handling
  assets/images/simple-illustrations/simple-illustration__receipt-location-marker.svg
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ConfirmContent.tsx
  src/components/ConfirmModal.tsx
  src/components/Icon/Illustrations.ts
  src/components/LocationPermissionModal/index.android.tsx
  src/components/LocationPermissionModal/index.tsx
  src/components/LocationPermissionModal/types.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepScan/LocationPermission/index.android.ts
  src/pages/iou/request/step/IOURequestStepScan/LocationPermission/index.ios.ts
  src/pages/iou/request/step/IOURequestStepScan/LocationPermission/index.ts
Labels: Ready To Build

#42897 Reset amount on reset button click
  src/components/MoneyRequestAmountInput.tsx
  src/components/MoneyRequestConfirmationList.tsx
Labels: Ready To Build

#45299 Revert "Fix show onboarding modal functions"
  src/CONST.ts
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/Navigation/types.ts
  src/libs/NavigationUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Welcome.ts
  src/libs/hasCompletedGuidedSetupFlowSelector.ts
  src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/pages/OnboardingPurpose/types.ts
  src/pages/OnboardingWork/BaseOnboardingWork.tsx
  tests/ui/UnreadIndicatorsTest.tsx
Labels: Ready To Build

#44483 [Free trial] Implement and show Trial Ended banner, Expensify DM GBR and custom Expensify DM chat item in the App after Free Trial ends
  assets/images/simple-illustrations/simple-illustration__tire.svg
  src/CONST.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/shouldRenderAppPaymentCard/index.native.ts
  src/libs/shouldRenderAppPaymentCard/index.ts
  src/libs/shouldRenderAppPaymentCard/types.ts
  src/pages/home/report/ReportActionItem.tsx
  src/pages/settings/Subscription/CardSection/BillingBanner/TrialEndedBillingBanner.tsx
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/types/onyx/OriginalMessage.ts
Labels: Ready To Build

#44674 fix: update grouped expense on search page
  src/components/Button/index.tsx
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/SelectionList/SearchTableHeader.tsx
  src/styles/index.ts
  src/styles/utils/sizing.ts
Labels: Ready To Build

#44807 Change high resolution image with preview
  src/CONST.ts
  src/components/AttachmentModal.tsx
  src/components/Attachments/AttachmentCarousel/CarouselItem.tsx
  src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPagerContext.ts
  src/components/Attachments/AttachmentCarousel/Pager/index.tsx
  src/components/Attachments/AttachmentCarousel/extractAttachments.ts
  src/components/Attachments/AttachmentView/DefaultAttachmentView/index.tsx
  src/components/Attachments/AttachmentView/HighResolutionInfo.tsx
  src/components/Attachments/AttachmentView/index.tsx
  src/components/Attachments/types.ts
  src/components/Lightbox/index.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/fileDownload/FileUtils.ts
  src/styles/utils/getHighResolutionInfoWrapperStyle/index.native.ts
  src/styles/utils/getHighResolutionInfoWrapperStyle/index.ts
  src/styles/utils/getHighResolutionInfoWrapperStyle/types.ts
  src/styles/utils/index.ts
Labels: Ready To Build

#45335 [CP Staging] fix: frequent component re-mount
  src/libs/freezeScreenWithLazyLoading.tsx
Labels: Ready To Build

#45332 [NO QA] Attempt to fix Android builds with ruby workaround
  .github/workflows/platformDeploy.yml
  .github/workflows/testBuild.yml
  patches/@react-native-community+netinfo+11.2.1+002+turbomodule.patch
Labels: Ready To Build

#45389 [No QA] Fix missing parts of react-native-community/netinfo patch
  patches/@react-native-community+netinfo+11.2.1+002+turbomodule.patch
Labels: Ready To Build

#45314 Make Slider Transformation Function Callback a worklet
  src/components/AvatarCropModal/Slider.tsx
Labels: Ready To Build

#45155 [No QA] Create new Card Details page
  src/ROUTES.ts
  src/SCREENS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/workspace/card/issueNew/ConfirmationStep.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx
  src/styles/index.ts
  src/types/onyx/Card.ts
Labels: Ready To Build

#45426 Check for hybrid app when completing onboarding
  src/components/HybridAppMiddleware/index.tsx
Labels: Ready To Build

#44059 [Wave Collect][Xero] Enforce 2FA for xero
  .storybook/webpack.config.ts
  src/Expensify.tsx
  src/ROUTES.ts
  src/components/ConnectToXeroButton/index.native.tsx
  src/components/ConnectToXeroButton/index.tsx
  src/components/RequireTwoFactorAuthenticationModal.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/pages/settings/Security/TwoFactorAuth/Steps/SuccessStep.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx
  src/types/onyx/Account.ts
Labels: Ready To Build

#44724 Fix "New messages" banner shows up every time sending a message in a chat
  src/components/PopoverMenu.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#45562 [No QA] Upgrade electron-builder
  package-lock.json
  package.json
Labels: Ready To Build

#45614 Add Export CSV and handle offline for all actions
  src/CONST.ts
  src/components/DecisionModal.tsx
  src/components/Search/SearchActionOptionsUtils.desktop.tsx
  src/components/Search/SearchActionOptionsUtils.native.tsx
  src/components/Search/SearchActionOptionsUtils.tsx
  src/components/Search/SearchListWithHeader.tsx
  src/components/Search/SearchPageHeader.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/ExportSearchItemsToCSVParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Search.ts
  src/libs/fileDownload/index.ts
  src/libs/fileDownload/types.ts
Labels: Ready To Build

#45649 Revert "[Wave Collect][Xero] Enforce 2FA for xero"
  .storybook/webpack.config.ts
  src/Expensify.tsx
  src/ROUTES.ts
  src/components/ConnectToXeroButton/index.native.tsx
  src/components/ConnectToXeroButton/index.tsx
  src/components/RequireTwoFactorAuthenticationModal.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/pages/settings/Security/TwoFactorAuth/Steps/SuccessStep.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx
  src/types/onyx/Account.ts
Labels: Ready To Build

#39072 Add displaying svg logos inside QR code
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/QRCode.tsx
  src/components/QRShare/index.tsx
  src/components/QRShare/types.ts
  src/libs/ReportUtils.ts
  src/pages/ShareCodePage.tsx
  src/pages/home/report/ReportDetailsShareCodePage.tsx
  src/pages/workspace/WorkspaceProfileSharePage.tsx
Labels: Ready To Build

#45664 Full screen Composer, reaplying
  src/styles/index.ts
Labels: Ready To Build

#45688 Fullstory Asset Uploader build phase added.
  ios/NewExpensify.xcodeproj/project.pbxproj
Labels: InternalQA

#44531 Pick only params from route before passing them to screen
  src/ROUTES.ts
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/getTopmostFullScreenRoute.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/linkingConfig/createNormalizedConfigs.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Navigation/switchPolicyID.ts
  src/pages/Search/SearchFilters.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/settings/Subscription/CardSection/CardSection.tsx
Labels: Ready To Build

#45327 Dismissing onboarding fix
  src/CONST.ts
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/Navigation/types.ts
  src/libs/NavigationUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Welcome.ts
  src/libs/hasCompletedGuidedSetupFlowSelector.ts
  src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx
  src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx
  src/pages/OnboardingPurpose/types.ts
  src/pages/OnboardingWork/BaseOnboardingWork.tsx
  tests/ui/UnreadIndicatorsTest.tsx
Labels: Ready To Build

#42571 Feat/dupe detection confirmation
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/hooks/useReviewDuplicatesNavigation.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/TransactionMergeParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/TransactionUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Transaction.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/TransactionDuplicate/ReviewBillable.tsx
  src/pages/TransactionDuplicate/ReviewCategory.tsx
  src/pages/TransactionDuplicate/ReviewDescription.tsx
  src/pages/TransactionDuplicate/ReviewFields.tsx
  src/pages/TransactionDuplicate/ReviewMerchant.tsx
  src/pages/TransactionDuplicate/ReviewReimbursable.tsx
  src/pages/TransactionDuplicate/ReviewTag.tsx
  src/pages/TransactionDuplicate/ReviewTaxCode.tsx
  src/types/onyx/ReviewDuplicates.ts
  src/types/onyx/Transaction.ts
Labels: Ready To Build

#45757 Return early if the hybrid module is not defined
  src/components/HybridAppMiddleware/index.ios.tsx
Labels: InternalQA, Ready To Build

#45593 [Search] Export CSV on native devices
  src/components/Search/SearchActionOptionsUtils.desktop.tsx
  src/components/Search/SearchActionOptionsUtils.native.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/libs/fileDownload/DownloadUtils.ts
  src/libs/fileDownload/index.android.ts
  src/libs/fileDownload/index.desktop.ts
  src/libs/fileDownload/index.ios.ts
  src/libs/fileDownload/index.ts
Labels: Ready To Build

#45776 Capture navigation logs to build breadcrumbs in Crashlytics
  src/libs/Firebase/index.native.ts
  src/libs/Firebase/index.ts
  src/libs/Firebase/types.ts
  src/libs/Navigation/NavigationRoot.tsx
Labels: InternalQA

#45702 [Wave Collect][Xero] Enforce 2FA for xero
  .storybook/webpack.config.ts
  src/Expensify.tsx
  src/ROUTES.ts
  src/components/ConnectToXeroButton/index.native.tsx
  src/components/ConnectToXeroButton/index.tsx
  src/components/RequireTwoFactorAuthenticationModal.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/types.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/pages/settings/Security/TwoFactorAuth/Steps/SuccessStep.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx
  src/types/onyx/Account.ts
Labels: Ready To Build

#45415 [No QA] Card settings page
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/FormHelpMessage.tsx
  src/components/MenuItem.tsx
  src/components/SelectionList/RadioListItem.tsx
  src/components/SelectionList/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/BankAccountUtils.ts
  src/libs/CardUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Card.ts
  src/pages/workspace/accounting/reconciliation/CardReconciliationPage.tsx
  src/pages/workspace/accounting/reconciliation/ReconciliationAccountSettingsPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceCardSettingsPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardBankAccounts.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceSettlementAccountPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceSettlementFrequencyPage.tsx
  src/types/onyx/ExpensifyCardSettings.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#45863 [CP Staging] Revert "Add support for viewing full screen Group Chat custom avatars"
  src/ROUTES.ts
  src/components/AvatarWithImagePicker.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/pages/NewChatConfirmPage.tsx
  src/pages/ReportAvatar.tsx
  src/pages/ReportDetailsPage.tsx
  src/types/onyx/Report.ts
Labels: Ready To Build

#45918 [CP Staging] Backport a fix for `react-native-gesture-handler`
  patches/react-native-gesture-handler+2.14.1.patch
Labels: Ready To Build

#45690 [No QA] Empty state modal
  assets/images/emptystate__expensifycard.svg
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/components/Icon/Illustrations.ts
  src/components/Skeletons/CardRowSkeleton.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/Card.ts
  src/pages/workspace/card/issueNew/AssigneeStep.tsx
  src/pages/workspace/expensifyCard/EmptyCardView.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardBankAccounts.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardListPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardPageEmptyState.tsx
Labels: Ready To Build

#45040 Missing Save & continue button on 'Choose your bank account'
  src/pages/AddPersonalBankAccountPage.tsx
Labels: Ready To Build

#45922 [CP Staging] fix description is not displayed
  src/components/ReportActionItem/MoneyRequestView.tsx
Labels: Ready To Build

#43868 General purpose memoization tool
  .eslintrc.js
  package-lock.json
  src/components/ProfilingToolMenu/BaseProfilingToolMenu.tsx
  src/components/Search/index.tsx
  src/libs/EmojiUtils.ts
  src/libs/LocaleDigitUtils.ts
  src/libs/NumberFormatUtils/index.ts
  src/libs/NumberFormatUtils/intlPolyfill.ios.ts
  src/libs/NumberFormatUtils/intlPolyfill.ts
  src/libs/UnreadIndicatorUpdater/index.ts
  src/libs/freezeScreenWithLazyLoading.tsx
  src/libs/memoize/cache/ArrayCache.ts
  src/libs/memoize/cache/types.ts
  src/libs/memoize/const.ts
  src/libs/memoize/index.ts
  src/libs/memoize/stats.ts
  src/libs/memoize/types.ts
  src/libs/memoize/utils.ts
  src/types/utils/TupleOperations.ts
  tests/unit/memoizeTest.ts
Labels: Ready To Build

#46070 [CP Staging] Revert "Merge pull request #44432 from margelo/feat/release-profiler-on-web"
  .github/workflows/platformDeploy.yml
  README.md
  config/webpack/webpack.dev.ts
  desktop/electron-serve.ts
  desktop/main.ts
  desktop/package-lock.json
  desktop/package.json
  package-lock.json
  package.json
  patches/http-server+14.1.1.patch
  scripts/build-desktop.sh
  scripts/combine-web-sourcemaps.ts
  scripts/release-profile.ts
  src/components/ClientSideLoggingToolMenu/BaseClientSideLoggingToolMenu.tsx
  src/components/ClientSideLoggingToolMenu/index.tsx
  src/components/ProfilingToolMenu/BaseProfilingToolMenu.tsx
  src/components/ProfilingToolMenu/RNFS/index.ts
  src/components/ProfilingToolMenu/RNFS/index.web.ts
  src/components/ProfilingToolMenu/Share/index.ts
  src/components/ProfilingToolMenu/Share/index.web.ts
  src/components/ProfilingToolMenu/index.android.tsx
  src/components/ProfilingToolMenu/index.ios.tsx
  src/components/ProfilingToolMenu/index.tsx
  web/proxy.ts
  workflow_tests/assertions/platformDeployAssertions.ts
  workflow_tests/mocks/platformDeployMocks.ts
Labels: Ready To Build

#45620 Prevent initial focus when the screen cannot be focused.
  src/components/FocusTrap/FocusTrapForScreen/index.web.tsx
Labels: Ready To Build

#44763 [Payment history] add "Request early cancelation" menu item to the Subscription page (UI)
  assets/images/calendar-solid.svg
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/FeedbackSurvey.tsx
  src/components/Icon/Expensicons.ts
  src/hooks/useCancellationType.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CancelBillingSubscriptionParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/actions/Subscription.ts
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.native.tsx
  src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx
  src/pages/settings/Subscription/RequestEarlyCancellationPage/index.native.tsx
  src/pages/settings/Subscription/RequestEarlyCancellationPage/index.tsx
  src/types/onyx/CancellationDetails.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#45384 fix: Individually selected expense rows in grouped reports don't have a background color applied to them.
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/ReportListItem.tsx
  src/styles/utils/spacing.ts
Labels: Ready To Build

#46191 Add files via upload
  docs/assets/images/Itinerary.png
Labels: Design

#45681 Feature: A new section in the workspace member’s details
  src/languages/en.ts
  src/languages/es.ts
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#44761 Fix: Add more space to bottom docked button
  src/components/FormAlertWithSubmitButton.tsx
  src/hooks/useSafePaddingBottomStyle.ts
  src/pages/iou/request/step/IOURequestStepDate.tsx
Labels: Ready To Build

#41115 Use Font XML resources and standardise font usage on native platforms
  .storybook/fonts.css
  .storybook/theme.ts
  android/app/src/main/java/com/expensify/chat/MainApplication.kt
  android/app/src/main/res/font/expensify_mono.xml
  android/app/src/main/res/font/expensify_neue.xml
  android/app/src/main/res/font/expensify_new_kansas.xml
  android/app/src/main/res/font/expensifymono_bold.otf
  android/app/src/main/res/font/expensifymono_regular.otf
  android/app/src/main/res/font/expensifyneue_bold.otf
  android/app/src/main/res/font/expensifyneue_bolditalic.otf
  android/app/src/main/res/font/expensifyneue_italic.otf
  android/app/src/main/res/font/expensifyneue_regular.otf
  android/app/src/main/res/font/expensifynewkansas_medium.otf
  android/app/src/main/res/font/expensifynewkansas_mediumitalic.otf
  android/app/src/main/res/font/expneuebold.otf
  android/app/src/main/res/font/expneueregular.otf
  android/app/src/main/res/values/styles.xml
  android/link-assets-manifest.json
  assets/README.md
  assets/css/fonts.css
  docs/_sass/_fonts.scss
  docs/_sass/_main.scss
  docs/_sass/_search-bar.scss
  ios/link-assets-manifest.json
  src/components/EnvironmentBadge.tsx
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/CodeRenderer.tsx
  src/components/Onfido/BaseOnfidoWeb.tsx
  src/components/Text.tsx
  src/hooks/useMarkdownStyle.ts
  src/pages/home/HeaderView.tsx
  src/styles/index.ts
  src/styles/utils/FontUtils/fontFamily/bold/index.android.ts
  src/styles/utils/FontUtils/fontFamily/bold/index.ios.ts
  src/styles/utils/FontUtils/fontFamily/bold/index.ts
  src/styles/utils/FontUtils/fontFamily/bold/types.ts
  src/styles/utils/FontUtils/fontFamily/multiFontFamily.ts
  src/styles/utils/FontUtils/fontFamily/multiFontFamily/index.native.ts
  src/styles/utils/FontUtils/fontFamily/multiFontFamily/index.ts
  src/styles/utils/FontUtils/fontFamily/singleFontFamily.ts
  src/styles/utils/FontUtils/fontFamily/singleFontFamily/index.ts
  src/styles/utils/FontUtils/fontFamily/types.ts
  src/styles/utils/FontUtils/fontWeight/bold/index.android.ts
  src/styles/utils/FontUtils/fontWeight/bold/index.ts
  src/styles/utils/FontUtils/fontWeight/bold/types.ts
  src/styles/utils/FontUtils/fontWeight/index.ts
  src/styles/utils/FontUtils/index.ts
  src/styles/utils/emojiDefaultStyles/index.native.ts
  src/styles/utils/emojiDefaultStyles/index.ts
  src/styles/utils/generators/TooltipStyleUtils/index.native.ts
  src/styles/utils/generators/TooltipStyleUtils/index.ts
  src/styles/utils/index.ts
  tests/ui/UnreadIndicatorsTest.tsx
Labels: Ready To Build

#46236 remove the underscore in cardList because we already have it in ONYKEYS
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
Labels: Ready To Build

#46247 Allow `Search` command to run in support mode
  src/libs/Network/NetworkStore.ts
Labels: InternalQA

#40692 Emojis larger in other contexts than just single character messages
  src/CONST.ts
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/components/InlineCodeBlock/WrappedText.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/components/SelectionList/UserListItem.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextWithTooltip/index.android.tsx
  src/components/TextWithTooltip/index.ios.tsx
  src/components/TextWithTooltip/types.ts
  src/hooks/useMarkdownStyle.ts
  src/libs/EmojiUtils.ts
  src/libs/ValidationUtils.ts
  src/pages/home/report/ReportActionItemFragment.tsx
  src/pages/home/report/ReportActionItemMessageHeaderSender.tsx
  src/pages/home/report/comment/TextCommentFragment.tsx
  src/pages/home/report/comment/TextWithEmojiFragment.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Profile/DisplayNamePage.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#45996 [No QA] Design improvements
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/pages/workspace/expensifyCard/EmptyCardView.tsx
  src/pages/workspace/expensifyCard/issueNew/AssigneeStep.tsx
  src/pages/workspace/expensifyCard/issueNew/CardNameStep.tsx
  src/pages/workspace/expensifyCard/issueNew/CardTypeStep.tsx
  src/pages/workspace/expensifyCard/issueNew/ConfirmationStep.tsx
  src/pages/workspace/expensifyCard/issueNew/IssueNewCardPage.tsx
  src/pages/workspace/expensifyCard/issueNew/LimitStep.tsx
  src/pages/workspace/expensifyCard/issueNew/LimitTypeStep.tsx
Labels: Ready To Build

#43084 Fixed task description when edit second time 42660
  src/pages/tasks/TaskDescriptionPage.tsx
Labels: Ready To Build

#46021 Fix not found page shows when going back from WS list after open a WS join link
  src/ROUTES.ts
  src/SCREENS.ts
  src/libs/navigateAfterJoinRequest/index.desktop.ts
  src/libs/navigateAfterJoinRequest/index.ts
  src/libs/navigateAfterJoinRequest/index.web.ts
Labels: Ready To Build

#44733 [QBO Export] Implement offline pattern B for manual report exports
  src/components/ReportActionItem/ExportWithDropdownMenu.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/languages/types.ts
  src/libs/API/parameters/MarkAsExportedParams.ts
  src/libs/API/parameters/ReportExportParams.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/pages/home/report/ReportDetailsExportPage.tsx
Labels: Ready To Build

#46020 #45949 & #45950 Divide workflows page into three sections & Update payment section with bank icon
  src/languages/en.ts
  src/languages/es.ts
  src/libs/PaymentUtils.ts
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
  src/types/onyx/Policy.ts
Labels: Ready To Build

#46463 Revert "Emojis larger in other contexts than just single character messages"
  src/CONST.ts
  src/components/Composer/index.native.tsx
  src/components/Composer/index.tsx
  src/components/InlineCodeBlock/WrappedText.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/components/SelectionList/UserListItem.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/components/TextWithTooltip/index.ios.tsx
  src/components/TextWithTooltip/index.native.tsx
  src/components/TextWithTooltip/types.ts
  src/hooks/useMarkdownStyle.ts
  src/libs/EmojiUtils.ts
  src/libs/ValidationUtils.ts
  src/pages/home/report/ReportActionItemFragment.tsx
  src/pages/home/report/ReportActionItemMessageHeaderSender.tsx
  src/pages/home/report/comment/TextCommentFragment.tsx
  src/pages/home/report/comment/TextWithEmojiFragment.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Profile/DisplayNamePage.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#44889 New Attachment Upload UX with Real-Time Previews
  src/CONST.ts
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx
  src/components/AttachmentModal.tsx
  src/components/Attachments/AttachmentCarousel/extractAttachments.ts
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx
  src/libs/ReportUtils.ts
  src/libs/isReportMessageAttachment.ts
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/comment/AttachmentCommentFragment.tsx
Labels: Ready To Build

#45352 Adds support for mentions in room description
  src/libs/Parser.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/pages/home/report/ReportActionItem.tsx
  src/pages/workspace/WorkspaceNewRoomPage.tsx
Labels: Ready To Build

#43063 Associate crashes with user info
  __mocks__/@react-native-firebase/crashlytics.ts
  src/Expensify.tsx
  src/components/TestCrash/index.native.tsx
  src/components/TestCrash/index.tsx
  src/components/TestToolMenu.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/setCrashlyticsUserId/index.native.ts
  src/libs/setCrashlyticsUserId/index.ts
  src/libs/testCrash/index.native.ts
  src/libs/testCrash/index.ts
Labels: InternalQA, Ready To Build

#46598 fix: bank account option in payment methods
  src/components/AddPaymentMethodMenu.tsx
Labels: Ready To Build
