Repository Expensify/App, pull requests merged in 2025-07, with the labels that each got.

#65242 Bump `react-native-airship`
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#64714 [Onboarding Private Domain] - Show workspace options after adding a work email
  src/libs/actions/Welcome/index.ts
  src/pages/OnboardingWorkEmail/BaseOnboardingWorkEmail.tsx
  src/pages/OnboardingWorkEmailValidation/BaseOnboardingWorkEmailValidation.tsx
  src/types/onyx/Onboarding.ts
  tests/ui/WorkEmailOnboarding.tsx
Labels: Ready To Build

#65899 [Avatars - Reports] Fix expense report header avatar incorrectly shows "as a copilot for receiver"
  src/components/AvatarWithDisplayName.tsx
Labels: CP Staging

#66011 [CP Staging] [Fix]: Missing Copy on Tag Import Screen
  src/components/ImportSpreadsheet.tsx
Labels: Ready To Build

#65624 Multi scan send button doesn't register the first tap
  src/libs/actions/IOU.ts
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build

#64008 Add deprecated field error handling to RulesCustomNamePage
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/pages/workspace/rules/RulesCustomNamePage.tsx
Labels: InternalQA

#66586 [CP Staging] Revert #65878 "Flatten transaction item row view hierarchy to improve performance[PART 1]"
  src/components/Search/index.tsx
  src/components/SelectionList/Search/CardListItemHeader.tsx
  src/components/SelectionList/Search/ReportListItemHeader.tsx
  src/components/SelectionList/Search/TransactionGroupListItem.tsx
  src/components/SelectionList/Search/TransactionListItem.tsx
  src/pages/Search/SearchPage.tsx
  src/styles/index.ts
  src/types/onyx/MobileSelectionMode.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#66922 BBA Add bank account wording update
  src/hooks/usePaymentOptions.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/pages/ReimbursementAccount/ConnectedVerifiedBankAccount.tsx
  src/pages/ReimbursementAccount/NonUSD/Finish/index.tsx
  src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx
  src/pages/ReimbursementAccount/USD/ConnectBankAccount/ConnectBankAccount.tsx
  src/pages/ReimbursementAccount/VerifiedBankAccountFlowEntryPoint.tsx
  src/pages/home/report/ReportActionItemMessage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx
Labels: Ready To Build

#67274 Wallet empty state
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
Labels: Ready To Build

#65178 Bring back new `SignInPage`
  __mocks__/@ua/react-native-airship.ts
  modules/hybrid-app/android/src/main/java/com/expensify/reactnativehybridapp/ReactNativeHybridApp.kt
  modules/hybrid-app/ios/ReactNativeHybridApp.mm
  modules/hybrid-app/src/NativeReactNativeHybridApp.ts
  modules/hybrid-app/src/index.native.ts
  modules/hybrid-app/src/index.ts
  modules/hybrid-app/src/types.ts
  src/App.tsx
  src/CONFIG.ts
  src/Expensify.tsx
  src/HybridAppHandler.tsx
  src/components/ScreenWrapper/index.tsx
  src/components/SignInButtons/GoogleSignIn/index.native.tsx
  src/libs/HybridApp.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/AppNavigator/index.native.tsx
  src/libs/Notification/PushNotification/index.native.ts
  src/libs/actions/App.ts
  src/libs/actions/Delegate.ts
  src/libs/actions/HybridApp/index.ts
  src/libs/actions/HybridApp/types.ts
  src/libs/actions/QueuedOnyxUpdates.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/SignInRedirect.ts
  src/libs/actions/User.ts
  src/pages/ErrorPage/SessionExpiredPage.tsx
  src/pages/OnboardingAccounting/BaseOnboardingAccounting.tsx
  src/pages/OnboardingInterestedFeatures/BaseOnboardingInterestedFeatures.tsx
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Security/MergeAccounts/MergeResultPage.tsx
  src/pages/signin/SignUpWelcomeForm.tsx
  src/types/onyx/HybridApp.ts
  src/types/onyx/TryNewDot.ts
Labels: InternalQA
