Repository Expensify/App, pull requests merged in 2025-01, with the labels that each got.

#54730 Revert "fix: messages content overlap when bottom sheet is shown"
  patches/react-native-reanimated+3.16.4+001+mock-useDerivedValue-getter.patch
  src/App.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetAwareScrollViewContext.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetKeyboardSpace.tsx
  src/components/ActionSheetAwareScrollView/index.ios.tsx
  src/components/ActionSheetAwareScrollView/index.tsx
  src/components/EmojiPicker/EmojiPickerButton.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer.tsx
  src/components/KeyboardAvoidingView/index.android.tsx
  src/components/KeyboardAvoidingView/index.ios.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/PopoverMenu.tsx
  src/components/PopoverWithMeasuredContent.tsx
  src/components/ReportActionItem/MoneyRequestAction.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportActionItem/TaskPreview.tsx
  src/components/SelectionList/ChatListItem.tsx
  src/components/ShowContextMenuContext.ts
  src/components/ThreeDotsMenu/index.tsx
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.tsx
  src/hooks/useRestoreInputFocus.ts
  src/hooks/useRestoreInputFocus/index.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.native.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.ts
  src/hooks/useWorkletStateMachine/index.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionsList.tsx
Labels: CP Staging

#54705 [CP Staging] update preserved keys
  src/libs/actions/QueuedOnyxUpdates.ts
Labels: CP Staging

#53048 feat: There is no way to identify the primary workspace, making it appear essentially random.
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/SetNameValuePairParams.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
Labels: Ready To Build

#54774 [No QA] Feat: Remove default selection of the card
  src/pages/workspace/companyCards/assignCard/AssigneeStep.tsx
Labels: InternalQA

#54433 [Internal QA]: Add additional navigation for not existing export
  src/ROUTES.ts
  src/components/ConnectionLayout.tsx
  src/libs/Navigation/types.ts
  src/pages/workspace/accounting/intacct/export/SageIntacctExportPage.tsx
  src/pages/workspace/accounting/netsuite/export/NetSuiteExportConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx
  src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/utils.tsx
Labels: InternalQA

#54832 [CP Staging] Fix crash when opening context menu
  src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx
Labels: Ready To Build

#54414 [No QA] Cache old dot node_modules in workflows
  .github/actions/composite/setupNode/action.yml
  .github/workflows/deploy.yml
  .github/workflows/testBuildHybrid.yml
Labels: Ready To Build

#54865 [CP Staging] Add loading state to ProductTrainingContextProvider
  src/components/ProductTrainingContext/index.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  tests/ui/components/ProductTrainingContextProvider.tsx
Labels: Ready To Build

#54878 [CP Staging] Revert "Merge pull request #53760 from callstack-internal/JKobrynski/…
  src/components/MoneyRequestConfirmationList.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
Labels: CP Staging

#54904 fix: return an empty string when the feed name is not a string
  src/libs/CardUtils.ts
Labels: InternalQA

#54897 [CP Stag] Fix: Reports - "Customize your search" tooltip reappears while creating an expense
  src/hooks/useBottomTabIsFocused.ts
  src/pages/Search/SearchTypeMenuNarrow.tsx
Labels: Ready To Build

#54308 Update manage-travel-member-roles.md
  docs/articles/new-expensify/travel/manage-travel-member-roles.md
Labels: Reviewing, Daily, HelpDot

#55011 fix: dispatch callback after dismissing modal
  patches/react-native-image-picker+7.1.2+002+callback-in-completion-block.patch
Labels: Ready To Build

#55005 Fix: "Travel and expense" modal not showing for migrated users
  src/hooks/useOnboardingFlow.ts
Labels: Ready To Build

#55082 [CP Staging] fix: remove using StatusBar height
  src/styles/utils/getSafeAreaInsets/index.android.ts
Labels: Ready To Build

#52612 fix: get all the cards from different feeds
  src/libs/CardUtils.ts
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
Labels: InternalQA, Ready To Build

#54424 [No QA][CI] Bump Xcode version
  .github/actionlint.yaml
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  .github/workflows/testBuildHybrid.yml
Labels: Ready To Build

#54999 [Internal QA] Implement additional loading indication during direct feed connection
  src/ROUTES.ts
  src/libs/actions/Card.ts
  src/pages/workspace/companyCards/addNew/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
Labels: InternalQA, Ready To Build

#53852 Fix cycle dependencies in metro console
  .eslintrc.changed.js
  metro.config.js
  src/CONST.ts
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/UserInfoCell.tsx
  src/libs/API/index.ts
  src/libs/API/parameters/ResolveDuplicatesParams.ts
  src/libs/DistanceRequestUtils.ts
  src/libs/HttpUtils.ts
  src/libs/Log.ts
  src/libs/Middleware/Reauthentication.ts
  src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/CustomRouter.ts
  src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/syncBrowserHistory/index.web.ts
  src/libs/Navigation/AppNavigator/getActionsFromPartialDiff.ts
  src/libs/Navigation/Navigation.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/Navigation/dismissModalWithReport.ts
  src/libs/Navigation/extractPolicyIDFromQuery.ts
  src/libs/Navigation/getStateFromPath.ts
  src/libs/Navigation/linkTo/index.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
  src/libs/Navigation/linkingConfig/index.ts
  src/libs/Navigation/linkingConfig/subscribe/index.native.ts
  src/libs/Navigation/linkingConfig/subscribe/index.ts
  src/libs/Navigation/switchPolicyID.ts
  src/libs/Network/MainQueue.ts
  src/libs/Network/SequentialQueue.ts
  src/libs/Network/index.ts
  src/libs/PolicyUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/Request.ts
  src/libs/SearchQueryUtils.ts
  src/libs/SearchUIUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/App.ts
  src/libs/actions/BankAccounts.ts
  src/libs/actions/IOU.ts
  src/libs/actions/OnyxUpdateManager/index.ts
  src/libs/actions/Policy/Category.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Policy/Tag.ts
  src/libs/actions/PriorityMode.ts
  src/libs/actions/Report.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/SignInRedirect.ts
  src/libs/actions/Welcome/OnboardingFlow.ts
  src/libs/fileDownload/index.ios.ts
  src/libs/processReportIDDeeplink/getReportIDFromUrl.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ReportActionItemMessageHeaderSender/types.ts
  src/pages/workspace/members/WorkspaceOwnerPaymentCardForm.tsx
  src/types/onyx/OriginalMessage.ts
Labels: Ready To Build

#52183 Fix - Expense - Submit button appears for archived workspace chat if delayed submission is enabled
  src/ROUTES.ts
  src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx
  src/components/BrokenConnectionDescription.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer.tsx
  src/components/MoneyReportHeader.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportWelcomeText.tsx
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.tsx
  src/hooks/useReportIDs.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/DebugTabView.tsx
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/WorkspacesSettingsUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Task.ts
  src/libs/actions/TransactionEdit.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportFooter.tsx
  src/pages/home/report/withReportAndPrivateNotesOrNotFound.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/settings/Report/NotificationPreferencePage.tsx
  src/pages/settings/Report/ReportSettingsPage.tsx
  src/pages/settings/Report/VisibilityPage.tsx
Labels: Ready To Build

#55151 Fix card assignment flow for one card and several assignees
  src/pages/workspace/companyCards/assignCard/AssigneeStep.tsx
Labels: InternalQA, Ready To Build

#55198 feat: Update the invitation process to include the role
  src/languages/en.ts
  src/languages/es.ts
  src/libs/actions/Policy/Member.ts
  src/pages/workspace/WorkspaceInviteMessagePage.tsx
  src/types/form/WorkspaceInviteMessageForm.ts
  tests/actions/PolicyMemberTest.ts
Labels: Ready To Build

#53834 feat: setup background task from scratch on iOS
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify/AppDelegate.mm
  ios/NewExpensify/Info.plist
  ios/Podfile.lock
  ios/tmp.xcconfig
  jest/setup.ts
  modules/background-task/expensify-react-native-background-task.podspec
  modules/background-task/ios/RNBackgroundTaskManager.h
  modules/background-task/ios/RNBackgroundTaskManager.m
  modules/background-task/ios/ReactNativeBackgroundTask.h
  modules/background-task/ios/ReactNativeBackgroundTask.mm
  modules/background-task/package.json
  modules/background-task/react-native.config.js
  modules/background-task/src/NativeReactNativeBackgroundTask.ts
  modules/background-task/src/index.ts
  package-lock.json
  package.json
  src/App.tsx
  src/setup/backgroundTask/index.ios.ts
  src/setup/backgroundTask/index.ts
Labels: Ready To Build

#54593 Don't automatically unpause focus trap
  patches/focus-trap+7.5.4.patch
  src/components/FocusTrap/FocusTrapForModal/index.web.tsx
  src/components/FocusTrap/FocusTrapForScreen/index.web.tsx
Labels: Ready To Build

#52658 Use POST for SAML login
  src/languages/en.ts
  src/languages/es.ts
  src/libs/LoginUtils.ts
  src/pages/LogInWithShortLivedAuthTokenPage.tsx
  src/pages/signin/SAMLSignInPage/index.native.tsx
  src/pages/signin/SAMLSignInPage/index.tsx
Labels: Ready To Build

#55339 [No QA] Update en.ts
  src/languages/en.ts
  src/languages/es.ts
Labels: Ready To Build

#55223 [InternalQA] fix: always send feedType with the order number for custom feeds
  src/libs/CardUtils.ts
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/addNew/DetailsStep.tsx
  src/types/onyx/CardFeeds.ts
  tests/unit/CardUtilsTest.ts
Labels: InternalQA, Ready To Build

#55225 Fixed double clicking behavior on pronouns page
  src/pages/settings/Preferences/LanguagePage.tsx
  src/pages/settings/Preferences/ThemePage.tsx
  src/pages/settings/Profile/PronounsPage.tsx
Labels: Ready To Build

#54201 Create Expense Part 2 - Clean up
  src/CONST.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/components/ReportWelcomeText.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/UpdateMoneyRequestParams.ts
  src/libs/Permissions.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
  src/pages/iou/MoneyRequestAmountForm.tsx
  src/pages/iou/request/IOURequestStartPage.tsx
  src/pages/iou/request/step/IOURequestStepDestination.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepSubrate.tsx
  src/pages/iou/request/step/IOURequestStepTime.tsx
Labels: Ready To Build

#55209 [Internal QA]: Fix bank name pick from url during goBack from export item
  src/ROUTES.ts
  src/pages/workspace/accounting/intacct/export/SageIntacctExportPage.tsx
  src/pages/workspace/accounting/netsuite/export/NetSuiteExportConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx
  src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx
Labels: InternalQA

#55366 [CP Staging] Update messaging on Here's your magic code page
  src/components/ValidateCode/ValidateCodeModal.tsx
  src/languages/en.ts
  src/languages/es.ts
Labels: Ready To Build

#53938 Adding animation for children of switch components
  src/components/Accordion/index.native.tsx
  src/components/Accordion/index.tsx
  src/libs/Navigation/linkTo/index.ts
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
Labels: Ready To Build

#55148 fix: Improve visibility of tooltips
  src/components/Tooltip/BaseGenericTooltip/index.native.tsx
  src/components/Tooltip/BaseGenericTooltip/index.tsx
  src/components/Tooltip/BaseGenericTooltip/types.ts
  src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx
  src/components/Tooltip/GenericTooltip.tsx
  src/components/Tooltip/types.ts
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
  src/styles/theme/themes/light.ts
  src/styles/utils/generators/TooltipStyleUtils/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#55272 Bump fullstory to 1.7.2
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: Ready To Build

#55203 Update the direct bank connection flow on desktop
  src/SCREENS.ts
  src/components/DeeplinkWrapper/index.website.tsx
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
Labels: InternalQA

#54616 feat(Android): setup background task
  android/app/src/main/AndroidManifest.xml
  modules/background-task/android/build.gradle
  modules/background-task/android/gradle.properties
  modules/background-task/android/src/main/AndroidManifest.xml
  modules/background-task/android/src/main/java/com/expensify/reactnativebackgroundtask/BackgroundJobService.kt
  modules/background-task/android/src/main/java/com/expensify/reactnativebackgroundtask/ReactNativeBackgroundTaskModule.kt
  modules/background-task/android/src/main/java/com/expensify/reactnativebackgroundtask/ReactNativeBackgroundTaskPackage.kt
  modules/background-task/android/src/newarch/ReactNativeBackgroundTaskSpec.kt
  modules/background-task/android/src/oldarch/ReactNativeBackgroundTaskSpec.kt
  modules/background-task/react-native.config.js
  src/setup/backgroundTask/index.native.ts
  src/setup/backgroundTask/index.ts
Labels: Ready To Build

#55269 [Internal QA]: Add force to auth bank if credentials expired during member assignment card
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
Labels: Ready To Build

#55477 Always show Restore stashed login when there is a support token
  src/libs/actions/Session/index.ts
  src/pages/settings/InitialSettingsPage.tsx
Labels: InternalQA

#53845 feat: Provide education/confirmation before creating workspaces in New Workspace flows
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/CurrencyPicker.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateWorkspaceParams.ts
  src/libs/CurrencyUtils.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/ReportUtils.ts
  src/libs/actions/App.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/fileDownload/FileUtils.ts
  src/pages/WorkspaceSwitcherPage/WorkspaceCardCreateAWorkspace.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/workspace/WorkspaceConfirmationPage.tsx
  src/pages/workspace/WorkspaceNamePage.tsx
  src/pages/workspace/WorkspacesListPage.tsx
  src/types/form/WorkspaceConfirmationForm.tsx
  src/types/form/index.ts
Labels: Ready To Build

#55521 [CP Staging] remove toString method
  src/pages/home/HeaderView.tsx
Labels: Ready To Build

#55513 fix: add missing parameter when registering broadcast receiver
  modules/background-task/android/src/main/java/com/expensify/reactnativebackgroundtask/ReactNativeBackgroundTaskModule.kt
Labels: Ready To Build

#55016 Tweaks to the expense flow
  src/components/MoneyRequestConfirmationList.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/OptionsListUtils.ts
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
Labels: Ready To Build

#55387 fix: logic enable allow deleting transaction
  src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsPage.tsx
Labels: InternalQA

#53816 fix: Hmm it's not here in RHP is displayed after deleting a workspace
  tests/unit/PolicyUtilsTest.ts
Labels: Ready To Build

#55282 Fix desktop build issue with notarization
  .github/workflows/README.md
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  README.md
  config/electronBuilder.config.js
  desktop/README.md
Labels: InternalQA, Ready To Build

#53954 [HybridApp] Fix `Not found page` on shortcuts
  src/libs/actions/Session/index.ts
Labels: Ready To Build

#55561 [Internal QA]: Update web behaviour of bank connection for card assign
  src/pages/workspace/companyCards/assignCard/BankConnection/index.tsx
Labels: InternalQA, Ready To Build

#55095 Add view transactions cta to Expensify card and company cards page
  src/languages/en.ts
  src/languages/es.ts
  src/libs/SearchQueryUtils.ts
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
Labels: Ready To Build

#54901 Early discount countdown banner
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/libs/API/parameters/AddPaymentCardParams.ts
  src/libs/ReportUtils.ts
  src/libs/SubscriptionUtils.ts
  src/libs/actions/PaymentMethods.ts
  src/pages/home/HeaderView.tsx
  src/pages/settings/Subscription/CardSection/BillingBanner/BillingBanner.tsx
  src/pages/settings/Subscription/CardSection/BillingBanner/EarlyDiscountBanner.tsx
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  src/styles/theme/types.ts
  src/styles/utils/flex.ts
  tests/unit/SubscriptionUtilsTest.ts
Labels: Ready To Build

#54804 Tweak UI for deleted message and expense
  assets/images/arrows-leftright.svg
  assets/images/chatbubble-slash.svg
  src/CONST.ts
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/DeletedActionRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/index.ts
  src/components/Icon/Expensicons.ts
  src/components/ReportActionItem/MoneyRequestAction.tsx
  src/components/ReportActionItem/TaskPreview.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionItemContentCreated.tsx
  src/pages/home/report/ReportActionItemFragment.tsx
Labels: Ready To Build

#55716 [CP Staging] Fix - Self DM - User can submit track expense to self (You) again and send invoice to self
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
Labels: Ready To Build, CP Staging

#52272 feature: Add loading indicator when ReconnectApp is running
  src/CONST.ts
  src/components/LoadingBar.tsx
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/pages/home/HeaderView.tsx
  src/styles/index.ts
Labels: Ready To Build

#55738 Update the isCustom name method
  src/libs/CardUtils.ts
  tests/unit/CardUtilsTest.ts
Labels: InternalQA, Ready To Build

#54744 Improve ActiveHoverable CPU performance
  src/components/Hoverable/ActiveHoverable.tsx
Labels: InternalQA, Ready To Build

#55286 Fix broken feed connection error display on the Company Cards page
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/DotIndicatorMessage.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/FULL_SCREEN_TO_RHP_MAPPING.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/PolicyUtils.ts
  src/libs/actions/CompanyCards.ts
  src/libs/actions/getCompanyCardBankConnection/index.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsListHeaderButtons.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
  src/types/onyx/Card.ts
  src/types/onyx/CardFeeds.ts
Labels: InternalQA

#55790 [CP Staging] Revert PR #54071
  src/pages/home/report/ReportActionsList.tsx
Labels: CP Staging

#55505 fix: Distance - The route is cut off in the receipt in the split.
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/libs/PhoneNumber.ts
  src/libs/actions/IOU.ts
  src/pages/iou/SplitBillDetailsPage.tsx
Labels: Ready To Build

#55766 Unmask the search input field for Fullstory
  src/components/Search/SearchRouter/SearchRouterInput.tsx
Labels: InternalQA

#55616 Fix article bullet spacing
  docs/articles/new-expensify/travel/Manage-Travel-Member-Roles.md
Labels: Daily

#55078 Redesign search to always show search input(mobile + desktop).
  patches/react-native-reanimated+3.16.4+004+fix-transform-animation-gitter.patch
  src/components/Search/SearchPageHeader/SearchPageHeader.tsx
  src/components/Search/SearchPageHeader/SearchPageHeaderInput.tsx
  src/components/Search/SearchPageHeader/SearchStatusBar.tsx
  src/components/Search/SearchPageHeader/SearchTypeMenuPopover.tsx
  src/components/Search/SearchRouter/SearchRouterInput.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/SearchQueryUtils.ts
  src/libs/SearchUIUtils.ts
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/Search/SearchSelectedNarrow.tsx
  src/pages/Search/SearchSelectionModeHeader.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/utils/searchHeaderDefaultOffset/index.desktop.ts
  src/styles/utils/searchHeaderDefaultOffset/index.ts
  src/styles/utils/searchHeaderHeight/index.desktop.ts
  src/styles/utils/searchHeaderHeight/index.ts
  src/styles/utils/sizing.ts
  src/styles/variables.ts
Labels: Ready To Build

#55610 Fix submit button when there is only non-reimbursable expenses
  src/components/MoneyReportHeader.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/libs/SearchUIUtils.ts
  src/libs/actions/IOU.ts
Labels: Ready To Build

#55478 Add animation for switch children
  src/components/Accordion/index.native.tsx
  src/components/Accordion/index.tsx
  src/libs/Navigation/linkTo/index.ts
  src/libs/PolicyUtils.ts
  src/libs/actions/Policy/Category.ts
  src/libs/actions/Policy/DistanceRate.ts
  src/libs/actions/Policy/PerDiem.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Policy/Tag.ts
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
  src/pages/workspace/workflows/ToggleSettingsOptionRow.tsx
Labels: Ready To Build

#54358 Recreate a receipt for native
  jest/setup.ts
  src/libs/API/index.ts
  src/libs/HttpUtils.ts
  src/libs/Request.ts
  src/libs/prepareRequestPayload/index.native.ts
  src/libs/prepareRequestPayload/index.ts
  src/libs/prepareRequestPayload/types.ts
  src/libs/validateFormDataParameter.ts
  src/types/onyx/Request.ts
  tests/unit/SequentialQueueTest.ts
Labels: Ready To Build

#56000 Revert "fix: On selecting a category/ tags by multiple tapping, user directed to conversation page."
  src/components/SelectionList/BaseSelectionList.tsx
  src/pages/WorkspaceSwitcherPage/index.tsx
  tests/unit/BaseSelectionListTest.tsx
Labels: Ready To Build

#55809 [Internal QA]: Add possibility to assign cards from members page when feeds are configured
  src/libs/CardUtils.ts
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
Labels: InternalQA, Ready To Build

#56053 [CP Staging] Revert "Redesign search to always show search input(mobile + desktop)."
  patches/react-native-reanimated+3.16.4+004+fix-transform-animation-gitter.patch
  src/components/Search/SearchPageHeader.tsx
  src/components/Search/SearchPageHeader/SearchTypeMenuPopover.tsx
  src/components/Search/SearchPageHeaderInput.tsx
  src/components/Search/SearchRouter/SearchRouterInput.tsx
  src/components/Search/SearchStatusBar.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
  src/libs/SearchQueryUtils.ts
  src/libs/SearchUIUtils.ts
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageBottomTab.tsx
  src/pages/Search/SearchSelectedNarrow.tsx
  src/pages/Search/SearchSelectionModeHeader.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/utils/searchHeaderDefaultOffset/index.desktop.ts
  src/styles/utils/searchHeaderDefaultOffset/index.ts
  src/styles/utils/searchHeaderHeight/index.desktop.ts
  src/styles/utils/searchHeaderHeight/index.ts
  src/styles/utils/sizing.ts
  src/styles/variables.ts
Labels: Ready To Build

#55302 add tasks for new user first workspace
  src/CONST.ts
  src/ROUTES.ts
  src/libs/API/parameters/CategorizeTrackedExpenseParams.ts
  src/libs/API/parameters/CreateWorkspaceParams.ts
  src/libs/API/parameters/ShareTrackedExpenseParams.ts
  src/libs/ReportUtils.ts
  src/libs/actions/App.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Report.ts
  src/pages/OnboardingAccounting/BaseOnboardingAccounting.tsx
  src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx
  src/pages/iou/request/step/IOURequestStepUpgrade.tsx
  src/types/onyx/IntroSelected.ts
  tests/actions/PolicyTest.ts
Labels: Ready To Build

#55903 Remove $ to fix Google Geolocation API
  .env.staging
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
Labels: Ready To Build

#55607 [InternalQA] Bring in Settle Up feature for workspace feeds on monthly settlement frequency
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/libs/API/parameters/QueueExpensifyCardForBillingParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Card.ts
  src/pages/workspace/expensifyCard/WorkspaceCardListHeader.tsx
  src/pages/workspace/expensifyCard/WorkspaceCardsListLabel.tsx
Labels: InternalQA, Ready To Build

#55222 Add clickable custom emoji support for onboarding task
  assets/images/customEmoji/global-create.svg
  src/CONST.ts
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/components/HTMLEngineProvider/CustomEmojiWithDefaultPressableAction.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/CustomEmojiRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/index.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
Labels: Ready To Build
