Repository Expensify/App, pull requests merged in 2025-06, with the labels that each got.

#48861 Fix: Unable to upload HEIF image as money request
  package-lock.json
  package.json
  src/CONST.ts
  src/libs/fileDownload/heicConverter/index.native.ts
  src/libs/fileDownload/heicConverter/index.ts
  src/libs/fileDownload/heicConverter/types.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build

#63238 Do not display call button for concierge
  src/pages/home/HeaderView.tsx
Labels: InternalQA

#63549 Revert "Merge pull request #59375 from Expensify/georgia-avatars"
  src/libs/ReportUtils.ts
  src/pages/home/report/ReportActionItemSingle.tsx
Labels: CP Staging

#63408 Add robots.txt
  config/webpack/webpack.common.ts
  web/robots.txt
Labels: Ready To Build

#61767 Fix/premature onfido exit
  android/app/src/main/java/com/expensify/chat/AppStateTrackerModule.java
  android/app/src/main/java/com/expensify/chat/ExpensifyAppPackage.java
  android/app/src/main/java/com/expensify/chat/MainApplication.kt
  src/components/Onfido/index.native.tsx
  src/components/Onfido/types.ts
  src/pages/ReimbursementAccount/USD/Requestor/VerifyIdentity/VerifyIdentity.tsx
  src/types/modules/react-native.d.ts
Labels: Ready To Build

#63615 [CP Staging] Revert "Bulk hold"
  src/libs/API/parameters/BulkHoldRequestParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/IOU.ts
  src/pages/Search/SearchHoldReasonPage.tsx
Labels: CP Staging

#56219 refactor: Add `AttachmentModalScreen` component to replace `AttachmentModal`
  src/ROUTES.ts
  src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPagerContext.ts
  src/components/Attachments/AttachmentCarousel/Pager/index.tsx
  src/components/Attachments/AttachmentCarousel/types.ts
  src/components/Attachments/AttachmentCarousel/useCarouselContextEvents.ts
  src/components/Attachments/AttachmentView/AttachmentViewPdf/BaseAttachmentViewPdf.tsx
  src/components/ImportSpreadsheet.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/index.tsx
  src/components/Modal/types.ts
  src/components/Popover/index.tsx
  src/components/PopoverWithoutOverlay/index.tsx
  src/libs/AttachmentUtils.ts
  src/libs/Navigation/AppNavigator/attachmentModalScreenOptions/index.native.ts
  src/libs/Navigation/AppNavigator/attachmentModalScreenOptions/index.ts
  src/libs/Navigation/types.ts
  src/pages/home/report/ReportAttachments.tsx
  src/pages/media/AttachmentModalScreen/AttachmentModalBaseContent.tsx
  src/pages/media/AttachmentModalScreen/AttachmentModalContainer/index.native.tsx
  src/pages/media/AttachmentModalScreen/AttachmentModalContainer/index.tsx
  src/pages/media/AttachmentModalScreen/AttachmentModalContainer/types.ts
  src/pages/media/AttachmentModalScreen/AttachmentModalContext.tsx
  src/pages/media/AttachmentModalScreen/index.tsx
  src/pages/media/AttachmentModalScreen/routes/ProfileAvatarModalContent.tsx
  src/pages/media/AttachmentModalScreen/routes/ReportAttachmentModalContent.tsx
  src/pages/media/AttachmentModalScreen/routes/ReportAvatarModalContent.tsx
  src/pages/media/AttachmentModalScreen/routes/TransactionReceiptModalContent.tsx
  src/pages/media/AttachmentModalScreen/routes/WorkspaceAvatarModalContent.tsx
  src/pages/media/AttachmentModalScreen/types.ts
  tests/ui/ReportAttachments.tsx
  tests/unit/SidebarUtilsTest.ts
Labels: Ready To Build

#63987 Fix unresponsive app launched via shortcut when onboarding is not completed
  src/App.tsx
Labels: Ready To Build

#63998 Remove unwanted keys when exporting Onyx state
  src/libs/ExportOnyxState/common.ts
  src/libs/ExportOnyxState/index.native.ts
  src/libs/ExportOnyxState/index.ts
  src/libs/ExportOnyxState/types.ts
  src/libs/ImportOnyxStateUtils.ts
  src/libs/actions/ImportOnyxState.ts
  src/types/onyx/OnyxState.ts
Labels: InternalQA

#62345 Fix: On tapping device back button to close troubleshoot box from LHN, navigated out of site
  src/Expensify.tsx
  src/NAVIGATORS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Search/SearchRouter/SearchRouterContext.tsx
  src/components/Search/SearchRouter/SearchRouterModal.tsx
  src/components/TestToolsModal.tsx
  src/components/TestToolsModalPage.tsx
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/Navigators/TestToolsModalNavigator.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/TestTool.ts
  src/styles/index.ts
Labels: Ready To Build

#64503 [CP Staging] Fix emoji code crash
  src/components/EmojiWithTooltip/index.tsx
Labels: InternalQA

#56092 Add PlusMinus icon and allow negative values in MoneyRequestAmountInput
  assets/images/plus-minus.svg
  src/components/Icon/Expensicons.ts
  src/components/MoneyRequestAmountInput.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.tsx
  src/components/TextInputWithCurrencySymbol/types.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/ModifiedExpenseMessage.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/pages/iou/MoneyRequestAmountForm.tsx
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/styles/utils/spacing.ts
Labels: Ready To Build

#64156 [Internal QA] Add new success page on the report card lost or damage flow
  assets/images/product-illustrations/illustration__card-replacement-success.svg
  src/components/ConfirmationPage.tsx
  src/components/Icon/Illustrations.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/pages/settings/Security/MergeAccounts/MergeResultPage.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/pages/settings/Wallet/ReportCardLostPage.tsx
  src/pages/settings/Wallet/SuccessReportCardLost.tsx
  src/styles/utils/getSuccessReportCardLostIllustrationStyle/index.native.ts
  src/styles/utils/getSuccessReportCardLostIllustrationStyle/index.ts
  src/styles/utils/index.ts
Labels: InternalQA

#64752 fix: adding debit card requires bank account
  src/pages/settings/Subscription/PaymentCard/index.tsx
Labels: InternalQA

#64769 [CP Staging] Revert "Use tripdata payload to get reservations setup"
  cspell.json
  src/ROUTES.ts
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/ReportActionItem/TripDetailsView.tsx
  src/components/ReportActionItem/TripRoomPreview.tsx
  src/libs/DebugUtils.ts
  src/libs/Navigation/types.ts
  src/libs/TripReservationUtils.ts
  src/pages/Travel/CarTripDetails.tsx
  src/pages/Travel/TripDetailsPage.tsx
  src/pages/Travel/TripSummaryPage.tsx
  src/pages/home/report/TripSummary.tsx
  src/types/onyx/Report.ts
  src/types/onyx/TripData.ts
  tests/ui/ReservationAddressTest.tsx
Labels: Ready To Build

#64919 [CP Stag]Revert "Merge pull request #56092 from callstack-internal/feature/all…
  assets/images/plus-minus.svg
  src/components/Icon/Expensicons.ts
  src/components/MoneyRequestAmountInput.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.tsx
  src/components/TextInputWithCurrencySymbol/types.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/ModifiedExpenseMessage.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/pages/iou/MoneyRequestAmountForm.tsx
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/styles/utils/spacing.ts
Labels: CP Staging

#64633 [CP Staging] Onboarding-Concierge test drive task in Test drive receiver account directs to hmm not here
  src/components/ReportActionItem/TaskPreview.tsx
Labels: CP Staging
