Repository Expensify/App, pull requests merged in 2025-08, with the labels that each got.

#68061 [CP Staging] Revert #63054 "fix: reimbursable features"
  src/CONST/index.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/API/parameters/CreateDistanceRequestParams.ts
  src/libs/API/parameters/CreatePerDiemRequestParams.ts
  src/libs/API/parameters/RequestMoneyParams.ts
  src/libs/API/parameters/SetPolicyCashExpenseModeParams.ts
  src/libs/API/parameters/SplitBillParams.ts
  src/libs/API/parameters/StartSplitBillParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/ModifiedExpenseMessage.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/RELATIONS/WORKSPACE_TO_RHP.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/NextStepUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/Share/SubmitDetailsPage.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/workspace/rules/IndividualExpenseRulesSection.tsx
  src/pages/workspace/rules/RulesReimbursableDefaultPage.tsx
  src/types/onyx/OriginalMessage.ts
  src/types/onyx/Policy.ts
Labels: Ready To Build

#63201 Fix fees URL redirect
  src/CONST/index.ts
  src/pages/EnablePayments/TermsPage/ShortTermsForm.tsx
Labels: Ready To Build

#68156 [CP Staging] Revert "PopoverWithMeasuredContent optimization"
  src/components/PopoverWithMeasuredContent.tsx
  src/components/PopoverWithMeasuredContent/index.tsx
  src/components/PopoverWithMeasuredContent/types.ts
  src/components/Search/FilterDropdowns/DropdownButton.tsx
  tests/ui/components/OnboardingHelpDropdownButtonTest.tsx
Labels: Ready To Build

#68550 [NO QA] Fix app_deployers mention in CP conflict Slack notification
  .github/workflows/cherryPick.yml
Labels: InternalQA

#68740 [QBO] Fix export issue with card
  src/pages/workspace/companyCards/utils.tsx
Labels: Ready To Build

#66608 Add the ability to cycle through reports
  src/CONST/index.ts
  src/ONYXKEYS.ts
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestReportView/MoneyRequestReportNavigation.tsx
  src/components/PrevNextButtons.tsx
  src/components/Search/index.tsx
  src/components/Search/types.ts
  src/libs/API/types.ts
  src/libs/ReportUtils.ts
  src/libs/actions/ReportNavigation.ts
  src/libs/actions/Search.ts
  src/styles/utils/flex.ts
  src/styles/utils/sizing.ts
  src/types/onyx/ReportNavigation.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#68895 fix: inverted flatlist overscroll recoil
  patches/react-native-web/details.md
  patches/react-native-web/react-native-web+0.20.0+012+fix-overscroll-recoil.patch
Labels: Ready To Build

#69055 [CP Staging] Revert #67412 "Duplicate workspace"
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/WorkspaceConfirmationForm.tsx
  src/hooks/useWorkspaceConfirmationAvatar.tsx
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/API/parameters/DuplicateWorkspaceParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/getFirstAlphaNumericCharacter.ts
  src/pages/workspace/WorkspacesListPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/pages/workspace/duplicate/WorkspaceDuplicateForm.tsx
  src/pages/workspace/duplicate/WorkspaceDuplicatePage.tsx
  src/pages/workspace/duplicate/WorkspaceDuplicateSelectFeaturesForm.tsx
  src/pages/workspace/duplicate/WorkspaceDuplicateSelectFeaturesPage.tsx
  src/pages/workspace/duplicate/utils.ts
  src/types/form/WorkspaceDuplicateForm.tsx
  src/types/form/index.ts
  src/types/onyx/DuplicateWorkspace.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#68648 fix: `ActionSheetAwareScrollView` not working with `maintainVisibleContentPosition`
  src/components/ActionSheetAwareScrollView/index.ios.tsx
  src/components/ActionSheetAwareScrollView/useActionSheetKeyboardSpacing.tsx
Labels: Ready To Build

#69363 Change condition for uber banner
  src/pages/workspace/receiptPartners/WorkspaceReceiptPartnersPromotionBanner.tsx
Labels: CP Staging
