Repository Expensify/App, pull requests merged in 2025-02, with the labels that each got.

#56232 [No QA] Update adhoc flow to use mobile-expensify PR link
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/testBuildHybrid.yml
Labels: Ready To Build

#55338 handle offline mode for bank connection
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/addNew/BankConnection/index.tsx
Labels: InternalQA, Ready To Build

#50135 Add room name to the top of searched chats
  src/components/ArchivedReportFooter.tsx
  src/components/AvatarWithDisplayName.tsx
  src/components/BrokenConnectionDescription.tsx
  src/components/Reactions/ReactionTooltipContent.tsx
  src/components/ReportActionItem/IssueCardMessage.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportActionItem/TaskView.tsx
  src/components/ReportWelcomeText.tsx
  src/components/Search/SearchFiltersParticipantsSelector.tsx
  src/components/SelectionList/ChatListItem.tsx
  src/hooks/useBasePopoverReactionList/index.ts
  src/libs/ModifiedExpenseMessage.ts
  src/libs/NextStepUtils.ts
  src/libs/Notification/LocalNotification/BrowserNotifications.ts
  src/libs/OptionsListUtils.ts
  src/libs/PersonalDetailsUtils.ts
  src/libs/ReportActionsUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SearchUIUtils.ts
  src/libs/SidebarUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Policy/Policy.ts
  src/pages/ReportAvatar.tsx
  src/pages/ReportDetailsPage.tsx
  src/pages/ReportParticipantsPage.tsx
  src/pages/RoomMembersPage.tsx
  src/pages/ShareCodePage.tsx
  src/pages/TransactionDuplicate/Review.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
  src/pages/home/report/ReportActionItem.tsx
  src/pages/home/report/ReportActionItemSingle.tsx
  src/pages/home/report/ReportTypingIndicator.tsx
  src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/WorkspacesListRow.tsx
  src/styles/index.ts
  src/types/onyx/SearchResults.ts
  tests/perf-test/ModifiedExpenseMessage.perf-test.ts
  tests/unit/ModifiedExpenseMessageTest.ts
  tests/unit/Search/SearchUIUtilsTest.ts
Labels: Ready To Build

#56370 [fix] Setup specialist appears in member list and throws error when invited
  src/CONST.ts
  src/libs/OptionsListUtils.ts
  src/libs/actions/Report.ts
Labels: Ready To Build

#56269 Force Amex to production API
  src/libs/ApiUtils.ts
  src/libs/actions/getCompanyCardBankConnection/index.tsx
Labels: InternalQA, Ready To Build

#56285 [No QA]Move all iOS/Android secrets to be fetched by `op` cli
  .github/workflows/androidBump.yml
  .github/workflows/buildAndroid.yml
  .github/workflows/compareNDandODbuilds.yml
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  .github/workflows/testBuildHybrid.yml
  android/app/android-fastlane-json-key.json.gpg
  android/app/my-upload-key.keystore.gpg
  fastlane/Fastfile
  ios/Certificates.p12.gpg
  ios/NewApp_AdHoc.mobileprovision.gpg
  ios/NewApp_AdHoc_Notification_Service.mobileprovision.gpg
  ios/NewApp_AdHoc_Share_Extension.mobileprovision.gpg
  ios/NewApp_AppStore.mobileprovision.gpg
  ios/NewApp_AppStore_Notification_Service.mobileprovision.gpg
  ios/NewApp_Development.mobileprovision.gpg
  ios/ios-fastlane-json-key.json.gpg
Labels: Ready To Build

#55517 feat: Add distance label on map route
  src/components/DistanceRequest/DistanceRequestFooter.tsx
  src/components/MapView/MapView.tsx
  src/components/MapView/MapViewImpl.website.tsx
  src/components/MapView/MapViewTypes.ts
  src/libs/DistanceRequestUtils.ts
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/styles/index.ts
Labels: Ready To Build

#56430 [No QA]Move remaining encrypted secrets into 1Password
  .github/actions/composite/setupGitForOSBotify/action.yml
  .github/actions/composite/setupGitForOSBotifyApp/action.yml
  .github/workflows/OSBotify-private-key.asc.gpg
  .github/workflows/README.md
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
  .github/workflows/deploy.yml
  .github/workflows/finishReleaseCycle.yml
  .github/workflows/preDeploy.yml
  .github/workflows/testBuild.yml
  desktop/developer_id.p12.gpg
Labels: Ready To Build

#55863 (Tweaks to the Create Expense Flow) - follow-up - change workspace subtitle
  src/components/AvatarWithDisplayName.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
Labels: Ready To Build

#55740 Prevent self approvals
  src/languages/en.ts
  src/languages/es.ts
  src/libs/PolicyUtils.ts
  src/pages/workspace/WorkspaceMembersPage.tsx
  src/pages/workspace/rules/ExpenseReportRulesSection.tsx
Labels: Ready To Build

#56489 [No QA] feat: bump jvm heap memory size
  android/gradle.properties
Labels: Ready To Build

#56535 [CP Staging] Revert "Merge pull request #55932 from prakashbask/fix/53718"
  src/hooks/useHtmlPaste/index.ts
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
Labels: CP Staging

#56562 Improve custom rules formatting
  src/libs/actions/Policy/Policy.ts
  src/pages/workspace/rules/CustomRulesSection.tsx
Labels: Ready To Build

#56400 [No QA] Fix syntax in testBuildHybrid.yml
  .github/workflows/testBuildHybrid.yml
Labels: Ready To Build

#56558 Make Retry Payment button available for amount owed overdue state
  src/pages/settings/Subscription/CardSection/utils.ts
  tests/unit/CardsSectionUtilsTest.ts
Labels: InternalQA

#56090 feat: skip participant step in create flow
  src/ROUTES.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/components/SelectionList/UserListItem.tsx
  src/components/SelectionList/types.ts
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build

#56597 fix: group chat avatar disappears after adding other members and creating the group
  src/pages/NewChatConfirmPage.tsx
Labels: Ready To Build

#56600 Do not return empty card Objects for AdvancedFilters
  src/libs/CardUtils.ts
Labels: Ready To Build

#56624 [No QA] Parameterize the 1P vault used in CI
  .github/actions/composite/setupGitForOSBotify/action.yml
  .github/actions/composite/setupGitForOSBotifyApp/action.yml
  .github/workflows/androidBump.yml
  .github/workflows/buildAndroid.yml
  .github/workflows/compareNDandODbuilds.yml
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  .github/workflows/testBuildHybrid.yml
Labels: Ready To Build

#56401 Remove hybrid app check from getEnvironment
  src/libs/Environment/getEnvironment/index.native.ts
Labels: Ready To Build

#56638 fix create expense flow regression
  src/ROUTES.ts
  src/components/MoneyRequestConfirmationList.tsx
  src/libs/OptionsListUtils.ts
  src/pages/iou/request/step/IOURequestStepDistance.tsx
Labels: CP Staging

#56684 [Native Share Provisioning] Add ADHOC share extension profile to fastfile / build script
  .github/workflows/deploy.yml
  .github/workflows/testBuild.yml
  fastlane/Fastfile
Labels: Ready To Build

#56744 [NO QA] Revert "Remove hybrid app check from getEnvironment"
  src/libs/Environment/getEnvironment/index.native.ts
Labels: Ready To Build, CP Staging

#56669 Upgarde react-fast-pdf package
  package-lock.json
  package.json
Labels: Ready To Build

#56865 [CP Staging] fix: FAB is not responsive after exiting create expense flow
  src/libs/Navigation/navigateAfterInteraction/index.ios.ts
  src/libs/Navigation/navigateAfterInteraction/index.ts
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
Labels: Ready To Build

#53112 fix: update how we show pending and scanning status
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/languages/en.ts
  src/languages/es.ts
Labels: Ready To Build

#56887 [CP Staging] [navigation] fix navigation bugs in bugs workspace card page
  src/ROUTES.ts
  src/libs/Navigation/types.ts
  src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceEditCardLimitTypePage.tsx
  src/pages/workspace/expensifyCard/WorkspaceEditCardNamePage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
Labels: CP Staging

#54207 Emoji overlaps the word above
  src/pages/home/report/comment/TextWithEmojiFragment/index.ios.tsx
Labels: Ready To Build

#56917 [CP staging] fix: app crashes when submitting the track distance to the workspace
  src/components/SelectionList/Search/TransactionListItemRow.tsx
Labels: Ready To Build

#56973 Add preventSpotnanaTravel beta and prevent those users from seeing travel related content
  src/CONST.ts
  src/libs/Permissions.ts
  src/pages/Travel/MyTripsPage.tsx
  src/pages/Travel/TravelTerms.tsx
  src/pages/Travel/TripDetailsPage.tsx
  src/pages/Travel/TripSummaryPage.tsx
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
Labels: InternalQA

#55066 [No QA] Console error cleanup pt3
  patches/react-native-draggable-flatlist+4.0.1+001+initial.patch
  patches/react-native-draggable-flatlist+4.0.1+002+fix-console-error-ref-measureLayout.patch
  src/components/AvatarWithDisplayName.tsx
  src/components/Button/index.tsx
  src/components/Button/utils/index.ts
  src/components/Button/utils/index.web.ts
  src/components/Button/utils/types.ts
  src/components/HTMLEngineProvider/HTMLRenderers/DeletedActionRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/MultiGestureCanvas/usePinchGesture.ts
  src/components/MultiGestureCanvas/useTapGestures.ts
  src/components/ReceiptAudit.tsx
  src/components/ReferralProgramCTA.tsx
  src/components/ReportActionItem/ReportActionItemImages.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/components/SelectionList/BaseListItem.tsx
  src/components/SelectionList/Search/ActionCell.tsx
  src/components/SelectionList/Search/ExpenseItemHeaderNarrow.tsx
  src/components/SelectionList/Search/TransactionListItemRow.tsx
  src/components/TextBlock.tsx
  src/components/ThreeDotsMenu/index.tsx
  src/components/ThreeDotsMenu/types.ts
  src/libs/actions/Link.ts
  src/pages/Search/AdvancedSearchFilters.tsx
  src/pages/workspace/WorkspacesListRow.tsx
Labels: Ready To Build

#55888 [Internal QA]: Clean up BankConnection components
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/BankConnection/index.tsx
  src/pages/workspace/companyCards/BankConnection/openBankConnection/index.tsx
  src/pages/workspace/companyCards/BankConnection/openBankConnection/index.website.tsx
  src/pages/workspace/companyCards/addNew/AddNewCardPage.tsx
  src/pages/workspace/companyCards/addNew/DetailsStep.tsx
  src/pages/workspace/companyCards/assignCard/AssignCardFeedPage.tsx
  src/pages/workspace/companyCards/assignCard/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/assignCard/BankConnection/index.tsx
  src/pages/workspace/companyCards/assignCard/BankConnection/openBankConnection/index.tsx
  src/pages/workspace/companyCards/assignCard/BankConnection/openBankConnection/index.website.tsx
Labels: InternalQA

#55157 [UX Reliability] Improve the bottom modal animations
  src/CONST.ts
  src/components/FloatingActionButton.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/BottomDockedModal/Backdrop/index.tsx
  src/components/Modal/BottomDockedModal/Backdrop/index.web.tsx
  src/components/Modal/BottomDockedModal/Container/index.tsx
  src/components/Modal/BottomDockedModal/Container/index.web.tsx
  src/components/Modal/BottomDockedModal/index.tsx
  src/components/Modal/BottomDockedModal/types.ts
  src/components/Modal/types.ts
  src/components/PopoverMenu.tsx
  src/components/PopoverWithMeasuredContent.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
Labels: Ready To Build

#56326 Add search input to mobile search page(with fixed performance)
  patches/react-native-reanimated+3.16.4+004+fix-transform-animation-gitter.patch
  patches/react-native-reanimated+3.16.4+005+fix-web-layout-animation.patch
  src/ROUTES.ts
  src/components/Navigation/BottomTabBar/index.tsx
  src/components/Navigation/TopBar.tsx
  src/components/Search/SearchAutocompleteInput.tsx
  src/components/Search/SearchAutocompleteList.tsx
  src/components/Search/SearchPageHeader/SearchPageHeader.tsx
  src/components/Search/SearchPageHeader/SearchPageHeaderInput.tsx
  src/components/Search/SearchPageHeader/SearchStatusBar.tsx
  src/components/Search/SearchPageHeader/SearchTypeMenuPopover.tsx
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/components/Search/getSearchFiltersButtonTransition.ts/index.native.ts
  src/components/Search/getSearchFiltersButtonTransition.ts/index.ts
  src/components/Search/getSearchFiltersButtonTransition.ts/types.ts
  src/components/TextInput/BaseTextInput/index.native.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/hooks/useDeleteSavedSearch.tsx
  src/hooks/useOnboardingFlow.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/SearchQueryUtils.ts
  src/libs/SearchUIUtils.ts
  src/pages/Search/AdvancedSearchFilters.tsx
  src/pages/Search/SavedSearchRenamePage.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchPageNarrow.tsx
  src/pages/Search/SearchSelectedNarrow.tsx
  src/pages/Search/SearchSelectionModeHeader.tsx
  src/pages/Search/SearchTypeMenu.tsx
  src/pages/Search/SearchTypeMenuNarrow.tsx
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
  src/pages/settings/Wallet/WalletPage/WalletPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
  src/styles/index.ts
  src/styles/utils/index.ts
  src/styles/utils/searchBottomTabHeaderStyles.ts/index.android.ts
  src/styles/utils/searchBottomTabHeaderStyles.ts/index.ts
  src/styles/utils/searchHeaderDefaultOffset/index.ts
  src/styles/utils/searchHeaderHeight/index.desktop.ts
  src/styles/utils/searchHeaderHeight/index.ts
  src/styles/utils/sizing.ts
  src/styles/variables.ts
Labels: Ready To Build

#57060 Safely filter out categories without a name in `SearchMultipleSelectionPicker`
  src/components/Search/SearchMultipleSelectionPicker.tsx
Labels: InternalQA

#56987 Add defaults for missing NSQS values
  src/pages/workspace/accounting/nsqs/advanced/NSQSAdvancedPage.tsx
  src/pages/workspace/accounting/nsqs/import/NSQSCustomersDisplayedAsPage.tsx
  src/pages/workspace/accounting/nsqs/import/NSQSCustomersPage.tsx
  src/pages/workspace/accounting/nsqs/import/NSQSImportPage.tsx
  src/pages/workspace/accounting/nsqs/import/NSQSProjectsDisplayedAsPage.tsx
  src/pages/workspace/accounting/nsqs/import/NSQSProjectsPage.tsx
  src/types/onyx/Policy.ts
Labels: InternalQA

#57015 Don't override Environment on hybrid app
  src/libs/Environment/getEnvironment/index.native.ts
  src/libs/getPlaidLinkTokenParameters/index.android.ts
Labels: Ready To Build

#57107 [CP Staging] Fix Android reanimated worklets crash.
  patches/react-native-reanimated+3.16.4+006+fix-worklet-runtime-creation.patch
Labels: Ready To Build

#54404 Migrate Two Factor Authentication to use separate screens (remove react-native-animatable)
  src/CONST.ts
  src/Expensify.tsx
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AnimatedStep/AnimatedStepContext.ts
  src/components/AnimatedStep/AnimatedStepProvider.tsx
  src/components/AnimatedStep/index.tsx
  src/components/AnimatedStep/useAnimatedStepContext.ts
  src/components/ConnectToXeroFlow/index.native.tsx
  src/components/ConnectToXeroFlow/index.tsx
  src/components/TabSelector/TabSelectorItem.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/linkingConfig/RELATIONS/SETTINGS_TO_RHP.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/TwoFactorAuthActions.ts
  src/pages/ReimbursementAccount/ConnectBankAccount/components/Enable2FACard.tsx
  src/pages/ReimbursementAccount/NonUSD/Finish/index.tsx
  src/pages/settings/Security/SecuritySettingsPage.tsx
  src/pages/settings/Security/TwoFactorAuth/CopyCodesPage.tsx
  src/pages/settings/Security/TwoFactorAuth/DisablePage.tsx
  src/pages/settings/Security/TwoFactorAuth/DisabledPage.tsx
  src/pages/settings/Security/TwoFactorAuth/EnabledPage.tsx
  src/pages/settings/Security/TwoFactorAuth/StepWrapper/StepWrapper.tsx
  src/pages/settings/Security/TwoFactorAuth/Steps/SuccessStep.tsx
  src/pages/settings/Security/TwoFactorAuth/SuccessPage.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthContext/index.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthContext/useTwoFactorAuth.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/types.ts
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthPage.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx
  src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthWrapper.tsx
  src/pages/settings/Security/TwoFactorAuth/VerifyPage.tsx
  src/styles/index.ts
  src/types/onyx/Account.ts
Labels: Ready To Build

#57061 Promotional Banner: Fix workspace enabled feature highlight
  src/pages/workspace/WorkspaceInitialPage.tsx
Labels: Ready To Build

#57126 switch to old dot experience in hybrid app
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
Labels: Ready To Build

#56610 Implement the React-Native Pusher library for iOS and Android
  __mocks__/@pusher/pusher-websocket-react-native/index.ts
  __mocks__/pusher-js/react-native.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  src/CONST.ts
  src/libs/API/index.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Pusher/index.native.ts
  src/libs/Pusher/index.ts
  src/libs/Pusher/library/index.native.ts
  src/libs/Pusher/library/index.ts
  src/libs/Pusher/library/types.ts
  src/libs/Pusher/types.ts
  src/libs/PusherConnectionManager.ts
  src/libs/PusherUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/User.ts
  src/types/modules/pusher.d.ts
  tests/utils/PusherHelper.ts
  tests/utils/TestHelper.ts
Labels: Ready To Build

#56957 Create Edit-expenses.md
  docs/articles/expensify-classic/expenses/Edit-expenses.md
Labels: Daily, Task

#56940 Upgraded onfido-sdk-ui to v14.42.0
  package-lock.json
  package.json
  src/components/Onfido/BaseOnfidoWeb.tsx
  src/components/Onfido/types.ts
Labels: Ready To Build

#55514 Redirect non-micro companies on web
  src/libs/API/parameters/SwitchToOldDotOnCompanySizeParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/actions/Welcome/index.ts
  src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx
Labels: Ready To Build

#56921 Feature: Add closed cards to card filter on reports page
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCardPage.tsx
  tests/unit/Search/buildCardFilterDataTest.ts
Labels: InternalQA

#56144 Allow NewDot collect customers to add one third-party card feed
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/linkingConfig/RELATIONS/WORKSPACE_TO_RHP.ts
  src/libs/Navigation/types.ts
  src/pages/workspace/WorkspaceMoreFeaturesPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
  src/pages/workspace/companyCards/addNew/SelectBankStep.tsx
  src/pages/workspace/downgrade/WorkspaceDowngradePage.tsx
  src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx
Labels: Ready To Build

#56169 [NoQA] Unsubscribe from Broadcast receiver task
  ios/NewExpensify/AppDelegate.mm
  modules/background-task/android/src/main/java/com/expensify/reactnativebackgroundtask/ReactNativeBackgroundTaskModule.kt
Labels: Ready To Build

#56866 Add border radius to auto complete
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Search/SearchAutocompleteInput.tsx
  src/components/TextInput/BaseTextInput/index.tsx
  src/hooks/useMarkdownStyle.ts
Labels: Ready To Build

#56735 feat: update policy expense chat name
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/libs/OptionsListUtils.ts
  src/libs/ReportUtils.ts
  src/libs/SidebarUtils.ts
  tests/unit/OptionsListUtilsTest.ts
  tests/unit/ReportUtilsTest.ts
  tests/unit/SidebarOrderTest.ts
  tests/unit/SidebarUtilsTest.ts
Labels: Ready To Build

#57362 Revert #55966 / Fix "just sign in here" Magic Code page link
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/actions/App.ts
  src/libs/actions/Session/index.ts
Labels: Ready To Build

#55704 Fix the viewport is scrolled to bottom when the search modal shows while a keyboard is visible
  package-lock.json
  package.json
  src/components/Search/SearchRouter/SearchRouterModal.tsx
Labels: Ready To Build

#57064 Change generic card illustration fallback
  __mocks__/Illustrations.ts
  assets/images/companyCards/card=-generic.svg
  assets/images/companyCards/generic-csv-dark.svg
  assets/images/companyCards/generic-csv-light.svg
  assets/images/companyCards/generic-dark.svg
  assets/images/companyCards/generic-light.svg
  assets/images/companyCards/large/card-generic-large.svg
  assets/images/companyCards/large/generic-csv-dark-large.svg
  assets/images/companyCards/large/generic-csv-light-large.svg
  assets/images/companyCards/large/generic-dark-large.svg
  assets/images/companyCards/large/generic-light-large.svg
  src/CONST.ts
  src/components/Icon/Illustrations.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/CardUtils.ts
  src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCardPage.tsx
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsListHeaderButtons.tsx
  src/pages/workspace/companyCards/addNew/SelectBankStep.tsx
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  src/pages/workspace/members/WorkspaceMemberNewCardPage.tsx
  src/styles/theme/illustrations/themes/dark.ts
  src/styles/theme/illustrations/themes/light.ts
  src/styles/theme/illustrations/types.ts
  tests/unit/CardUtilsTest.ts
  tests/unit/Search/buildCardFilterDataTest.ts
Labels: Ready To Build

#57178 Fix scrollbar appears every time switch report type
  src/pages/Search/SearchTypeMenu.tsx
  src/styles/index.ts
Labels: Ready To Build

#57242 Follow ups to Broken Connection with direct feeds
  src/components/BrokenConnectionDescription.tsx
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/libs/TransactionUtils/index.ts
Labels: Ready To Build

#56924 Use simple styles for code blocks in Native platforms
  src/components/InlineCodeBlock/WrappedText.tsx
  src/components/InlineCodeBlock/index.native.tsx
  src/styles/index.ts
  src/styles/utils/codeStyles/index.android.ts
  src/styles/utils/codeStyles/index.ios.ts
  src/styles/utils/codeStyles/index.ts
  src/styles/utils/codeStyles/types.ts
  tests/unit/splitLongWordTest.ts
Labels: Ready To Build

#55510 Fix-55026: Make shouldShowAddMissingDetails condition consistent
  src/components/ReportActionItem/IssueCardMessage.tsx
  src/libs/ReportActionsUtils.ts
  src/pages/MissingPersonalDetails/MissingPersonalDetailsMagicCodeModal.tsx
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  tests/unit/ReportActionsUtilsTest.ts
Labels: Ready To Build

#57219 fix: can't Hold card expenses
  src/libs/ReportUtils.ts
Labels: Ready To Build
