Repository Expensify/App, pull requests merged in 2025-04, with the labels that each got.

#58227 fix: Nothing happens after hitting Enter
  src/components/Button/validateSubmitShortcut/index.ts
Labels: Ready To Build

#59547 [CP Staging] Update `setup-ruby` to fix iOS setup error
  .github/workflows/androidBump.yml
  .github/workflows/buildAndroid.yml
  .github/workflows/compareNDandODbuilds.yml
  .github/workflows/deploy.yml
  .github/workflows/deployNewHelp.yml
  .github/workflows/testBuildHybrid.yml
  .github/workflows/verifyHybridApp.yml
Labels: CP Staging

#59576 [CP Staging] Revert "Merge pull request #59008 from ishpaul777/revert-59004-revert…
  src/components/ProductTrainingContext/TOOLTIPS.ts
  src/components/ProductTrainingContext/index.tsx
  src/hooks/useOnboardingFlow.ts
  src/libs/API/parameters/DismissProductTraining.ts
  src/libs/TooltipUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Welcome/index.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/types/onyx/DismissedProductTraining.ts
  tests/ui/components/ProductTrainingContextProvider.tsx
  tests/unit/OptionsListUtilsTest.ts
Labels: CP Staging

#58718 Show submit button if not all transactions has violation
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  tests/unit/IOUUtilsTest.ts
Labels: InternalQA

#58910 Update policyOwnerAmountOwedOverdue billing banner
  src/CONST.ts
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/pages/settings/Subscription/CardSection/CardSection.tsx
  src/pages/settings/Subscription/CardSection/utils.ts
  src/types/onyx/PurchaseList.ts
  src/types/onyx/index.ts
  tests/unit/CardsSectionUtilsTest.ts
Labels: InternalQA

#59730 [CP Staging] Fix - [Manager McTest] Group chat - Test manager can be added to group chat when Add to group button is absent
  src/pages/NewChatPage.tsx
Labels: CP Staging

#58983 iOS - Scroll up to the beginning loads the end of the conversation
  src/components/FlatList/index.ios.ts
  src/components/FlatList/index.ios.tsx
Labels: Ready To Build

#58050 Feature: Add `Edit profile` row in RHP profile
  src/ROUTES.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/useRootNavigatorScreenOptions.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/ReportUtils.ts
  src/pages/ProfilePage.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx
  src/pages/settings/Profile/ProfilePage.tsx
  tests/navigation/NavigateTests.tsx
Labels: Ready To Build

#58783 fix: No Add Bank Account button In report from employee without added BA
  src/libs/ReportUtils.ts
Labels: Ready To Build

#59798 [CP Staging] Fix - [Manager McTest] Only Allow Submitting Test Receipt to Manager
  src/components/MoneyRequestConfirmationList.tsx
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
Labels: CP Staging

#58407 Render ConciergeCategoryOptions actions
  src/CONST.ts
  src/components/ReportActionItem/ActionableItemButtons.tsx
  src/libs/ReportActionsUtils.ts
  src/libs/actions/Report.ts
  src/pages/home/report/PureReportActionItem.tsx
  src/types/onyx/OriginalMessage.ts
Labels: Ready To Build

#59657 Wrap the card name and number when assigning card
  src/libs/CardUtils.ts
  src/pages/settings/Wallet/PaymentMethodList.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/assignCard/CardSelectionStep.tsx
  src/pages/workspace/companyCards/assignCard/ConfirmationStep.tsx
  src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
  tests/unit/CardUtilsTest.ts
Labels: InternalQA

#59930 [CP Staging] Revert "fix: empty green button after paying with Expensify"
  src/libs/ReportPreviewActionUtils.ts
  src/libs/ReportPrimaryActionUtils.ts
Labels: Emergency

#60110 Fix error modal sometimes when desktop tries to update in background
  desktop/main.ts
Labels: InternalQA

#56068 Update Datepicker UX
  src/CONST.ts
  src/components/DatePicker/CalendarPicker/index.tsx
  src/components/DatePicker/DatePickerModal.tsx
  src/components/DatePicker/index.tsx
  src/components/DatePicker/types.ts
  src/components/PopoverWithMeasuredContent.tsx
  src/components/ScreenWrapper.tsx
  src/components/SubStepForms/DateOfBirthStep.tsx
  src/components/TextInput/BaseTextInput/implementation/index.native.tsx
  src/components/TextInput/BaseTextInput/implementation/index.tsx
  src/components/TextInput/BaseTextInput/types.ts
  src/pages/EditReportFieldDate.tsx
  src/pages/ReimbursementAccount/USD/BusinessInfo/subSteps/IncorporationDateBusiness.tsx
  src/pages/iou/request/step/IOURequestStepDate.tsx
  src/pages/settings/Profile/CustomStatus/SetDatePage.tsx
  src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.tsx
  src/pages/workspace/companyCards/assignCard/TransactionStartDateSelectorPage.tsx
  src/styles/index.ts
Labels: Ready To Build

#59077 [Collect Pricing Update] Update Collect subscription pricing and the subscription page composition
  src/CONST.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/Modal/BottomDockedModal/types.ts
  src/components/Section/index.tsx
  src/hooks/useHasTeam2025Pricing.tsx
  src/hooks/usePreferredCurrency.ts
  src/hooks/useSubscriptionPrice.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/params.ts
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/linkingConfig/RELATIONS/SETTINGS_TO_RHP.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/SubscriptionUtils.ts
  src/pages/settings/Subscription/CardSection/BillingBanner/EarlyDiscountBanner.tsx
  src/pages/settings/Subscription/PaymentCard/index.tsx
  src/pages/settings/Subscription/SubscriptionDetails/index.native.tsx
  src/pages/settings/Subscription/SubscriptionDetails/index.tsx
  src/pages/settings/Subscription/SubscriptionPlan/AddMembersButton/index.native.tsx
  src/pages/settings/Subscription/SubscriptionPlan/AddMembersButton/index.tsx
  src/pages/settings/Subscription/SubscriptionPlan/ComparePlansModal.tsx
  src/pages/settings/Subscription/SubscriptionPlan/SaveWithExpensifyButton/index.tsx
  src/pages/settings/Subscription/SubscriptionPlan/SubscriptionPlanCard.tsx
  src/pages/settings/Subscription/SubscriptionPlan/SubscriptionPlanCardActionButton.tsx
  src/pages/settings/Subscription/SubscriptionPlan/index.tsx
  src/pages/settings/Subscription/SubscriptionSettings/index.native.tsx
  src/pages/settings/Subscription/SubscriptionSettings/index.tsx
  src/pages/settings/Subscription/SubscriptionSettingsPage.tsx
  src/styles/index.ts
  tests/ui/WorkspaceUpgradeTest.tsx
Labels: Ready To Build

#59662 Use react-native-airship 21.4.0
  __mocks__/@ua/react-native-airship.ts
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: InternalQA, Ready To Build

#59363 [Pre RN 0.79] Migrate documents picker
  __mocks__/@react-native-documents/picker.ts
  __mocks__/react-native-document-picker.ts
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AttachmentPicker/index.native.tsx
  src/components/FilePicker/index.native.tsx
Labels: Ready To Build

#60426 Fix getting in-wallet card status
  modules/expensify-react-native-wallet.tgz
  package-lock.json
  src/libs/Wallet/index.ios.ts
  src/types/onyx/Card.ts
Labels: InternalQA

#60120 [Internal QA]: Add QBD to company card export
  src/ROUTES.ts
  src/libs/API/parameters/UpdateQuickbooksDesktopCompanyCardExpenseAccountTypeParams.ts
  src/libs/API/parameters/UpdateQuickbooksDesktopExpensesExportDestinationTypeParams.ts
  src/libs/Navigation/helpers/goBackFromExportConnection.ts
  src/libs/Navigation/helpers/replaceCompanyCardsRoute.ts
  src/libs/Navigation/types.ts
  src/libs/actions/connections/QuickbooksDesktop.ts
  src/pages/workspace/accounting/intacct/export/SageIntacctExportPage.tsx
  src/pages/workspace/accounting/netsuite/export/NetSuiteExportConfigurationPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopCompanyCardExpenseAccountPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopCompanyCardExpenseAccountSelectCardPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopCompanyCardExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopExportDateSelectPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopExportPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopOutOfPocketExpenseAccountSelectPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopOutOfPocketExpenseConfigurationPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopOutOfPocketExpenseEntitySelectPage.tsx
  src/pages/workspace/accounting/qbd/export/QuickbooksDesktopPreferredExporterConfigurationPage.tsx
  src/pages/workspace/accounting/qbo/export/QuickbooksExportConfigurationPage.tsx
  src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx
  src/pages/workspace/companyCards/utils.tsx
Labels: InternalQA

#60866 Show the report stolen card button for cards in open and not activated state
  src/pages/settings/Wallet/ExpensifyCardPage.tsx
Labels: InternalQA

#61131 [CP Staging] Revert "Fix workspace features multiselect"
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/components/SelectionListWithModal/index.tsx
Labels: CP Staging

#60932 FIX: Android mWeb bottom navigation viewport cutoff
  web/index.html
Labels: Ready To Build

#61125 Make sure that we stay in NewDot for small companies
  src/CONST.ts
  src/libs/actions/Report.ts
  src/pages/OnboardingAccounting/BaseOnboardingAccounting.tsx
Labels: Ready To Build
