Repository Expensify/App, pull requests merged in 2025-09, with the labels that each got.

#69799 Revert #68190 "Consolidate ConfirmModal instances into a global component"
  src/App.tsx
  src/components/ConfirmModal.tsx
  src/components/Modal/Global/ConfirmModalWrapper.tsx
  src/components/Modal/Global/ModalContext.tsx
  src/components/Modal/Global/index.ts
  src/components/Modal/Global/useModalHook.tsx
  src/components/MoneyReportHeader.tsx
Labels: Ready To Build

#69350 [NoQA] Migrate RNEF to ROCK
  .github/scripts/verifyPodfile.sh
  .github/workflows/remote-build-android.yml
  .github/workflows/remote-build-ios.yml
  .gitignore
  .prettierignore
  README.md
  android/app/build.gradle
  android/settings.gradle
  cspell.json
  ios/Podfile
  ios/Podfile.lock
  ios/bundle-react-native-code-and-images.sh
  package-lock.json
  package.json
  rock.config.mjs
  scripts/run-build.sh
Labels: InternalQA

#68204 Fix some regression issues of merge expenses
  src/components/ReportActionItem/MoneyRequestView.tsx
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/MergeTransactionUtils.ts
  src/libs/ReportSecondaryActionUtils.ts
  src/libs/actions/MergeTransaction.ts
  src/pages/TransactionMerge/ConfirmationPage.tsx
  src/pages/TransactionMerge/DetailsReviewPage.tsx
  src/pages/TransactionMerge/MergeFieldReview.tsx
  src/pages/TransactionMerge/MergeTransactionsListContent.tsx
  src/pages/TransactionReceiptPage.tsx
  src/types/onyx/MergeTransaction.ts
  tests/unit/MergeTransactionUtilsTest.ts
  tests/utils/collections/mergeTransaction.ts
Labels: Ready To Build

#70245 [NoQA] Fix claude code action
  .github/workflows/helpdot-review.yml
Labels: HelpDot Review

#70323 [NO QA] Improve App cherry-pick workfow
  .github/workflows/cherryPick.yml
  .github/workflows/createNewVersion.yml
Labels: InternalQA

#66964 Optimize InviteReportParticipantsPage component via useSearchSelector hook
  src/CONST/index.ts
  src/hooks/useSearchSelector.base.ts
  src/hooks/useSearchSelector.native.ts
  src/hooks/useSearchSelector.ts
  src/libs/OptionsListUtils/index.ts
  src/libs/OptionsListUtils/types.ts
  src/pages/InviteReportParticipantsPage.tsx
Labels: AI Review

#70250 [63253] (1/2) Open transaction thread on top
  src/components/ActionSheetAwareScrollView/index.ios.tsx
  src/components/ActionSheetAwareScrollView/types.ts
  src/hooks/useReportScrollManager/index.native.ts
  src/hooks/useReportScrollManager/index.ts
  src/hooks/useReportScrollManager/types.ts
  src/pages/home/report/ReportActionsList.tsx
Labels: AI Review

#70689 Send more Fraud Protection events
  src/CONST/index.ts
  src/libs/API/index.ts
  src/libs/API/parameters/UpdateExpensifyCardLimitParams.ts
  src/libs/Middleware/FraudMonitoring.ts
  src/libs/actions/Card.ts
  src/libs/actions/Session/index.ts
  src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx
Labels: InternalQA

#71031 More FP events
  modules/group-ib-fp/index.d.ts
  src/CONST/index.ts
  src/libs/FraudProtection/GroupIBSdkBridge/index.native.ts
  src/libs/FraudProtection/GroupIBSdkBridge/index.ts
  src/libs/FraudProtection/index.ts
  src/libs/Middleware/FraudMonitoring.ts
Labels: InternalQA

#69468 Remove`isSupportRequest` in favor of checking in auth
  src/ONYXKEYS.ts
  src/components/SupportalActionRestrictedModal.tsx
  src/components/SupportalPermissionDeniedModalProvider.tsx
  src/languages/de.ts
  src/languages/en.ts
  src/languages/es.ts
  src/languages/fr.ts
  src/languages/it.ts
  src/languages/ja.ts
  src/languages/nl.ts
  src/languages/pl.ts
  src/languages/pt-BR.ts
  src/languages/zh-hans.ts
  src/libs/API/index.ts
  src/libs/Middleware/SupportalPermission.ts
  src/libs/Middleware/index.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Network/NetworkStore.ts
  src/libs/Request.ts
  src/libs/actions/App.ts
  src/pages/workspace/WorkspacesListPage.tsx
  src/setup/index.ts
  src/types/onyx/SupportalPermissionDenied.ts
  src/types/onyx/index.ts
  tests/unit/APITest.ts
Labels: InternalQA
