Repository Expensify/App, pull requests merged in 2025-03, with the labels that each got.

#57484 [No QA][HybridApp] Fix `is-hybrid-app.sh` script
  scripts/is-hybrid-app.sh
Labels: Ready To Build

#56523 fix: remove flashing effect when opening a report
  src/hooks/useCurrentReportID.tsx
  src/hooks/useReportIDs.tsx
Labels: Ready To Build

#56602 Clickable emoji for exoense task
  assets/images/customEmoji/global-create.svg
  src/CONST.ts
  src/components/FABPopoverProvider.tsx
  src/components/HTMLEngineProvider/BaseHTMLEngineProvider.tsx
  src/components/HTMLEngineProvider/CustomEmojiWithDefaultPressableAction.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/CustomEmojiRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/index.ts
  src/components/Navigation/BottomTabBar/index.tsx
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/ReportUtils.ts
  src/libs/actions/Policy/Policy.ts
  src/libs/actions/Report.ts
  src/pages/home/sidebar/BottomTabBarFloatingActionButton/index.native.tsx
  src/pages/home/sidebar/BottomTabBarFloatingActionButton/index.tsx
  src/pages/home/sidebar/BottomTabBarFloatingActionButton/types.ts
  src/pages/home/sidebar/FloatingActionButtonPopover.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#57791 [NO QA] Update Expense-Types.md
  docs/articles/expensify-classic/expenses/Expense-Types.md
Labels: Ready To Build

#56314 fix loading indicator when the app is loading
  src/components/Navigation/TopBar.tsx
  src/pages/Search/SearchPageNarrow.tsx
  src/pages/home/sidebar/SidebarLinks.tsx
  src/styles/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#56604 [InternalQA] Redirect to OldDot to clear cookies
  src/CONST.ts
  src/libs/API/types.ts
  src/libs/actions/Session/index.ts
  src/types/onyx/Response.ts
  tests/actions/SessionTest.ts
Labels: InternalQA

#57831 [CP Staging] Fix: Scroll Issue on Reports Page, side pane appearing after language change
  src/hooks/useSidePane.ts
  src/libs/Navigation/AppNavigator/useRootNavigatorScreenOptions.ts
  src/libs/actions/App.ts
Labels: Ready To Build

#56877 Show/hide delete expense button based on Liability type for card transaction
  src/CONST.ts
  src/libs/DebugUtils.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/pages/ReportDetailsPage.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/types/onyx/Transaction.ts
  tests/ui/ReportDetailsPageTest.tsx
  tests/unit/ReportUtilsTest.ts
Labels: InternalQA

#56698 [HybridApp] Receive structured initialProperties (not as url) and improve url handling
  src/App.tsx
  src/CONST.ts
  src/components/BookTravelButton.tsx
  src/components/InitialURLContextProvider.tsx
  src/components/ScreenWrapper.tsx
  src/libs/Notification/PushNotification/subscribePushNotification/index.ts
  src/libs/actions/Delegate.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/Welcome/index.ts
  src/pages/ErrorPage/SessionExpiredPage.tsx
  src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx
  src/pages/home/sidebar/FloatingActionButtonPopover.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/types/modules/react-native.d.ts
Labels: Ready To Build

#57420 Fix session expired errors right after login
  src/libs/API/index.ts
  src/libs/Authentication.ts
  src/libs/Middleware/Reauthentication.ts
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/actions/Session/AttachmentImageReauthenticator.ts
  src/libs/actions/Session/index.ts
  src/pages/LogOutPreviousUserPage.tsx
  src/types/onyx/Session.ts
Labels: Ready To Build

#56605 [UX Reliability] New modal in `AttachmentPickerWithMenuItems`
  src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx
Labels: Ready To Build

#57353 Fix: Handle unsupported videos in iOS
  assets/images/video-slash.svg
  patches/expo-av+15.0.1.patch
  src/components/AttachmentOfflineIndicator.tsx
  src/components/Icon/Expensicons.ts
  src/components/VideoPlayer/BaseVideoPlayer.tsx
  src/components/VideoPlayer/VideoErrorIndicator.tsx
  src/components/VideoPlayerContexts/PlaybackContext.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/styles/utils/spacing.ts
Labels: Ready To Build

#58004 Side Pane Stage 2: Add baseline content for each major section
  patches/@react-navigation+core+6.4.11+004+side-pane.patch
  src/ONYXKEYS.ts
  src/components/Navigation/RootNavigatorExtraContent.tsx
  src/components/Navigation/TopLevelBottomTabBar/index.tsx
  src/components/SidePane/HelpButton.tsx
  src/components/SidePane/SidePaneOverlay.tsx
  src/components/SidePane/getHelpContent.tsx
  src/components/SidePane/index.tsx
  src/hooks/useSidePane.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/Navigators/SearchFullscreenNavigator.tsx
  src/libs/Navigation/AppNavigator/createRootStackNavigator/index.tsx
  src/libs/Navigation/AppNavigator/useRootNavigatorScreenOptions.ts
  src/libs/SidePaneUtils.ts
  src/styles/index.ts
Labels: Ready To Build

#57753 Adjust adaptStateIfNecessary to push a split navigator without a sidebar screen v2
  src/libs/Navigation/AppNavigator/createSplitNavigator/SplitRouter.ts
  src/pages/workspace/companyCards/WorkspaceCompanyCardFeedSelectorPage.tsx
Labels: Ready To Build

#56302 Fix blank modal after fullscreen video ends on Android
  patches/expo-av+15.0.1+001+fix-blank-screen-android.patch
Labels: Ready To Build

#57648 Embed media files in New Expensify #admins room tasks
  src/CONST.ts
  src/components/Attachments/AttachmentCarousel/extractAttachments.ts
  src/components/Attachments/AttachmentCarousel/index.native.tsx
  src/components/Attachments/AttachmentCarousel/index.tsx
  src/components/ReportActionItem/TaskView.tsx
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
Labels: Ready To Build

#57610 Loading state perception improvement
  src/CONST.ts
  src/components/LoadingBar.tsx
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestHeader.tsx
  src/components/ReportActionsSkeletonView/SkeletonViewLines.tsx
  src/pages/Debug/ReportAction/DebugReportActionCreatePage.tsx
  src/pages/Debug/ReportAction/DebugReportActionPreview.tsx
  src/pages/TransactionDuplicate/DuplicateTransactionItem.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/ReportScreen.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionItemParentAction.tsx
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportActionsListItemRenderer.tsx
  src/pages/home/report/ReportActionsView.tsx
  src/styles/index.ts
  src/styles/theme/themes/dark.ts
  src/styles/theme/themes/light.ts
  tests/ui/PaginationTest.tsx
Labels: Ready To Build

#57547 Fix desktop updates to install the latest one
  desktop/main.ts
Labels: Ready To Build

#57323 Allow users to export report as PDF
  src/CONST.ts
  src/ONYXKEYS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/ExportReportPDFParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Permissions.ts
  src/libs/actions/Report.ts
  src/pages/ReportDetailsPage.tsx
Labels: Ready To Build

#58074 Company Cards - Remove Direct feed display RBR
  src/libs/CardUtils.ts
Labels: InternalQA, Ready To Build

#57993 fix: hide keyboard before navigating search
  src/components/Search/SearchPageHeader/SearchPageHeaderInput.tsx
Labels: Ready To Build

#58301 [HybridApp] Add HybridApp turbomodule
  .eslintrc.js
  ios/Podfile.lock
  jest/setup.ts
  modules/hybrid-app/ReactNativeHybridApp.podspec
  modules/hybrid-app/android/build.gradle
  modules/hybrid-app/android/gradle.properties
  modules/hybrid-app/android/src/main/AndroidManifest.xml
  modules/hybrid-app/android/src/main/java/com/expensify/reactnativehybridapp/ReactNativeHybridApp.kt
  modules/hybrid-app/android/src/main/java/com/expensify/reactnativehybridapp/ReactNativeHybridAppPackage.kt
  modules/hybrid-app/ios/ReactNativeHybridApp.h
  modules/hybrid-app/ios/ReactNativeHybridApp.mm
  modules/hybrid-app/package.json
  modules/hybrid-app/react-native.config.js
  modules/hybrid-app/src/NativeReactNativeHybridApp.ts
  modules/hybrid-app/src/index.native.ts
  modules/hybrid-app/src/index.ts
  modules/hybrid-app/src/types.ts
  package-lock.json
  package.json
  src/CONFIG.ts
  src/Expensify.tsx
  src/components/BookTravelButton.tsx
  src/components/ScreenWrapper.tsx
  src/hooks/useOnboardingFlow.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/AppNavigator/index.native.tsx
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/Notification/PushNotification/subscribePushNotification/index.ts
  src/libs/actions/AppUpdate/updateApp/index.android.ts
  src/libs/actions/AppUpdate/updateApp/index.ios.ts
  src/libs/actions/Delegate.ts
  src/libs/actions/Session/index.ts
  src/libs/actions/Welcome/index.ts
  src/pages/ErrorPage/SessionExpiredPage.tsx
  src/pages/ErrorPage/UpdateRequiredView.tsx
  src/pages/LogInWithShortLivedAuthTokenPage.tsx
  src/pages/LogOutPreviousUserPage.tsx
  src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx
  src/pages/Travel/MyTripsPage.tsx
  src/pages/Travel/TravelTerms.tsx
  src/pages/Travel/TripDetailsPage.tsx
  src/pages/Travel/TripSummaryPage.tsx
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
  src/pages/settings/InitialSettingsPage.tsx
  src/types/modules/react-native.d.ts
  tsconfig.json
Labels: Ready To Build

#57885 [Report Creation UI] Create new reusable transaction component
  src/CONST.ts
  src/components/TransactionItemRow/DataCells/CategoryCell.tsx
  src/components/TransactionItemRow/DataCells/DateCell.tsx
  src/components/TransactionItemRow/DataCells/MerchantCell.tsx
  src/components/TransactionItemRow/DataCells/ReceiptCell.tsx
  src/components/TransactionItemRow/DataCells/TagCell.tsx
  src/components/TransactionItemRow/DataCells/TotalCell.tsx
  src/components/TransactionItemRow/DataCells/TransactionDataCellProps.ts
  src/components/TransactionItemRow/DataCells/TypeCell.tsx
  src/components/TransactionItemRow/index.tsx
  src/stories/TransactionItemRow.stories.tsx
  src/stories/objects/Transaction.ts
  src/styles/index.ts
  src/styles/utils/flex.ts
  src/styles/utils/spacing.ts
Labels: Ready To Build

#58394 [CP Staging] Revert "Make Troubleshoot menu available in Sign In page"
  src/Expensify.tsx
  src/NAVIGATORS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/TestToolMenu.tsx
  src/components/TestToolsModal.tsx
  src/hooks/useDebugShortcut.tsx
  src/hooks/useIsAuthenticated.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/Navigators/PublicRightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
  src/libs/Navigation/AppNavigator/PublicScreens.tsx
  src/libs/Navigation/AppNavigator/useCustomScreenOptions.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/pages/settings/AboutPage/ConsolePage.tsx
Labels: Ready To Build

#58101 fix: decode bank param to get all cards correctly
  src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardEditCardNamePage.tsx
  src/pages/workspace/companyCards/assignCard/AssignCardFeedPage.tsx
Labels: InternalQA

#58482 [CP Staging] Revert "Adds new RESOLVEDDUPLICATES action"
  src/CONST.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/TransactionMergeParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/ReportUtils.ts
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/types/onyx/OriginalMessage.ts
Labels: Ready To Build

#58390 Fixed scan expense flow when participants are missing
  src/libs/actions/IOU.ts
  src/pages/iou/request/step/IOURequestStepAmount.tsx
  src/pages/iou/request/step/IOURequestStepDistance.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
Labels: Ready To Build, CP Staging

#57922 Update the messsage on LHN on Ship card flow
  src/components/ReportActionItem/IssueCardMessage.tsx
  src/libs/CardMessageUtils.ts
  src/libs/SidebarUtils.ts
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
Labels: InternalQA

#58273 fix: NewDot is infinite loading and onboarding model does't display
  src/libs/Navigation/AppNavigator/Navigators/ReportsSplitNavigator.tsx
  src/libs/actions/OnyxUpdates.ts
Labels: Ready To Build

#53821 feat: Bump react-native-pager-view version and remove patch
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-pager-view+6.5.1+001+initial.patch
Labels: Ready To Build

#58600 fix: Keep legacy bottom safe area handling if we don't use one of the new edge-to-edge flags
  src/components/Form/FormWrapper.tsx
Labels: Ready To Build

#58534 Fixes for change policy feature
  src/components/ChangeWorkspaceMenuSectionList.tsx
  src/hooks/useWorkspaceList.ts
  src/libs/actions/Report.ts
  src/pages/ReportChangeWorkspacePage.tsx
  src/pages/WorkspaceSwitcherPage/index.tsx
Labels: Ready To Build

#58675 [CP Staging] Revert "[CP Staging] fix: blocked scrolling event in reports list"
  src/pages/home/report/ReportActionsList.tsx
Labels: Ready To Build

#58079 Static skeleton loader for offline reports
  src/pages/home/report/ReportActionsList.tsx
  src/pages/home/report/ReportActionsView.tsx
Labels: Ready To Build

#50640 Update Payment flow on clicking Pay
  src/components/MoneyReportHeader.tsx
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/SettlementButton/index.tsx
  src/components/SettlementButton/types.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/PayInvoiceParams.ts
  src/libs/ReportUtils.ts
  src/libs/actions/IOU.ts
Labels: InternalQA, Ready To Build

#58507 fix: Better `OfflineIndicator` bottom safe area handling
  src/CONST.ts
  src/components/BlockingViews/BlockingView.tsx
  src/components/BlockingViews/FullPageNotFoundView.tsx
  src/components/BlockingViews/FullPageOfflineBlockingView.tsx
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/components/FixedFooter.tsx
  src/components/Form/FormProvider.tsx
  src/components/Form/FormWrapper.tsx
  src/components/NavigationBar/index.android.tsx
  src/components/OfflineIndicator.tsx
  src/components/ScreenWrapper.tsx
  src/components/ScrollView.tsx
  src/components/SectionList/BaseSectionList.tsx
  src/components/SectionList/types.ts
  src/components/SelectionList/BaseSelectionList.tsx
  src/components/SelectionList/types.ts
  src/hooks/useBottomSafeSafeAreaPaddingStyle.ts
  src/pages/home/report/ReportFooter.tsx
  src/styles/index.ts
Labels: Ready To Build

#58474 Help button spacing and alignment
  src/components/AttachmentModal.tsx
  src/components/ConnectToQuickbooksOnlineFlow/index.native.tsx
  src/components/ConnectToXeroFlow/index.native.tsx
  src/components/Header.tsx
  src/components/HeaderWithBackButton/index.tsx
  src/components/Navigation/TopBar.tsx
  src/components/Search/SearchPageHeader/SearchPageHeaderInput.tsx
  src/components/Search/SearchRouter/SearchRouter.tsx
  src/components/SidePane/HelpButton.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/home/HeaderView.tsx
  src/pages/home/sidebar/BaseSidebarScreen.tsx
  src/pages/home/sidebar/SignInButton.tsx
  src/pages/settings/Subscription/CardAuthenticationModal/index.tsx
  src/pages/workspace/WorkspaceInitialPage.tsx
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/styles/index.ts
Labels: Ready To Build

#58620 [HybridApp] Handle `initialURL` navigation in `InitialURLContextProvider`
  src/components/InitialURLContextProvider.tsx
  src/libs/Navigation/AppNavigator/index.native.tsx
Labels: InternalQA

#58757 [CP Staging] Revert "Fix browser history review duplicates and delete workspace flows"
  patches/@react-navigation+native+6.1.12+002+fix-getting-history-entry-when-navigating-back.patch
  patches/@react-navigation+native+6.1.12.patch
  src/libs/PolicyUtils.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
Labels: Ready To Build

#58191 Remove reportID param from dismissModal function
  contributingGuides/NAVIGATION.md
  src/libs/Navigation/AppNavigator/createRootStackNavigator/GetStateForActionHandlers.ts
  src/libs/Navigation/AppNavigator/createRootStackNavigator/RootStackRouter.ts
  src/libs/Navigation/AppNavigator/createRootStackNavigator/types.ts
  src/libs/Navigation/Navigation.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Report.ts
  src/libs/actions/Task.ts
  src/libs/actions/TeachersUnite.ts
  src/pages/AddPersonalBankAccountPage.tsx
  src/pages/EnablePayments/AddBankAccount/AddBankAccount.tsx
  src/pages/NewChatPage.tsx
  src/pages/RoomInvitePage.tsx
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/TransactionReceiptPage.tsx
  src/pages/tasks/TaskAssigneeSelectorModal.tsx
  src/pages/tasks/TaskDescriptionPage.tsx
  src/pages/tasks/TaskTitlePage.tsx
  src/pages/workspace/WorkspaceInviteMessagePage.tsx
  src/pages/workspace/WorkspaceNewRoomPage.tsx
  src/pages/workspace/WorkspaceOverviewSharePage.tsx
Labels: Ready To Build

#58640 Debug desktop updates
  desktop/main.ts
Labels: InternalQA

#57765 Add VoiceOver for chat list items
  src/components/LHNOptionsList/OptionRowLHN.tsx
  tests/ui/GroupChatNameTests.tsx
  tests/ui/LHNItemsPresence.tsx
  tests/ui/UnreadIndicatorsTest.tsx
  tests/unit/SidebarFilterTest.ts
  tests/unit/SidebarOrderTest.ts
  tests/utils/TestHelper.ts
Labels: Ready To Build

#58666 Add close button to product training tooltips and track dismissal method
  src/components/ProductTrainingContext/TOOLTIPS.ts
  src/components/ProductTrainingContext/index.tsx
  src/hooks/useOnboardingFlow.ts
  src/libs/API/parameters/DismissProductTraining.ts
  src/libs/TooltipUtils.ts
  src/libs/actions/Report.ts
  src/libs/actions/Welcome/index.ts
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/types/onyx/DismissedProductTraining.ts
  tests/ui/components/ProductTrainingContextProvider.tsx
  tests/unit/OptionsListUtilsTest.ts
Labels: Ready To Build

#58271 fix: add sender name
  src/libs/OptionsListUtils.ts
  src/libs/SidebarUtils.ts
  tests/unit/OptionsListUtilsTest.ts
Labels: Ready To Build

#58630 Card assignment flow errors handling
  src/libs/actions/CompanyCards.ts
  src/pages/workspace/companyCards/BankConnection/index.native.tsx
  src/pages/workspace/companyCards/BankConnection/index.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsPage.tsx
  src/pages/workspace/companyCards/assignCard/ConfirmationStep.tsx
  src/types/onyx/AssignCard.ts
Labels: InternalQA, Ready To Build

#58901 [CP Staging] Receipt - Unable to replace receipt and page stucks
  src/components/AttachmentModal.tsx
Labels: Ready To Build

#58626 [Better Expense Report View] Add messages count ChatBubble to MoneyRequestReportView rows
  assets/images/chatbubble-counter.svg
  src/components/Icon/Expensicons.ts
  src/components/MoneyRequestReportView/MoneyRequestReportTableHeader.tsx
  src/components/MoneyRequestReportView/MoneyRequestReportTransactionList.tsx
  src/components/TransactionItemRow/DataCells/ChatBubbleCell.tsx
  src/components/TransactionItemRow/index.tsx
  src/stories/TransactionItemRow.stories.tsx
  src/styles/utils/index.ts
  src/styles/variables.ts
Labels: Ready To Build

#58713 [Better Expense Report View] Add sorting functionality to MoneyRequestReportView
  src/components/MoneyRequestReportView/MoneyRequestReportTableHeader.tsx
  src/components/MoneyRequestReportView/MoneyRequestReportTransactionList.tsx
  src/libs/SearchUIUtils.ts
Labels: Ready To Build

#58834 Revert "Revert "Share extension Android and iOS implementation""
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/expensify/chat/ExpensifyAppPackage.java
  android/app/src/main/java/com/expensify/chat/MainActivity.kt
  android/app/src/main/java/com/expensify/chat/ShareActionHandlerModule.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/AbstractIntentHandler.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/FileIntentHandler.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/IntentHandler.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/IntentHandlerFactory.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/ShareFileObject.kt
  android/app/src/main/java/com/expensify/chat/intentHandler/TextIntentHandler.kt
  android/app/src/main/java/com/expensify/chat/utils/FileUtils.kt
  ios/NewExpensify.xcodeproj/project.pbxproj
  ios/NewExpensify.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  ios/NewExpensify/Chat.entitlements
  ios/RCTShareActionHandlerModule.h
  ios/RCTShareActionHandlerModule.m
  ios/ShareViewController/Base.lproj/MainInterface.storyboard
  ios/ShareViewController/Info.plist
  ios/ShareViewController/ShareViewController.entitlements
  ios/ShareViewController/ShareViewController.swift
  src/CONST.ts
  src/NAVIGATORS.ts
  src/ONYXKEYS.ts
  src/ROUTES.ts
  src/SCREENS.ts
  src/components/AttachmentPreview.tsx
  src/components/Attachments/AttachmentView/index.tsx
  src/components/MoneyRequestConfirmationList.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/Share/ShareTabParticipantsSelector.tsx
  src/components/Skeletons/TabNavigatorSkeleton.tsx
  src/components/TabSelector/TabSelector.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/AppNavigator/AuthScreens.tsx
  src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
  src/libs/Navigation/AppNavigator/createRootStackNavigator/GetStateForActionHandlers.ts
  src/libs/Navigation/linkingConfig/config.ts
  src/libs/Navigation/types.ts
  src/libs/OptionsListUtils.ts
  src/libs/ShareActionHandlerModule/index.ts
  src/libs/actions/Report.ts
  src/libs/actions/Share.ts
  src/pages/Share/ShareDetailsPage.tsx
  src/pages/Share/ShareRootPage.tsx
  src/pages/Share/ShareTab.tsx
  src/pages/Share/SubmitDetailsPage.tsx
  src/pages/Share/SubmitTab.tsx
  src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
  src/styles/utils/spacing.ts
  src/types/modules/react-native.d.ts
  src/types/onyx/ShareTempFile.ts
  src/types/onyx/index.ts
Labels: Ready To Build

#57588 Fix: Expensify Card page in empty state has two scoll bars
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/pages/Search/EmptySearchView.tsx
  src/pages/workspace/categories/WorkspaceCategoriesPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsFeedAddedEmptyPage.tsx
  src/pages/workspace/companyCards/WorkspaceCompanyCardsFeedPendingPage.tsx
  src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
  src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx
  src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx
  src/pages/workspace/tags/WorkspaceTagsPage.tsx
Labels: Ready To Build

#58977 Update NewDot report action copy to make it clear when the action is automatically (vs manually) initiated
  src/languages/en.ts
  src/languages/es.ts
  src/libs/ReportActionsUtils.ts
Labels: Ready To Build

#58475 [NO QA] Update Terser config to keep function and class names for stack traces
  config/webpack/webpack.common.ts
Labels: Ready To Build

#59066 [CP Staging] Fix error creating expense in self DM
  src/pages/Share/SubmitDetailsPage.tsx
Labels: CP Staging

#59067 Fix Unable to dismiss keyboard by tapping outside the message field
  src/CONST.ts
  src/pages/Share/ShareDetailsPage.tsx
Labels: CP Staging

#58916 Add RBR leading member to broken card connection error
  src/CONST.ts
  src/hooks/useIndicatorStatus.ts
  src/pages/settings/InitialSettingsPage.tsx
Labels: InternalQA

#58363 Pass auth token when downloading report as PDF
  src/libs/actions/Report.ts
  src/libs/addEncryptedAuthTokenToURL.ts
  src/libs/fileDownload/DownloadUtils.ts
  src/pages/ReportDetailsPage.tsx
Labels: Ready To Build

#58795 Feature/kuba nowakowski/add empty state to expense view
  src/components/EmptyStateComponent/index.tsx
  src/components/EmptyStateComponent/types.ts
  src/components/MoneyReportHeader.tsx
  src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx
  src/components/MoneyRequestReportView/MoneyRequestReportTransactionList.tsx
  src/components/MoneyRequestReportView/SearchMoneyRequestReportEmptyState.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateAppReportParams.ts
  src/libs/NextStepUtils.ts
  src/libs/ReportUtils.ts
  src/libs/actions/Report.ts
  src/pages/home/sidebar/FloatingActionButtonAndPopover.tsx
  src/styles/index.ts
Labels: Ready To Build

#59188 Return early when caching sound
  src/libs/Sound/index.ts
Labels: Ready To Build
