Repository Expensify/App, pull requests merged in 2025-05, with the labels that each got.

#58540 Add RBR/GBR chat and Account switcher tooltips
  src/CONST.ts
  src/components/AccountSwitcher.tsx
  src/components/LHNOptionsList/LHNOptionsList.tsx
  src/components/LHNOptionsList/OptionRowLHN.tsx
  src/components/LHNOptionsList/types.ts
  src/components/ProductTrainingContext/TOOLTIPS.ts
  src/languages/en.ts
  src/languages/es.ts
  src/libs/Navigation/helpers/useRouteActive.ts
  src/pages/settings/InitialSettingsPage.tsx
  src/styles/variables.ts
  src/types/onyx/DismissedProductTraining.ts
Labels: Ready To Build

#61666 Fix validated code bug on replace card flow
  src/libs/actions/Card.ts
  src/pages/settings/Wallet/ReportCardLostPage.tsx
Labels: InternalQA

#60270 Setup `react-native-wallet` on Android
  modules/expensify-react-native-wallet.tgz
  package-lock.json
  react-native.config.js
  src/components/AddToWalletButton/index.native.tsx
  src/languages/en.ts
  src/languages/es.ts
  src/libs/API/parameters/CreateAppleDigitalWalletParams.ts
  src/libs/API/parameters/CreateDigitalWalletParams.ts
  src/libs/API/parameters/index.ts
  src/libs/API/types.ts
  src/libs/Wallet/index.android.ts
  src/libs/Wallet/index.ios.ts
  src/libs/actions/Wallet.ts
  src/types/onyx/Card.ts
  src/types/onyx/index.ts
Labels: InternalQA

#62200 Revert "Merge pull request #61884 from nkdengineer/fix/61016"
  src/hooks/useSidePanel.ts
Labels: CP Staging

#61574 [Multi-Scan] Refactor IOU screens to support handling multiple expense creation
  src/libs/TransactionUtils/index.ts
  src/libs/actions/IOU.ts
  src/libs/actions/Transaction.ts
  src/libs/actions/TransactionEdit.ts
  src/pages/iou/request/step/IOURequestStepConfirmation.tsx
  src/pages/iou/request/step/IOURequestStepParticipants.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.native.tsx
  src/pages/iou/request/step/IOURequestStepScan/index.tsx
  src/pages/iou/request/step/IOURequestStepScan/types.ts
Labels: Ready To Build

#61769 Fix getting in-wallet card status on iOS
  modules/expensify-react-native-wallet.tgz
  package-lock.json
  src/components/AddToWalletButton/index.native.tsx
  src/libs/Wallet/index.android.ts
  src/libs/Wallet/index.ios.ts
  src/libs/Wallet/index.ts
  src/types/onyx/Card.ts
Labels: InternalQA

#56908 fix: not here page when clicking attachment from email
  src/components/AttachmentModal.tsx
  src/components/Attachments/AttachmentView/DefaultAttachmentView/index.tsx
  src/components/FullscreenLoadingIndicator.tsx
  src/libs/actions/QueuedOnyxUpdates.ts
  src/pages/home/report/ReportAttachments.tsx
  tests/ui/ReportAttachments.tsx
  tests/utils/TestHelper.ts
Labels: Ready To Build

#60990 fix - Do not use credentials for sending OTP on private domain onboarding flow
  src/hooks/useOnboardingFlow.ts
  src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/actions/Report.ts
  src/libs/actions/Welcome/OnboardingFlow.ts
  src/pages/OnboardingPrivateDomain/BaseOnboardingPrivateDomain.tsx
Labels: Ready To Build

#62637 Send email of the user who support logged in so we can log it
  src/libs/Network/enhanceParameters.ts
Labels: InternalQA

#54764 fix: messages content overlap when bottom sheet is shown
  jest/setup.ts
  src/App.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetAwareScrollViewContext.tsx
  src/components/ActionSheetAwareScrollView/ActionSheetKeyboardSpace.tsx
  src/components/ActionSheetAwareScrollView/index.ios.tsx
  src/components/ActionSheetAwareScrollView/index.tsx
  src/components/EmojiPicker/EmojiPickerButton.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
  src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer.tsx
  src/components/KeyboardAvoidingView/BaseKeyboardAvoidingView/index.android.tsx
  src/components/KeyboardAvoidingView/BaseKeyboardAvoidingView/index.ios.tsx
  src/components/MoneyRequestConfirmationListFooter.tsx
  src/components/PopoverMenu.tsx
  src/components/PopoverWithMeasuredContent.tsx
  src/components/ReportActionItem/MoneyRequestAction.tsx
  src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
  src/components/ReportActionItem/MoneyRequestPreview/types.ts
  src/components/ReportActionItem/ReportPreview.tsx
  src/components/ReportActionItem/TaskPreview.tsx
  src/components/ReportActionItem/TaskView.tsx
  src/components/ShowContextMenuContext.ts
  src/components/ThreeDotsMenu/index.tsx
  src/components/VideoPlayerPreview/VideoPlayerThumbnail.tsx
  src/hooks/useRestoreInputFocus/index.android.ts
  src/hooks/useRestoreInputFocus/index.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.native.ts
  src/hooks/useWorkletStateMachine/executeOnUIRuntimeSync/index.ts
  src/hooks/useWorkletStateMachine/index.ts
  src/pages/TransactionDuplicate/Confirmation.tsx
  src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx
  src/pages/home/report/ContextMenu/ContextMenuActions.tsx
  src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx
  src/pages/home/report/PureReportActionItem.tsx
  src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
  src/pages/home/report/ReportActionsList.tsx
  tests/ui/components/ReportPreviewTest.tsx
  tests/unit/VideoRendererTest.tsx
Labels: Ready To Build

#61322 fix: move truncation of HTML paste into parser
  src/hooks/useHtmlPaste/index.ts
  src/libs/Parser.ts
Labels: Ready To Build

#62720 Open last visited path on native for report screen
  src/libs/Navigation/NavigationRoot.tsx
  src/libs/shouldOpenLastVisitedPath/index.native.ts
  src/libs/shouldOpenLastVisitedPath/index.ts
  src/setup/index.ts
  src/setup/initializeLastVisitedPath/index.native.ts
  src/setup/initializeLastVisitedPath/index.ts
Labels: Ready To Build

#62213 fix: the tooltip button is not functional on android
  src/components/ProductTrainingContext/createPressHandler/index.android.ts
  src/components/ProductTrainingContext/createPressHandler/index.ts
  src/components/ProductTrainingContext/createPressHandler/types.ts
  src/components/ProductTrainingContext/index.tsx
Labels: Ready To Build
